/**
 * Niagara/effect-specific JSON-schema property fragments.
 */
import type { PropertyMap } from '../properties.js';
import { str, num, bool, vec3 } from '../../shared/schema-props.js';

export const E: PropertyMap = {
  scale: { description: 'Scale of the spawned system: one uniform number, or [x, y, z] (an {x, y, z} object is accepted). Default 1.' },
  templateEmitterPath: str('Niagara emitter asset the authored system starts from; defaults to the engine template for the effect kind. Ignored when systemPath names an existing system.'),
  fromNode: str('Source node: its GUID, name or title.'),
  fromPin: str('Output pin name (or display name) on the source node.'),
  toNode: str('Destination node: its GUID, name or title.'),
  toPin: str('Input pin name (or display name) on the destination node.'),
  thickness: num('Line thickness of the debug shape (default 2).'),
  boxSize: vec3('Box half extents as [x, y, z] for shapeType box (default the radius on every axis).'),
  endLocation: vec3('End point as [x, y, z] for line, arrow and cylinder shapes.'),
  direction: vec3('Direction as [x, y, z] for a cone (default up).'),
  length: num('Cone length (default twice the radius).'),
  angle: num('Cone half angle in degrees (default 45).'),
  halfHeight: num('Capsule half height (default the radius).'),
  systemPath: str('Canonical /Game Niagara System asset path.'),
  systemName: str('Runtime Niagara system/component name on the target actor.'),
  system: str('Niagara system path; alias normalized to systemPath.'),
  emitterName: str('Emitter name within the target Niagara system.'),
  emitter: str('Emitter name; alias normalized to emitterName.'),
  emitterProperties: {
    type: 'object',
    additionalProperties: true,
    description: 'Emitter settings to change. Supported key: enabled (boolean); any other key is refused. Module inputs are set with set_parameter_value.',
    'x-unreal-reflection-boundary': true,
  },
  savePath: str('Canonical /Game directory for the created asset.'),
  scriptType: str('Niagara script usage (System, Emitter, Particle).'),
  modulePath: str('Canonical /Niagara module script path to insert.'),
  nodeId: str('Niagara graph node identifier.'),
  targetNodeId: str('Niagara graph node the dynamic input is attached to.'),
  autoConnect: bool('Whether inserted pins are auto-connected.'),
  dynamicInputScriptPath: str('Canonical /Niagara dynamic input script path.'),
  inputName: str('Module input name receiving the dynamic input.'),
  replaceExisting: bool('Whether an existing dynamic input is replaced.'),
  parameterName: str('Niagara parameter name.'),
  parameterType: str('Niagara parameter type (Float, Vector, Color, ...).'),
  parameterValue: { description: 'Niagara parameter value (any type).' },
  sourceBinding: str('Data source the parameter binds to.'),
  forceType: str('Force module type (Gravity, Drag, Wind, Curl, Vortex, PointAttraction).'),
  velocityMode: str('Velocity module mode (Linear, Cone, FromPoint).'),
  color: { description: 'Color as an {r, g, b, a} object or an [r, g, b, a] array: 0 to 255 channels for debug_shape, 0 to 1 for a light.' },
  materialPath: str('Canonical /Game material asset path for the renderer; its Niagara sprite or ribbon usage flag is set and the material saved, so the renderer never falls back to the default material.'),
  lightRadius: num('Multiplier on each particle\'s light radius (the renderer RadiusScale, engine default 1). Left unchanged when omitted.'),
  eventName: str('Niagara event name.'),
  eventType: str('Niagara event generator type (Location, Death, Collision).'),
  eventSpawnCount: num('Particles spawned per received event.'),
  spawnOnEvent: bool('Whether the receiver spawns particles on each event.'),
  stageName: str('Simulation stage name.'),
  stageIterationSource: str('Simulation stage iteration source.'),
  deterministicEnabled: bool('Whether deterministic GPU simulation is enabled.'),
  fixedBoundsEnabled: bool('Whether fixed system bounds are enabled.'),
  attachToActor: str('Name of the actor the spawned system attaches to.'),
  reset: bool('Whether the effect restarts from its initial state.'),
  deltaTime: num('Simulation delta time per step, in seconds.'),
  steps: num('Number of simulation steps to advance.'),
  filter: str('Actor name prefix selecting which transient effects are cleaned up.'),
  preset: str('Particle preset name or canonical /Game particle asset path.'),
  shapeType: str('Debug shape type (Sphere, Box, Line, Capsule).'),
  intensity: num('Light intensity.'),
  lightType: str('Dynamic light type: Point (the default, and what any other value gives), Spot, Directional or Rect, in any case; there is no sky light here.'),
  density: num('Volumetric fog density.'),
  scattering: num('Volumetric fog scattering distribution.'),
  extinction: num('Volumetric fog extinction scale.'),
};
