/**
 * manage_effect records: particle/Niagara core, debug and lifecycle, Niagara
 * parameters, emitter props, modules, renderers, data interfaces, events, GPU
 * sim and validation. Niagara-gated via the Niagara plugin.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { E } from './effect-properties.js';

const T = 'manage_effect';
const F = 'effect';
const W = ['A particle, Niagara or debug effect must be authored or run.'];
const NIAGARA = ['Niagara'];
const EMITTER_REQUIRED = ['systemPath', 'emitterName'];

export const EFFECT_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.particle`, action: 'particle', family: F,
    summary: 'Author a particle effect (Cascade/Niagara).', whenToUse: W, whenNotToUse: ['Use niagara.'],
    inputProps: { name: P.name, path: P.path, preset: E.preset, shapeType: E.shapeType, color: E.color, duration: P.duration, location: P.location, radius: P.radius }, required: [],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'particle', preset: 'Default', shapeType: 'sphere', radius: 30 } }),
  buildRecord({ parentTool: T, id: `${T}.niagara`, action: 'niagara', family: F,
    summary: 'Author a Niagara system.', whenToUse: W, whenNotToUse: ['Use particle.'],
    inputProps: { name: P.name, path: P.path, actorName: P.actorName, systemPath: E.systemPath, attachToActor: E.attachToActor, location: P.location }, required: ['systemPath'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    outputProps: { actorPath: P.string_, actorName: P.actorName, actorGuid: P.string_, existsAfter: P.bool_, actorClass: P.string_ }, outputRequired: [],
    exampleInput: { action: 'niagara', systemPath: '/Game/NS_Explosion', actorName: 'FX_1' }, exampleOutput: { success: true, message: 'Niagara system authored', actorName: 'FX_1' } }),
  buildRecord({ parentTool: T, id: `${T}.debug_shape`, action: 'debug_shape', family: F,
    summary: 'Spawn a debug shape in the editor viewport.', whenToUse: ['Visualize a region/volume.'], whenNotToUse: ['Use spawn_niagara.'],
    inputProps: { shape: P.string_, shapeType: E.shapeType, location: P.location, radius: P.radius, color: E.color, duration: P.duration }, required: [],
    effect: 'write', editorStates: ['edit'], latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'debug_shape', shape: 'Sphere', location: [0, 0, 0], radius: 100 } }),
  buildRecord({ parentTool: T, id: `${T}.spawn_niagara`, action: 'spawn_niagara', family: F,
    topics: ['spawn particle', 'play effect', 'spawn vfx', 'spawn niagara system', 'emit particles'],
    summary: 'Spawn a Niagara system instance at runtime (PIE).', whenToUse: ['A Niagara effect must play on a live actor.'], whenNotToUse: ['Author the system.'],
    inputProps: { actorName: P.actorName, assetPath: P.assetPath, system: E.system, systemPath: E.systemPath, location: P.location }, required: [],
    effect: 'write', editorStates: ['edit', 'pie', 'simulate'], behavior: {  }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'spawn_niagara', system: '/Game/NS_Explosion', location: [0, 0, 100] } }),
  buildRecord({ parentTool: T, id: `${T}.create_dynamic_light`, action: 'create_dynamic_light', family: F,
    summary: 'Create a dynamic light actor.', whenToUse: ['Runtime light needed.'], whenNotToUse: ['Use build_environment lights.'],
    inputProps: { name: P.name, location: P.location, lightType: E.lightType, intensity: E.intensity, color: E.color }, required: ['name'],
    effect: 'write', editorStates: ['edit', 'pie'], latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_dynamic_light', name: 'Light_1', lightType: 'Point', intensity: 750 } }),
  buildRecord({ parentTool: T, id: `${T}.create_niagara_system`, action: 'create_niagara_system', family: F,
    topics: ['niagara', 'particle system', 'vfx', 'particle effect', 'new niagara system'],
    summary: 'Create a Niagara System asset.', whenToUse: W, whenNotToUse: ['Use niagara.'],
    inputProps: { name: P.name, path: P.path, savePath: E.savePath }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    outputProps: { systemPath: P.assetPath }, outputRequired: ['systemPath'],
    exampleInput: { action: 'create_niagara_system', name: 'NS_Fire' }, exampleOutput: { success: true, message: 'Niagara system created', systemPath: '/Game/NS_Fire' } }),
  buildRecord({ parentTool: T, id: `${T}.create_niagara_emitter`, action: 'create_niagara_emitter', family: F,
    summary: 'Create a Niagara Emitter asset.', whenToUse: ['A reusable emitter is needed.'], whenNotToUse: ['Use create_niagara_system.'],
    inputProps: { name: P.name, path: P.path, savePath: E.savePath, emitterName: E.emitterName }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_niagara_emitter', name: 'NE_Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.create_volumetric_fog`, action: 'create_volumetric_fog', family: F,
    summary: 'Create a volumetric fog effect.', whenToUse: ['Volumetric fog needed.'], whenNotToUse: ['Use build_environment fog.'],
    inputProps: { name: P.name, path: P.path, density: E.density, scattering: E.scattering, extinction: E.extinction }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_volumetric_fog', name: 'VF_Mist', density: 0.02 } }),
  buildRecord({ parentTool: T, id: `${T}.create_particle_trail`, action: 'create_particle_trail', family: F,
    summary: 'Create a particle trail effect.', whenToUse: ['A trailing effect is needed.'], whenNotToUse: ['Use create_niagara_ribbon for a ribbon-based trail.'],
    inputProps: { name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_particle_trail', name: 'PT_Trail' } }),
  buildRecord({ parentTool: T, id: `${T}.create_environment_effect`, action: 'create_environment_effect', family: F,
    summary: 'Create an environment effect (weather/atmosphere).', whenToUse: ['Ambient FX needed.'], whenNotToUse: ['Use build_environment weather.'],
    inputProps: { name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_environment_effect', name: 'EE_Rain' } }),
  buildRecord({ parentTool: T, id: `${T}.create_impact_effect`, action: 'create_impact_effect', family: F,
    summary: 'Create an impact effect.', whenToUse: ['Hit FX needed.'], whenNotToUse: ['Use create_niagara_system.'],
    inputProps: { name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_impact_effect', name: 'IE_Bullet' } }),
  buildRecord({ parentTool: T, id: `${T}.create_niagara_ribbon`, action: 'create_niagara_ribbon', family: F,
    summary: 'Create a Niagara ribbon effect.', whenToUse: ['Trail/ribbon FX needed.'], whenNotToUse: ['Use create_niagara_system.'],
    inputProps: { name: P.name, path: P.path, systemPath: E.systemPath, location: P.location }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'create_niagara_ribbon', name: 'NR_Slash' } }),
  buildRecord({ parentTool: T, id: `${T}.activate`, action: 'activate', family: F,
    summary: 'Activate a spawned effect component (PIE).', whenToUse: ['Effect must turn on at runtime.'], whenNotToUse: ['Author the effect.'],
    inputProps: { actorName: P.actorName, reset: E.reset }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent' }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'activate', actorName: 'FX_1', reset: false } }),
  buildRecord({ parentTool: T, id: `${T}.activate_effect`, action: 'activate_effect', family: F,
    summary: 'Activate an effect by asset on a runtime actor.', whenToUse: ['Asset-driven runtime FX.'], whenNotToUse: ['Use activate.'],
    inputProps: { actorName: P.actorName, assetPath: P.assetPath, systemName: E.systemName }, required: [],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: {  }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'activate_effect', systemName: 'FX_1' } }),
  buildRecord({ parentTool: T, id: `${T}.deactivate`, action: 'deactivate', family: F,
    summary: 'Deactivate a runtime effect component.', whenToUse: ['Effect must turn off.'], whenNotToUse: ['Use activate.'],
    inputProps: { actorName: P.actorName }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent' }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'deactivate', actorName: 'FX_1' } }),
  buildRecord({ parentTool: T, id: `${T}.reset`, action: 'reset', family: F,
    summary: 'Reset a runtime effect to initial state.', whenToUse: ['Effect must restart.'], whenNotToUse: ['Use deactivate.'],
    inputProps: { actorName: P.actorName, reset: E.reset }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { safeToRetry: true }, latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'reset', actorName: 'FX_1', reset: true } }),
  buildRecord({ parentTool: T, id: `${T}.advance_simulation`, action: 'advance_simulation', family: F,
    summary: 'Advance a Niagara simulation by time (PIE/editor).', whenToUse: ['Step the sim manually.'], whenNotToUse: ['Let it run.'],
    inputProps: { actorName: P.actorName, deltaTime: E.deltaTime, steps: E.steps }, required: [],
    effect: 'write', editorStates: ['edit', 'pie', 'simulate'], latency: 'instant', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'advance_simulation', deltaTime: 0.016, steps: 2 } }),
  buildRecord({ parentTool: T, id: `${T}.add_niagara_module`, action: 'add_niagara_module', family: F,
    summary: 'Add a module to a Niagara emitter.', whenToUse: ['Emitter needs a module.'], whenNotToUse: ['Use connect_niagara_pins.'],
    inputProps: { assetPath: P.assetPath, systemPath: E.systemPath, emitterName: E.emitterName, modulePath: E.modulePath, scriptType: E.scriptType, name: P.name }, required: ['assetPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    outputProps: { nodeId: E.nodeId }, outputRequired: [],
    exampleInput: { action: 'add_niagara_module', assetPath: '/Game/NS_Fire', emitterName: 'Spark', modulePath: '/Niagara/Modules/Emitter/EmitterState.EmitterState', scriptType: 'Update' }, exampleOutput: { success: true, message: 'Niagara module added', nodeId: 'A1B2C3' } }),
  buildRecord({ parentTool: T, id: `${T}.connect_niagara_pins`, action: 'connect_niagara_pins', family: F,
    summary: 'Connect Niagara graph pins.', whenToUse: ['Modules must wire together.'], whenNotToUse: ['Use add_niagara_module.'],
    inputProps: { assetPath: P.assetPath, emitterName: E.emitterName, scriptType: E.scriptType, autoConnect: E.autoConnect }, required: ['assetPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'connect_niagara_pins', assetPath: '/Game/NS_Fire', scriptType: 'Update', autoConnect: true } }),
  buildRecord({ parentTool: T, id: `${T}.remove_niagara_node`, action: 'remove_niagara_node', family: F,
    summary: 'Remove a Niagara graph node.', whenToUse: ['Node must be removed.'], whenNotToUse: ['Use connect_niagara_pins.'],
    inputProps: { assetPath: P.assetPath, systemPath: E.systemPath, emitterName: E.emitterName, scriptType: E.scriptType, nodeId: E.nodeId }, required: ['assetPath'],
    effect: 'destructive', behavior: { safeToRetry: false }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'remove_niagara_node', assetPath: '/Game/NS_Fire', nodeId: 'A1B2C3' } }),
  buildRecord({ parentTool: T, id: `${T}.set_niagara_parameter`, action: 'set_niagara_parameter', family: F,
    summary: 'Set a Niagara system parameter.', whenToUse: ['A parameter value must change.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { actorName: P.actorName, assetPath: P.assetPath, parameterName: E.parameterName, parameterType: E.parameterType, value: P.value }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_niagara_parameter', actorName: 'FX_1', parameterName: 'SpawnRate', parameterType: 'Float', value: 1.25 } }),
  buildRecord({ parentTool: T, id: `${T}.clear_debug_shapes`, action: 'clear_debug_shapes', family: F,
    summary: 'Clear all editor debug shapes.', whenToUse: ['Debug shapes must be removed.'], whenNotToUse: ['Use debug_shape.'],
    inputProps: {}, required: [], effect: 'write', editorStates: ['edit'], behavior: { safeToRetry: true }, latency: 'instant', resources: 'low',
    exampleInput: { action: 'clear_debug_shapes' } }),
  buildRecord({ parentTool: T, id: `${T}.cleanup`, action: 'cleanup', family: F,
    summary: 'Clean up transient effect authoring state.', whenToUse: ['Reset authoring session.'], whenNotToUse: ['Persist work.'],
    inputProps: { filter: E.filter }, required: [], effect: 'write', behavior: { safeToRetry: true }, latency: 'instant', resources: 'low',
    exampleInput: { action: 'cleanup', filter: 'MCP_ManageEffectDefaultActor_' } }),
  buildRecord({ parentTool: T, id: `${T}.list_debug_shapes`, action: 'list_debug_shapes', family: F,
    summary: 'List active editor debug shapes.', whenToUse: ['Enumerate debug shapes.'], whenNotToUse: ['Mutate shapes.'],
    inputProps: {}, required: [], effect: 'read', editorStates: ['edit'], latency: 'instant', resources: 'low',
    outputProps: { shapes: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'list_debug_shapes' }, exampleOutput: { success: true, message: 'Debug shapes listed', shapes: ['Sphere_0'] } }),
  buildRecord({ parentTool: T, id: `${T}.add_emitter_to_system`, action: 'add_emitter_to_system', family: F,
    summary: 'Add an emitter to a Niagara system.', whenToUse: ['System needs an emitter.'], whenNotToUse: ['Use create_niagara_emitter.'],
    inputProps: { assetPath: P.assetPath, systemPath: E.systemPath, emitterPath: P.assetPath, save: P.save }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    outputProps: { emitterName: E.emitterName }, outputRequired: [],
    exampleInput: { action: 'add_emitter_to_system', systemPath: '/Game/NS_Fire', emitterPath: '/Game/NE_Spark', save: false }, exampleOutput: { success: true, message: 'Emitter added', emitterName: 'NE_Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.set_emitter_properties`, action: 'set_emitter_properties', family: F,
    summary: 'Set emitter properties.', whenToUse: ['Emitter config must change.'], whenNotToUse: ['Use add_emitter_to_system.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, emitterProperties: E.emitterProperties, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_emitter_properties', systemPath: '/Game/NS_Fire', emitterName: 'Spark', emitterProperties: { enabled: true } } }),
  buildRecord({ parentTool: T, id: `${T}.add_spawn_rate_module`, action: 'add_spawn_rate_module', family: F,
    summary: 'Insert the SpawnRate module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Emitter spawns over time.'], whenNotToUse: ['Use add_spawn_burst_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, emitter: E.emitter, save: P.save }, required: ['systemPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spawn_rate_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spawn_burst_module`, action: 'add_spawn_burst_module', family: F,
    summary: 'Insert the SpawnBurst_Instantaneous module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Burst spawn needed.'], whenNotToUse: ['Use add_spawn_rate_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spawn_burst_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spawn_per_unit_module`, action: 'add_spawn_per_unit_module', family: F,
    summary: 'Insert the SpawnPerUnit module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Spawn along a path/unit.'], whenNotToUse: ['Use add_spawn_rate_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spawn_per_unit_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_initialize_particle_module`, action: 'add_initialize_particle_module', family: F,
    summary: 'Insert the InitializeParticle module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particle init needed.'], whenNotToUse: ['Use add_particle_state_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_initialize_particle_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_particle_state_module`, action: 'add_particle_state_module', family: F,
    summary: 'Add a particle-state module.', whenToUse: ['Particle lifecycle state needed.'], whenNotToUse: ['Use add_initialize_particle_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_particle_state_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_force_module`, action: 'add_force_module', family: F,
    summary: 'Insert the the chosen force module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particles need force.'], whenNotToUse: ['Use add_velocity_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, forceType: E.forceType, save: P.save }, required: ['systemPath', 'emitterName', 'forceType'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_force_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', forceType: 'Gravity' } }),
  buildRecord({ parentTool: T, id: `${T}.add_velocity_module`, action: 'add_velocity_module', family: F,
    summary: 'Add a velocity module.', whenToUse: ['Particles need velocity.'], whenNotToUse: ['Use add_force_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, velocityMode: E.velocityMode, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_velocity_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', velocityMode: 'Linear' } }),
  buildRecord({ parentTool: T, id: `${T}.add_acceleration_module`, action: 'add_acceleration_module', family: F,
    summary: 'Insert the AccelerationForce module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particles need acceleration.'], whenNotToUse: ['Use add_velocity_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_acceleration_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_size_module`, action: 'add_size_module', family: F,
    summary: 'Insert the ScaleSpriteSize module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particle size must change.'], whenNotToUse: ['Use add_color_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_size_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_color_module`, action: 'add_color_module', family: F,
    summary: 'Insert the Color module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particle color must change.'], whenNotToUse: ['Use add_size_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: ['systemPath', 'emitterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_color_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_user_parameter`, action: 'add_user_parameter', family: F,
    summary: 'Add a user parameter to a system.', whenToUse: ['Expose a user param.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { systemPath: E.systemPath, parameterName: E.parameterName, parameterType: E.parameterType, save: P.save }, required: ['systemPath', 'parameterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_user_parameter', systemPath: '/Game/NS_Fire', parameterName: 'Intensity', parameterType: 'Float' } }),
  buildRecord({ parentTool: T, id: `${T}.set_parameter_value`, action: 'set_parameter_value', family: F,
    summary: 'Set a user parameter value.', whenToUse: ['Param value must change.'], whenNotToUse: ['Use add_user_parameter.'],
    inputProps: { systemPath: E.systemPath, parameterName: E.parameterName, parameterValue: E.parameterValue, save: P.save }, required: ['systemPath', 'parameterName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_parameter_value', systemPath: '/Game/NS_Fire', parameterName: 'Intensity', parameterValue: 2 } }),
  buildRecord({ parentTool: T, id: `${T}.bind_parameter_to_source`, action: 'bind_parameter_to_source', family: F,
    summary: 'Bind a parameter to a data source.', whenToUse: ['Param driven externally.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, parameterType: E.parameterType, sourceBinding: E.sourceBinding, save: P.save }, required: ['systemPath', 'parameterName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'bind_parameter_to_source', systemPath: '/Game/NS_Fire', parameterName: 'Intensity', sourceBinding: 'Emitter.Age' } }),
  buildRecord({ parentTool: T, id: `${T}.set_niagara_dynamic_input`, action: 'set_niagara_dynamic_input', family: F,
    summary: 'Configure a Niagara dynamic input expression.', whenToUse: ['Expression-driven value needed.'], whenNotToUse: ['Use set_parameter_value.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, targetNodeId: E.targetNodeId, moduleName: { type: 'string', description: 'Module (function call) name that owns inputName; alternative to targetNodeId.' }, inputName: E.inputName, dynamicInputScriptPath: E.dynamicInputScriptPath, replaceExisting: E.replaceExisting, save: P.save }, required: ['systemPath', 'inputName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'set_niagara_dynamic_input', systemPath: '/Game/NS_Fire', inputName: 'EmitterState.ScaleSpawnCountCurve', dynamicInputScriptPath: '/Niagara/DynamicInputs/Add/Add_Float.Add_Float' } }),
  buildRecord({ parentTool: T, id: `${T}.add_sprite_renderer_module`, action: 'add_sprite_renderer_module', family: F,
    summary: 'Add a sprite renderer module.', whenToUse: ['Sprite rendering needed.'], whenNotToUse: ['Use add_mesh_renderer_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, materialPath: E.materialPath, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_sprite_renderer_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', materialPath: '/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial' } }),
  buildRecord({ parentTool: T, id: `${T}.add_mesh_renderer_module`, action: 'add_mesh_renderer_module', family: F,
    summary: 'Add a mesh renderer module.', whenToUse: ['Mesh rendering needed.'], whenNotToUse: ['Use add_sprite_renderer_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, meshPath: P.meshPath, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_mesh_renderer_module', systemPath: '/Game/NS_Debris', emitterName: 'Chunks', meshPath: '/Engine/BasicShapes/Cube.Cube' } }),
  buildRecord({ parentTool: T, id: `${T}.add_ribbon_renderer_module`, action: 'add_ribbon_renderer_module', family: F,
    summary: 'Add a ribbon renderer module.', whenToUse: ['Ribbon/trail rendering.'], whenNotToUse: ['Use add_mesh_renderer_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, materialPath: E.materialPath, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_ribbon_renderer_module', systemPath: '/Game/NS_Trail', emitterName: 'Trail' } }),
  buildRecord({ parentTool: T, id: `${T}.add_light_renderer_module`, action: 'add_light_renderer_module', family: F,
    summary: 'Add a light renderer module.', whenToUse: ['Per-particle light needed.'], whenNotToUse: ['Use add_sprite_renderer_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, lightRadius: E.lightRadius, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_light_renderer_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark', lightRadius: 200 } }),
  buildRecord({ parentTool: T, id: `${T}.add_collision_module`, action: 'add_collision_module', family: F,
    summary: 'Insert the Collision module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particles must collide.'], whenNotToUse: ['Use add_kill_particles_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_collision_module', systemPath: '/Game/NS_Debris', emitterName: 'Chunks' } }),
  buildRecord({ parentTool: T, id: `${T}.add_kill_particles_module`, action: 'add_kill_particles_module', family: F,
    summary: 'Insert the KillParticles module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Particles must die on condition.'], whenNotToUse: ['Use add_collision_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_kill_particles_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_camera_offset_module`, action: 'add_camera_offset_module', family: F,
    summary: 'Insert the CameraOffset module with its default inputs; tune them with set_parameter_value (parameterName "<Module>.<Input>").', whenToUse: ['Camera-relative particles.'], whenNotToUse: ['Use add_velocity_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_camera_offset_module', systemPath: '/Game/NS_Fire', emitterName: 'Spark' } }),
  buildRecord({ parentTool: T, id: `${T}.add_skeletal_mesh_data_interface`, action: 'add_skeletal_mesh_data_interface', family: F,
    summary: 'Add a skeletal-mesh data interface.', whenToUse: ['Read skeletal mesh data.'], whenNotToUse: ['Use add_static_mesh_data_interface.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_skeletal_mesh_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'SkelDI' } }),
  buildRecord({ parentTool: T, id: `${T}.add_static_mesh_data_interface`, action: 'add_static_mesh_data_interface', family: F,
    summary: 'Add a static-mesh data interface.', whenToUse: ['Read static mesh data.'], whenNotToUse: ['Use add_skeletal_mesh_data_interface.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_static_mesh_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'StaticDI' } }),
  buildRecord({ parentTool: T, id: `${T}.add_spline_data_interface`, action: 'add_spline_data_interface', family: F,
    summary: 'Add a spline data interface.', whenToUse: ['Sample spline data.'], whenNotToUse: ['Use add_static_mesh_data_interface.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_spline_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'SplineDI' } }),
  buildRecord({ parentTool: T, id: `${T}.add_audio_spectrum_data_interface`, action: 'add_audio_spectrum_data_interface', family: F,
    summary: 'Add an audio-spectrum data interface.', whenToUse: ['Audio-reactive particles.'], whenNotToUse: ['Use add_spline_data_interface.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_audio_spectrum_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'AudioDI' } }),
  buildRecord({ parentTool: T, id: `${T}.add_collision_query_data_interface`, action: 'add_collision_query_data_interface', family: F,
    summary: 'Add a collision-query data interface.', whenToUse: ['Query collisions in graph.'], whenNotToUse: ['Use add_collision_module.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, parameterName: E.parameterName, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_collision_query_data_interface', systemPath: '/Game/NS_Fire', emitterName: 'Spark', parameterName: 'CollisionDI' } }),
  buildRecord({ parentTool: T, id: `${T}.add_event_generator`, action: 'add_event_generator', family: F,
    summary: 'Add a Niagara event generator.', whenToUse: ['Emitter emits events.'], whenNotToUse: ['Use add_event_receiver.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, eventName: E.eventName, eventType: E.eventType, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_event_generator', systemPath: '/Game/NS_Fire', emitterName: 'Spark', eventName: 'Burst', eventType: 'Location' } }),
  buildRecord({ parentTool: T, id: `${T}.add_event_receiver`, action: 'add_event_receiver', family: F,
    summary: 'Add a Niagara event receiver.', whenToUse: ['Emitter consumes events.'], whenNotToUse: ['Use add_event_generator.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, eventName: E.eventName, spawnOnEvent: E.spawnOnEvent, eventSpawnCount: E.eventSpawnCount, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_event_receiver', systemPath: '/Game/NS_Fire', emitterName: 'Spark', eventName: 'Burst', spawnOnEvent: true, eventSpawnCount: 2 } }),
  buildRecord({ parentTool: T, id: `${T}.enable_gpu_simulation`, action: 'enable_gpu_simulation', family: F,
    summary: 'Enable GPU simulation on a system.', whenToUse: ['GPU particles needed.'], whenNotToUse: ['Use add_simulation_stage.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, fixedBoundsEnabled: E.fixedBoundsEnabled, deterministicEnabled: E.deterministicEnabled, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'medium', plugins: NIAGARA,
    exampleInput: { action: 'enable_gpu_simulation', systemPath: '/Game/NS_Fire', emitterName: 'Spark', fixedBoundsEnabled: true } }),
  buildRecord({ parentTool: T, id: `${T}.add_simulation_stage`, action: 'add_simulation_stage', family: F,
    summary: 'Add a simulation stage.', whenToUse: ['Custom sim stage needed.'], whenNotToUse: ['Use enable_gpu_simulation.'],
    inputProps: { systemPath: E.systemPath, emitterName: E.emitterName, stageName: E.stageName, stageIterationSource: E.stageIterationSource, save: P.save }, required: EMITTER_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: NIAGARA,
    exampleInput: { action: 'add_simulation_stage', systemPath: '/Game/NS_Fire', emitterName: 'Spark', stageName: 'Stage_0', stageIterationSource: 'Particles' } }),
  buildRecord({ parentTool: T, id: `${T}.get_niagara_info`, action: 'get_niagara_info', family: F,
    summary: 'Read Niagara system metadata.', whenToUse: ['Inspect a Niagara system.'], whenNotToUse: ['Mutate the system.'],
    inputProps: { assetPath: P.assetPath }, required: ['assetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: NIAGARA,
    outputProps: { emitterCount: P.num_ }, outputRequired: [],
    exampleInput: { action: 'get_niagara_info', assetPath: '/Game/NS_Fire' }, exampleOutput: { success: true, message: 'Niagara info', emitterCount: 2 } }),
  buildRecord({ parentTool: T, id: `${T}.validate_niagara_system`, action: 'validate_niagara_system', family: F,
    summary: 'Validate a Niagara system for errors.', whenToUse: ['Catch authoring errors.'], whenNotToUse: ['Use get_niagara_info.'],
    inputProps: { systemPath: E.systemPath, assetPath: P.assetPath, system: E.system }, required: [], requiredOneOf: ['systemPath', 'assetPath', 'system'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: NIAGARA,
    outputProps: { valid: P.bool_, errors: P.arrayOfStrings, warnings: P.arrayOfStrings }, outputRequired: ['valid'],
    exampleInput: { action: 'validate_niagara_system', systemPath: '/Game/NS_Fire' }, exampleOutput: { success: true, message: 'Niagara validated', valid: true, errors: [] } }),
];
