#!/usr/bin/env node
import path from 'node:path';
import { pathToFileURL } from 'node:url';
/**
 * Comprehensive Integration Test Suite for Utility Tools - Part 1
 *
 * Covers first half of MCP tools:
 * - manage_data (62 actions) = 124 tests
 * - manage_build (48 actions) = 96 tests
 * - manage_editor_utilities (45 actions) = 90 tests
 * - manage_performance (20 actions) = 40 tests
 * - manage_character_avatar - MetaHuman & Groom/Hair (32 actions) = 64 tests
 *
 * Usage:
 *   node tests/category-tests/utility-tools-part1.test.mjs
 */

import { runToolTests } from '../test-runner.mjs';

const TEST_FOLDER = '/Game/UtilityToolsTest';
const ADV_TEST_FOLDER = '/Game/UtilityToolsAdvTest';

export const utilityToolsTestsPart1 = [
  // ============================================================================
  // SETUP: Create test folders
  // ============================================================================
  { scenario: 'Setup: create test folder', toolName: 'manage_asset', arguments: { action: 'create_folder', path: TEST_FOLDER }, expected: 'success|already exists' },
  { scenario: 'Setup: create advanced test folder', toolName: 'manage_asset', arguments: { action: 'create_folder', path: ADV_TEST_FOLDER }, expected: 'success|already exists' },
  { scenario: 'Setup: spawn test actor', toolName: 'control_actor', arguments: { action: 'spawn', classPath: '/Engine/BasicShapes/Cube', actorName: 'UT_TestCube', location: { x: 0, y: 0, z: 100 } }, expected: 'success' },
  { scenario: 'Setup: spawn second test actor', toolName: 'control_actor', arguments: { action: 'spawn', classPath: '/Engine/BasicShapes/Sphere', actorName: 'UT_TestSphere', location: { x: 200, y: 0, z: 100 } }, expected: 'success' },

  // ============================================================================
  // manage_data (62 actions) - 124 tests
  // ============================================================================
  // Data Assets (4 actions x 2 = 8 tests)
  { scenario: 'Data: create_data_asset success', toolName: 'manage_data', arguments: { action: 'create_data_asset', assetPath: `${TEST_FOLDER}/DA_TestItem` }, expected: 'success|already exists' },
  { scenario: 'Data: create_data_asset with class', toolName: 'manage_data', arguments: { action: 'create_data_asset', assetPath: `${TEST_FOLDER}/DA_TestItem2`, dataAssetClass: '/Script/Engine.DataAsset' }, expected: 'success|already exists' },
  { scenario: 'Data: create_primary_data_asset success', toolName: 'manage_data', arguments: { action: 'create_primary_data_asset', assetPath: `${TEST_FOLDER}/PDA_TestPrimary`, primaryAssetType: 'TestType', primaryAssetName: 'TestAsset' }, expected: 'success|already exists' },
  { scenario: 'Data: create_primary_data_asset alternate', toolName: 'manage_data', arguments: { action: 'create_primary_data_asset', assetPath: `${TEST_FOLDER}/PDA_TestPrimary2`, primaryAssetType: 'ItemType', primaryAssetName: 'Item001' }, expected: 'success|already exists' },
  { scenario: 'Data: get_data_asset_info success', toolName: 'manage_data', arguments: { action: 'get_data_asset_info', assetPath: `${TEST_FOLDER}/DA_TestItem` }, expected: 'success|not found' },
  { scenario: 'Data: get_data_asset_info not found', toolName: 'manage_data', arguments: { action: 'get_data_asset_info', assetPath: '/Game/NonExistent/DA_Missing' }, expected: 'not found|error' },
  { scenario: 'Data: set_data_asset_property success', toolName: 'manage_data', arguments: { action: 'set_data_asset_property', assetPath: `${TEST_FOLDER}/DA_TestItem`, propertyName: 'ItemName', propertyValue: 'Test Item' }, expected: 'success|not found' },
  { scenario: 'Data: set_data_asset_property invalid', toolName: 'manage_data', arguments: { action: 'set_data_asset_property', assetPath: '/Game/NonExistent', propertyName: 'Test', propertyValue: 'Value' }, expected: 'not found|error' },

  // Data Tables (8 actions x 2 = 16 tests)
  { scenario: 'Data: create_data_table success', toolName: 'manage_data', arguments: { action: 'create_data_table', assetPath: `${TEST_FOLDER}/DT_TestTable` }, expected: 'success|already exists' },
  { scenario: 'Data: create_data_table with struct', toolName: 'manage_data', arguments: { action: 'create_data_table', assetPath: `${TEST_FOLDER}/DT_TestTable2`, rowStructPath: '/Script/Engine.TableRowBase' }, expected: 'success|already exists' },
  { scenario: 'Data: add_data_table_row success', toolName: 'manage_data', arguments: { action: 'add_data_table_row', assetPath: `${TEST_FOLDER}/DT_TestTable`, rowName: 'Row001', rowData: { Name: 'TestItem', Value: 100 } }, expected: 'success|not found' },
  { scenario: 'Data: add_data_table_row second', toolName: 'manage_data', arguments: { action: 'add_data_table_row', assetPath: `${TEST_FOLDER}/DT_TestTable`, rowName: 'Row002', rowData: { Name: 'TestItem2', Value: 200 } }, expected: 'success|not found' },
  { scenario: 'Data: get_data_table_row success', toolName: 'manage_data', arguments: { action: 'get_data_table_row', assetPath: `${TEST_FOLDER}/DT_TestTable`, rowName: 'Row001' }, expected: 'success|not found' },
  { scenario: 'Data: get_data_table_row missing', toolName: 'manage_data', arguments: { action: 'get_data_table_row', assetPath: `${TEST_FOLDER}/DT_TestTable`, rowName: 'NonExistent' }, expected: 'not found|success' },
  { scenario: 'Data: get_data_table_rows success', toolName: 'manage_data', arguments: { action: 'get_data_table_rows', assetPath: `${TEST_FOLDER}/DT_TestTable` }, expected: 'success|not found' },
  { scenario: 'Data: get_data_table_rows not found', toolName: 'manage_data', arguments: { action: 'get_data_table_rows', assetPath: '/Game/NonExistent/DT_Missing' }, expected: 'not found|error' },
  { scenario: 'Data: remove_data_table_row success', toolName: 'manage_data', arguments: { action: 'remove_data_table_row', assetPath: `${TEST_FOLDER}/DT_TestTable`, rowName: 'Row002' }, expected: 'success|not found' },
  { scenario: 'Data: remove_data_table_row missing', toolName: 'manage_data', arguments: { action: 'remove_data_table_row', assetPath: `${TEST_FOLDER}/DT_TestTable`, rowName: 'NonExistent' }, expected: 'not found|success' },
  { scenario: 'Data: import_data_table_csv success', toolName: 'manage_data', arguments: { action: 'import_data_table_csv', assetPath: `${TEST_FOLDER}/DT_TestTable`, csvString: 'Name,Value\nItem1,50\nItem2,100' }, expected: 'success|not found' },
  { scenario: 'Data: import_data_table_csv empty', toolName: 'manage_data', arguments: { action: 'import_data_table_csv', assetPath: `${TEST_FOLDER}/DT_TestTable`, csvString: '' }, expected: 'success|error|not found' },
  { scenario: 'Data: export_data_table_csv success', toolName: 'manage_data', arguments: { action: 'export_data_table_csv', assetPath: `${TEST_FOLDER}/DT_TestTable` }, expected: 'success|not found' },
  { scenario: 'Data: export_data_table_csv not found', toolName: 'manage_data', arguments: { action: 'export_data_table_csv', assetPath: '/Game/NonExistent/DT_Missing' }, expected: 'not found|error' },
  { scenario: 'Data: empty_data_table success', toolName: 'manage_data', arguments: { action: 'empty_data_table', assetPath: `${TEST_FOLDER}/DT_TestTable` }, expected: 'success|not found' },
  { scenario: 'Data: empty_data_table not found', toolName: 'manage_data', arguments: { action: 'empty_data_table', assetPath: '/Game/NonExistent/DT_Missing' }, expected: 'not found|error' },

  // Curve Tables (5 actions x 2 = 10 tests)
  { scenario: 'Data: create_curve_table success', toolName: 'manage_data', arguments: { action: 'create_curve_table', assetPath: `${TEST_FOLDER}/CT_TestCurve` }, expected: 'success|already exists' },
  { scenario: 'Data: create_curve_table alternate', toolName: 'manage_data', arguments: { action: 'create_curve_table', assetPath: `${TEST_FOLDER}/CT_TestCurve2` }, expected: 'success|already exists' },
  { scenario: 'Data: add_curve_row success', toolName: 'manage_data', arguments: { action: 'add_curve_row', assetPath: `${TEST_FOLDER}/CT_TestCurve`, rowName: 'DamageCurve', keys: [{ time: 0, value: 0 }, { time: 1, value: 100 }] }, expected: 'success|not found' },
  { scenario: 'Data: add_curve_row second', toolName: 'manage_data', arguments: { action: 'add_curve_row', assetPath: `${TEST_FOLDER}/CT_TestCurve`, rowName: 'HealCurve', keys: [{ time: 0, value: 100 }, { time: 1, value: 0 }] }, expected: 'success|not found' },
  { scenario: 'Data: get_curve_value success', toolName: 'manage_data', arguments: { action: 'get_curve_value', assetPath: `${TEST_FOLDER}/CT_TestCurve`, rowName: 'DamageCurve', keyTime: 0.5 }, expected: 'success|not found' },
  { scenario: 'Data: get_curve_value edge', toolName: 'manage_data', arguments: { action: 'get_curve_value', assetPath: `${TEST_FOLDER}/CT_TestCurve`, rowName: 'DamageCurve', keyTime: 0 }, expected: 'success|not found' },
  { scenario: 'Data: import_curve_table_csv success', toolName: 'manage_data', arguments: { action: 'import_curve_table_csv', assetPath: `${TEST_FOLDER}/CT_TestCurve`, csvString: '---,0,0.5,1\nCurve1,0,50,100' }, expected: 'success|not found' },
  { scenario: 'Data: import_curve_table_csv empty', toolName: 'manage_data', arguments: { action: 'import_curve_table_csv', assetPath: `${TEST_FOLDER}/CT_TestCurve`, csvString: '' }, expected: 'success|error|not found' },
  { scenario: 'Data: export_curve_table_csv success', toolName: 'manage_data', arguments: { action: 'export_curve_table_csv', assetPath: `${TEST_FOLDER}/CT_TestCurve` }, expected: 'success|not found' },
  { scenario: 'Data: export_curve_table_csv not found', toolName: 'manage_data', arguments: { action: 'export_curve_table_csv', assetPath: '/Game/NonExistent/CT_Missing' }, expected: 'not found|error' },

  // Save Game (6 actions x 2 = 12 tests)
  { scenario: 'Data: create_save_game_blueprint success', toolName: 'manage_data', arguments: { action: 'create_save_game_blueprint', assetPath: `${TEST_FOLDER}/BP_TestSaveGame` }, expected: 'success|already exists' },
  { scenario: 'Data: create_save_game_blueprint alternate', toolName: 'manage_data', arguments: { action: 'create_save_game_blueprint', assetPath: `${TEST_FOLDER}/BP_TestSaveGame2` }, expected: 'success|already exists' },
  { scenario: 'Data: does_save_exist success', toolName: 'manage_data', arguments: { action: 'does_save_exist', slotName: 'UtilityTestSlot' }, expected: 'success' },
  { scenario: 'Data: does_save_exist nonexistent', toolName: 'manage_data', arguments: { action: 'does_save_exist', slotName: 'NonExistentSlot12345' }, expected: 'success' },
  { scenario: 'Data: save_game_to_slot success', toolName: 'manage_data', arguments: { action: 'save_game_to_slot', slotName: 'UtilityTestSlot', userIndex: 0, saveData: { level: 5, score: 1000 } }, expected: 'success' },
  { scenario: 'Data: save_game_to_slot complex', toolName: 'manage_data', arguments: { action: 'save_game_to_slot', slotName: 'UtilityTestSlot2', userIndex: 0, saveData: { level: 10, score: 5000, inventory: ['item1', 'item2'], position: { x: 100, y: 200, z: 50 } } }, expected: 'success' },
  { scenario: 'Data: load_game_from_slot success', toolName: 'manage_data', arguments: { action: 'load_game_from_slot', slotName: 'UtilityTestSlot', userIndex: 0 }, expected: 'success|not found' },
  { scenario: 'Data: load_game_from_slot missing', toolName: 'manage_data', arguments: { action: 'load_game_from_slot', slotName: 'NonExistentSlot', userIndex: 0 }, expected: 'not found|success' },
  { scenario: 'Data: get_save_slot_names success', toolName: 'manage_data', arguments: { action: 'get_save_slot_names' }, expected: 'success' },
  { scenario: 'Data: get_save_slot_names with filter', toolName: 'manage_data', arguments: { action: 'get_save_slot_names', filter: 'Utility' }, expected: 'success' },
  { scenario: 'Data: delete_save_slot success', toolName: 'manage_data', arguments: { action: 'delete_save_slot', slotName: 'UtilityTestSlot' }, expected: 'success|not found' },
  { scenario: 'Data: delete_save_slot missing', toolName: 'manage_data', arguments: { action: 'delete_save_slot', slotName: 'NonExistentSlot' }, expected: 'not found|success' },

  // Gameplay Tags (9 actions x 2 = 18 tests)
  { scenario: 'Data: get_all_gameplay_tags success', toolName: 'manage_data', arguments: { action: 'get_all_gameplay_tags' }, expected: 'success' },
  { scenario: 'Data: get_all_gameplay_tags filtered', toolName: 'manage_data', arguments: { action: 'get_all_gameplay_tags', filter: 'Ability' }, expected: 'success' },
  { scenario: 'Data: create_gameplay_tag success', toolName: 'manage_data', arguments: { action: 'create_gameplay_tag', tagName: 'Test.Utility.Tag1' }, expected: 'success' },
  { scenario: 'Data: create_gameplay_tag nested', toolName: 'manage_data', arguments: { action: 'create_gameplay_tag', tagName: 'Test.Utility.Nested.Deep.Tag' }, expected: 'success' },
  { scenario: 'Data: add_native_gameplay_tag success', toolName: 'manage_data', arguments: { action: 'add_native_gameplay_tag', tagName: 'Test.Utility.NativeTag', tagDevComment: 'Test native tag' }, expected: 'success' },
  { scenario: 'Data: add_native_gameplay_tag alternate', toolName: 'manage_data', arguments: { action: 'add_native_gameplay_tag', tagName: 'Test.Utility.NativeTag2', tagDevComment: 'Another native tag' }, expected: 'success' },
  { scenario: 'Data: request_gameplay_tag success', toolName: 'manage_data', arguments: { action: 'request_gameplay_tag', tagName: 'Ability.Sprint' }, expected: 'success' },
  { scenario: 'Data: request_gameplay_tag custom', toolName: 'manage_data', arguments: { action: 'request_gameplay_tag', tagName: 'Test.Utility.Tag1' }, expected: 'success' },
  { scenario: 'Data: check_tag_match success', toolName: 'manage_data', arguments: { action: 'check_tag_match', tagName: 'Test.Utility', tagToCheck: 'Test.Utility.Tag1' }, expected: 'success' },
  { scenario: 'Data: check_tag_match exact', toolName: 'manage_data', arguments: { action: 'check_tag_match', tagName: 'Test.Utility.Tag1', tagToCheck: 'Test.Utility.Tag1', exactMatch: true }, expected: 'success' },
  { scenario: 'Data: create_tag_container success', toolName: 'manage_data', arguments: { action: 'create_tag_container', containerName: 'TestContainer' }, expected: 'success' },
  { scenario: 'Data: create_tag_container alternate', toolName: 'manage_data', arguments: { action: 'create_tag_container', containerName: 'TestContainer2' }, expected: 'success' },
  { scenario: 'Data: add_tag_to_container success', toolName: 'manage_data', arguments: { action: 'add_tag_to_container', containerName: 'TestContainer', tagName: 'Test.Utility.Tag1' }, expected: 'success' },
  { scenario: 'Data: add_tag_to_container multiple', toolName: 'manage_data', arguments: { action: 'add_tag_to_container', containerName: 'TestContainer', tagName: 'Test.Utility.NativeTag' }, expected: 'success' },
  { scenario: 'Data: remove_tag_from_container success', toolName: 'manage_data', arguments: { action: 'remove_tag_from_container', containerName: 'TestContainer', tagName: 'Test.Utility.Tag1' }, expected: 'success' },
  { scenario: 'Data: remove_tag_from_container missing', toolName: 'manage_data', arguments: { action: 'remove_tag_from_container', containerName: 'TestContainer', tagName: 'NonExistent.Tag' }, expected: 'success|not found' },
  { scenario: 'Data: has_tag success', toolName: 'manage_data', arguments: { action: 'has_tag', containerName: 'TestContainer', tagName: 'Test.Utility.Tag1' }, expected: 'success' },
  { scenario: 'Data: has_tag missing', toolName: 'manage_data', arguments: { action: 'has_tag', containerName: 'TestContainer', tagName: 'NonExistent.Tag' }, expected: 'success' },

  // Config (5 actions x 2 = 10 tests)
  { scenario: 'Data: read_config_value success', toolName: 'manage_data', arguments: { action: 'read_config_value', configSection: '/Script/Engine.Engine', configKey: 'bEnableOnScreenDebugMessages', configName: 'Engine' }, expected: 'success|not found' },
  { scenario: 'Data: read_config_value game', toolName: 'manage_data', arguments: { action: 'read_config_value', configSection: '/Script/EngineSettings.GameMapsSettings', configKey: 'GlobalDefaultGameMode', configName: 'Game' }, expected: 'success|not found' },
  { scenario: 'Data: get_config_section success', toolName: 'manage_data', arguments: { action: 'get_config_section', configSection: '/Script/Engine.Engine', configName: 'Engine' }, expected: 'success|not found' },
  { scenario: 'Data: get_config_section missing', toolName: 'manage_data', arguments: { action: 'get_config_section', configSection: 'NonExistent', configName: 'Engine' }, expected: 'success|not found' },
  { scenario: 'Data: write_config_value success', toolName: 'manage_data', arguments: { action: 'write_config_value', configSection: '/Script/McpTest', configKey: 'TestValue', configValue: 'TestData', configName: 'Engine' }, expected: 'success' },
  { scenario: 'Data: write_config_value alternate', toolName: 'manage_data', arguments: { action: 'write_config_value', configSection: '/Script/McpTest', configKey: 'TestValue2', configValue: '12345', configName: 'Engine' }, expected: 'success' },
  { scenario: 'Data: flush_config success', toolName: 'manage_data', arguments: { action: 'flush_config', configName: 'Engine' }, expected: 'success' },
  { scenario: 'Data: flush_config game', toolName: 'manage_data', arguments: { action: 'flush_config', configName: 'Game' }, expected: 'success' },
  { scenario: 'Data: reload_config success', toolName: 'manage_data', arguments: { action: 'reload_config', configName: 'Engine' }, expected: 'success' },
  { scenario: 'Data: reload_config game', toolName: 'manage_data', arguments: { action: 'reload_config', configName: 'Game' }, expected: 'success' },

  // Modding/UGC (25 actions x 2 = 50 tests)
  { scenario: 'Data: configure_mod_loading_paths success', toolName: 'manage_data', arguments: { action: 'configure_mod_loading_paths' }, expected: 'success' },
  { scenario: 'Data: configure_mod_loading_paths with paths', toolName: 'manage_data', arguments: { action: 'configure_mod_loading_paths', modPaths: ['/Mods', '/DLC'] }, expected: 'success' },
  { scenario: 'Data: scan_for_mod_paks success', toolName: 'manage_data', arguments: { action: 'scan_for_mod_paks' }, expected: 'success' },
  { scenario: 'Data: scan_for_mod_paks with path', toolName: 'manage_data', arguments: { action: 'scan_for_mod_paks', scanPath: '/Game/Mods' }, expected: 'success' },
  { scenario: 'Data: list_installed_mods success', toolName: 'manage_data', arguments: { action: 'list_installed_mods' }, expected: 'success' },
  { scenario: 'Data: list_installed_mods with filter', toolName: 'manage_data', arguments: { action: 'list_installed_mods', filter: 'enabled' }, expected: 'success' },
  { scenario: 'Data: get_mod_info non-existent', toolName: 'manage_data', arguments: { action: 'get_mod_info', assetPath: '/Game/Mods/NonExistent' }, expected: 'not found|success' },
  { scenario: 'Data: get_mod_info missing', toolName: 'manage_data', arguments: { action: 'get_mod_info', assetPath: '/Game/Mods/Missing' }, expected: 'not found|success' },
  { scenario: 'Data: load_mod_pak non-existent', toolName: 'manage_data', arguments: { action: 'load_mod_pak', assetPath: '/Game/Mods/NonExistent.pak' }, expected: 'not found|error|success' },
  { scenario: 'Data: load_mod_pak invalid', toolName: 'manage_data', arguments: { action: 'load_mod_pak', assetPath: '/Game/Mods/Invalid.pak' }, expected: 'not found|error|success' },
  { scenario: 'Data: unload_mod_pak non-existent', toolName: 'manage_data', arguments: { action: 'unload_mod_pak', assetPath: '/Game/Mods/NonExistent.pak' }, expected: 'not found|error|success' },
  { scenario: 'Data: unload_mod_pak invalid', toolName: 'manage_data', arguments: { action: 'unload_mod_pak', assetPath: '/Game/Mods/NotLoaded.pak' }, expected: 'not found|error|success' },
  { scenario: 'Data: validate_mod_pak success', toolName: 'manage_data', arguments: { action: 'validate_mod_pak', assetPath: '/Game/Mods/Test.pak' }, expected: 'success|not found' },
  { scenario: 'Data: validate_mod_pak missing', toolName: 'manage_data', arguments: { action: 'validate_mod_pak', assetPath: '/Game/Mods/Missing.pak' }, expected: 'not found|success' },
  { scenario: 'Data: configure_mod_load_order success', toolName: 'manage_data', arguments: { action: 'configure_mod_load_order' }, expected: 'success' },
  { scenario: 'Data: configure_mod_load_order with order', toolName: 'manage_data', arguments: { action: 'configure_mod_load_order', loadOrder: ['Mod1', 'Mod2'] }, expected: 'success' },
  { scenario: 'Data: enable_mod success', toolName: 'manage_data', arguments: { action: 'enable_mod', assetPath: '/Game/Mods/TestMod' }, expected: 'success|not found' },
  { scenario: 'Data: enable_mod missing', toolName: 'manage_data', arguments: { action: 'enable_mod', assetPath: '/Game/Mods/MissingMod' }, expected: 'success|not found' },
  { scenario: 'Data: disable_mod success', toolName: 'manage_data', arguments: { action: 'disable_mod', assetPath: '/Game/Mods/TestMod' }, expected: 'success|not found' },
  { scenario: 'Data: disable_mod missing', toolName: 'manage_data', arguments: { action: 'disable_mod', assetPath: '/Game/Mods/MissingMod' }, expected: 'success|not found' },
  { scenario: 'Data: check_mod_compatibility success', toolName: 'manage_data', arguments: { action: 'check_mod_compatibility', assetPath: '/Game/Mods/TestMod' }, expected: 'success' },
  { scenario: 'Data: check_mod_compatibility version', toolName: 'manage_data', arguments: { action: 'check_mod_compatibility', assetPath: '/Game/Mods/TestMod', engineVersion: '5.3' }, expected: 'success' },
  { scenario: 'Data: configure_asset_override_paths success', toolName: 'manage_data', arguments: { action: 'configure_asset_override_paths' }, expected: 'success' },
  { scenario: 'Data: configure_asset_override_paths with paths', toolName: 'manage_data', arguments: { action: 'configure_asset_override_paths', overridePaths: ['/Game/Overrides'] }, expected: 'success' },
  { scenario: 'Data: register_mod_asset_redirect success', toolName: 'manage_data', arguments: { action: 'register_mod_asset_redirect', assetPath: '/Game/Original', propertyValue: '/Game/Modded' }, expected: 'success' },
  { scenario: 'Data: register_mod_asset_redirect multiple', toolName: 'manage_data', arguments: { action: 'register_mod_asset_redirect', assetPath: '/Game/Original2', propertyValue: '/Game/Modded2' }, expected: 'success' },
  { scenario: 'Data: restore_original_asset success', toolName: 'manage_data', arguments: { action: 'restore_original_asset', assetPath: '/Game/Original' }, expected: 'success|not found' },
  { scenario: 'Data: restore_original_asset missing', toolName: 'manage_data', arguments: { action: 'restore_original_asset', assetPath: '/Game/NonExistent' }, expected: 'success|not found' },
  { scenario: 'Data: list_asset_overrides success', toolName: 'manage_data', arguments: { action: 'list_asset_overrides' }, expected: 'success' },
  { scenario: 'Data: list_asset_overrides filtered', toolName: 'manage_data', arguments: { action: 'list_asset_overrides', filter: '/Game' }, expected: 'success' },
  { scenario: 'Data: export_moddable_headers success', toolName: 'manage_data', arguments: { action: 'export_moddable_headers' }, expected: 'success' },
  { scenario: 'Data: export_moddable_headers with path', toolName: 'manage_data', arguments: { action: 'export_moddable_headers', exportPath: '/Path/to/headers' }, expected: 'success' },
  { scenario: 'Data: create_mod_template_project success', toolName: 'manage_data', arguments: { action: 'create_mod_template_project' }, expected: 'success' },
  { scenario: 'Data: create_mod_template_project named', toolName: 'manage_data', arguments: { action: 'create_mod_template_project', projectName: 'TestModProject' }, expected: 'success' },
  { scenario: 'Data: configure_exposed_classes success', toolName: 'manage_data', arguments: { action: 'configure_exposed_classes' }, expected: 'success' },
  { scenario: 'Data: configure_exposed_classes with list', toolName: 'manage_data', arguments: { action: 'configure_exposed_classes', exposedClasses: ['AActor', 'UActorComponent'] }, expected: 'success' },
  { scenario: 'Data: get_sdk_config success', toolName: 'manage_data', arguments: { action: 'get_sdk_config' }, expected: 'success' },
  { scenario: 'Data: get_sdk_config verbose', toolName: 'manage_data', arguments: { action: 'get_sdk_config', verbose: true }, expected: 'success' },
  { scenario: 'Data: configure_mod_sandbox success', toolName: 'manage_data', arguments: { action: 'configure_mod_sandbox' }, expected: 'success' },
  { scenario: 'Data: configure_mod_sandbox strict', toolName: 'manage_data', arguments: { action: 'configure_mod_sandbox', strict: true }, expected: 'success' },
  { scenario: 'Data: set_allowed_mod_operations success', toolName: 'manage_data', arguments: { action: 'set_allowed_mod_operations' }, expected: 'success' },
  { scenario: 'Data: set_allowed_mod_operations list', toolName: 'manage_data', arguments: { action: 'set_allowed_mod_operations', allowedOperations: ['SpawnActor', 'ModifyProperty'] }, expected: 'success' },
  { scenario: 'Data: validate_mod_content success', toolName: 'manage_data', arguments: { action: 'validate_mod_content', assetPath: '/Game/Mods/TestMod' }, expected: 'success|not found' },
  { scenario: 'Data: validate_mod_content missing', toolName: 'manage_data', arguments: { action: 'validate_mod_content', assetPath: '/Game/Mods/MissingMod' }, expected: 'success|not found' },
  { scenario: 'Data: get_security_config success', toolName: 'manage_data', arguments: { action: 'get_security_config' }, expected: 'success' },
  { scenario: 'Data: get_security_config verbose', toolName: 'manage_data', arguments: { action: 'get_security_config', verbose: true }, expected: 'success' },
  { scenario: 'Data: get_modding_info success', toolName: 'manage_data', arguments: { action: 'get_modding_info' }, expected: 'success' },
  { scenario: 'Data: get_modding_info detailed', toolName: 'manage_data', arguments: { action: 'get_modding_info', detailed: true }, expected: 'success' },
  { scenario: 'Data: reset_mod_system success', toolName: 'manage_data', arguments: { action: 'reset_mod_system' }, expected: 'success' },
  { scenario: 'Data: reset_mod_system force', toolName: 'manage_data', arguments: { action: 'reset_mod_system', force: true }, expected: 'success' },

  // ============================================================================
  // manage_build (48 actions) - 96 tests
  // ============================================================================
  // Pipeline (7 actions x 2 = 14 tests)
  { scenario: 'Build: get_build_info success', toolName: 'manage_build', arguments: { action: 'get_build_info' }, expected: 'success' },
  { scenario: 'Build: get_build_info verbose', toolName: 'manage_build', arguments: { action: 'get_build_info', verbose: true }, expected: 'success' },
  { scenario: 'Build: run_ubt info', toolName: 'manage_build', arguments: { action: 'run_ubt', target: 'Info' }, expected: 'success|error' },
  { scenario: 'Build: run_ubt version', toolName: 'manage_build', arguments: { action: 'run_ubt', target: 'Version' }, expected: 'success|error' },
  { scenario: 'Build: generate_project_files success', toolName: 'manage_build', arguments: { action: 'generate_project_files' }, expected: 'success' },
  { scenario: 'Build: generate_project_files clean', toolName: 'manage_build', arguments: { action: 'generate_project_files', clean: true }, expected: 'success' },
  { scenario: 'Build: compile_shaders success', toolName: 'manage_build', arguments: { action: 'compile_shaders' }, expected: 'success' },
  { scenario: 'Build: compile_shaders platform', toolName: 'manage_build', arguments: { action: 'compile_shaders', platform: 'Win64' }, expected: 'success' },
  { scenario: 'Build: cook_content success', toolName: 'manage_build', arguments: { action: 'cook_content', maps: ['/Game/Maps/TestMap'] }, expected: 'success|not found' },
  { scenario: 'Build: cook_content multiple', toolName: 'manage_build', arguments: { action: 'cook_content', maps: ['/Game/Maps/Map1', '/Game/Maps/Map2'], platform: 'Win64' }, expected: 'success|not found|error' },
  { scenario: 'Build: package_project development', toolName: 'manage_build', arguments: { action: 'package_project', platform: 'Win64', configuration: 'Development' }, expected: 'success|error' },
  { scenario: 'Build: package_project shipping', toolName: 'manage_build', arguments: { action: 'package_project', platform: 'Win64', configuration: 'Shipping' }, expected: 'success|error' },
  { scenario: 'Build: configure_build_settings success', toolName: 'manage_build', arguments: { action: 'configure_build_settings', settingName: 'Test', settingValue: 'Value' }, expected: 'success' },
  { scenario: 'Build: configure_build_settings alternate', toolName: 'manage_build', arguments: { action: 'configure_build_settings', settingName: 'BuildMode', settingValue: 'Incremental' }, expected: 'success' },

  // Platform Configuration (3 actions x 2 = 6 tests)
  { scenario: 'Build: get_target_platforms success', toolName: 'manage_build', arguments: { action: 'get_target_platforms' }, expected: 'success' },
  { scenario: 'Build: get_target_platforms filtered', toolName: 'manage_build', arguments: { action: 'get_target_platforms', filter: 'desktop' }, expected: 'success' },
  { scenario: 'Build: get_platform_settings success', toolName: 'manage_build', arguments: { action: 'get_platform_settings' }, expected: 'success' },
  { scenario: 'Build: get_platform_settings platform', toolName: 'manage_build', arguments: { action: 'get_platform_settings', platform: 'Win64' }, expected: 'success' },
  { scenario: 'Build: configure_platform success', toolName: 'manage_build', arguments: { action: 'configure_platform', platform: 'Win64' }, expected: 'success' },
  { scenario: 'Build: configure_platform android', toolName: 'manage_build', arguments: { action: 'configure_platform', platform: 'Android' }, expected: 'success' },

  // Asset Validation (4 actions x 2 = 8 tests)
  { scenario: 'Build: validate_assets success', toolName: 'manage_build', arguments: { action: 'validate_assets', assetPaths: ['/Engine/BasicShapes/Cube'] }, expected: 'success' },
  { scenario: 'Build: validate_assets multiple', toolName: 'manage_build', arguments: { action: 'validate_assets', assetPaths: ['/Engine/BasicShapes/Cube', '/Engine/BasicShapes/Sphere', '/Engine/BasicShapes/Cylinder'] }, expected: 'success' },
  { scenario: 'Build: audit_assets success', toolName: 'manage_build', arguments: { action: 'audit_assets', assetPaths: ['/Engine/BasicShapes'] }, expected: 'success' },
  { scenario: 'Build: audit_assets recursive', toolName: 'manage_build', arguments: { action: 'audit_assets', assetPaths: ['/Engine'], recursive: true }, expected: 'success' },
  { scenario: 'Build: get_asset_size_info success', toolName: 'manage_build', arguments: { action: 'get_asset_size_info', assetPath: '/Engine/BasicShapes/Cube' }, expected: 'success|not found' },
  { scenario: 'Build: get_asset_size_info missing', toolName: 'manage_build', arguments: { action: 'get_asset_size_info', assetPath: '/Game/NonExistent' }, expected: 'not found|success' },
  { scenario: 'Build: get_asset_references success', toolName: 'manage_build', arguments: { action: 'get_asset_references', assetPath: '/Engine/BasicShapes/Cube' }, expected: 'success|not found' },
  { scenario: 'Build: get_asset_references missing', toolName: 'manage_build', arguments: { action: 'get_asset_references', assetPath: '/Game/NonExistent' }, expected: 'not found|success' },

  // PAK & Chunking (3 actions x 2 = 6 tests)
  { scenario: 'Build: configure_chunking success', toolName: 'manage_build', arguments: { action: 'configure_chunking' }, expected: 'success' },
  { scenario: 'Build: configure_chunking with id', toolName: 'manage_build', arguments: { action: 'configure_chunking', chunkId: 1 }, expected: 'success' },
  { scenario: 'Build: create_pak_file success', toolName: 'manage_build', arguments: { action: 'create_pak_file', pakFilePath: `${TEST_FOLDER}/TestPak.pak`, pakContentPaths: ['/Game/TestContent'] }, expected: 'success|error' },
  { scenario: 'Build: create_pak_file compressed', toolName: 'manage_build', arguments: { action: 'create_pak_file', pakFilePath: `${TEST_FOLDER}/TestPak2.pak`, pakContentPaths: ['/Game/TestContent'], compress: true }, expected: 'success|error' },
  { scenario: 'Build: configure_encryption success', toolName: 'manage_build', arguments: { action: 'configure_encryption' }, expected: 'success' },
  { scenario: 'Build: configure_encryption enabled', toolName: 'manage_build', arguments: { action: 'configure_encryption', enabled: true }, expected: 'success' },

  // Plugin Management (4 actions x 2 = 8 tests)
  { scenario: 'Build: list_plugins success', toolName: 'manage_build', arguments: { action: 'list_plugins' }, expected: 'success' },
  { scenario: 'Build: list_plugins engine', toolName: 'manage_build', arguments: { action: 'list_plugins', includeEngine: true }, expected: 'success' },
  { scenario: 'Build: get_plugin_info success', toolName: 'manage_build', arguments: { action: 'get_plugin_info', pluginName: 'McpAutomationBridge' }, expected: 'success|not found' },
  { scenario: 'Build: get_plugin_info missing', toolName: 'manage_build', arguments: { action: 'get_plugin_info', pluginName: 'NonExistentPlugin' }, expected: 'not found|success' },
  { scenario: 'Build: enable_plugin success', toolName: 'manage_build', arguments: { action: 'enable_plugin', pluginName: 'EditorScriptingUtilities' }, expected: 'success|already' },
  { scenario: 'Build: enable_plugin missing', toolName: 'manage_build', arguments: { action: 'enable_plugin', pluginName: 'NonExistentPlugin' }, expected: 'not found|success' },
  { scenario: 'Build: disable_plugin info', toolName: 'manage_build', arguments: { action: 'disable_plugin', pluginName: 'NonExistentTestPlugin' }, expected: 'success|not found' },
  { scenario: 'Build: disable_plugin missing', toolName: 'manage_build', arguments: { action: 'disable_plugin', pluginName: 'MissingPlugin' }, expected: 'not found|success' },

  // DDC Management (3 actions x 2 = 6 tests)
  { scenario: 'Build: get_ddc_stats success', toolName: 'manage_build', arguments: { action: 'get_ddc_stats' }, expected: 'success' },
  { scenario: 'Build: get_ddc_stats verbose', toolName: 'manage_build', arguments: { action: 'get_ddc_stats', verbose: true }, expected: 'success' },
  { scenario: 'Build: configure_ddc success', toolName: 'manage_build', arguments: { action: 'configure_ddc' }, expected: 'success' },
  { scenario: 'Build: configure_ddc paths', toolName: 'manage_build', arguments: { action: 'configure_ddc', ddcPath: '/Path/to/ddc' }, expected: 'success' },
  { scenario: 'Build: clear_ddc success', toolName: 'manage_build', arguments: { action: 'clear_ddc', clearLocal: true }, expected: 'success' },
  { scenario: 'Build: clear_ddc shared', toolName: 'manage_build', arguments: { action: 'clear_ddc', clearLocal: true, clearShared: true }, expected: 'success' },

  // Testing (24 actions x 2 = 48 tests)
  { scenario: 'Build: list_tests success', toolName: 'manage_build', arguments: { action: 'list_tests' }, expected: 'success' },
  { scenario: 'Build: list_tests category', toolName: 'manage_build', arguments: { action: 'list_tests', pluginCategory: 'Editor' }, expected: 'success' },
  { scenario: 'Build: run_tests success', toolName: 'manage_build', arguments: { action: 'run_tests' }, expected: 'success|error' },
  { scenario: 'Build: run_tests filter', toolName: 'manage_build', arguments: { action: 'run_tests', filter: 'Core' }, expected: 'success|error' },
  { scenario: 'Build: run_test success', toolName: 'manage_build', arguments: { action: 'run_test', pluginName: 'System.Core' }, expected: 'success|not found|error' },
  { scenario: 'Build: run_test missing', toolName: 'manage_build', arguments: { action: 'run_test', pluginName: 'NonExistent.Test' }, expected: 'not found|success|error' },
  { scenario: 'Build: get_test_results success', toolName: 'manage_build', arguments: { action: 'get_test_results' }, expected: 'success' },
  { scenario: 'Build: get_test_results filtered', toolName: 'manage_build', arguments: { action: 'get_test_results', filter: 'passed' }, expected: 'success' },
  { scenario: 'Build: get_test_info success', toolName: 'manage_build', arguments: { action: 'get_test_info', pluginName: 'System.Core' }, expected: 'success|not found' },
  { scenario: 'Build: get_test_info missing', toolName: 'manage_build', arguments: { action: 'get_test_info', pluginName: 'NonExistent.Test' }, expected: 'not found|success' },
  { scenario: 'Build: list_functional_tests success', toolName: 'manage_build', arguments: { action: 'list_functional_tests' }, expected: 'success' },
  { scenario: 'Build: list_functional_tests map', toolName: 'manage_build', arguments: { action: 'list_functional_tests', mapPath: '/Game/Maps/TestMap' }, expected: 'success' },
  { scenario: 'Build: run_functional_test success', toolName: 'manage_build', arguments: { action: 'run_functional_test', pluginName: 'TestMap' }, expected: 'success|not found' },
  { scenario: 'Build: run_functional_test missing', toolName: 'manage_build', arguments: { action: 'run_functional_test', pluginName: 'MissingMap' }, expected: 'not found|success' },
  { scenario: 'Build: get_functional_test_results success', toolName: 'manage_build', arguments: { action: 'get_functional_test_results' }, expected: 'success' },
  { scenario: 'Build: get_functional_test_results verbose', toolName: 'manage_build', arguments: { action: 'get_functional_test_results', verbose: true }, expected: 'success' },
  { scenario: 'Build: start_trace success', toolName: 'manage_build', arguments: { action: 'start_trace' }, expected: 'success|already' },
  { scenario: 'Build: start_trace named', toolName: 'manage_build', arguments: { action: 'start_trace', traceName: 'TestTrace' }, expected: 'success|already' },
  { scenario: 'Build: get_trace_status success', toolName: 'manage_build', arguments: { action: 'get_trace_status' }, expected: 'success' },
  { scenario: 'Build: get_trace_status verbose', toolName: 'manage_build', arguments: { action: 'get_trace_status', verbose: true }, expected: 'success' },
  { scenario: 'Build: stop_trace success', toolName: 'manage_build', arguments: { action: 'stop_trace' }, expected: 'success|not running' },
  { scenario: 'Build: stop_trace named', toolName: 'manage_build', arguments: { action: 'stop_trace', traceName: 'TestTrace' }, expected: 'success|not running' },
  { scenario: 'Build: enable_visual_logger success', toolName: 'manage_build', arguments: { action: 'enable_visual_logger' }, expected: 'success|already' },
  { scenario: 'Build: enable_visual_logger forced', toolName: 'manage_build', arguments: { action: 'enable_visual_logger', force: true }, expected: 'success|already' },
  { scenario: 'Build: get_visual_logger_status success', toolName: 'manage_build', arguments: { action: 'get_visual_logger_status' }, expected: 'success' },
  { scenario: 'Build: get_visual_logger_status verbose', toolName: 'manage_build', arguments: { action: 'get_visual_logger_status', verbose: true }, expected: 'success' },
  { scenario: 'Build: disable_visual_logger success', toolName: 'manage_build', arguments: { action: 'disable_visual_logger' }, expected: 'success|not enabled' },
  { scenario: 'Build: disable_visual_logger forced', toolName: 'manage_build', arguments: { action: 'disable_visual_logger', force: true }, expected: 'success|not enabled' },
  { scenario: 'Build: start_stats_capture success', toolName: 'manage_build', arguments: { action: 'start_stats_capture' }, expected: 'success|already' },
  { scenario: 'Build: start_stats_capture named', toolName: 'manage_build', arguments: { action: 'start_stats_capture', captureName: 'TestCapture' }, expected: 'success|already' },
  { scenario: 'Build: stop_stats_capture success', toolName: 'manage_build', arguments: { action: 'stop_stats_capture' }, expected: 'success|not running' },
  { scenario: 'Build: stop_stats_capture named', toolName: 'manage_build', arguments: { action: 'stop_stats_capture', captureName: 'TestCapture' }, expected: 'success|not running' },
  { scenario: 'Build: get_memory_report success', toolName: 'manage_build', arguments: { action: 'get_memory_report' }, expected: 'success' },
  { scenario: 'Build: get_memory_report detailed', toolName: 'manage_build', arguments: { action: 'get_memory_report', detailed: true }, expected: 'success' },
  { scenario: 'Build: get_performance_stats success', toolName: 'manage_build', arguments: { action: 'get_performance_stats' }, expected: 'success' },
  { scenario: 'Build: get_performance_stats detailed', toolName: 'manage_build', arguments: { action: 'get_performance_stats', detailed: true }, expected: 'success' },
  { scenario: 'Build: validate_asset success', toolName: 'manage_build', arguments: { action: 'validate_asset', assetPath: '/Engine/BasicShapes/Cube' }, expected: 'success' },
  { scenario: 'Build: validate_asset missing', toolName: 'manage_build', arguments: { action: 'validate_asset', assetPath: '/Game/NonExistent' }, expected: 'not found|success' },
  { scenario: 'Build: validate_assets_in_path success', toolName: 'manage_build', arguments: { action: 'validate_assets_in_path', assetPath: '/Engine/BasicShapes' }, expected: 'success' },
  { scenario: 'Build: validate_assets_in_path recursive', toolName: 'manage_build', arguments: { action: 'validate_assets_in_path', assetPath: '/Engine', recursive: true }, expected: 'success' },
  { scenario: 'Build: validate_blueprint success', toolName: 'manage_build', arguments: { action: 'validate_blueprint', assetPath: `${TEST_FOLDER}/BP_Test` }, expected: 'success|not found' },
  { scenario: 'Build: validate_blueprint missing', toolName: 'manage_build', arguments: { action: 'validate_blueprint', assetPath: '/Game/NonExistent/BP_Missing' }, expected: 'not found|success' },
  { scenario: 'Build: check_map_errors success', toolName: 'manage_build', arguments: { action: 'check_map_errors' }, expected: 'success' },
  { scenario: 'Build: check_map_errors map', toolName: 'manage_build', arguments: { action: 'check_map_errors', mapPath: '/Game/Maps/TestMap' }, expected: 'success|not found' },
  { scenario: 'Build: get_redirectors success', toolName: 'manage_build', arguments: { action: 'get_redirectors', assetPath: '/Game' }, expected: 'success' },
  { scenario: 'Build: get_redirectors path', toolName: 'manage_build', arguments: { action: 'get_redirectors', assetPath: TEST_FOLDER }, expected: 'success' },
  { scenario: 'Build: fix_redirectors success', toolName: 'manage_build', arguments: { action: 'fix_redirectors', assetPath: '/Game' }, expected: 'success' },
  { scenario: 'Build: fix_redirectors path', toolName: 'manage_build', arguments: { action: 'fix_redirectors', assetPath: TEST_FOLDER }, expected: 'success' },

  // ============================================================================
  // manage_editor_utilities (45 actions) - 90 tests
  // ============================================================================
  // Editor Modes (4 actions x 2 = 8 tests)
  { scenario: 'EditorUtils: get_editor_utilities_info success', toolName: 'manage_editor_utilities', arguments: { action: 'get_editor_utilities_info' }, expected: 'success' },
  { scenario: 'EditorUtils: get_editor_utilities_info verbose', toolName: 'manage_editor_utilities', arguments: { action: 'get_editor_utilities_info', verbose: true }, expected: 'success' },
  { scenario: 'EditorUtils: set_editor_mode default', toolName: 'manage_editor_utilities', arguments: { action: 'set_editor_mode', modeName: 'Default' }, expected: 'success' },
  { scenario: 'EditorUtils: set_editor_mode landscape', toolName: 'manage_editor_utilities', arguments: { action: 'set_editor_mode', modeName: 'Landscape' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: configure_editor_preferences success', toolName: 'manage_editor_utilities', arguments: { action: 'configure_editor_preferences', preferences: { showFPS: true } }, expected: 'success' },
  { scenario: 'EditorUtils: configure_editor_preferences multiple', toolName: 'manage_editor_utilities', arguments: { action: 'configure_editor_preferences', preferences: { showFPS: true, autoSave: false } }, expected: 'success' },
  { scenario: 'EditorUtils: set_grid_settings success', toolName: 'manage_editor_utilities', arguments: { action: 'set_grid_settings', gridSize: 10, rotationSnap: 15, scaleSnap: 0.25 }, expected: 'success' },
  { scenario: 'EditorUtils: set_grid_settings fine', toolName: 'manage_editor_utilities', arguments: { action: 'set_grid_settings', gridSize: 1, rotationSnap: 5, scaleSnap: 0.1 }, expected: 'success' },
  { scenario: 'EditorUtils: set_snap_settings success', toolName: 'manage_editor_utilities', arguments: { action: 'set_snap_settings', gridSize: 20 }, expected: 'success' },
  { scenario: 'EditorUtils: set_snap_settings large', toolName: 'manage_editor_utilities', arguments: { action: 'set_snap_settings', gridSize: 100, rotationSnap: 45 }, expected: 'success' },

  // Content Browser (5 actions x 2 = 10 tests)
  { scenario: 'EditorUtils: navigate_to_path success', toolName: 'manage_editor_utilities', arguments: { action: 'navigate_to_path', path: '/Game' }, expected: 'success' },
  { scenario: 'EditorUtils: navigate_to_path engine', toolName: 'manage_editor_utilities', arguments: { action: 'navigate_to_path', path: '/Engine/BasicShapes' }, expected: 'success' },
  { scenario: 'EditorUtils: sync_to_asset success', toolName: 'manage_editor_utilities', arguments: { action: 'sync_to_asset', assetPath: '/Engine/BasicShapes/Cube' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: sync_to_asset missing', toolName: 'manage_editor_utilities', arguments: { action: 'sync_to_asset', assetPath: '/Game/NonExistent' }, expected: 'not found|success' },
  { scenario: 'EditorUtils: create_collection local', toolName: 'manage_editor_utilities', arguments: { action: 'create_collection', collectionName: 'UtilityTestCollection', collectionType: 'Local' }, expected: 'success|already exists' },
  { scenario: 'EditorUtils: create_collection shared', toolName: 'manage_editor_utilities', arguments: { action: 'create_collection', collectionName: 'SharedTestCollection', collectionType: 'Shared' }, expected: 'success|already exists' },
  { scenario: 'EditorUtils: add_to_collection success', toolName: 'manage_editor_utilities', arguments: { action: 'add_to_collection', collectionName: 'UtilityTestCollection', assetPaths: ['/Engine/BasicShapes/Cube'] }, expected: 'success|not found' },
  { scenario: 'EditorUtils: add_to_collection multiple', toolName: 'manage_editor_utilities', arguments: { action: 'add_to_collection', collectionName: 'UtilityTestCollection', assetPaths: ['/Engine/BasicShapes/Cube', '/Engine/BasicShapes/Sphere'] }, expected: 'success|not found' },
  { scenario: 'EditorUtils: show_in_explorer success', toolName: 'manage_editor_utilities', arguments: { action: 'show_in_explorer', path: '/Game' }, expected: 'success' },
  { scenario: 'EditorUtils: show_in_explorer engine', toolName: 'manage_editor_utilities', arguments: { action: 'show_in_explorer', path: '/Engine' }, expected: 'success' },

  // Selection (7 actions x 2 = 14 tests)
  { scenario: 'EditorUtils: deselect_all success', toolName: 'manage_editor_utilities', arguments: { action: 'deselect_all' }, expected: 'success' },
  { scenario: 'EditorUtils: deselect_all force', toolName: 'manage_editor_utilities', arguments: { action: 'deselect_all', force: true }, expected: 'success' },
  { scenario: 'EditorUtils: select_actor success', toolName: 'manage_editor_utilities', arguments: { action: 'select_actor', actorName: 'UT_TestCube' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: select_actor add', toolName: 'manage_editor_utilities', arguments: { action: 'select_actor', actorName: 'UT_TestSphere', addToSelection: true }, expected: 'success|not found' },
  { scenario: 'EditorUtils: get_selected_actors success', toolName: 'manage_editor_utilities', arguments: { action: 'get_selected_actors' }, expected: 'success' },
  { scenario: 'EditorUtils: get_selected_actors verbose', toolName: 'manage_editor_utilities', arguments: { action: 'get_selected_actors', verbose: true }, expected: 'success' },
  { scenario: 'EditorUtils: select_actors_by_class mesh', toolName: 'manage_editor_utilities', arguments: { action: 'select_actors_by_class', className: 'StaticMeshActor' }, expected: 'success' },
  { scenario: 'EditorUtils: select_actors_by_class light', toolName: 'manage_editor_utilities', arguments: { action: 'select_actors_by_class', className: 'Light' }, expected: 'success' },
  { scenario: 'EditorUtils: select_actors_by_tag success', toolName: 'manage_editor_utilities', arguments: { action: 'select_actors_by_tag', tag: 'TestTag' }, expected: 'success' },
  { scenario: 'EditorUtils: select_actors_by_tag missing', toolName: 'manage_editor_utilities', arguments: { action: 'select_actors_by_tag', tag: 'NonExistentTag' }, expected: 'success' },
  { scenario: 'EditorUtils: group_actors success', toolName: 'manage_editor_utilities', arguments: { action: 'group_actors', groupName: 'TestGroup' }, expected: 'success|no selection' },
  { scenario: 'EditorUtils: group_actors named', toolName: 'manage_editor_utilities', arguments: { action: 'group_actors', groupName: 'TestGroup2' }, expected: 'success|no selection' },
  { scenario: 'EditorUtils: ungroup_actors success', toolName: 'manage_editor_utilities', arguments: { action: 'ungroup_actors', groupName: 'TestGroup' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: ungroup_actors missing', toolName: 'manage_editor_utilities', arguments: { action: 'ungroup_actors', groupName: 'NonExistentGroup' }, expected: 'not found|success' },

  // Collision (4 actions x 2 = 8 tests)
  { scenario: 'EditorUtils: get_collision_info success', toolName: 'manage_editor_utilities', arguments: { action: 'get_collision_info' }, expected: 'success' },
  { scenario: 'EditorUtils: get_collision_info verbose', toolName: 'manage_editor_utilities', arguments: { action: 'get_collision_info', verbose: true }, expected: 'success' },
  { scenario: 'EditorUtils: create_collision_channel object', toolName: 'manage_editor_utilities', arguments: { action: 'create_collision_channel', channelName: 'TestChannel', channelType: 'Object' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_collision_channel trace', toolName: 'manage_editor_utilities', arguments: { action: 'create_collision_channel', channelName: 'TestTraceChannel', channelType: 'Trace' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_collision_profile success', toolName: 'manage_editor_utilities', arguments: { action: 'create_collision_profile', profileName: 'TestProfile' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_collision_profile named', toolName: 'manage_editor_utilities', arguments: { action: 'create_collision_profile', profileName: 'TestProfile2' }, expected: 'success|note' },
  { scenario: 'EditorUtils: configure_channel_responses success', toolName: 'manage_editor_utilities', arguments: { action: 'configure_channel_responses', profileName: 'TestProfile', responses: { WorldStatic: 'Block' } }, expected: 'success|not found' },
  { scenario: 'EditorUtils: configure_channel_responses multiple', toolName: 'manage_editor_utilities', arguments: { action: 'configure_channel_responses', profileName: 'TestProfile', responses: { WorldStatic: 'Block', WorldDynamic: 'Overlap' } }, expected: 'success|not found' },

  // Physical Materials (5 actions x 2 = 10 tests)
  { scenario: 'EditorUtils: create_physical_material success', toolName: 'manage_editor_utilities', arguments: { action: 'create_physical_material', materialName: `${TEST_FOLDER}/PM_TestPhysical`, friction: 0.5, restitution: 0.3 }, expected: 'success' },
  { scenario: 'EditorUtils: create_physical_material bouncy', toolName: 'manage_editor_utilities', arguments: { action: 'create_physical_material', materialName: `${TEST_FOLDER}/PM_Bouncy`, friction: 0.1, restitution: 0.9 }, expected: 'success' },
  { scenario: 'EditorUtils: get_physical_material_info success', toolName: 'manage_editor_utilities', arguments: { action: 'get_physical_material_info', assetPath: `${TEST_FOLDER}/PM_TestPhysical` }, expected: 'success|not found' },
  { scenario: 'EditorUtils: get_physical_material_info missing', toolName: 'manage_editor_utilities', arguments: { action: 'get_physical_material_info', assetPath: '/Game/NonExistent/PM_Missing' }, expected: 'not found|success' },
  { scenario: 'EditorUtils: set_friction success', toolName: 'manage_editor_utilities', arguments: { action: 'set_friction', assetPath: `${TEST_FOLDER}/PM_TestPhysical`, friction: 0.8 }, expected: 'success|not found' },
  { scenario: 'EditorUtils: set_friction zero', toolName: 'manage_editor_utilities', arguments: { action: 'set_friction', assetPath: `${TEST_FOLDER}/PM_TestPhysical`, friction: 0.0 }, expected: 'success|not found' },
  { scenario: 'EditorUtils: set_restitution success', toolName: 'manage_editor_utilities', arguments: { action: 'set_restitution', assetPath: `${TEST_FOLDER}/PM_TestPhysical`, restitution: 0.5 }, expected: 'success|not found' },
  { scenario: 'EditorUtils: set_restitution max', toolName: 'manage_editor_utilities', arguments: { action: 'set_restitution', assetPath: `${TEST_FOLDER}/PM_TestPhysical`, restitution: 1.0 }, expected: 'success|not found' },
  { scenario: 'EditorUtils: configure_surface_type metal', toolName: 'manage_editor_utilities', arguments: { action: 'configure_surface_type', assetPath: `${TEST_FOLDER}/PM_TestPhysical`, surfaceType: 'Metal' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: configure_surface_type wood', toolName: 'manage_editor_utilities', arguments: { action: 'configure_surface_type', assetPath: `${TEST_FOLDER}/PM_TestPhysical`, surfaceType: 'Wood' }, expected: 'success|not found' },

  // Subsystems (4 actions x 2 = 8 tests)
  { scenario: 'EditorUtils: get_subsystem_info success', toolName: 'manage_editor_utilities', arguments: { action: 'get_subsystem_info' }, expected: 'success' },
  { scenario: 'EditorUtils: get_subsystem_info verbose', toolName: 'manage_editor_utilities', arguments: { action: 'get_subsystem_info', verbose: true }, expected: 'success' },
  { scenario: 'EditorUtils: create_game_instance_subsystem success', toolName: 'manage_editor_utilities', arguments: { action: 'create_game_instance_subsystem', subsystemClass: 'TestGameInstanceSubsystem' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_game_instance_subsystem named', toolName: 'manage_editor_utilities', arguments: { action: 'create_game_instance_subsystem', subsystemClass: 'MyGameSubsystem' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_world_subsystem success', toolName: 'manage_editor_utilities', arguments: { action: 'create_world_subsystem', subsystemClass: 'TestWorldSubsystem' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_world_subsystem named', toolName: 'manage_editor_utilities', arguments: { action: 'create_world_subsystem', subsystemClass: 'MyWorldSubsystem' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_local_player_subsystem success', toolName: 'manage_editor_utilities', arguments: { action: 'create_local_player_subsystem', subsystemClass: 'TestLocalPlayerSubsystem' }, expected: 'success|note' },
  { scenario: 'EditorUtils: create_local_player_subsystem named', toolName: 'manage_editor_utilities', arguments: { action: 'create_local_player_subsystem', subsystemClass: 'MyPlayerSubsystem' }, expected: 'success|note' },

  // Timers (4 actions x 2 = 8 tests)
  { scenario: 'EditorUtils: get_active_timers success', toolName: 'manage_editor_utilities', arguments: { action: 'get_active_timers' }, expected: 'success' },
  { scenario: 'EditorUtils: get_active_timers verbose', toolName: 'manage_editor_utilities', arguments: { action: 'get_active_timers', verbose: true }, expected: 'success' },
  { scenario: 'EditorUtils: set_timer success', toolName: 'manage_editor_utilities', arguments: { action: 'set_timer', timerHandle: 'TestTimer', duration: 5.0, looping: false, functionName: 'TestFunction' }, expected: 'success' },
  { scenario: 'EditorUtils: set_timer looping', toolName: 'manage_editor_utilities', arguments: { action: 'set_timer', timerHandle: 'LoopTimer', duration: 1.0, looping: true, functionName: 'LoopFunction' }, expected: 'success' },
  { scenario: 'EditorUtils: clear_timer success', toolName: 'manage_editor_utilities', arguments: { action: 'clear_timer', timerHandle: 'TestTimer' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: clear_timer missing', toolName: 'manage_editor_utilities', arguments: { action: 'clear_timer', timerHandle: 'NonExistentTimer' }, expected: 'not found|success' },
  { scenario: 'EditorUtils: clear_all_timers success', toolName: 'manage_editor_utilities', arguments: { action: 'clear_all_timers' }, expected: 'success' },
  { scenario: 'EditorUtils: clear_all_timers force', toolName: 'manage_editor_utilities', arguments: { action: 'clear_all_timers', force: true }, expected: 'success' },

  // Delegates (5 actions x 2 = 10 tests)
  { scenario: 'EditorUtils: create_event_dispatcher success', toolName: 'manage_editor_utilities', arguments: { action: 'create_event_dispatcher', dispatcherName: 'TestDispatcher' }, expected: 'success' },
  { scenario: 'EditorUtils: create_event_dispatcher named', toolName: 'manage_editor_utilities', arguments: { action: 'create_event_dispatcher', dispatcherName: 'MyEventDispatcher' }, expected: 'success' },
  { scenario: 'EditorUtils: bind_to_event success', toolName: 'manage_editor_utilities', arguments: { action: 'bind_to_event', eventName: 'TestEvent', functionName: 'TestFunction' }, expected: 'success' },
  { scenario: 'EditorUtils: bind_to_event alternate', toolName: 'manage_editor_utilities', arguments: { action: 'bind_to_event', eventName: 'TestEvent2', functionName: 'Handler2' }, expected: 'success' },
  { scenario: 'EditorUtils: unbind_from_event success', toolName: 'manage_editor_utilities', arguments: { action: 'unbind_from_event', eventName: 'TestEvent', functionName: 'TestFunction' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: unbind_from_event missing', toolName: 'manage_editor_utilities', arguments: { action: 'unbind_from_event', eventName: 'NonExistent', functionName: 'Missing' }, expected: 'not found|success' },
  { scenario: 'EditorUtils: broadcast_event success', toolName: 'manage_editor_utilities', arguments: { action: 'broadcast_event', eventName: 'TestEvent' }, expected: 'success|not found' },
  { scenario: 'EditorUtils: broadcast_event missing', toolName: 'manage_editor_utilities', arguments: { action: 'broadcast_event', eventName: 'NonExistentEvent' }, expected: 'not found|success' },
  { scenario: 'EditorUtils: create_blueprint_interface success', toolName: 'manage_editor_utilities', arguments: { action: 'create_blueprint_interface', interfaceName: `${TEST_FOLDER}/BPI_TestInterface` }, expected: 'success' },
  { scenario: 'EditorUtils: create_blueprint_interface named', toolName: 'manage_editor_utilities', arguments: { action: 'create_blueprint_interface', interfaceName: `${TEST_FOLDER}/BPI_MyInterface` }, expected: 'success' },

  // Transactions (6 actions x 2 = 12 tests)
  { scenario: 'EditorUtils: begin_transaction success', toolName: 'manage_editor_utilities', arguments: { action: 'begin_transaction', transactionName: 'UtilityTestTransaction' }, expected: 'success' },
  { scenario: 'EditorUtils: begin_transaction scoped', toolName: 'manage_editor_utilities', arguments: { action: 'begin_transaction', transactionName: 'ScopedTransaction' }, expected: 'success' },
  { scenario: 'EditorUtils: end_transaction success', toolName: 'manage_editor_utilities', arguments: { action: 'end_transaction' }, expected: 'success' },
  { scenario: 'EditorUtils: end_transaction save', toolName: 'manage_editor_utilities', arguments: { action: 'end_transaction', save: true }, expected: 'success' },
  { scenario: 'EditorUtils: get_transaction_history success', toolName: 'manage_editor_utilities', arguments: { action: 'get_transaction_history' }, expected: 'success' },
  { scenario: 'EditorUtils: get_transaction_history limit', toolName: 'manage_editor_utilities', arguments: { action: 'get_transaction_history', limit: 10 }, expected: 'success' },
  { scenario: 'EditorUtils: cancel_transaction success', toolName: 'manage_editor_utilities', arguments: { action: 'cancel_transaction' }, expected: 'success|no active' },
  { scenario: 'EditorUtils: cancel_transaction force', toolName: 'manage_editor_utilities', arguments: { action: 'cancel_transaction', force: true }, expected: 'success|no active' },
  { scenario: 'EditorUtils: undo success', toolName: 'manage_editor_utilities', arguments: { action: 'undo' }, expected: 'success|nothing' },
  { scenario: 'EditorUtils: undo multiple', toolName: 'manage_editor_utilities', arguments: { action: 'undo', count: 2 }, expected: 'success|nothing' },
  { scenario: 'EditorUtils: redo success', toolName: 'manage_editor_utilities', arguments: { action: 'redo' }, expected: 'success|nothing' },
  { scenario: 'EditorUtils: redo multiple', toolName: 'manage_editor_utilities', arguments: { action: 'redo', count: 2 }, expected: 'success|nothing' },

  // ============================================================================
  // manage_performance (20 actions) - 40 tests
  // ============================================================================
  { scenario: 'Performance: start_profiling CPU', toolName: 'manage_performance', arguments: { action: 'start_profiling', type: 'CPU' }, expected: 'success|already' },
  { scenario: 'Performance: start_profiling GPU', toolName: 'manage_performance', arguments: { action: 'start_profiling', type: 'GPU' }, expected: 'success|already' },
  { scenario: 'Performance: start_profiling memory', toolName: 'manage_performance', arguments: { action: 'start_profiling', type: 'Memory' }, expected: 'success|already' },
  { scenario: 'Performance: start_profiling all', toolName: 'manage_performance', arguments: { action: 'start_profiling', type: 'All' }, expected: 'success|already' },
  { scenario: 'Performance: stop_profiling success', toolName: 'manage_performance', arguments: { action: 'stop_profiling' }, expected: 'success|not running' },
  { scenario: 'Performance: stop_profiling force', toolName: 'manage_performance', arguments: { action: 'stop_profiling', force: true }, expected: 'success|not running' },
  { scenario: 'Performance: run_benchmark success', toolName: 'manage_performance', arguments: { action: 'run_benchmark' }, expected: 'success' },
  { scenario: 'Performance: run_benchmark duration', toolName: 'manage_performance', arguments: { action: 'run_benchmark', duration: 5.0 }, expected: 'success' },
  { scenario: 'Performance: show_fps enable', toolName: 'manage_performance', arguments: { action: 'show_fps', enabled: true }, expected: 'success' },
  { scenario: 'Performance: show_fps disable', toolName: 'manage_performance', arguments: { action: 'show_fps', enabled: false }, expected: 'success' },
  { scenario: 'Performance: show_stats enable', toolName: 'manage_performance', arguments: { action: 'show_stats', enabled: true }, expected: 'success' },
  { scenario: 'Performance: show_stats disable', toolName: 'manage_performance', arguments: { action: 'show_stats', enabled: false }, expected: 'success' },
  { scenario: 'Performance: generate_memory_report success', toolName: 'manage_performance', arguments: { action: 'generate_memory_report' }, expected: 'success' },
  { scenario: 'Performance: generate_memory_report detailed', toolName: 'manage_performance', arguments: { action: 'generate_memory_report', detailed: true }, expected: 'success' },
  { scenario: 'Performance: set_scalability high', toolName: 'manage_performance', arguments: { action: 'set_scalability', level: 3 }, expected: 'success' },
  { scenario: 'Performance: set_scalability low', toolName: 'manage_performance', arguments: { action: 'set_scalability', level: 0 }, expected: 'success' },
  { scenario: 'Performance: set_scalability epic', toolName: 'manage_performance', arguments: { action: 'set_scalability', level: 4 }, expected: 'success' },
  { scenario: 'Performance: set_resolution_scale 100', toolName: 'manage_performance', arguments: { action: 'set_resolution_scale', scale: 100 }, expected: 'success' },
  { scenario: 'Performance: set_resolution_scale 50', toolName: 'manage_performance', arguments: { action: 'set_resolution_scale', scale: 50 }, expected: 'success' },
  { scenario: 'Performance: set_resolution_scale high', toolName: 'manage_performance', arguments: { action: 'set_resolution_scale', scale: 150 }, expected: 'success' },
  { scenario: 'Performance: set_vsync enable', toolName: 'manage_performance', arguments: { action: 'set_vsync', enabled: true }, expected: 'success' },
  { scenario: 'Performance: set_vsync disable', toolName: 'manage_performance', arguments: { action: 'set_vsync', enabled: false }, expected: 'success' },
  { scenario: 'Performance: set_frame_rate_limit 60', toolName: 'manage_performance', arguments: { action: 'set_frame_rate_limit', maxFPS: 60 }, expected: 'success' },
  { scenario: 'Performance: set_frame_rate_limit 120', toolName: 'manage_performance', arguments: { action: 'set_frame_rate_limit', maxFPS: 120 }, expected: 'success' },
  { scenario: 'Performance: set_frame_rate_limit unlimited', toolName: 'manage_performance', arguments: { action: 'set_frame_rate_limit', maxFPS: 0 }, expected: 'success' },
  { scenario: 'Performance: enable_gpu_timing success', toolName: 'manage_performance', arguments: { action: 'enable_gpu_timing', enabled: true }, expected: 'success' },
  { scenario: 'Performance: enable_gpu_timing disable', toolName: 'manage_performance', arguments: { action: 'enable_gpu_timing', enabled: false }, expected: 'success' },
  { scenario: 'Performance: configure_texture_streaming success', toolName: 'manage_performance', arguments: { action: 'configure_texture_streaming', poolSize: 1000 }, expected: 'success' },
  { scenario: 'Performance: configure_texture_streaming large', toolName: 'manage_performance', arguments: { action: 'configure_texture_streaming', poolSize: 4000 }, expected: 'success' },
  { scenario: 'Performance: configure_lod default', toolName: 'manage_performance', arguments: { action: 'configure_lod', lodBias: 1.0, distanceScale: 1.0 }, expected: 'success' },
  { scenario: 'Performance: configure_lod aggressive', toolName: 'manage_performance', arguments: { action: 'configure_lod', lodBias: 2.0, distanceScale: 0.5 }, expected: 'success' },
  { scenario: 'Performance: apply_baseline_settings success', toolName: 'manage_performance', arguments: { action: 'apply_baseline_settings' }, expected: 'success' },
  { scenario: 'Performance: apply_baseline_settings preset', toolName: 'manage_performance', arguments: { action: 'apply_baseline_settings', preset: 'High' }, expected: 'success' },
  { scenario: 'Performance: optimize_draw_calls success', toolName: 'manage_performance', arguments: { action: 'optimize_draw_calls', enableInstancing: true, enableBatching: true }, expected: 'success' },
  { scenario: 'Performance: optimize_draw_calls disabled', toolName: 'manage_performance', arguments: { action: 'optimize_draw_calls', enableInstancing: false, enableBatching: false }, expected: 'success' },
  { scenario: 'Performance: merge_actors success', toolName: 'manage_performance', arguments: { action: 'merge_actors', actors: ['UT_TestCube', 'UT_TestSphere'] }, expected: 'success|not found' },
  { scenario: 'Performance: merge_actors single', toolName: 'manage_performance', arguments: { action: 'merge_actors', actors: ['UT_TestCube'] }, expected: 'success|not found' },
  { scenario: 'Performance: configure_occlusion_culling success', toolName: 'manage_performance', arguments: { action: 'configure_occlusion_culling' }, expected: 'success' },
  { scenario: 'Performance: configure_occlusion_culling enabled', toolName: 'manage_performance', arguments: { action: 'configure_occlusion_culling', enabled: true }, expected: 'success' },
  { scenario: 'Performance: optimize_shaders success', toolName: 'manage_performance', arguments: { action: 'optimize_shaders' }, expected: 'success' },
  { scenario: 'Performance: optimize_shaders compile', toolName: 'manage_performance', arguments: { action: 'optimize_shaders', recompile: true }, expected: 'success' },
  { scenario: 'Performance: configure_nanite default', toolName: 'manage_performance', arguments: { action: 'configure_nanite', maxPixelsPerEdge: 1.0 }, expected: 'success' },
  { scenario: 'Performance: configure_nanite quality', toolName: 'manage_performance', arguments: { action: 'configure_nanite', maxPixelsPerEdge: 0.5 }, expected: 'success' },
  { scenario: 'Performance: configure_world_partition default', toolName: 'manage_performance', arguments: { action: 'configure_world_partition', cellSize: 12800 }, expected: 'success' },
  { scenario: 'Performance: configure_world_partition large', toolName: 'manage_performance', arguments: { action: 'configure_world_partition', cellSize: 51200 }, expected: 'success' },

  // ============================================================================
  // manage_character_avatar (60 actions) - 120 tests (First half: MetaHuman + Groom)
  // ============================================================================
  // MetaHuman (18 actions x 2 = 36 tests)
  { scenario: 'CharAvatar: get_metahuman_info non-existent', toolName: 'manage_character_avatar', arguments: { action: 'get_metahuman_info', actorName: 'NonExistentMetaHuman' }, expected: 'error|not found' },
  { scenario: 'CharAvatar: get_metahuman_info missing', toolName: 'manage_character_avatar', arguments: { action: 'get_metahuman_info', actorName: 'MissingActor' }, expected: 'error|not found' },
  { scenario: 'CharAvatar: list_available_presets success', toolName: 'manage_character_avatar', arguments: { action: 'list_available_presets' }, expected: 'success' },
  { scenario: 'CharAvatar: list_available_presets filtered', toolName: 'manage_character_avatar', arguments: { action: 'list_available_presets', category: 'Face' }, expected: 'success' },
  { scenario: 'CharAvatar: import_metahuman success', toolName: 'manage_character_avatar', arguments: { action: 'import_metahuman', sourcePath: '/Game/MetaHumans/Test' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: import_metahuman path', toolName: 'manage_character_avatar', arguments: { action: 'import_metahuman', sourcePath: '/Game/MetaHumans/Character01' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: spawn_metahuman_actor success', toolName: 'manage_character_avatar', arguments: { action: 'spawn_metahuman_actor', metahumanPath: '/Game/MetaHumans/Test', location: { x: 500, y: 0, z: 100 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: spawn_metahuman_actor rotation', toolName: 'manage_character_avatar', arguments: { action: 'spawn_metahuman_actor', metahumanPath: '/Game/MetaHumans/Test', location: { x: 600, y: 0, z: 100 }, rotation: { pitch: 0, yaw: 90, roll: 0 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: get_metahuman_component success', toolName: 'manage_character_avatar', arguments: { action: 'get_metahuman_component', actorName: 'UT_TestCube' }, expected: 'success|not found' },
  { scenario: 'CharAvatar: get_metahuman_component missing', toolName: 'manage_character_avatar', arguments: { action: 'get_metahuman_component', actorName: 'MissingActor' }, expected: 'not found|success' },
  { scenario: 'CharAvatar: set_body_type masculine', toolName: 'manage_character_avatar', arguments: { action: 'set_body_type', actorName: 'TestMetaHuman', bodyType: 'Masculine' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_body_type feminine', toolName: 'manage_character_avatar', arguments: { action: 'set_body_type', actorName: 'TestMetaHuman', bodyType: 'Feminine' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_face_parameter success', toolName: 'manage_character_avatar', arguments: { action: 'set_face_parameter', actorName: 'TestMetaHuman', parameterName: 'eyeSize', parameterValue: 0.5 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_face_parameter alt', toolName: 'manage_character_avatar', arguments: { action: 'set_face_parameter', actorName: 'TestMetaHuman', parameterName: 'noseWidth', parameterValue: 0.3 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_skin_tone success', toolName: 'manage_character_avatar', arguments: { action: 'set_skin_tone', actorName: 'TestMetaHuman', skinTone: 3 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_skin_tone alt', toolName: 'manage_character_avatar', arguments: { action: 'set_skin_tone', actorName: 'TestMetaHuman', skinTone: 5 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_style success', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_style', actorName: 'TestMetaHuman', hairStylePath: '/Game/Hair/Test' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_style path', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_style', actorName: 'TestMetaHuman', hairStylePath: '/Game/Hair/Style02' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_eye_color blue', toolName: 'manage_character_avatar', arguments: { action: 'set_eye_color', actorName: 'TestMetaHuman', eyeColor: { r: 0.2, g: 0.5, b: 0.8, a: 1 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_eye_color brown', toolName: 'manage_character_avatar', arguments: { action: 'set_eye_color', actorName: 'TestMetaHuman', eyeColor: { r: 0.4, g: 0.2, b: 0.1, a: 1 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_metahuman_lod success', toolName: 'manage_character_avatar', arguments: { action: 'configure_metahuman_lod', actorName: 'TestMetaHuman', lodLevel: 2 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_metahuman_lod max', toolName: 'manage_character_avatar', arguments: { action: 'configure_metahuman_lod', actorName: 'TestMetaHuman', lodLevel: 0 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: enable_body_correctives true', toolName: 'manage_character_avatar', arguments: { action: 'enable_body_correctives', actorName: 'TestMetaHuman', enableBodyCorrectives: true }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: enable_body_correctives false', toolName: 'manage_character_avatar', arguments: { action: 'enable_body_correctives', actorName: 'TestMetaHuman', enableBodyCorrectives: false }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: enable_neck_correctives true', toolName: 'manage_character_avatar', arguments: { action: 'enable_neck_correctives', actorName: 'TestMetaHuman', enableNeckCorrectives: true }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: enable_neck_correctives false', toolName: 'manage_character_avatar', arguments: { action: 'enable_neck_correctives', actorName: 'TestMetaHuman', enableNeckCorrectives: false }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_quality_level high', toolName: 'manage_character_avatar', arguments: { action: 'set_quality_level', actorName: 'TestMetaHuman', qualityLevel: 'High' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_quality_level cinematic', toolName: 'manage_character_avatar', arguments: { action: 'set_quality_level', actorName: 'TestMetaHuman', qualityLevel: 'Cinematic' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_face_rig success', toolName: 'manage_character_avatar', arguments: { action: 'configure_face_rig', actorName: 'TestMetaHuman' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_face_rig settings', toolName: 'manage_character_avatar', arguments: { action: 'configure_face_rig', actorName: 'TestMetaHuman', rigSettings: { useRigLogic: true } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_body_part outfit', toolName: 'manage_character_avatar', arguments: { action: 'set_body_part', actorName: 'TestMetaHuman', bodyPartType: 'Outfit', bodyPartPath: '/Game/Outfits/Test' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_body_part accessories', toolName: 'manage_character_avatar', arguments: { action: 'set_body_part', actorName: 'TestMetaHuman', bodyPartType: 'Accessories', bodyPartPath: '/Game/Accessories/Test' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: apply_preset default', toolName: 'manage_character_avatar', arguments: { action: 'apply_preset', actorName: 'TestMetaHuman', presetName: 'Default' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: apply_preset custom', toolName: 'manage_character_avatar', arguments: { action: 'apply_preset', actorName: 'TestMetaHuman', presetName: 'MyPreset' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: export_metahuman_settings success', toolName: 'manage_character_avatar', arguments: { action: 'export_metahuman_settings', actorName: 'TestMetaHuman', exportPath: `${TEST_FOLDER}/MetaHumanExport.json` }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: export_metahuman_settings path', toolName: 'manage_character_avatar', arguments: { action: 'export_metahuman_settings', actorName: 'TestMetaHuman', exportPath: `${TEST_FOLDER}/MH_Settings.json` }, expected: 'success|not found|not available' },

  // Groom/Hair (14 actions x 2 = 28 tests)
  { scenario: 'CharAvatar: create_groom_asset success', toolName: 'manage_character_avatar', arguments: { action: 'create_groom_asset', name: 'TestGroom', destinationPath: ADV_TEST_FOLDER }, expected: 'success|not available' },
  { scenario: 'CharAvatar: create_groom_asset named', toolName: 'manage_character_avatar', arguments: { action: 'create_groom_asset', name: 'HairGroom', destinationPath: ADV_TEST_FOLDER }, expected: 'success|not available' },
  { scenario: 'CharAvatar: import_groom success', toolName: 'manage_character_avatar', arguments: { action: 'import_groom', sourcePath: '/Path/to/groom.abc', destinationPath: ADV_TEST_FOLDER }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: import_groom alt', toolName: 'manage_character_avatar', arguments: { action: 'import_groom', sourcePath: '/Path/to/hair.abc', destinationPath: ADV_TEST_FOLDER }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: create_groom_binding success', toolName: 'manage_character_avatar', arguments: { action: 'create_groom_binding', groomAssetPath: `${ADV_TEST_FOLDER}/TestGroom`, skeletalMeshPath: '/Engine/EngineMeshes/SkeletalCube' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: create_groom_binding alt', toolName: 'manage_character_avatar', arguments: { action: 'create_groom_binding', groomAssetPath: `${ADV_TEST_FOLDER}/HairGroom`, skeletalMeshPath: '/Game/Characters/TestMesh' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: spawn_groom_actor success', toolName: 'manage_character_avatar', arguments: { action: 'spawn_groom_actor', groomAssetPath: `${ADV_TEST_FOLDER}/TestGroom`, location: { x: 600, y: 0, z: 100 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: spawn_groom_actor rotation', toolName: 'manage_character_avatar', arguments: { action: 'spawn_groom_actor', groomAssetPath: `${ADV_TEST_FOLDER}/TestGroom`, location: { x: 700, y: 0, z: 100 }, rotation: { pitch: 0, yaw: 45, roll: 0 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: attach_groom_to_skeletal_mesh success', toolName: 'manage_character_avatar', arguments: { action: 'attach_groom_to_skeletal_mesh', actorName: 'TestActor', groomAssetPath: `${ADV_TEST_FOLDER}/TestGroom` }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: attach_groom_to_skeletal_mesh alt', toolName: 'manage_character_avatar', arguments: { action: 'attach_groom_to_skeletal_mesh', actorName: 'CharacterActor', groomAssetPath: `${ADV_TEST_FOLDER}/HairGroom` }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_hair_simulation success', toolName: 'manage_character_avatar', arguments: { action: 'configure_hair_simulation', actorName: 'TestActor', simulationSettings: { damping: 0.5, stiffness: 0.3 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_hair_simulation wind', toolName: 'manage_character_avatar', arguments: { action: 'configure_hair_simulation', actorName: 'TestActor', simulationSettings: { damping: 0.3, stiffness: 0.5, windStrength: 1.0 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_width success', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_width', actorName: 'TestActor', hairWidth: 0.01 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_width thin', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_width', actorName: 'TestActor', hairWidth: 0.005 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_root_scale success', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_root_scale', actorName: 'TestActor', hairRootScale: 1.0 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_root_scale large', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_root_scale', actorName: 'TestActor', hairRootScale: 1.5 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_tip_scale success', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_tip_scale', actorName: 'TestActor', hairTipScale: 0.5 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_tip_scale small', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_tip_scale', actorName: 'TestActor', hairTipScale: 0.2 }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_color brown', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_color', actorName: 'TestActor', hairColor: { r: 0.2, g: 0.1, b: 0.05, a: 1 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: set_hair_color blonde', toolName: 'manage_character_avatar', arguments: { action: 'set_hair_color', actorName: 'TestActor', hairColor: { r: 0.9, g: 0.8, b: 0.5, a: 1 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_hair_physics success', toolName: 'manage_character_avatar', arguments: { action: 'configure_hair_physics', actorName: 'TestActor', physicsSettings: { solverIterations: 8 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_hair_physics detailed', toolName: 'manage_character_avatar', arguments: { action: 'configure_hair_physics', actorName: 'TestActor', physicsSettings: { solverIterations: 12, subSteps: 2 } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_hair_rendering strands', toolName: 'manage_character_avatar', arguments: { action: 'configure_hair_rendering', actorName: 'TestActor', renderingSettings: { renderMode: 'Strands' } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: configure_hair_rendering cards', toolName: 'manage_character_avatar', arguments: { action: 'configure_hair_rendering', actorName: 'TestActor', renderingSettings: { renderMode: 'Cards' } }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: enable_hair_simulation true', toolName: 'manage_character_avatar', arguments: { action: 'enable_hair_simulation', actorName: 'TestActor', enableSimulation: true }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: enable_hair_simulation false', toolName: 'manage_character_avatar', arguments: { action: 'enable_hair_simulation', actorName: 'TestActor', enableSimulation: false }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: get_groom_info success', toolName: 'manage_character_avatar', arguments: { action: 'get_groom_info', actorName: 'TestActor' }, expected: 'success|not found|not available' },
  { scenario: 'CharAvatar: get_groom_info missing', toolName: 'manage_character_avatar', arguments: { action: 'get_groom_info', actorName: 'MissingActor' }, expected: 'not found|success|not available' },
];

// Run tests
const main = async () => {
  await runToolTests('utility-tools-part1', utilityToolsTestsPart1);
};

if (import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main();
}
