// Struct authoring records: Blueprint Struct CRUD, member management,
// comparison, usage search, recompilation, import/export, and
// FInstancedStruct property access (issue #510, #struct-ecosystem).

import type { RecordSpec } from './builder.js';
import { arrObj, bool, DESTRUCTIVE, DESTRUCTIVE_POLICY, HIGH, LOW, MEDIUM, NON_IDEMPOTENT, READ, READ_POLICY, r, schema, str, WRITE, WRITE_POLICY } from './builder.js';

const STRUCT_PATH = str('Asset path of the Blueprint Struct (e.g. /Game/Structs/S_MyStruct).');
const MEMBER_NAME = str('Member (variable) name.');
const MEMBER_TYPE = str('Unreal property type: Bool, Int, Float, String, Name, Text, Vector, Rotator, Transform, Object, SoftObject, Class, SoftClass, Enum:<Name>, Struct:<Path>, or with container prefix Array:..., Set:..., Map:<K>,<V>:');
const OK = schema({ success: bool('Operation succeeded.'), details: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Operation details.' } }, ['success']);

export const STRUCT_RECORDS: readonly RecordSpec[] = [
  r('create_struct', 'struct', 'Create a new Blueprint Struct asset.', schema({ name: str('Struct name.'), path: str('Package path.'), members: arrObj('Member definitions.') }, ['name']), OK, WRITE, WRITE_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('get_struct', 'struct', 'Retrieve Blueprint Struct metadata and member list.', schema({ structPath: STRUCT_PATH }, ['structPath']), OK, READ, READ_POLICY, LOW, { dispatchMode: 'tool' }),
  r('read_struct', 'struct', 'Read the full value of a Blueprint Struct asset.', schema({ structPath: STRUCT_PATH }, ['structPath']), OK, READ, READ_POLICY, LOW, { dispatchMode: 'tool' }),
  r('list_struct_members', 'struct', 'List all members of a Blueprint Struct.', schema({ structPath: STRUCT_PATH }, ['structPath']), OK, READ, READ_POLICY, LOW, { dispatchMode: 'tool' }),
  r('add_struct_member', 'struct', 'Add a new member to a Blueprint Struct.', schema({ structPath: STRUCT_PATH, memberName: MEMBER_NAME, memberType: MEMBER_TYPE, defaultValue: str('Default value as string.'), tooltip: str('Member tooltip.'), metadata: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Metadata key/value pairs.' } }, ['structPath', 'memberName', 'memberType']), OK, WRITE, WRITE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('remove_struct_member', 'struct', 'Remove a member from a Blueprint Struct.', schema({ structPath: STRUCT_PATH, memberName: MEMBER_NAME, varGuid: str('Stable member GUID.') }, ['structPath', 'memberName']), OK, DESTRUCTIVE, DESTRUCTIVE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('rename_struct_member', 'struct', 'Rename a member in a Blueprint Struct.', schema({ structPath: STRUCT_PATH, memberName: MEMBER_NAME, newMemberName: str('New member name.'), varGuid: str('Stable member GUID.') }, ['structPath', 'memberName', 'newMemberName']), OK, NON_IDEMPOTENT, WRITE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('set_struct_member_type', 'struct', 'Change the type of a member in a Blueprint Struct.', schema({ structPath: STRUCT_PATH, memberName: MEMBER_NAME, memberType: MEMBER_TYPE, varGuid: str('Stable member GUID.') }, ['structPath', 'memberName', 'memberType']), OK, WRITE, WRITE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('reorder_struct_members', 'struct', 'Reorder members in a Blueprint Struct.', schema({ structPath: STRUCT_PATH, position: { type: 'string', enum: ['first', 'last', 'before', 'after'], description: 'Reorder anchor position.' }, relativeTo: str('Target member GUID/name.'), varGuid: str('Member GUID to move.') }, ['structPath', 'position']), OK, WRITE, WRITE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('set_struct_member_default', 'struct', 'Set the default value of a member in a Blueprint Struct.', schema({ structPath: STRUCT_PATH, memberName: MEMBER_NAME, defaultValue: str('Default value as string.'), varGuid: str('Stable member GUID.') }, ['structPath', 'memberName', 'defaultValue']), OK, WRITE, WRITE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('set_struct_member_metadata', 'struct', 'Set metadata (tooltip, etc.) on a member in a Blueprint Struct.', schema({ structPath: STRUCT_PATH, memberName: MEMBER_NAME, tooltip: str('Member tooltip.'), metadata: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Metadata key/value pairs.' }, varGuid: str('Stable member GUID.') }, ['structPath', 'memberName']), OK, WRITE, WRITE_POLICY, LOW, { dispatchMode: 'tool' }),
  r('compare_structs', 'struct', 'Compare two Blueprint Structs for differences.', schema({ structPath: STRUCT_PATH, otherStructPath: str('Second struct path for comparison.') }, ['structPath', 'otherStructPath']), OK, READ, READ_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('search_struct_usage', 'struct', 'Search for references to a Blueprint Struct across the project.', schema({ structPath: STRUCT_PATH, searchScope: str('Optional path scope.') }, ['structPath']), OK, READ, READ_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('recompile_struct', 'struct', 'Recompile a Blueprint Struct to update generated headers.', schema({ structPath: STRUCT_PATH }, ['structPath']), OK, WRITE, WRITE_POLICY, HIGH, { dispatchMode: 'tool' }),
  r('rename_struct', 'struct', 'Rename a Blueprint Struct asset.', schema({ structPath: STRUCT_PATH, newName: str('New struct name.') }, ['structPath', 'newName']), OK, NON_IDEMPOTENT, WRITE_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('duplicate_struct', 'struct', 'Duplicate a Blueprint Struct asset.', schema({ structPath: STRUCT_PATH, destinationPath: str('Destination /Game path.'), destinationName: str('New asset name.') }, ['structPath', 'destinationPath']), OK, WRITE, WRITE_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('delete_struct', 'struct', 'Delete a Blueprint Struct asset.', schema({ structPath: STRUCT_PATH }, ['structPath']), OK, DESTRUCTIVE, DESTRUCTIVE_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('refresh_struct_dependencies', 'struct', 'Refresh dependencies of a Blueprint Struct after external changes.', schema({ structPath: STRUCT_PATH }, ['structPath']), OK, WRITE, WRITE_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('list_structs', 'struct', 'List all Blueprint Struct assets in a path.', schema({ path: str('Package path to search.'), searchScope: str('Optional path scope.') }, []), OK, READ, READ_POLICY, LOW, { dispatchMode: 'tool' }),
  r('export_struct', 'struct', 'Export a Blueprint Struct to a file.', schema({ structPath: STRUCT_PATH, destinationPath: str('Export file path.') }, ['structPath', 'destinationPath']), OK, READ, READ_POLICY, LOW, { dispatchMode: 'tool' }),
  r('import_struct', 'struct', 'Import a Blueprint Struct from a file or member definitions.', schema({ structPath: str('Destination struct path.'), sourcePath: str('Source file path.'), members: arrObj('Member definitions.') }, ['structPath']), OK, WRITE, WRITE_POLICY, MEDIUM, { dispatchMode: 'tool' }),
  r('get_instanced_struct_property', 'struct', 'Get a property from an FInstancedStruct on an asset.', schema({ assetPath: str('Asset /Game path.'), propertyName: str('Property name.') }, ['assetPath', 'propertyName']), OK, READ, READ_POLICY, LOW, { dispatchMode: 'tool' }),
  r('set_instanced_struct_property', 'struct', 'Set a property on an FInstancedStruct on an asset.', schema({ assetPath: str('Asset /Game path.'), propertyName: str('Property name.'), structType: str('Inner UScriptStruct asset path.'), structValues: { type: 'object', 'x-unreal-reflection-boundary': true, description: 'Field-name to value map.' } }, ['assetPath', 'propertyName', 'structType']), OK, WRITE, WRITE_POLICY, LOW, { dispatchMode: 'tool' })
];
