// scripts/canonical-registry/cpp-registry.ts
//
// Emits the native parent-tool registry: one translation unit that registers
// every canonical parent tool's name, description and category with
// FMcpToolRegistry at static-init time. Parameter schemas are not emitted: the
// native gateway validates against the capability records themselves
// (McpGeneratedCapabilityShards_*), so a parent needs only its identity here.

import { compareAscii } from '../../src/utils/serialization/ordering.js';
import { cppStringLiteral } from './types.js';
import type { ToolDefinition } from '../../src/tools/definitions/shared/tool-definition.js';

export const buildParentRegistrySource = (parents: readonly ToolDefinition[]): string => {
  const rows = [...parents]
    .sort((a, b) => compareAscii(a.name, b.name))
    .map((p) =>
      `\t\t\t{TEXT("${cppStringLiteral(p.name)}"), TEXT("${cppStringLiteral(p.description)}"), ` +
      `TEXT("${cppStringLiteral(p.category ?? 'utility')}")},`,
    )
    .join('\n');
  return (
    '// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.\n\n' +
    '#include "MCP/Registry/McpToolDefinition.h"\n' +
    '#include "MCP/Registry/McpToolRegistry.h"\n\n' +
    '// The canonical parent tools, registered before any request can arrive.\n' +
    'namespace\n{\n' +
    'struct FRegisterGeneratedParentTools\n{\n' +
    '\tFRegisterGeneratedParentTools()\n\t{\n' +
    '\t\tstatic FMcpToolDefinition Tools[] = {\n' +
    `${rows}\n` +
    '\t\t};\n' +
    '\t\tfor (FMcpToolDefinition& Tool : Tools)\n\t\t{\n' +
    '\t\t\tFMcpToolRegistry::Get().Register(&Tool);\n\t\t}\n' +
    '\t}\n};\n\n' +
    'FRegisterGeneratedParentTools GRegisterGeneratedParentTools;\n}\n'
  );
};
