// scripts/canonical-registry/native-shards.ts
//
// Deterministic emission of the native capability shard tables,
// framed as MSVC-safe translation units for Task-25 native discovery.
//
// Each shard carries the COMPLETE CapabilityRecord for every record (aliases,
// legacyIds, discovery, schemas.input + output, examples, availability with
// major/minor/patch/channel/preview + plugins + editorStates, behavior, policy,
// cost, routing, normalization, the complete deprecation object, and both
// hashes). Records are wrapped as {record: full} so native discovery can
// reproduce every field deterministically. Every record
// (ALL_CAPABILITY_RECORD_COUNT of them) is split into exactly 23 reviewable
// per-parent shards keyed on `routing.parentTool`, plus a generated index
// header that publishes the shard table.
//
// WHY per-parent (not per-domain): source-structure contract
// `tests/unit/plugin/source_structure.test.ts` requires every generated
// directory to stay within 25 source files. 23 shard sources + 1 index header =
// 24 files. Keying on `discovery.domain` would have produced 41 files.
//
// WHY chunked, escaped, ASCII literals (not one raw literal per shard):
// Task 23 emitted `TEXT(R"MCPCS(<whole shard>)MCPCS")`, up to 416,805
// characters on one logical line. That is unbuildable on MSVC once a
// translation unit includes it -- C2026 caps a single string literal at 65,535
// bytes and C1064 caps a source line. Raw delimiters additionally break if the
// payload ever contains the closing sequence. Splitting the payload into
// bounded, backslash-escaped, pure-ASCII literals removes all three hazards by
// construction instead of depending on the corpus never triggering them.

import type { CapabilityRecord } from '../../src/tools/catalog/capabilities/model.js';
import { compareAscii, sortById } from '../../src/utils/serialization/ordering.js';

const GENERATED_BANNER =
  '// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.\n';

const INDEX_INCLUDE = '#include "MCP/Generated/McpGeneratedCapabilityShards.h"';

// Bounded so that even an all-escaped chunk stays far below the MSVC 65,535-byte
// literal ceiling and the source-line token limit.
const MAX_CHUNK_CHARS = 4000;

// Parent names are validated snake_case, so upper-casing yields a unique C++ identifier.
const shardSymbol = (parent: string): string => `MCP_CAP_SHARD_${parent.toUpperCase()}`;

// Every code unit outside printable ASCII becomes a JSON \uXXXX escape. The
// result parses to the identical value and keeps the emitted C++ pure ASCII, so
// no universal-character-name is ever required.
const toAsciiJson = (json: string): string =>
  json.replace(
    /[^\x20-\x7e]/gu,
    (ch) => `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`,
  );

// Chunk boundaries are safe at any index: escaping happens per chunk and
// concatenation restores the exact payload, including split \uXXXX sequences.
const chunkPayload = (payload: string): readonly string[] => {
  const chunks: string[] = [];
  for (let i = 0; i < payload.length; i += MAX_CHUNK_CHARS) {
    chunks.push(payload.slice(i, i + MAX_CHUNK_CHARS));
  }
  return chunks;
};

const escapeCppLiteral = (chunk: string): string =>
  chunk.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

export interface NativeCapabilityShard {
  readonly symbol: string; // sanitized C++ identifier (unique)
  readonly parent: string; // original routing.parentTool
  readonly count: number; // record count in this shard
  readonly json: string; // compact ASCII-safe JSON array of { record }
  readonly chunks: readonly string[]; // bounded literal payloads, in order
}

// The ordered per-parent shard plan. Throws on a duplicate canonical id.
export const buildNativeCapabilityShards = (
  records: readonly CapabilityRecord[],
): readonly NativeCapabilityShard[] => {
  const seenIds = new Set<string>();
  for (const r of records) {
    if (seenIds.has(r.id)) {
      throw new Error(`FATAL: duplicate canonical id "${r.id}" in native capability input.`);
    }
    seenIds.add(r.id);
  }

  const byParent = new Map<string, CapabilityRecord[]>();
  for (const r of records) {
    const parent = r.routing.parentTool;
    const bucket = byParent.get(parent);
    if (bucket) bucket.push(r);
    else byParent.set(parent, [r]);
  }

  const shards: NativeCapabilityShard[] = [];
  for (const parent of [...byParent.keys()].sort(compareAscii)) {
    const ordered = sortById(byParent.get(parent) as CapabilityRecord[]);
    const entries = ordered.map((r) => ({ record: r }));
    const json = toAsciiJson(JSON.stringify(entries));
    shards.push({
      symbol: shardSymbol(parent),
      parent,
      count: entries.length,
      json,
      chunks: chunkPayload(json),
    });
  }
  return shards;
};

// Generated index header: extern chunk arrays plus the shard table the native
// loader enumerates. Payload bytes live in the per-shard translation units, so
// including this header stays cheap.
export const buildNativeCapabilityIndexHeader = (
  shards: readonly NativeCapabilityShard[],
  catalogRevision: string,
): string => {
  const externs = shards.map(
    (s) => `\textern const TCHAR* const ${s.symbol}_CHUNKS[];\t// ${s.parent} (${s.count})`,
  );
  const rows = shards.map(
    (s) =>
      `\t\t{ TEXT("${s.parent}"), Detail::${s.symbol}_CHUNKS, ${s.chunks.length}, ${s.count} },`,
  );
  const total = shards.reduce((n, s) => n + s.count, 0);
  return (
    `${GENERATED_BANNER}` +
    '#pragma once\n\n' +
    '#include "CoreMinimal.h"\n\n' +
    '/**\n' +
    ' * Generated native capability shard index (Task 23 data, Task 25 framing).\n' +
    ' *\n' +
    ' * One shard per routing.parentTool. Each shard is a chunked, escaped,\n' +
    ' * pure-ASCII JSON payload carrying the COMPLETE CapabilityRecord for native\n' +
    ' * discovery (aliases, legacyIds, discovery, schemas.input/output, examples,\n' +
    ' * availability, behavior/policy, normalization, deprecation, hashes).\n' +
    ` * ${shards.length} shards, ${total} records total.\n` +
    ' *\n' +
    ' * Chunks are bounded so no single string literal approaches the MSVC 65,535-byte\n' +
    ' * ceiling; concatenating a shard\'s chunks in order yields its exact JSON.\n' +
    ' */\n' +
    'namespace McpGeneratedCapabilityShards\n{\n' +
    'namespace Detail\n{\n' +
    externs.join('\n') +
    '\n}\n\n' +
    'struct FMcpCapabilityShard\n{\n' +
    '\tconst TCHAR* ParentTool;\n' +
    '\tconst TCHAR* const* Chunks;\n' +
    '\tint32 ChunkCount;\n' +
    '\tint32 RecordCount;\n' +
    '};\n\n' +
    `inline int32 Num() { return ${shards.length}; }\n\n` +
    'inline const FMcpCapabilityShard& At(int32 Index)\n{\n' +
    '\tstatic const FMcpCapabilityShard Table[] = {\n' +
    rows.join('\n') +
    '\n\t};\n' +
    '\tcheck(Index >= 0 && Index < Num());\n' +
    '\treturn Table[Index];\n' +
    '}\n\n' +
    `inline int32 TotalRecordCount() { return ${total}; }\n\n` +
    `inline const TCHAR* CatalogRevision() { return TEXT("${catalogRevision}"); }\n` +
    '}\n'
  );
};

// One shard translation unit: its bounded literal chunks.
export const buildNativeCapabilityShardSource = (
  shard: NativeCapabilityShard,
): string =>
  `${GENERATED_BANNER}` +
  `${INDEX_INCLUDE}\n\n` +
  `// ${shard.parent}: ${shard.count} records, ${shard.chunks.length} chunks, ` +
  `${shard.json.length} payload characters.\n` +
  'namespace McpGeneratedCapabilityShards\n{\nnamespace Detail\n{\n' +
  `const TCHAR* const ${shard.symbol}_CHUNKS[] = {\n` +
  shard.chunks.map((c) => `\tTEXT("${escapeCppLiteral(c)}"),`).join('\n') +
  '\n};\n}\n}\n';

export { MAX_CHUNK_CHARS };
