// scripts/canonical-registry/ts-targets.ts
//
// Deterministic emission of the TypeScript + neutral JSON generated artifacts:
//   - canonical-registry.generated.json (the record data)
//   - canonical-registry.generated.ts (typed entry point that imports the JSON)
//   - parent-tool-definitions.generated.ts (23 parent ToolDefinitions)

import { compareAscii } from '../../src/utils/serialization/ordering.js';
import type { CapabilityRecord } from '../../src/tools/catalog/capabilities/model.js';
import type { ToolDefinition } from '../../src/tools/definitions/shared/tool-definition.js';

const TS_HEADER = `/* eslint-disable */
// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.
// Re-run the generator after changing canonical tool definitions or capability records.
`;

export interface TsDataParams {
  readonly records: readonly CapabilityRecord[];
  readonly catalogRevision: string;
  readonly recordCount: number;
}

// The records live once, in the JSON; this module only types and parses them.
export const buildTsDataModule = (params: TsDataParams): string => `${TS_HEADER}
import registry from './canonical-registry.generated.json' with { type: 'json' };
import type { CapabilityRecord } from '../model.js';
import { parseCapabilityCatalog } from '../parser.js';

export const CANONICAL_CAPABILITY_RECORD_COUNT = ${params.recordCount};
export const CATALOG_REVISION = ${JSON.stringify(params.catalogRevision)};
export const CANONICAL_CAPABILITY_RECORDS: readonly CapabilityRecord[] = parseCapabilityCatalog(registry.records);

export type { CapabilityRecord };
`;

export const buildParentDefsModule = (parents: readonly ToolDefinition[]): string =>
  `${TS_HEADER}
import type { ToolDefinition } from '../../../definitions/shared/tool-definition.js';

/**
 * Generated 23-parent-tool definitions.
 * Emitted from the parents DERIVED in parent-derivation.ts, so the gateway
 * manifest and registry keep one canonical source derived from the records.
 */
export const generatedParentToolDefinitions: readonly ToolDefinition[] = ${JSON.stringify(parents, null, 2)};
`;

// Cost index: `<tool>::<action>` -> `"<latency>|<resources>"`.
//
// Emitted as its own module because the request-dispatch path needs a
// capability's cost class on every call, and importing the full canonical
// registry there costs ~1.4s and ~185MB of resident heap. This projection is a
// few tens of KB of plain string data and carries no schemas.
const LATENCY_RANK: Record<string, number> = { instant: 0, interactive: 1, 'long-running': 2 };
const RESOURCE_RANK: Record<string, number> = { low: 0, medium: 1, high: 2 };

const costRank = (latency: string, resources: string): number => {
  const latencyRank = LATENCY_RANK[latency];
  const resourceRank = RESOURCE_RANK[resources];
  if (latencyRank === undefined || resourceRank === undefined) {
    throw new Error(`FATAL: unknown capability cost class "${latency}|${resources}". Refusing to generate.`);
  }
  return latencyRank * 3 + resourceRank;
};

export const buildCostIndexModule = (records: readonly CapabilityRecord[]): string => {
  const index = new Map<string, string>();

  for (const record of records) {
    const value = `${record.cost.latency}|${record.cost.resources}`;
    // Guard the value before it is stored so a malformed class fails the build
    // rather than silently reaching the dispatch path.
    const rank = costRank(record.cost.latency, record.cost.resources);

    // A capability is reachable under its routing pair AND under every legacy
    // pair, and the dispatch layer may see either spelling.
    const keys = new Set<string>([
      `${record.routing.parentTool}::${record.routing.dispatchAction}`,
      ...record.legacyIds.map((legacy) => `${legacy.tool}::${legacy.action}`),
    ]);

    for (const key of keys) {
      const existing = index.get(key);
      if (existing === undefined) {
        index.set(key, value);
        continue;
      }
      if (existing === value) continue;
      // Several capabilities can share one dispatch route. Under-budgeting a
      // shared route would kill the expensive member mid-flight, so the route
      // inherits the most expensive contributor.
      const [existingLatency, existingResources] = existing.split('|');
      if (rank > costRank(existingLatency as string, existingResources as string)) {
        index.set(key, value);
      }
    }
  }

  const sorted = [...index.entries()].sort(([a], [b]) => compareAscii(a, b));
  const body = sorted.map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)}`).join(',\n');

  return `${TS_HEADER}
// \`<parentTool>::<action>\` -> \`"<cost.latency>|<cost.resources>"\`, projected
// from the capability records so a request deadline can be derived from what
// the capability actually costs instead of one flat number for every action.
//
// Both the routing pair and every legacy pair are keyed, because either
// spelling can reach the dispatch layer. Where capabilities share a dispatch
// route, the route carries the most expensive contributor's cost class.

export const CAPABILITY_COST_INDEX: Readonly<Record<string, string>> = {
${body}
};

export const CAPABILITY_COST_INDEX_KEY_COUNT = ${sorted.length};
`;
};

export const buildNeutralModel = (params: TsDataParams): string =>
  JSON.stringify(
    { catalogRevision: params.catalogRevision, recordCount: params.recordCount, records: params.records },
    null,
    2,
  );
