/**
 * Landscape family records (16 actions).
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildRecord } from './helpers.js';
import { P } from './properties.js';

const F = 'landscape';
const WU = ['A landscape must be created or modified in the current level.'];
// The landscape the edit targets: by label, package path or actor object path.
const LANDSCAPE = { landscapeName: P.landscapeName, landscapePath: P.landscapePath, landscapeActorPath: P.landscapeActorPath };
const PAINT = { region: P.region, strength: P.strength, skipFlush: P.skipFlush };

export const LANDSCAPE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'build_environment.create_landscape', action: 'create_landscape', family: F,
    topics: ['landscape', 'terrain', 'new landscape', 'heightfield', 'add a landscape'],
    summary: 'Create a new Landscape actor in the current level.',
    whenToUse: WU, whenNotToUse: ['A landscape already exists and should be modified.'],
    inputProps: { name: P.name, landscapeName: P.landscapeName, location: P.location, sizeX: P.sizeX,
      sizeY: P.sizeY, quadsPerSection: P.quadsPerSection, sectionSize: P.sectionSize,
      sectionsPerComponent: P.sectionsPerComponent, componentCount: P.componentCount, materialPath: P.materialPath },
    requiredOneOf: ['name', 'landscapeName'],
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'create_landscape',
    exampleInput: { action: 'create_landscape', name: 'Landscape_1', sizeX: 1009, sizeY: 1009 },
  }),
  buildRecord({
    id: 'build_environment.sculpt', action: 'sculpt', family: F,
    summary: 'Sculpt the landscape heightmap at a location with a brush.',
    whenToUse: WU, whenNotToUse: ['The landscape should be modified via raw heightmap data.'],
    inputProps: { ...LANDSCAPE,
      tool: P.tool, location: P.location, radius: P.radius, strength: P.strength,
      falloff: P.falloff, skipFlush: P.skipFlush },
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'sculpt_landscape',
    exampleInput: { action: 'sculpt', landscapeName: 'Landscape_1', location: { x: 0, y: 0, z: 0 }, radius: 500 },
    aliases: ['build_environment.sculpt_heightmap'],
  }),
  buildRecord({
    id: 'build_environment.modify_heightmap', action: 'modify_heightmap', family: F,
    summary: 'Modify landscape heightmap data in a region.',
    whenToUse: WU, whenNotToUse: ['The landscape should be sculpted interactively.'],
    inputProps: { ...LANDSCAPE,
      operation: P.operation, heightData: P.heightData, minX: P.minX, minY: P.minY,
      maxX: P.maxX, maxY: P.maxY, region: P.region, updateNormals: P.updateNormals, skipFlush: P.skipFlush },
    effect: 'write', latency: 'interactive', resources: 'medium',
    dispatchAction: 'modify_heightmap',
    exampleInput: { action: 'modify_heightmap', landscapeName: 'Landscape_1', operation: 'set', heightData: [100, 200] },
  }),
  buildRecord({
    id: 'build_environment.set_landscape_material', action: 'set_landscape_material', family: F,
    summary: 'Set the material applied to a landscape.',
    whenToUse: ['A landscape needs a different material assignment.'],
    whenNotToUse: ['The material should be configured with layer blends.'],
    inputProps: { ...LANDSCAPE, materialPath: P.materialPath },
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    dispatchAction: 'set_landscape_material',
    exampleInput: { action: 'set_landscape_material', landscapeName: 'Landscape_1', materialPath: '/Game/Materials/M_Landscape' },
  }),
  buildRecord({
    id: 'build_environment.paint_landscape', action: 'paint_landscape', family: F,
    summary: 'Paint a landscape layer over a brush disc (location + radius), a vertex region, or the whole landscape.',
    whenToUse: WU, whenNotToUse: ['The landscape layer weight should be set via raw data.'],
    inputProps: { ...LANDSCAPE, layerName: P.layerName,
      location: { ...P.location, description: 'Brush centre in world space; paints the disc of radius around it (radius required).' },
      radius: { ...P.radius, description: 'Brush radius in world units (with location).' }, ...PAINT },
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'paint_landscape', landscapeName: 'Landscape_1', layerName: 'Grass', location: { x: 0, y: 0, z: 0 }, radius: 500 },
  }),
  buildRecord({
    id: 'build_environment.paint_landscape_layer', action: 'paint_landscape_layer', family: F,
    summary: 'Paint a landscape layer at a uniform weight over a vertex region, or the whole landscape.',
    whenToUse: WU, whenNotToUse: ['The landscape should be painted interactively.'],
    inputProps: { ...LANDSCAPE, layerName: P.layerName,
      layerInfoPath: { ...P.layerInfoPath, description: 'Layer info asset to use when the landscape has no layer of that name yet (else one lives only inside the landscape).' },
      ...PAINT },
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'paint_landscape_layer', landscapeName: 'Landscape_1', layerName: 'Grass' },
  }),
  buildRecord({
    id: 'build_environment.import_heightmap', action: 'import_heightmap', family: F,
    summary: 'Import a heightmap file into a landscape.',
    whenToUse: ['A heightmap file must be imported to create or update a landscape.'],
    whenNotToUse: ['The heightmap should be generated procedurally.'],
    inputProps: { ...LANDSCAPE, heightmapPath: { type: 'string', description: 'Raw 16-bit heightmap file, project-relative.' },
      region: P.region, updateNormals: P.updateNormals, skipFlush: P.skipFlush },
    effect: 'write', latency: 'interactive', resources: 'medium',
    exampleInput: { action: 'import_heightmap', landscapeName: 'Landscape_1', heightmapPath: 'Saved/Heightmaps/terrain.raw' },
  }),
  buildRecord({
    id: 'build_environment.export_heightmap', action: 'export_heightmap', family: F,
    summary: 'Export a landscape heightmap to a file.',
    whenToUse: ['A landscape heightmap must be exported for external editing.'],
    whenNotToUse: ['The heightmap should be modified in the editor.'],
    inputProps: { outputPath: P.outputPath, ...LANDSCAPE, path: P.path, region: P.region },
    effect: 'read', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'export_heightmap', landscapeName: 'Landscape_1', path: '/Game/Heightmaps/export.raw' },
  }),
  buildRecord({
    id: 'build_environment.create_landscape_layer_info', action: 'create_landscape_layer_info', family: F,
    summary: 'Create a landscape layer info asset.',
    whenToUse: ['A new landscape layer info asset is needed for painting.'],
    whenNotToUse: ['An existing layer info asset should be reused.'],
    inputProps: { hardness: P.hardness, noWeightBlend: P.noWeightBlend, name: P.name, path: P.path, layerName: P.layerName, physicalMaterialPath: P.physicalMaterialPath },
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'create_landscape_layer_info', name: 'LI_Grass', path: '/Game/Landscape' },
  }),
  buildRecord({
    id: 'build_environment.configure_landscape_material', action: 'configure_landscape_material', family: F,
    summary: 'Assign the material a landscape renders with (its layer blends come from the material).',
    whenToUse: ['A landscape needs a different material assignment.'],
    whenNotToUse: ['Layers should be painted: use paint_landscape_layer.'],
    inputProps: { ...LANDSCAPE, materialPath: P.materialPath },
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_landscape_material', landscapeName: 'Landscape_1', materialPath: '/Game/M_Landscape' },
  }),
  buildRecord({
    id: 'build_environment.configure_landscape_splines', action: 'configure_landscape_splines', family: F,
    summary: 'Replace a landscape\'s splines with one through the given points (width, loop, terrain deform, painted layer).',
    whenToUse: ['Landscape splines need to be added or modified.'],
    whenNotToUse: ['Standalone spline actors should be used instead.'],
    inputProps: { ...LANDSCAPE, points: P.points,
      width: { ...P.width, description: 'Spline width in world units (default 256); side falloff is half of it.' },
      closedLoop: P.closedLoop, layerName: { ...P.layerName, description: 'Landscape layer the spline paints.' },
      raiseTerrain: P.raiseTerrain, lowerTerrain: P.lowerTerrain },
    effect: 'write', latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_landscape_splines', landscapeName: 'Landscape_1' },
  }),
  buildRecord({
    id: 'build_environment.configure_landscape_lod', action: 'configure_landscape_lod', family: F,
    summary: 'Configure LOD settings for a landscape; fails when nothing applied.',
    whenToUse: ['Landscape LOD distance or screen-size must be tuned.'],
    whenNotToUse: ['LODs should be generated rather than configured.'],
    inputProps: { ...LANDSCAPE,
      settings: { ...P.settings, description: 'Landscape properties by name, e.g. {"MaxLODLevel": 2, "LODDistributionSetting": 1.5}.' } },
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    exampleInput: { action: 'configure_landscape_lod', landscapeName: 'Landscape_1' },
  }),
  buildRecord({
    id: 'build_environment.create_landscape_streaming_proxy', action: 'create_landscape_streaming_proxy', family: F,
    summary: 'Create a landscape streaming proxy for World Partition.',
    whenToUse: ['A landscape streaming proxy is needed for World Partition tiles.'],
    whenNotToUse: ['The level does not use World Partition.'],
    inputProps: { ...LANDSCAPE,
      actorName: { ...P.actorName, description: 'Label of the proxy (found and reused when it exists; default LandscapeStreamingProxy).' },
      location: { ...P.location, description: 'Proxy location (default the landscape\'s).' },
      rotation: { ...P.rotation, description: 'Proxy rotation (default the landscape\'s).' } },
    effect: 'write', latency: 'interactive', resources: 'medium',
    exampleInput: { action: 'create_landscape_streaming_proxy', landscapeName: 'Landscape_1' },
  }),
  buildRecord({
    id: 'build_environment.create_landscape_grass_type', action: 'create_landscape_grass_type', family: F,
    summary: 'Create a landscape grass type asset.',
    whenToUse: ['A grass type asset is needed for landscape grass rendering.'],
    whenNotToUse: ['Foliage instances should be placed manually.'],
    inputProps: { name: P.name, meshPath: P.meshPath, staticMesh: P.staticMesh, path: P.path },
    effect: 'write', latency: 'interactive', resources: 'low',
    dispatchAction: 'create_landscape_grass_type',
    exampleInput: { action: 'create_landscape_grass_type', name: 'GT_Grass', meshPath: '/Game/Meshes/SM_Grass' },
  }),
  buildRecord({
    id: 'build_environment.generate_lods', action: 'generate_lods', family: F,
    summary: 'Generate LODs for static mesh assets (foliage meshes included).',
    whenToUse: ['LODs must be generated for one or more assets.'],
    whenNotToUse: ['LODs have already been generated.'],
    inputProps: { assetPath: P.assetPath, assetPaths: P.assetPaths, assets: P.assets, numLODs: P.numLODs },
    effect: 'write', latency: 'long-running', resources: 'high',
    behavior: { longRunning: true },
    exampleInput: { action: 'generate_lods', assetPaths: ['/Game/Meshes/SM_Rock'], numLODs: 3 },
  }),
];
