// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_SystemControl : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("system_control"); }
	FString GetDescription() const override { return TEXT("Control the project runtime: profiling, benchmarks, scalability/LOD/Nanite settings, CVars, console commands, Python scripts, UBT, tests, logs, and widgets."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.Array(TEXT("actors"), TEXT("Actor names to merge (>=2 required)."), TEXT("string"));
			Schema.String(TEXT("archiveDirectory"), TEXT("Archive directory package_project wrote (default <Project>/Packaged). Must be inside the project."));
			Schema.String(TEXT("arguments"), TEXT("Extra UBT arguments (validated)."));
			Schema.String(TEXT("assetPath"), TEXT("Single asset path to validate."));
			Schema.Bool(TEXT("boostPlayerLocation"), TEXT("Prioritize streaming around the player."));
			Schema.Bool(TEXT("build"), TEXT("Compile the game target first (default true)."));
			Schema.String(TEXT("category"), TEXT("Alternate category name field."));
			Schema.String(TEXT("categoryName"), TEXT("Category name (letters, digits, underscore, hyphen only)."));
			Schema.Number(TEXT("cellSize"), TEXT("Partition cell size."));
			Schema.String(TEXT("channels"), TEXT("Log channel(s) to subscribe to."));
			Schema.String(TEXT("childClass"), TEXT("Child component class (required)."));
			Schema.String(TEXT("code"), TEXT("Python code to execute inline (1 MB max)."));
			Schema.String(TEXT("command"), TEXT("Alternate CVar name field (parsed as name + value)."));
			Schema.String(TEXT("configuration"), TEXT("Build configuration (default Development)."));
			Schema.StringEnum(TEXT("connectionType"), { TEXT("file"), TEXT("network") }, TEXT("Trace connection type; network is restricted to loopback."));
			Schema.StringEnum(TEXT("control"), { TEXT("start"), TEXT("stop"), TEXT("benchmark"), TEXT("memory_report"), TEXT("show_stats"), TEXT("pause"), TEXT("resume"), TEXT("capture_trace"), TEXT("send_snapshot"), TEXT("write_snapshot"), TEXT("launch_viewer"), TEXT("subscribe"), TEXT("unsubscribe"), TEXT("spawn_category") }, TEXT("Which profile performance variant to run."));
			Schema.String(TEXT("cvar"), TEXT("Alternate CVar name field."));
			Schema.Bool(TEXT("detailed"), TEXT("Produce a detailed report."));
			Schema.Number(TEXT("duration"), TEXT("Notification duration."));
			Schema.Bool(TEXT("enableBatching"), TEXT("Enable batching."));
			Schema.Bool(TEXT("enableInstancing"), TEXT("Enable instancing on the merged mesh."));
			Schema.Bool(TEXT("enabled"), TEXT("Enable (true) or disable (false) VSync."));
			Schema.Bool(TEXT("enabledOnly"), TEXT("Return only plugins currently enabled for this project."));
			Schema.String(TEXT("file"), TEXT("Path to a .py file to execute."));
			Schema.String(TEXT("filename"), TEXT("Screenshot filename base."));
			Schema.String(TEXT("filter"), TEXT("Case-insensitive text a line must contain."));
			Schema.Number(TEXT("forceLOD"), TEXT("Forced LOD level."));
			Schema.Bool(TEXT("forceRecompile"), TEXT("Force a shader recompile."));
			Schema.Number(TEXT("height"), TEXT("Height in pixels."));
			Schema.String(TEXT("host"), TEXT("Trace host (loopback for network)."));
			Schema.Bool(TEXT("includeMetadata"), TEXT("Include capture metadata."));
			Schema.StringEnum(TEXT("info"), { TEXT("status"), TEXT("analyze") }, TEXT("Which get trace status variant to run; omit for 'status'."));
			Schema.String(TEXT("jobId"), TEXT("The jobId package_project or launch_build returned. Omit to list the jobIds this editor session knows."));
			Schema.String(TEXT("key"), TEXT("Alternate CVar name field."));
			Schema.StringEnum(TEXT("kind"), { TEXT("tests"), TEXT("ubt") }, TEXT("Which run build variant to run."));
			Schema.Bool(TEXT("launchViewer"), TEXT("Also open the Unreal Insights application on the new trace (default false)."));
			Schema.Number(TEXT("level"), TEXT("Level 0-4 (clamped)."));
			Schema.Number(TEXT("lines"), TEXT("How many of the newest matching lines to return, oldest first (default 100, max 1000)."));
			Schema.Number(TEXT("lodBias"), TEXT("Additional LOD bias."));
			Schema.Array(TEXT("maps"), TEXT("Maps to cook. Pass these when a map is reached by NAME at runtime (OpenLevel) rather than by reference, or the cooker will not find it."), TEXT("string"));
			Schema.Number(TEXT("maxFPS"), TEXT("Maximum frames per second."));
			Schema.Bool(TEXT("mergeActors"), TEXT("Whether to merge source actors; forced true by the merge_actors action."));
			Schema.String(TEXT("message"), TEXT("Notification message text."));
			Schema.FreeformObject(TEXT("metadata"), TEXT("Optional metadata payload."));
			Schema.StringEnum(TEXT("minVerbosity"), { TEXT("error"), TEXT("warning"), TEXT("display"), TEXT("log"), TEXT("verbose") }, TEXT("Least severe level to include (default log): error returns errors only, warning adds warnings, verbose returns everything."));
			Schema.String(TEXT("mode"), TEXT("Optimization mode."));
			Schema.String(TEXT("name"), TEXT("CVar name (alternatively cvar, key, or command)."));
			Schema.String(TEXT("outputPath"), TEXT("Output /Game folder for the merged asset."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite existing trace files."));
			Schema.String(TEXT("packageName"), TEXT("Package name for the merged asset."));
			Schema.Bool(TEXT("pak"), TEXT("Pak the staged content (default true)."));
			Schema.String(TEXT("parentName"), TEXT("Optional parent panel name."));
			Schema.String(TEXT("path"), TEXT("Alternate single asset path field."));
			Schema.Array(TEXT("paths"), TEXT("Asset paths to validate."), TEXT("string"));
			Schema.Number(TEXT("pitch"), TEXT("Pitch multiplier."));
			Schema.String(TEXT("platform"), TEXT("Platform (default Win64)."));
			Schema.String(TEXT("pluginName"), TEXT("Plugin name exactly as reported by list_plugins (the .uplugin name, not the friendly name)."));
			Schema.StringEnum(TEXT("pluginState"), { TEXT("enable"), TEXT("disable") }, TEXT("Which enable plugin variant to run; omit for 'enable'."));
			Schema.Number(TEXT("poolSize"), TEXT("Streaming pool size in MB."));
			Schema.Number(TEXT("port"), TEXT("Trace port."));
			Schema.String(TEXT("profile"), TEXT("Baseline profile name (default balanced)."));
			Schema.StringEnum(TEXT("profileType"), { TEXT("CPU"), TEXT("GPU"), TEXT("Memory"), TEXT("RenderThread"), TEXT("GameThread"), TEXT("All") }, TEXT("Profiling domain to display."));
			Schema.Bool(TEXT("recursive"), TEXT("Validate recursively."));
			Schema.Bool(TEXT("replaceSourceActors"), TEXT("Replace source actors in the level."));
			Schema.String(TEXT("resolution"), TEXT("Resolution as WxH (e.g. 1920x1080)."));
			Schema.Bool(TEXT("returnBase64"), TEXT("Return PNG as base64. Defaults to false — a plain capture returns path + metadata. Set true for inline image data; pair with resolution= (e.g. \"1280x720\") to keep the PNG under the base64 size cap."));
			Schema.String(TEXT("savePath"), TEXT("Destination /Game folder."));
			Schema.Number(TEXT("scale"), TEXT("Resolution scale percentage."));
			Schema.Number(TEXT("seconds"), TEXT("How long the game runs before it is closed (default 20, 5-120). Quitting or crashing sooner fails the run."));
			Schema.String(TEXT("section"), TEXT("Settings section."));
			Schema.StringEnum(TEXT("setting"), { TEXT("resolution"), TEXT("fullscreen"), TEXT("quality"), TEXT("cvar"), TEXT("fps"), TEXT("profile"), TEXT("scalability"), TEXT("frame_rate_limit"), TEXT("resolution_scale"), TEXT("vsync"), TEXT("lod"), TEXT("nanite"), TEXT("occlusion_culling"), TEXT("texture_streaming"), TEXT("world_partition"), TEXT("gpu_timing"), TEXT("draw_calls"), TEXT("shaders"), TEXT("baseline") }, TEXT("Which configure display variant to run."));
			Schema.String(TEXT("snapshotPath"), TEXT("Output snapshot path."));
			Schema.String(TEXT("soundPath"), TEXT("Sound asset path."));
			Schema.StringEnum(TEXT("source"), { TEXT("editor"), TEXT("livecoding"), TEXT("build"), TEXT("previous") }, TEXT("editor (default): the editor log. build: the UnrealBuildTool log of the last compile, where the compiler errors behind \"Live coding failed\" go. livecoding: the Live Coding console log (patching and linking). previous: the log of the editor's previous run, e.g. why an editor that went away exited. Only filter and lines apply to build, livecoding and previous."));
			Schema.Number(TEXT("streamingDistance"), TEXT("Loading/streaming range."));
			Schema.String(TEXT("target"), TEXT("UBT target name (required)."));
			Schema.String(TEXT("text"), TEXT("Optional text for text-bearing components."));
			Schema.String(TEXT("traceFile"), TEXT("Output trace file path."));
			Schema.String(TEXT("tracePath"), TEXT("Output trace directory path."));
			Schema.String(TEXT("type"), TEXT("Profiling domain to capture."));
			Schema.String(TEXT("value"), TEXT("Setting value."));
			Schema.Number(TEXT("volume"), TEXT("Volume multiplier (0 silences the request)."));
			Schema.String(TEXT("widgetId"), TEXT("Widget id; \"notification\" renders a notification."));
			Schema.StringEnum(TEXT("widgetOp"), { TEXT("create"), TEXT("add_child"), TEXT("show") }, TEXT("Which create widget variant to run; omit for 'create'."));
			Schema.String(TEXT("widgetPath"), TEXT("Full widget path; name and savePath are derived when name is absent."));
			Schema.String(TEXT("widgetType"), TEXT("Widget type."));
			Schema.Number(TEXT("width"), TEXT("Width in pixels."));
			Schema.String(TEXT("window"), TEXT("With mode full_editor_window, which window to capture: a list index (\"2\") or a case-insensitive substring of its title (\"WBP_HubUI\"). Omit for the main editor frame; responses list the open windows under windows[]."));
			Schema.Bool(TEXT("windowed"), TEXT("Show a 1280x720 window instead of rendering offscreen (default false: no window, no focus taken)."));
			Schema.StringEnum(TEXT("action"), { TEXT("configure_display"), TEXT("console_command"), TEXT("profile_performance"), TEXT("configure_performance"), TEXT("merge_actors"), TEXT("run_build"), TEXT("package_project"), TEXT("package_status"), TEXT("launch_build"), TEXT("subscribe"), TEXT("read_log"), TEXT("execute_python"), TEXT("set_project_setting"), TEXT("get_project_settings"), TEXT("validate_assets"), TEXT("lumen_update_scene"), TEXT("list_plugins"), TEXT("enable_plugin"), TEXT("start_session"), TEXT("get_trace_status"), TEXT("create_widget"), TEXT("play_sound"), TEXT("screenshot") }, TEXT("Action to invoke on system_control."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedCore_SystemCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_SystemControl());

}
