// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Tools/McpGeneratedParentRegistry.h"

class FMcpGenTool_Inspect : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("inspect"); }
	FString GetDescription() const override { return TEXT("Inspect any UObject: read/write properties, list components, export snapshots, and query class info. Actions: inspect_cdo (Blueprint CDO properties + all components without spawning an actor; use blueprintPath, optional detailed/componentName/propertyNames), inspect_class (class metadata), inspect_object (world actor), get_property/set_property, get_components, get_component_details (WORLD actors: actorName+componentName; a blueprintPath is routed to inspect_cdo), list_objects, find_by_class, find_by_tag, runtime_report."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("actorName"), TEXT("World actor name to inspect."));
			Schema.String(TEXT("blueprintPath"), TEXT("Blueprint asset /Game path (for CDO/component inspection without spawning)."));
			Schema.String(TEXT("className"), TEXT("Class name or /Script/ class path to inspect."));
			Schema.String(TEXT("classPath"), TEXT("Class asset path (alias of className)."));
			Schema.String(TEXT("componentName"), TEXT("Component name on the actor."));
			Schema.AnyValue(TEXT("componentNames"), TEXT("Return only these components in components, by name (case-insensitive); a name that matches none is listed under missingComponents."));
			Schema.Bool(TEXT("detailed"), TEXT("Return detailed property/component information."));
			Schema.StringEnum(TEXT("editorState"), { TEXT("selected_actors"), TEXT("viewport"), TEXT("world_settings"), TEXT("project_settings"), TEXT("editor_settings") }, TEXT("Which get editor state variant to run."));
			Schema.String(TEXT("filter"), TEXT("Runtime report filter expression."));
			Schema.StringEnum(TEXT("info"), { TEXT("details"), TEXT("property") }, TEXT("Which get component details variant to run; omit for 'details'."));
			Schema.StringEnum(TEXT("kind"), { TEXT("class"), TEXT("struct"), TEXT("cdo") }, TEXT("Which inspect class variant to run; omit for 'class'."));
			Schema.StringEnum(TEXT("lookup"), { TEXT("list"), TEXT("by_tag"), TEXT("metadata"), TEXT("bounding_box"), TEXT("export") }, TEXT("Which query object variant to run."));
			Schema.String(TEXT("name"), TEXT("Actor name identifier (alias of actorName)."));
			Schema.StringEnum(TEXT("objectKind"), { TEXT("object"), TEXT("actor"), TEXT("level"), TEXT("material"), TEXT("mesh"), TEXT("texture") }, TEXT("Which inspect object variant to run; omit for 'object'."));
			Schema.String(TEXT("objectPath"), TEXT("Object path of the world actor or asset (e.g. /Game/Maps/Demo.Demo_PersistentLevel)."));
			Schema.String(TEXT("propertyName"), TEXT("Property name to read or write."));
			Schema.Array(TEXT("propertyNames"), TEXT("Specific property names to include."), TEXT("string"));
			Schema.String(TEXT("propertyPath"), TEXT("Property path (alias of propertyName)."));
			Schema.String(TEXT("snapshotName"), TEXT("Snapshot name for create/restore."));
			Schema.StringEnum(TEXT("snapshotOp"), { TEXT("create"), TEXT("restore") }, TEXT("Which create snapshot variant to run; omit for 'create'."));
			Schema.StringEnum(TEXT("statsKind"), { TEXT("performance"), TEXT("memory"), TEXT("scene") }, TEXT("Which get stats variant to run."));
			Schema.String(TEXT("structPath"), TEXT("UserDefinedStruct asset /Game path to introspect."));
			Schema.String(TEXT("tag"), TEXT("Actor tag to match."));
			Schema.AnyValue(TEXT("value"), TEXT("Property value to set (type depends on the target property)."));
			Schema.StringEnum(TEXT("action"), { TEXT("inspect_object"), TEXT("get_blueprint_details"), TEXT("get_property"), TEXT("set_property"), TEXT("inspect_class"), TEXT("get_components"), TEXT("get_component_details"), TEXT("set_component_property"), TEXT("query_object"), TEXT("add_tag"), TEXT("create_snapshot"), TEXT("delete_object"), TEXT("find_by_class"), TEXT("runtime_report"), TEXT("get_editor_state"), TEXT("get_stats") }, TEXT("Action to invoke on inspect."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};

class FMcpGenTool_ManageLevel : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_level"); }
	FString GetDescription() const override { return TEXT("Load/save levels, configure streaming, and build lighting."); }
	FString GetCategory() const override { return TEXT("core"); }
	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		FMcpSchemaBuilder Schema;
			Schema.String(TEXT("assetPath"), TEXT("Alias of levelPath resolved by the manage_level argument normalizer."));
			Schema.Array(TEXT("color"), TEXT("Linear color [r, g, b] or [r, g, b, a]."), TEXT("number"));
			Schema.String(TEXT("destinationPath"), TEXT("Destination path for move/copy."));
			Schema.Bool(TEXT("enableWorldBoundsChecks"), TEXT("Whether actors leaving the world bounds are culled."));
			Schema.String(TEXT("exportPath"), TEXT("Export file path."));
			Schema.String(TEXT("gameMode"), TEXT("GameMode override for the level. Accepts the Blueprint asset path or its generated _C class path."));
			Schema.Number(TEXT("gravityZ"), TEXT("World gravity along Z; setting it also enables the global gravity override."));
			Schema.StringEnum(TEXT("info"), { TEXT("summary"), TEXT("current_level") }, TEXT("Which get summary variant to run; omit for 'summary'."));
			Schema.Number(TEXT("intensity"), TEXT("Light intensity."));
			Schema.Number(TEXT("killZ"), TEXT("Z height below which actors are destroyed."));
			Schema.String(TEXT("levelName"), TEXT("Level name identifier."));
			Schema.StringEnum(TEXT("levelOp"), { TEXT("duplicate"), TEXT("rename") }, TEXT("Which duplicate level variant to run; omit for 'duplicate'."));
			Schema.String(TEXT("levelPath"), TEXT("Level asset path (e.g. /Game/Maps/Demo)."));
			Schema.Array(TEXT("levelPaths"), TEXT("Array of level asset paths."), TEXT("string"));
			Schema.String(TEXT("lightType"), TEXT("Light type: Point, Directional, Spot, Sky, or Rect (short/class/lowercase accepted)."));
			Schema.FreeformObject(TEXT("location"), TEXT("Actor world location {x, y, z}."));
			Schema.FreeformObject(TEXT("metadata"), TEXT("Metadata key/value pairs to write."));
			Schema.String(TEXT("name"), TEXT("Light actor name."));
			Schema.String(TEXT("newName"), TEXT("New name for the level asset."));
			Schema.Bool(TEXT("overwrite"), TEXT("Overwrite if the destination already exists."));
			Schema.String(TEXT("packagePath"), TEXT("Package path for import."));
			Schema.String(TEXT("parentLevel"), TEXT("Parent level path for the sub-level."));
			Schema.String(TEXT("parentPath"), TEXT("Parent directory path for the sub-level."));
			Schema.String(TEXT("path"), TEXT("Alias of levelPath resolved by the manage_level argument normalizer."));
			Schema.String(TEXT("quality"), TEXT("Lighting build quality: Preview, Medium, High, or Production."));
			Schema.FreeformObject(TEXT("rotation"), TEXT("Actor rotation {pitch, yaw, roll} or {x, y, z, w}."));
			Schema.Bool(TEXT("saveDirtyPackages"), TEXT("Save dirty packages before the operation."));
			Schema.StringEnum(TEXT("saveMode"), { TEXT("save"), TEXT("as") }, TEXT("Which save variant to run; omit for 'save'."));
			Schema.String(TEXT("savePath"), TEXT("Path to save the level asset."));
			Schema.Bool(TEXT("shouldBeLoaded"), TEXT("Whether the level should be loaded."));
			Schema.Bool(TEXT("shouldBeVisible"), TEXT("Whether the level should be visible."));
			Schema.String(TEXT("sourcePath"), TEXT("Source path for import/move/copy."));
			Schema.StringEnum(TEXT("streamOp"), { TEXT("stream"), TEXT("unload") }, TEXT("Which stream variant to run; omit for 'stream'."));
			Schema.Bool(TEXT("streaming"), TEXT("Load the level in streaming mode."));
			Schema.String(TEXT("streamingMethod"), TEXT("Streaming method: Blueprint or AlwaysLoaded."));
			Schema.String(TEXT("subLevelPath"), TEXT("Sub-level asset path to add as a streaming child."));
			Schema.String(TEXT("targetPath"), TEXT("Alias of destinationPath resolved by the manage_level argument normalizer."));
			Schema.String(TEXT("template"), TEXT("Level template path accepted for compatibility; create_level dispatch does not apply it."));
			Schema.Number(TEXT("timeDilation"), TEXT("Global time dilation multiplier for the level."));
			Schema.Bool(TEXT("useWorldPartition"), TEXT("Create the level with World Partition enabled."));
			Schema.StringEnum(TEXT("action"), { TEXT("load"), TEXT("save"), TEXT("create_level"), TEXT("delete"), TEXT("duplicate_level"), TEXT("stream"), TEXT("unload_level"), TEXT("create_light"), TEXT("build_lighting"), TEXT("set_metadata"), TEXT("set_world_settings"), TEXT("list_levels"), TEXT("get_summary"), TEXT("validate_level"), TEXT("export_level"), TEXT("import_level"), TEXT("add_sublevel") }, TEXT("Action to invoke on manage_level."));
			Schema.Required({ TEXT("action") });
		return Schema.Build();
	}
};


void FMcpGeneratedParentRegistry::RegisterGeneratedCore_InspectCapabilities(FMcpToolRegistry& Registry)

{

	Registry.Register(new FMcpGenTool_Inspect());

	Registry.Register(new FMcpGenTool_ManageLevel());

}
