// GENERATED by scripts/generate-canonical-registry.ts -- do not edit.

#include "MCP/Registry/McpToolDefinition.h"
#include "MCP/Registry/McpToolRegistry.h"

// The canonical parent tools, registered before any request can arrive.
namespace
{
struct FRegisterGeneratedParentTools
{
	FRegisterGeneratedParentTools()
	{
		static FMcpToolDefinition Tools[] = {
			{TEXT("animation_physics"), TEXT("Author animation and physics assets: Animation Blueprints, blend spaces, montages, Control Rig/IK, skeletons, sockets, physics assets, cloth, ragdolls, and vehicles."), TEXT("gameplay")},
			{TEXT("build_environment"), TEXT("Build environments: landscapes, foliage, procedural terrain/biomes, lighting setups, spline roads/rivers/fences, and world decoration."), TEXT("world")},
			{TEXT("control_actor"), TEXT("Spawn actors, set transforms, enable physics, add components, manage tags, and attach actors."), TEXT("core")},
			{TEXT("control_editor"), TEXT("Start/stop PIE, control viewport camera, run console commands, take screenshots, simulate input."), TEXT("core")},
			{TEXT("inspect"), TEXT("Inspect any UObject: read/write properties, list components, export snapshots, and query class info. Actions: inspect_cdo (Blueprint CDO properties + all components without spawning an actor; use blueprintPath, optional detailed/componentName/propertyNames), inspect_class (class metadata), inspect_object (world actor), get_property/set_property, get_components, get_component_details (WORLD actors: actorName+componentName; a blueprintPath is routed to inspect_cdo), list_objects, find_by_class, find_by_tag, runtime_report."), TEXT("core")},
			{TEXT("manage_ai"), TEXT("Build AI systems: AI controllers, Behavior Trees, Blackboards, EQS, perception, State Trees, Smart Objects, NavMesh settings, nav modifiers, links, and pathfinding."), TEXT("gameplay")},
			{TEXT("manage_asset"), TEXT("Create/import/manage assets, material graphs, material instances, procedural textures, render targets, and dependency analysis."), TEXT("core")},
			{TEXT("manage_audio"), TEXT("Play/stop sounds, add audio components, configure mixes, attenuation, spatial audio, and author Sound Cues/MetaSounds."), TEXT("utility")},
			{TEXT("manage_blueprint"), TEXT("Create Blueprints and UMG widgets, add SCS/UI components, set defaults, and manipulate Blueprint graphs, bindings, and widget layouts."), TEXT("core")},
			{TEXT("manage_character"), TEXT("Create Character Blueprints with movement, locomotion, and animation state machines."), TEXT("gameplay")},
			{TEXT("manage_combat"), TEXT("Create weapons with hitscan/projectile firing, configure damage types, hitboxes, reload, and melee combat (combos, parry, block)."), TEXT("gameplay")},
			{TEXT("manage_effect"), TEXT("Niagara particle systems, VFX, debug shapes, and GPU simulations. Create systems, emitters, modules, and control particle effects."), TEXT("gameplay")},
			{TEXT("manage_gas"), TEXT("Create Gameplay Abilities, Effects, Attribute Sets, and Gameplay Cues for ability systems."), TEXT("gameplay")},
			{TEXT("manage_geometry"), TEXT("Create procedural meshes using Geometry Script: booleans, deformers, UVs, collision, and LOD generation."), TEXT("world")},
			{TEXT("manage_interaction"), TEXT("Create interactive objects: doors, switches, chests, levers. Set up destructible meshes and trigger volumes."), TEXT("gameplay")},
			{TEXT("manage_inventory"), TEXT("Create item data assets, inventory components, world pickups, loot tables, and crafting recipes."), TEXT("gameplay")},
			{TEXT("manage_level"), TEXT("Load/save levels, configure streaming, and build lighting."), TEXT("core")},
			{TEXT("manage_level_structure"), TEXT("Structure worlds: levels, sublevels, World Partition, streaming, data layers, HLOD, level instances, trigger/blocking/physics/audio/post-process volumes, and nav bounds."), TEXT("world")},
			{TEXT("manage_networking"), TEXT("Configure multiplayer and player flow: replication, RPCs, authority/relevancy, network prediction, sessions, split-screen, LAN/voice chat, game framework classes, match rules, and input mappings."), TEXT("utility")},
			{TEXT("manage_pcg"), TEXT("Create, edit, execute, and configure PCG graphs: graph assets, input/sampler/filter/spawner nodes, pin connections, node settings, and partition grid size."), TEXT("world")},
			{TEXT("manage_sequence"), TEXT("Edit Level Sequences, cinematic tracks, Movie Render Queue jobs, media playback assets, Take Recorder, and replay controls."), TEXT("utility")},
			{TEXT("manage_tools"), TEXT("Dynamic MCP tool management. List canonical tools, view category counts, and enable/disable tools or categories at runtime."), TEXT("core")},
			{TEXT("system_control"), TEXT("Control the project runtime: profiling, benchmarks, scalability/LOD/Nanite settings, CVars, console commands, Python scripts, UBT, tests, logs, and widgets."), TEXT("core")},
		};
		for (FMcpToolDefinition& Tool : Tools)
		{
			FMcpToolRegistry::Get().Register(&Tool);
		}
	}
};

FRegisterGeneratedParentTools GRegisterGeneratedParentTools;
}
