#if WITH_DEV_AUTOMATION_TESTS

#include "Tests/UnrealAgentStudioKitTestChecks.h"

#include "Misc/AutomationTest.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace UnrealAgent::AutomationTests
{
    bool RunStudioKitDomainSkillContentChecks(
        FAutomationTestBase& Test,
        const FString& TestDirectory)
    {
        bool bPassed = true;
        auto SkillPath = [&TestDirectory](const TCHAR* Name)
        {
            return FPaths::Combine(TestDirectory, TEXT(".opencode/skills"), Name, TEXT("SKILL.md"));
        };

        FString GameplayInputDisciplineSkillText;
        const FString GameplayInputDisciplineSkillPath = SkillPath(TEXT("unreal-gameplay-input-discipline"));
        bPassed &= Test.TestTrue(TEXT("Gameplay and input discipline skill is readable"), FFileHelper::LoadFileToString(GameplayInputDisciplineSkillText, *GameplayInputDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Gameplay and input discipline skill inspects framework ownership"), GameplayInputDisciplineSkillText.Contains(TEXT("GameMode")) && GameplayInputDisciplineSkillText.Contains(TEXT("PlayerController")) && GameplayInputDisciplineSkillText.Contains(TEXT("Pawn/Character")) && GameplayInputDisciplineSkillText.Contains(TEXT("HUD")));
        bPassed &= Test.TestTrue(TEXT("Gameplay and input discipline skill covers Enhanced Input"), GameplayInputDisciplineSkillText.Contains(TEXT("Enhanced Input Actions")) && GameplayInputDisciplineSkillText.Contains(TEXT("Mapping Contexts")) && GameplayInputDisciplineSkillText.Contains(TEXT("triggers")) && GameplayInputDisciplineSkillText.Contains(TEXT("modifiers")));
        bPassed &= Test.TestTrue(TEXT("Gameplay and input discipline skill requires PIE possession and input evidence"), GameplayInputDisciplineSkillText.Contains(TEXT("correct pawn is possessed")) && GameplayInputDisciplineSkillText.Contains(TEXT("expected input events fire")) && GameplayInputDisciplineSkillText.Contains(TEXT("camera and HUD respond")));
        FString AnimationPhysicsDisciplineSkillText;
        const FString AnimationPhysicsDisciplineSkillPath = SkillPath(TEXT("unreal-animation-physics-discipline"));
        bPassed &= Test.TestTrue(TEXT("Animation and physics discipline skill is readable"), FFileHelper::LoadFileToString(AnimationPhysicsDisciplineSkillText, *AnimationPhysicsDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Animation and physics discipline skill inspects animation ownership"), AnimationPhysicsDisciplineSkillText.Contains(TEXT("Skeletal Mesh")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("Skeleton")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("Animation Blueprint")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("AnimGraph/state machine")));
        bPassed &= Test.TestTrue(TEXT("Animation and physics discipline skill covers physics assets and collision"), AnimationPhysicsDisciplineSkillText.Contains(TEXT("Physics Asset bodies/constraints")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("collision profiles/channels")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("Chaos simulation")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("root-motion settings")));
        bPassed &= Test.TestTrue(TEXT("Animation and physics discipline skill requires PIE motion evidence"), AnimationPhysicsDisciplineSkillText.Contains(TEXT("expected animation state or montage plays")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("notifies fire at the expected time")) && AnimationPhysicsDisciplineSkillText.Contains(TEXT("physics bodies remain stable")));
        FString VfxMaterialDisciplineSkillText;
        const FString VfxMaterialDisciplineSkillPath = SkillPath(TEXT("unreal-vfx-material-discipline"));
        bPassed &= Test.TestTrue(TEXT("VFX and material discipline skill is readable"), FFileHelper::LoadFileToString(VfxMaterialDisciplineSkillText, *VfxMaterialDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("VFX and material discipline skill inspects Niagara ownership"), VfxMaterialDisciplineSkillText.Contains(TEXT("Niagara System")) && VfxMaterialDisciplineSkillText.Contains(TEXT("emitter stack")) && VfxMaterialDisciplineSkillText.Contains(TEXT("user parameters")) && VfxMaterialDisciplineSkillText.Contains(TEXT("attached sockets/components")));
        bPassed &= Test.TestTrue(TEXT("VFX and material discipline skill covers materials and bounds"), VfxMaterialDisciplineSkillText.Contains(TEXT("Material or Material Instance")) && VfxMaterialDisciplineSkillText.Contains(TEXT("texture assets")) && VfxMaterialDisciplineSkillText.Contains(TEXT("shader compile state")) && VfxMaterialDisciplineSkillText.Contains(TEXT("bounds/culling")));
        bPassed &= Test.TestTrue(TEXT("VFX and material discipline skill requires PIE visual evidence"), VfxMaterialDisciplineSkillText.Contains(TEXT("effect spawns at the expected location")) && VfxMaterialDisciplineSkillText.Contains(TEXT("material or texture assignment is visible")) && VfxMaterialDisciplineSkillText.Contains(TEXT("capture a viewport screenshot")));
        FString AudioDisciplineSkillText;
        const FString AudioDisciplineSkillPath = SkillPath(TEXT("unreal-audio-discipline"));
        bPassed &= Test.TestTrue(TEXT("Audio discipline skill is readable"), FFileHelper::LoadFileToString(AudioDisciplineSkillText, *AudioDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Audio discipline skill inspects source component and mix ownership"), AudioDisciplineSkillText.Contains(TEXT("Sound Wave")) && AudioDisciplineSkillText.Contains(TEXT("MetaSound Source or Preset")) && AudioDisciplineSkillText.Contains(TEXT("Audio Component")) && AudioDisciplineSkillText.Contains(TEXT("Submix, Sound Class/Mix")));
        bPassed &= Test.TestTrue(TEXT("Audio discipline skill covers spatialization and concurrency"), AudioDisciplineSkillText.Contains(TEXT("attenuation/spatialization")) && AudioDisciplineSkillText.Contains(TEXT("Sound Concurrency")) && AudioDisciplineSkillText.Contains(TEXT("listener/player context")));
        bPassed &= Test.TestTrue(TEXT("Audio discipline skill blocks direct binary asset edits"), AudioDisciplineSkillText.Contains(TEXT("Do not edit or move .uasset or .umap audio assets")));
        bPassed &= Test.TestTrue(TEXT("Audio discipline skill requires PIE playback evidence"), AudioDisciplineSkillText.Contains(TEXT("sound plays from the expected trigger")) && AudioDisciplineSkillText.Contains(TEXT("attenuation and spatialization respond")) && AudioDisciplineSkillText.Contains(TEXT("concurrency behavior matches intent")));
        FString CinematicSequenceDisciplineSkillText;
        const FString CinematicSequenceDisciplineSkillPath = SkillPath(TEXT("unreal-cinematic-sequence-discipline"));
        bPassed &= Test.TestTrue(TEXT("Cinematic sequence discipline skill is readable"), FFileHelper::LoadFileToString(CinematicSequenceDisciplineSkillText, *CinematicSequenceDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Cinematic sequence discipline skill inspects sequence ownership"), CinematicSequenceDisciplineSkillText.Contains(TEXT("Level Sequence Asset")) && CinematicSequenceDisciplineSkillText.Contains(TEXT("Level Sequence Actor")) && CinematicSequenceDisciplineSkillText.Contains(TEXT("spawnable or possessable ownership")));
        bPassed &= Test.TestTrue(TEXT("Cinematic sequence discipline skill covers cameras and render queue"), CinematicSequenceDisciplineSkillText.Contains(TEXT("Camera Cut track")) && CinematicSequenceDisciplineSkillText.Contains(TEXT("CineCameraActors")) && CinematicSequenceDisciplineSkillText.Contains(TEXT("Movie Render Queue")));
        bPassed &= Test.TestTrue(TEXT("Cinematic sequence discipline skill blocks direct binary asset edits"), CinematicSequenceDisciplineSkillText.Contains(TEXT("Do not edit or move .uasset or .umap sequence")));
        bPassed &= Test.TestTrue(TEXT("Cinematic sequence discipline skill requires playback evidence"), CinematicSequenceDisciplineSkillText.Contains(TEXT("timeline playback reaches the expected frames")) && CinematicSequenceDisciplineSkillText.Contains(TEXT("camera cuts take control correctly")) && CinematicSequenceDisciplineSkillText.Contains(TEXT("unresolved bindings")));
        FString NetworkingGasDisciplineSkillText;
        const FString NetworkingGasDisciplineSkillPath = SkillPath(TEXT("unreal-networking-gas-discipline"));
        bPassed &= Test.TestTrue(TEXT("Networking and GAS discipline skill is readable"), FFileHelper::LoadFileToString(NetworkingGasDisciplineSkillText, *NetworkingGasDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Networking and GAS discipline skill inspects authority and replicated state"), NetworkingGasDisciplineSkillText.Contains(TEXT("NetMode")) && NetworkingGasDisciplineSkillText.Contains(TEXT("GameState")) && NetworkingGasDisciplineSkillText.Contains(TEXT("replicated properties")) && NetworkingGasDisciplineSkillText.Contains(TEXT("RPC paths")));
        bPassed &= Test.TestTrue(TEXT("Networking and GAS discipline skill covers GAS ownership"), NetworkingGasDisciplineSkillText.Contains(TEXT("Ability System Component owner/avatar")) && NetworkingGasDisciplineSkillText.Contains(TEXT("Gameplay Effects")) && NetworkingGasDisciplineSkillText.Contains(TEXT("Gameplay Cues")) && NetworkingGasDisciplineSkillText.Contains(TEXT("prediction")));
        bPassed &= Test.TestTrue(TEXT("Networking and GAS discipline skill requires multiplayer PIE evidence"), NetworkingGasDisciplineSkillText.Contains(TEXT("server authority owns the mutation")) && NetworkingGasDisciplineSkillText.Contains(TEXT("clients see replicated state")) && NetworkingGasDisciplineSkillText.Contains(TEXT("single-player evidence is not used to claim multiplayer correctness")));
        FString CharacterSystemsDisciplineSkillText;
        const FString CharacterSystemsDisciplineSkillPath = SkillPath(TEXT("unreal-character-systems-discipline"));
        bPassed &= Test.TestTrue(TEXT("Character systems discipline skill is readable"), FFileHelper::LoadFileToString(CharacterSystemsDisciplineSkillText, *CharacterSystemsDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Character systems discipline skill inspects movement and collision ownership"), CharacterSystemsDisciplineSkillText.Contains(TEXT("Character Movement Component")) && CharacterSystemsDisciplineSkillText.Contains(TEXT("capsule/root component")) && CharacterSystemsDisciplineSkillText.Contains(TEXT("collision channels/profiles")));
        bPassed &= Test.TestTrue(TEXT("Character systems discipline skill covers combat inventory and interaction"), CharacterSystemsDisciplineSkillText.Contains(TEXT("health/damage component")) && CharacterSystemsDisciplineSkillText.Contains(TEXT("inventory/equipment data assets")) && CharacterSystemsDisciplineSkillText.Contains(TEXT("interactable Actor/interface/trace or overlap path")));
        bPassed &= Test.TestTrue(TEXT("Character systems discipline skill requires PIE playable evidence"), CharacterSystemsDisciplineSkillText.Contains(TEXT("correct pawn is possessed")) && CharacterSystemsDisciplineSkillText.Contains(TEXT("damage/health state changes once")) && CharacterSystemsDisciplineSkillText.Contains(TEXT("interaction prompts and activation work")));
        FString UiHudDisciplineSkillText;
        const FString UiHudDisciplineSkillPath = SkillPath(TEXT("unreal-ui-hud-discipline"));
        bPassed &= Test.TestTrue(TEXT("UI and HUD discipline skill is readable"), FFileHelper::LoadFileToString(UiHudDisciplineSkillText, *UiHudDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("UI and HUD discipline skill inspects widget ownership"), UiHudDisciplineSkillText.Contains(TEXT("Widget Blueprint")) && UiHudDisciplineSkillText.Contains(TEXT("UserWidget")) && UiHudDisciplineSkillText.Contains(TEXT("CommonUI")) && UiHudDisciplineSkillText.Contains(TEXT("PlayerController")));
        bPassed &= Test.TestTrue(TEXT("UI and HUD discipline skill covers focus layout and accessibility"), UiHudDisciplineSkillText.Contains(TEXT("input mode")) && UiHudDisciplineSkillText.Contains(TEXT("focus target")) && UiHudDisciplineSkillText.Contains(TEXT("DPI scale")) && UiHudDisciplineSkillText.Contains(TEXT("localization/accessibility risk")));
        bPassed &= Test.TestTrue(TEXT("UI and HUD discipline skill requires PIE viewport evidence"), UiHudDisciplineSkillText.Contains(TEXT("expected widget appears in the viewport")) && UiHudDisciplineSkillText.Contains(TEXT("keyboard/gamepad/mouse/touch focus and navigation work")) && UiHudDisciplineSkillText.Contains(TEXT("HUD updates from gameplay state")));
        FString AiNavigationDisciplineSkillText;
        const FString AiNavigationDisciplineSkillPath = SkillPath(TEXT("unreal-ai-navigation-discipline"));
        bPassed &= Test.TestTrue(TEXT("AI and navigation discipline skill is readable"), FFileHelper::LoadFileToString(AiNavigationDisciplineSkillText, *AiNavigationDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("AI and navigation discipline skill inspects AI brain ownership"), AiNavigationDisciplineSkillText.Contains(TEXT("AIController")) && AiNavigationDisciplineSkillText.Contains(TEXT("Behavior Tree")) && AiNavigationDisciplineSkillText.Contains(TEXT("Blackboard")) && AiNavigationDisciplineSkillText.Contains(TEXT("Perception")));
        bPassed &= Test.TestTrue(TEXT("AI and navigation discipline skill covers navigation and EQS"), AiNavigationDisciplineSkillText.Contains(TEXT("EQS")) && AiNavigationDisciplineSkillText.Contains(TEXT("Nav Mesh Bounds Volume")) && AiNavigationDisciplineSkillText.Contains(TEXT("RecastNavMesh")) && AiNavigationDisciplineSkillText.Contains(TEXT("path following")));
        bPassed &= Test.TestTrue(TEXT("AI and navigation discipline skill requires PIE behavior evidence"), AiNavigationDisciplineSkillText.Contains(TEXT("AIController possesses the expected pawn")) && AiNavigationDisciplineSkillText.Contains(TEXT("Blackboard keys update")) && AiNavigationDisciplineSkillText.Contains(TEXT("Behavior Tree reaches the expected branch or task")) && AiNavigationDisciplineSkillText.Contains(TEXT("path exists and movement follows the NavMesh")));
        FString DataSaveAccessibilityDisciplineSkillText;
        const FString DataSaveAccessibilityDisciplineSkillPath = SkillPath(TEXT("unreal-data-save-accessibility-discipline"));
        bPassed &= Test.TestTrue(TEXT("Data save accessibility discipline skill is readable"), FFileHelper::LoadFileToString(DataSaveAccessibilityDisciplineSkillText, *DataSaveAccessibilityDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Data save accessibility discipline skill inspects persistence and data ownership"), DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("SaveGame Blueprint or C++ class")) && DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("Data Assets/Data Tables/String Tables")) && DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("GameInstance/subsystem owner")));
        bPassed &= Test.TestTrue(TEXT("Data save accessibility discipline skill routes through existing MCP tools"), DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("manage_asset/manage_inventory/manage_blueprint/system_control")) && DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("UI/editor route")) && DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("Do not edit or move .uasset or .umap data assets")));
        bPassed &= Test.TestTrue(TEXT("Data save accessibility discipline skill requires save and accessibility evidence"), DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("SaveGame create/save/load/migration path works")) && DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("localized text resolves")) && DataSaveAccessibilityDisciplineSkillText.Contains(TEXT("accessibility options can be toggled and persisted")));
        FString SourceControlCollaborationDisciplineSkillText;
        const FString SourceControlCollaborationDisciplineSkillPath = SkillPath(TEXT("unreal-source-control-collaboration-discipline"));
        bPassed &= Test.TestTrue(TEXT("Source control collaboration discipline skill is readable"), FFileHelper::LoadFileToString(SourceControlCollaborationDisciplineSkillText, *SourceControlCollaborationDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Source control collaboration discipline skill inspects package state"), SourceControlCollaborationDisciplineSkillText.Contains(TEXT("Content Browser state")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("dirty packages")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("current map/external actor packages")));
        bPassed &= Test.TestTrue(TEXT("Source control collaboration discipline skill routes through existing MCP source control actions"), SourceControlCollaborationDisciplineSkillText.Contains(TEXT("get_source_control_state")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("source_control_checkout/source_control_submit")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("manage_asset")));
        bPassed &= Test.TestTrue(TEXT("Source control collaboration discipline skill separates local git from Unreal packages"), SourceControlCollaborationDisciplineSkillText.Contains(TEXT("Do not use git add/commit/reset/checkout/clean")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("raw filesystem edits")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("Unreal package source-control actions")));
        bPassed &= Test.TestTrue(TEXT("Source control collaboration discipline skill requires team-risk evidence"), SourceControlCollaborationDisciplineSkillText.Contains(TEXT("checked out by another user")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("conflicted")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("out of date")) && SourceControlCollaborationDisciplineSkillText.Contains(TEXT("re-run get_source_control_state")));
        FString PerformanceInsightsDisciplineSkillText;
        const FString PerformanceInsightsDisciplineSkillPath = SkillPath(TEXT("unreal-performance-insights-discipline"));
        bPassed &= Test.TestTrue(TEXT("Performance Insights discipline skill is readable"), FFileHelper::LoadFileToString(PerformanceInsightsDisciplineSkillText, *PerformanceInsightsDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Performance Insights discipline skill requires measured baseline and after evidence"), PerformanceInsightsDisciplineSkillText.Contains(TEXT("before/after measurement")) && PerformanceInsightsDisciplineSkillText.Contains(TEXT("baseline metric")) && PerformanceInsightsDisciplineSkillText.Contains(TEXT("Compare baseline and after values")));
        bPassed &= Test.TestTrue(TEXT("Performance Insights discipline skill routes through real performance and trace actions"), PerformanceInsightsDisciplineSkillText.Contains(TEXT("manage_performance actions")) && PerformanceInsightsDisciplineSkillText.Contains(TEXT("start_profiling/stop_profiling/show_stats/generate_memory_report/set_scalability")) && PerformanceInsightsDisciplineSkillText.Contains(TEXT("capture_insights_trace/get_trace_status/analyze_trace")));
        bPassed &= Test.TestTrue(TEXT("Performance Insights discipline skill separates quality changes from optimization proof"), PerformanceInsightsDisciplineSkillText.Contains(TEXT("setting change is not proof")) && PerformanceInsightsDisciplineSkillText.Contains(TEXT("reduced resolution")) && PerformanceInsightsDisciplineSkillText.Contains(TEXT("visual quality tradeoffs")));
        FString SystemProjectDisciplineSkillText;
        const FString SystemProjectDisciplineSkillPath = SkillPath(TEXT("unreal-system-project-discipline"));
        bPassed &= Test.TestTrue(TEXT("System and project discipline skill is readable"), FFileHelper::LoadFileToString(SystemProjectDisciplineSkillText, *SystemProjectDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("System and project discipline skill inspects project settings and config ownership"), SystemProjectDisciplineSkillText.Contains(TEXT("Project Settings")) && SystemProjectDisciplineSkillText.Contains(TEXT("maps and modes")) && SystemProjectDisciplineSkillText.Contains(TEXT("enabled plugins/modules")) && SystemProjectDisciplineSkillText.Contains(TEXT("config and scalability/device/platform state")));
        bPassed &= Test.TestTrue(TEXT("System and project discipline skill covers console Python and profiling work"), SystemProjectDisciplineSkillText.Contains(TEXT("console variables, console commands, Python/editor utility automation")) && SystemProjectDisciplineSkillText.Contains(TEXT("profiling/stat capture")) && SystemProjectDisciplineSkillText.Contains(TEXT("automation reports pass/fail counts")));
        bPassed &= Test.TestTrue(TEXT("System and project discipline skill requires exact output evidence"), SystemProjectDisciplineSkillText.Contains(TEXT("capture exact command output or log paths")) && SystemProjectDisciplineSkillText.Contains(TEXT("packaging/cook/build commands produce exact successful output")) && SystemProjectDisciplineSkillText.Contains(TEXT("Do not claim packaging or performance from config-only evidence")));
        FString ProjectSetupTemplateDisciplineSkillText;
        const FString ProjectSetupTemplateDisciplineSkillPath = SkillPath(TEXT("unreal-project-setup-template-discipline"));
        bPassed &= Test.TestTrue(TEXT("Project setup template discipline skill is readable"), FFileHelper::LoadFileToString(ProjectSetupTemplateDisciplineSkillText, *ProjectSetupTemplateDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Project setup template discipline skill anchors docs and read-back"), ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("Working with Projects and Templates")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("system_control get_project_settings read-back")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("Maps & Modes")));
        bPassed &= Test.TestTrue(TEXT("Project setup template discipline skill routes through real MCP surfaces"), ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("system_control get_project_settings before set_project_setting")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("manage_level/manage_level_structure route")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("control_editor route")));
        bPassed &= Test.TestTrue(TEXT("Project setup template discipline skill blocks raw content copies"), ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("Do not copy Content directories")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("canonical /Game package paths")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("mark migration blocked")));
        bPassed &= Test.TestTrue(TEXT("Project setup template discipline skill requires startup validation"), ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("run PIE for startup map/GameMode/Pawn/input behavior")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("restart only when approved")) && ProjectSetupTemplateDisciplineSkillText.Contains(TEXT("Do not claim a template")));
        FString DiagnosticsCrashRecoveryDisciplineSkillText;
        const FString DiagnosticsCrashRecoveryDisciplineSkillPath = SkillPath(TEXT("unreal-diagnostics-crash-recovery-discipline"));
        bPassed &= Test.TestTrue(TEXT("Diagnostics crash recovery discipline skill is readable"), FFileHelper::LoadFileToString(DiagnosticsCrashRecoveryDisciplineSkillText, *DiagnosticsCrashRecoveryDisciplineSkillPath));
        bPassed &= Test.TestTrue(TEXT("Diagnostics crash recovery discipline skill captures exact baseline"), DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("exact error text")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("call stack")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("Saved/Crashes")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("Saved/Logs")));
        bPassed &= Test.TestTrue(TEXT("Diagnostics crash recovery discipline skill classifies failure mode"), DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("crash/fatal/assert/ensure")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("Blueprint compiler")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("packaging/cook/build/deploy")));
        bPassed &= Test.TestTrue(TEXT("Diagnostics crash recovery discipline skill routes through real validation tools"), DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("run_tests/validate_assets/run_ubt")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("manage_blueprint compile route")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("control_editor route for PIE")));
        bPassed &= Test.TestTrue(TEXT("Diagnostics crash recovery discipline skill blocks broad cache deletion"), DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("Do not clear caches")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("delete Intermediate/Saved/DerivedDataCache")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("delete assets unless the user explicitly approves")));
        bPassed &= Test.TestTrue(TEXT("Diagnostics crash recovery discipline skill requires original failure retest"), DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("retest the original failure path first")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("original exact error must be absent")) && DiagnosticsCrashRecoveryDisciplineSkillText.Contains(TEXT("state the diagnosis is unverified")));
        return bPassed;
    }
}

#endif
