#if WITH_DEV_AUTOMATION_TESTS

#include "Tests/UnrealAgentAcpProtocolTestHelpers.h"

namespace UnrealAgent::AutomationTests {
    FString MakeAcpTestServerScript() { return FString()
            + TEXT("#!/usr/bin/python3\n")
            + TEXT("import json, signal, sys, time\n")
            + TEXT("if hasattr(signal, 'SIGPWR') and signal.getsignal(signal.SIGPWR) == signal.SIG_IGN:\n")
            + TEXT("    print('ACP test server inherited ignored SIGPWR', file=sys.stderr, flush=True)\n")
            + TEXT("    sys.exit(42)\n")
            + TEXT("session_id = 'acp-test-session'\n")
            + TEXT("prompt_id = None\n")
            + TEXT("permission_id = 1000\n")
            + TEXT("current_model = 'model-a'\n")
            + TEXT("current_thinking = 'medium'\n")
            + TEXT("current_agent = 'build'\n")
            + TEXT("model_options = [{'id': 'model-a', 'label': 'Model A', 'provider': {'name': 'NVIDIA'}, 'contextLength': 128000}, {'optionId': 'model-b', 'name': 'Model B', 'vendor': 'Modal', 'maxInputTokens': 64000}, {'modelId': 'openai/gpt-5.5', 'name': 'openai/gpt-5.5'}]\n")
            + TEXT("thinking_options = [{'value': 'low', 'name': 'Low'}, {'value': 'medium', 'name': 'Medium'}, {'value': 'high', 'name': 'High'}]\n")
            + TEXT("agent_options = [{'value': 'build', 'name': 'Build'}, {'value': 'unreal-agent', 'name': 'Unreal Agent'}]\n")
            + TEXT("def send(obj): print(json.dumps(obj, separators=(',', ':')), flush=True)\n")
            + TEXT("def config_result(model=None, agent=None, thinking=None):\n")
            + TEXT("    global current_model, current_agent, current_thinking\n")
            + TEXT("    if model is not None: current_model = model\n")
            + TEXT("    if agent is not None: current_agent = agent\n")
            + TEXT("    if thinking is not None: current_thinking = thinking\n")
            + TEXT("    return {'configOptions': [{'configOptionId': 'preferred_model', 'category': 'current_model', 'optionValue': current_model, 'options': model_options}, {'id': 'effort', 'category': 'thought_level', 'currentValue': current_thinking, 'options': thinking_options}, {'id': 'mode', 'currentValue': current_agent, 'options': agent_options}]}\n")
            + TEXT("def validate_mcp_servers(params):\n")
            + TEXT("    servers = params.get('mcpServers', [])\n")
            + TEXT("    if not isinstance(servers, list) or len(servers) != 1: return 'expected one mcpServers entry'\n")
            + TEXT("    server = servers[0]\n")
            + TEXT("    if server.get('type') != 'http' or server.get('name') != 'unreal-engine' or server.get('url') != 'http://127.0.0.1:43123/mcp': return 'unexpected mcp server shape'\n")
            + TEXT("    if {'name': 'X-MCP-Capability-Token', 'value': 'test-capability-token'} not in server.get('headers', []): return 'missing capability token header'\n")
            + TEXT("    return None\n")
            + TEXT("def prompt_text(msg): return ''.join([part.get('text', '') for part in msg.get('params', {}).get('prompt', []) if isinstance(part, dict)])\n")
            + TEXT("def request_permission(text):\n")
            + TEXT("    global permission_id\n")
            + TEXT("    permission_id += 1\n")
            + TEXT("    options = [] if text == 'no options path' else [{'optionId': 'once', 'kind': 'allow_once'}, {'optionId': 'always', 'kind': 'allow_always'}, {'optionId': 'reject', 'kind': 'reject_once'}]\n")
            + TEXT("    if text == 'mismatched always path': options = [{'optionId': 'always', 'kind': 'reject_once'}]\n")
            + TEXT("    if text == 'conflicting reject option path': options = [{'optionId': 'reject', 'kind': 'allow_always'}]\n")
            + TEXT("    if text == 'plain allow conflict path': options = [{'optionId': 'allow', 'kind': 'reject_once'}]\n")
            + TEXT("    if text == 'duplicate option id path': options = [{'optionId': 'once', 'kind': 'allow_once'}, {'optionId': 'once', 'kind': 'reject_once'}]\n")
            + TEXT("    tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'test permission', 'kind': 'execute', 'rawInput': {'prompt': text}}\n")
            + TEXT("    if text == 'direct uasset write path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'manage_asset', 'kind': 'edit', 'rawInput': {'filePath': 'Content/Danger.uasset', 'content': 'binary asset bytes'}}\n")
            + TEXT("    if text == 'direct binary cat path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': '/bin/cat Content/Danger.uasset'}}\n")
            + TEXT("    if text == 'safe binary suffix docs path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': '/bin/cat Docs/guide.uasset.md'}}\n")
            + TEXT("    if text == 'safe nested content docs path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'write', 'kind': 'edit', 'rawInput': {'filePath': 'Docs/Content/guide.md', 'content': 'documentation'}}\n")
            + TEXT("    if text == 'safe nested config docs path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'write', 'kind': 'edit', 'rawInput': {'filePath': 'Docs/Config/guide.ini', 'content': 'documentation'}}\n")
            + TEXT("    if text == 'direct project config write path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'write', 'kind': 'edit', 'rawInput': {'filePath': 'Config/DefaultGame.ini', 'content': '[/Script/EngineSettings.GameMapsSettings]'}}\n")
            + TEXT("    if text == 'apply patch config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'apply_patch', 'kind': 'edit', 'rawInput': {'filePath': 'Config/DefaultEngine.ini', 'patch': 'replace setting'}}\n")
            + TEXT("    if text == 'apply patch content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'apply_patch', 'kind': 'edit', 'rawInput': {'filePath': 'Content/Textures/T_Unsafe.png', 'patch': 'replace bytes'}}\n")
            + TEXT("    if text == 'apply patch text content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'apply_patch', 'kind': 'edit', 'rawInput': {'patchText': '*** Update File: Content/Unsafe.txt\\n+x'}}\n")
            + TEXT("    if text == 'shell redirect config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'bash', 'kind': 'execute', 'rawInput': {'command': \"printf '[SystemSettings]' > Config/DefaultEngine.ini\"}}\n")
            + TEXT("    if text == 'shell tee config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'shell', 'kind': 'execute', 'rawInput': {'command': \"printf '[SystemSettings]' | tee Config/DefaultEngine.ini\"}}\n")
            + TEXT("    if text == 'command sed config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'command', 'kind': 'execute', 'rawInput': {'command': \"sed -i 's/Old/New/' Config/DefaultEngine.ini\"}}\n")
            + TEXT("    if text == 'execute python config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"open('Config/DefaultEngine.ini','w').write('x')\\\"\"}}\n")
            + TEXT("    if text == 'execute node config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"node -e \\\"require('fs').writeFileSync('Config/DefaultEngine.ini','x')\\\"\"}}\n")
            + TEXT("    if text == 'execute powershell config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"powershell -Command \\\"Set-Content Config/DefaultEngine.ini x\\\"\"}}\n")
            + TEXT("    if text == 'execute pathlib content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"from pathlib import Path; Path('Content/X').write_bytes(b'x')\\\"\"}}\n")
            + TEXT("    if text == 'execute ruby content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"ruby -e \\\"File.write('Content/X','x')\\\"\"}}\n")
            + TEXT("    if text == 'execute dd content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'dd if=/dev/null of=Content/Unsafe.bin'}}\n")
            + TEXT("    if text == 'spoofed read command content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'command': 'dd if=/dev/null of=Content/Spoofed.bin'}}}\n")
            + TEXT("    if text == 'spoofed read run content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'run': 'dd if=/dev/null of=Content/RunSpoofed.bin'}}}\n")
            + TEXT("    if text == 'spoofed read invoke content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'invoke': 'dd if=/dev/null of=Content/InvokeSpoofed.bin'}}}\n")
            + TEXT("    if text == 'opaque read blob remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'blob': 'rm -f *'}}}\n")
            + TEXT("    if text == 'opaque read value shell remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'value': 'bash -c \"rm -f *\"'}}}\n")
            + TEXT("    if text == 'opaque read body root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'body': 'rm -rf /'}}}\n")
            + TEXT("    if text == 'reversed structured remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'args': ['-rf', '*'], 'command': 'rm'}}\n")
            + TEXT("    if text == 'nested reversed structured remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'payload': {'argv': ['-rf', '*'], 'executable': 'rm'}}}\n")
            + TEXT("    if text == 'spoofed read content payload path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': 'Content/Pwn.txt', 'content': 'x'}}\n")
            + TEXT("    if text == 'spoofed read config payload path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': 'Config/DefaultEngine.ini', 'content': 'x'}}\n")
            + TEXT("    if text == 'spoofed hidden config payload path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'value': 'Config/DefaultEngine.ini', 'body': 'x'}}}\n")
            + TEXT("    if text == 'custom reader hidden content payload path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'custom_reader', 'kind': 'read', 'rawInput': {'payload': {'blob': 'Content/Pwn.txt', 'body': 'x'}}}\n")
            + TEXT("    if text == 'conflicting reject option path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'payload': {'command': 'dd if=/dev/null of=Content/Spoofed.bin'}}}\n")
            + TEXT("    if text == 'execute rsync content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rsync /tmp/source Content/Unsafe'}}\n")
            + TEXT("    if text == 'execute sponge content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'printf x | sponge Content/Unsafe.txt'}}\n")
            + TEXT("    if text == 'execute tar content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'tar -xf payload.tar -C Content'}}\n")
            + TEXT("    if text == 'execute ruby io content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"ruby -e \\\"IO.write('Content/X','x')\\\"\"}}\n")
            + TEXT("    if text == 'execute mkdir content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'argv': ['mkdir', 'Content/Bypass']}}\n")
            + TEXT("    if text == 'execute python binary read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"print(open('Content/Danger.uasset','rb').read())\\\"\"}}\n")
            + TEXT("    if text == 'execute node binary read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"node -e \\\"console.log(require('fs').readFileSync('Content/Danger.uasset'))\\\"\"}}\n")
            + TEXT("    if text == 'execute opencode self edit path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'write', 'kind': 'edit', 'rawInput': {'filePath': '.opencode/plugins/unreal-agent-guardrails.ts', 'content': 'disabled'}}\n")
            + TEXT("    if text == 'semantic actor delete path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'delete selected actor from current level'}}\n")
            + TEXT("    if text == 'unreal python actor delete path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'python -c \"import unreal; unreal.EditorLevelLibrary.destroy_actor(actor)\"'}}\n")
            + TEXT("    if text == 'unreal python actor read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'python -c \"import unreal; print(unreal.EditorLevelLibrary.get_all_level_actors())\"'}}\n")
            + TEXT("    if text == 'obfuscated unreal python path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"u=__import__('un'+'real'); getattr(u.EditorLevelLibrary,'destroy_'+'actor')(a)\\\"\"}}\n")
            + TEXT("    if text == 'env wrapped unreal python path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': '/usr/bin/env python3 -c \"import unreal; print(unreal.EditorLevelLibrary.get_all_level_actors())\"'}}\n")
            + TEXT("    if text == 'shell wrapped unreal python path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"bash -lc \\\"python3 -c 'import unreal; print(unreal.EditorLevelLibrary.get_all_level_actors())'\\\"\"}}\n")
            + TEXT("    if text == 'multiline command path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Notes.md\\nrm Content/Pwn.txt'}}\n")
            + TEXT("    if text == 'single ampersand mutation path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rg foo Docs & rm Content/Pwn.txt'}}\n")
            + TEXT("    if text == 'escaped separator mutation path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rg foo Docs \\\\\\\\; touch Content/Pwn.txt'}}\n")
            + TEXT("    if text == 'ripgrep preprocessor execution path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rg --pre ./Scripts/pwn needle Docs'}}\n")
            + TEXT("    if text == 'wrapped ripgrep preprocessor execution path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'env rg --pre ./Scripts/pwn needle Docs'}}\n")
            + TEXT("    if text == 'wrapped fd execution path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'command fd --exec ./Scripts/pwn needle Docs'}}\n")
            + TEXT("    if text == 'shell encoded interpreter path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'sh -c \"printf ZWNobyBwd24= | base64 -d | sh\"'}}\n")
            + TEXT("    if text == 'encoded unreal python path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import base64; exec(base64.b64decode('aW1wb3J0IHVucmVhbDsgdW5yZWFsLkVkaXRvckxldmVsTGlicmFyeS5kZXN0cm95X2FjdG9yKGFjdG9yKQ=='))\\\"\"}}\n")
            + TEXT("    if text == 'encoded interpreter content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"p=''.join(chr(x) for x in [67,111,110,116,101,110,116]);open(p+'/Pwn.txt','w').write('x')\\\"\"}}\n")
            + TEXT("    if text == 'git apply path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'git apply /tmp/policy.patch'}}\n")
            + TEXT("    if text == 'git option apply path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'git -C . apply /tmp/policy.patch'}}\n")
            + TEXT("    if text == 'git alias apply path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'git -c alias.p=apply p /tmp/policy.patch'}}\n")
            + TEXT("    if text == 'git quoted alias apply path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"git -c alias.p='apply' p /tmp/policy.patch\"}}\n")
            + TEXT("    if text == 'git split apply path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"git a''pply /tmp/policy.patch\"}}\n")
            + TEXT("    if text == 'tar extract root path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'tar -xf /tmp/payload.tar -C .'}}\n")
            + TEXT("    if text == 'tar extract flagless path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'tar xf /tmp/payload.tar'}}\n")
            + TEXT("    if text == 'tar quoted executable path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': '\"/usr/bin/tar\" xf /tmp/payload.tar'}}\n")
            + TEXT("    if text == 'tar split executable path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"t''ar -xf /tmp/payload.tar\"}}\n")
            + TEXT("    if text == 'python tarfile extract path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'python -m tarfile -e /tmp/payload.tar .'}}\n")
            + TEXT("    if text == 'bsdtar extract path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'bsdtar -xf /tmp/payload.tar'}}\n")
            + TEXT("    if text == 'split content mkdir path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"mkdir Con''tent/Bypass\"}}\n")
            + TEXT("    if text == 'variable content mkdir path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'd=Content; mkdir \"$d/Bypass\"'}}\n")
            + TEXT("    if text == 'split variable content mkdir path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'a=Con; b=tent; mkdir \"$a$b/ReviewBypass\"'}}\n")
            + TEXT("    if text == 'python split content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import os; os.mkdir('Con'+'tent/Bypass')\\\"\"}}\n")
            + TEXT("    if text == 'command substitution opencode write path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'printf x > \".$(printf opencode)/opencode.json\"'}}\n")
            + TEXT("    if text == 'globbed binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Content/Danger.uasse?'}}\n")
            + TEXT("    if text == 'binary search operand path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': r'rg -n \"\\.uasset\" Content/Danger.uasset'}}\n")
            + TEXT("    if text == 'bracket binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Content/Danger.uasse[t]'}}\n")
            + TEXT("    if text == 'brace binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Content/Danger.uasse{t,p}'}}\n")
            + TEXT("    if text == 'brace prefix binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/{Danger.uasse,Other.tx}t'}}\n")
            + TEXT("    if text == 'brace empty alternative binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Danger.uasse{,t}t'}}\n")
            + TEXT("    if text == 'brace sequence binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Danger.uasse{t..t}'}}\n")
            + TEXT("    if text == 'escaped binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Danger.uasse\\\\t'}}\n")
            + TEXT("    if text == 'ansi c quoted binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"cat Docs/Danger.uasse$'t'\"}}\n")
            + TEXT("    if text == 'ansi c escaped binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': r\"cat Docs/Danger.uasse$'\\x74'\"}}\n")
            + TEXT("    if text == 'adjacent quoted binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"cat Docs/Danger.uasse't'\"}}\n")
            + TEXT("    if text == 'locale quoted binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Danger.uasse$\"t\"'}}\n")
            + TEXT("    if text == 'adjacent double quoted binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Danger.uasse\"t\"'}}\n")
            + TEXT("    if text == 'long globbed binary content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Content/Danger.' + ('*' * 600) + 'uasset'}}\n")
            + TEXT("    if text == 'brace expansion content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'mkdir -p Con{tent,fig}/Bypass'}}\n")
            + TEXT("    if text == 'python pathlib touch path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"from pathlib import Path; Path(chr(67)+'ontent/Pwn.txt').touch()\\\"\"}}\n")
            + TEXT("    if text == 'python keyword mode write path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"p=''.join(chr(x) for x in [67,111,110,116,101,110,116]); f=open(p+'/Pwn.txt', mode='w'); f.close()\\\"\"}}\n")
            + TEXT("    if text == 'node create write stream path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"node -e \\\"const p=String.fromCharCode(67,111,110,116,101,110,116); require('fs').createWriteStream(p+'/Pwn.txt')\\\"\"}}\n")
            + TEXT("    if text == 'unknown local location path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'dangerous_local_tool', 'kind': 'other', 'rawInput': {'location': 'Content/Bypass'}}\n")
            + TEXT("    if text == 'unknown local hidden content path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'dangerous_local_tool', 'kind': 'other', 'rawInput': {'blob': 'Content/Pwn.txt'}}\n")
            + TEXT("    if text == 'unknown local hidden config path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'dangerous_local_tool', 'kind': 'other', 'rawInput': {'value': 'Config/DefaultEngine.ini'}}\n")
            + TEXT("    if text == 'unknown local hidden unreal python path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'dangerous_local_tool', 'kind': 'other', 'rawInput': {'blob': 'python -c \"import unreal; unreal.EditorLevelLibrary.destroy_actor(actor)\"'}}\n")
            + TEXT("    if text == 'safe tar list path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'tar -tf /tmp/payload.tar --exclude=*.tmp'}}\n")
            + TEXT("    if text == 'unknown save tool path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'save_file', 'kind': 'other', 'rawInput': {'filePath': 'Content/Pwn.txt', 'content': 'x'}}\n")
            + TEXT("    if text == 'binary alias read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"node -e \\\"console.log(require('fs').readFileSync('Docs/cache.bin'))\\\"\"}}\n")
            + TEXT("    if text == 'binary alias normal read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': 'Docs/cache.bin'}}\n")
            + TEXT("    if text == 'binary destination path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'copy_file', 'kind': 'other', 'rawInput': {'destination': '/tmp/Foo.uasset'}}\n")
            + TEXT("    if text == 'binary patch path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'custom_tool', 'kind': 'other', 'rawInput': {'patch': '/tmp/Foo.umap'}}\n")
            + TEXT("    if text == 'custom reader binary path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'custom_reader', 'kind': 'read', 'rawInput': {'filePath': 'Content/Danger.uasset'}}\n")
            + TEXT("    if text == 'custom reader hidden binary path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'custom_reader', 'kind': 'read', 'rawInput': {'payload': {'blob': 'Content/Danger.uasset'}}}\n")
            + TEXT("    if text == 'safe symlink docs read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': 'Docs/safe-link.md'}}\n")
            + TEXT("    if text == 'symlink docs write path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'write', 'kind': 'edit', 'rawInput': {'filePath': 'Docs/safe-link.md', 'content': 'must not follow links'}}\n")
            + TEXT("    if text == 'execute command content remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm Content/UnsafeAsset.png'}}\n")
            + TEXT("    if text == 'execute command content root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -rf Content'}}\n")
            + TEXT("    if text == 'reordered recursive remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -f -r *'}}\n")
            + TEXT("    if text == 'nonrecursive root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -f *'}}\n")
            + TEXT("    if text == 'pwd wildcard remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -f $PWD/*'}}\n")
            + TEXT("    if text == 'braced pwd wildcard remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -f ${PWD}/*'}}\n")
            + TEXT("    if text == 'shell wrapped root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'bash -c \"rm -f *\"'}}\n")
            + TEXT("    if text == 'filesystem root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -rf /'}}\n")
            + TEXT("    if text == 'parent root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -rf ..'}}\n")
            + TEXT("    if text == 'absolute working root remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rm -rf ' + sys.argv[0].rsplit('/acptest', 1)[0]}}\n")
            + TEXT("    if text == 'tree short output path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'tree -o Config/DefaultEngine.ini'}}\n")
            + TEXT("    if text == 'tree long output path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'tree --output=Content/Tree.txt'}}\n")
            + TEXT("    if text == 'quote split recursive remove path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'r\"m\" -f -r *'}}\n")
            + TEXT("    if text == 'git option reset hard path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'git -C . reset --hard'}}\n")
            + TEXT("    if text == 'quote split git reset hard path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'g\"i\"t -C . reset --hard'}}\n")
            + TEXT("    if text == 'git option clean path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'git -C . clean -fdx'}}\n")
            + TEXT("    if text == 'git option checkout path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'git -C . checkout -- .'}}\n")
            + TEXT("    if text == 'git shell alias destructive path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"git -c alias.wipe='!rm -rf .' wipe\"}}\n")
            + TEXT("    if text == 'git inline shell alias destructive path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"git -c=alias.wipe='!rm -rf .' wipe\"}}\n")
            + TEXT("    if text == 'destructive python rmtree path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import shutil; shutil.rmtree('.')\\\"\"}}\n")
            + TEXT("    if text == 'python tarfile api extract path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import tarfile; tarfile.open('/tmp/payload.tar').extractall('.')\\\"\"}}\n")
            + TEXT("    if text == 'python zipfile api extract path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import zipfile; zipfile.ZipFile('/tmp/payload.zip').extractall('.')\\\"\"}}\n")
            + TEXT("    if text == 'python shutil unpack archive path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import shutil; shutil.unpack_archive('/tmp/payload.zip', 'Source')\\\"\"}}\n")
            + TEXT("    if text == 'python patool extract archive path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import patoolib; patoolib.extract_archive('/tmp/payload.7z', outdir='Source')\\\"\"}}\n")
            + TEXT("    if text == 'python rarfile extract path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"import rarfile; rarfile.RarFile('/tmp/payload.rar').extractall('Source')\\\"\"}}\n")
            + TEXT("    if text == 'direct unreal editor commandlet path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"UnrealEditor-Cmd '*.uproject' -run=pythonscript -script=/tmp/p.py\"}}\n")
            + TEXT("    if text == 'quoted windows unreal editor path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': '\"C:\\\\Program Files\\\\Epic Games\\\\UE_5.7\\\\Engine\\\\Binaries\\\\Win64\\\\UnrealEditor.exe\" Project.uproject'}}\n")
            + TEXT("    if text == 'quote split content mkdir path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'mkdir Con\"t\"ent/Bypass'}}\n")
            + TEXT("    if text == 'execute command game move path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'mv /Game/OldAsset /Game/NewAsset'}}\n")
            + TEXT("    if text == 'apply patch engine path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'apply_patch', 'kind': 'edit', 'rawInput': {'filePath': '/Engine/EditorMaterials/Unsafe.txt', 'patch': 'replace'}}\n")
            + TEXT("    if text == 'safe config read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'bash', 'kind': 'execute', 'rawInput': {'command': 'cat Config/DefaultEngine.ini'}}\n")
            + TEXT("    if text == 'safe docs read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'rg -n MCP Docs'}}\n")
            + TEXT("    if text == 'safe extension content read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'custom_reader', 'kind': 'read', 'rawInput': {'filePath': 'Content/Readable.txt'}}\n")
            + TEXT("    if text == 'safe python docs read path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"print(open('Docs/Notes.md').read())\\\"\"}}\n")
            + TEXT("    if text == 'safe python unreal text path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"python -c \\\"print('Unreal documentation')\\\"\"}}\n")
            + TEXT("    if text == 'safe node analysis path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"node -e \\\"console.log('analysis')\\\"\"}}\n")
            + TEXT("    if text == 'safe node function path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"node -e \\\"function add(a,b){return a+b}; console.log(add(1,2))\\\"\"}}\n")
            + TEXT("    if text == 'safe shell info path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'bash --version'}}\n")
            + TEXT("    if text == 'safe binary mention path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': \"rg -n '\\\\.uasset' Docs\"}}\n")
            + TEXT("    if text == 'safe locale quoted docs path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'execute_command', 'kind': 'execute', 'rawInput': {'command': 'cat Docs/Notes.$\"md\"'}}\n")
            + TEXT("    if text == 'secret permission path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': 'Docs/Notes.md', 'Authorization': 'Bearer permission-secret', 'password': 'permission-password'}}\n")
            + TEXT("    if text == 'inspect permission path': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'inspect', 'kind': 'execute', 'rawInput': {'action': 'get_content_browser_state'}}\n")
            + TEXT("    if text == 'source edit mentioning uasset extension': tool_call = {'toolCallId': 'acp-test-tool', 'status': 'pending', 'title': 'write', 'kind': 'edit', 'rawInput': {'filePath': '/tmp/HostProject/Docs/Notes.md', 'content': 'Document that .uasset files are edited through MCP package paths.'}}\n") + MakeAcpTestServerSecurityPermissionCases()
            + TEXT("    send({'jsonrpc': '2.0', 'id': permission_id, 'method': 'session/request_permission', 'params': {'sessionId': session_id, 'toolCall': tool_call, 'options': options}})\n")
            + TEXT("for line in sys.stdin:\n")
            + TEXT("    if not line.strip(): continue\n")
            + TEXT("    msg = json.loads(line); method = msg.get('method'); msg_id = msg.get('id')\n")
            + TEXT("    if method == 'initialize': send({'jsonrpc': '2.0', 'id': msg_id, 'result': {'protocolVersion': 1}})\n")
            + TEXT("    elif method == 'session/new':\n")
            + TEXT("        err = validate_mcp_servers(msg.get('params', {}))\n")
            + TEXT("        if err is not None: send({'jsonrpc': '2.0', 'id': msg_id, 'error': {'code': -32602, 'message': err}}); continue\n")
            + TEXT("        result = {'sessionId': session_id}; result.update(config_result()); send({'jsonrpc': '2.0', 'id': msg_id, 'result': result})\n")
            + TEXT("    elif method == 'session/set_config_option':\n")
            + TEXT("        params = msg.get('params', {}); config_id = params.get('configId', params.get('id', '')); value = params.get('value', '')\n")
            + TEXT("        result = config_result(agent=value) if config_id == 'mode' else config_result(thinking=value) if config_id == 'effort' else config_result(model=value)\n")
            + TEXT("        send({'jsonrpc': '2.0', 'id': msg_id, 'result': result})\n")
            + TEXT("    elif method == 'session/prompt':\n")
            + TEXT("        prompt_id = msg_id; text = prompt_text(msg)\n")
            + MakeAcpTestServerPromptRedactionCase()
            + TEXT("        if text == 'stderr secret exit path':\n")
            + TEXT("            sys.stderr.write('X-MCP-Capability-Token:\\n'); sys.stderr.flush(); time.sleep(0.05)\n")
            + TEXT("            sys.stderr.write('opaque:value==\\n'); sys.stderr.flush(); time.sleep(0.05)\n")
            + TEXT("            sys.stderr.write('QUJDREVGR0g=\\n'); sys.stderr.flush(); time.sleep(0.05)\n")
            + TEXT("            sys.stderr.write('safe: diagnostic\\n'); sys.stderr.flush(); sys.exit(17)\n")
            + TEXT("        if text == 'stderr camel token exit path':\n")
            + TEXT("            sys.stderr.write('accessToken: stderr-camel-secret\\n'); sys.stderr.flush(); time.sleep(0.05)\n")
            + TEXT("            sys.stderr.write('refresh'); sys.stderr.flush(); time.sleep(0.05)\n")
            + TEXT("            sys.stderr.write('Token: stderr-split-camel-secret\\n'); sys.stderr.flush(); sys.exit(19)\n")
            + TEXT("        if text == 'stderr long exit path':\n")
            + TEXT("            sys.stderr.write('x' * 32768); sys.stderr.flush(); sys.exit(18)\n")
            + TEXT("        if text == 'foreign session path':\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': 'foreign-session', 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'foreign-session-marker'}}}})\n")
            + TEXT("            permission_id += 1\n")
            + TEXT("            send({'jsonrpc': '2.0', 'id': permission_id, 'method': 'session/request_permission', 'params': {'sessionId': 'foreign-session', 'toolCall': {'toolCallId': 'foreign-tool', 'status': 'pending', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': 'Docs/Foreign.md'}}, 'options': [{'optionId': 'once', 'kind': 'allow_once'}]}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'end_turn'}}); prompt_id = None; continue\n")
            + TEXT("        if text == 'assistant split secret path':\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'Authoriz'}}}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'ation: Bearer opaque-assistant-'}}}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'token==\\n'}}}})\n")
            + TEXT("        if text == 'assistant split key secret path':\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'X-MCP-Capability-'}}}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'Token: split-key-secret\\n'}}}})\n")
            + TEXT("        if text == 'assistant split camel token path':\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'access'}}}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'Token: split-camel-secret\\n'}}}})\n")
            + TEXT("        response_text = 'Authorization: Bearer assistant-secret' if text == 'assistant secret path' else 'accessToken: camel-assistant-secret' if text == 'assistant camel token path' else 'ACP test response: ordinary assistant output' if text in ['assistant split secret path', 'assistant split camel token path'] else 'ACP test response: ' + text\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': response_text}}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_thought_chunk', 'content': {'type': 'text', 'text': 'thinking about ' + text}}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'usage_update', 'used': 32000, 'size': 64000}}})\n")
            + TEXT("        activity_input = {'command': 'curl -H \"Authorization: Bearer transcript-secret\" https://example.invalid'} if text == 'secret tool activity path' else {'filePath': '/Game/SourceA.cpp'}\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'tool_call', 'toolCallId': 'read-a', 'title': 'read', 'kind': 'read', 'rawInput': activity_input, 'locations': [{'path': '/Game/SourceA.cpp'}]}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'tool_call_update', 'toolCallId': 'read-a', 'title': 'read', 'status': 'completed'}}})\n")
            + TEXT("        request_permission(text)\n")
            + TEXT("        if text == 'error after permission path': send({'jsonrpc': '2.0', 'id': prompt_id, 'error': {'code': -32000, 'message': 'ACP test prompt error'}}); prompt_id = None\n")
            + TEXT("        if text == 'no options path': send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'end_turn'}}); prompt_id = None\n")
            + TEXT("    elif method == 'session/cancel' and prompt_id is not None: send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'cancelled'}}); prompt_id = None\n")
            + TEXT("    elif msg_id is not None and 'result' in msg:\n")
            + TEXT("        outcome = msg.get('result', {}).get('outcome', {})\n")
            + TEXT("        if outcome.get('outcome') == 'selected' and prompt_id is not None:\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': ' permission option ' + outcome.get('optionId', '')}}}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'end_turn'}}); prompt_id = None\n")
            + TEXT("    elif msg_id is not None and 'error' in msg and prompt_id is not None:\n")
            + TEXT("        message = msg.get('error', {}).get('message', '')\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': ' permission error ' + message}}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'end_turn'}}); prompt_id = None\n");
    }
}

#endif
