/**
 * Tag and search records: add_tag, remove_tag, find_by_tag/find_actors_by_tag,
 * find_by_name/find_actors_by_name, find_by_class/find_actors_by_class.
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildCoreRecord } from '../core/builder.js';
import { DOMAIN, P } from './properties.js';

const FAMILY_TAGS = 'tags';
const FAMILY_FIND = 'find';

const FIND_OUTPUT = { actors: P.actors, count: P.count };

export const SEARCH_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'add_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    topics: ['tag actor', 'actor tag', 'label actor'],
    summary: 'Add a gameplay tag to an actor, or to many actors at once with actorNames.',
    whenToUse: [
      'An actor must be tagged for later lookup or grouping.',
      'Many deliberate compositions must be marked mcp.placement.ok for audit_placement in one call.',
    ],
    whenNotToUse: ['The tag is already present (idempotent re-add is a no-op).'],
    inputProps: {
      actorName: P.actorName,
      actorNames: { type: 'array', items: { type: 'string' }, description: 'Several actors to tag in one call, in place of actorName; names not found are listed back.' },
      tag: P.tag,
    },
    required: ['tag'],
    requiredOneOf: ['actorName', 'actorNames'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    exampleInput: { action: 'add_tag', actorName: 'Cube1', tag: 'Pickup' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'remove_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    // Search folds "remove" to "delete", so without these "remove tag from
    // actor" out-scored this on control_actor.delete's summary words.
    topics: ['remove tag from actor', 'untag actor', 'delete tag'],
    summary: 'Remove a gameplay tag from an actor.',
    whenToUse: ['A tag must be removed from an actor.'],
    whenNotToUse: ['The tag is not present (no-op).'],
    inputProps: { actorName: P.actorName, tag: P.tag },
    required: ['actorName', 'tag'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    exampleInput: { action: 'remove_tag', actorName: 'Cube1', tag: 'Pickup' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_by_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    summary: 'Find all actors in the level matching a gameplay tag.',
    whenToUse: ['Actors sharing a tag must be located.'],
    whenNotToUse: ['A specific actor name is known (use find_by_name).'],
    inputProps: { tag: P.tag },
    required: [],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    exampleInput: { action: 'find_by_tag', tag: 'Pickup' },
    exampleOutput: { success: true, message: 'Found 1 actors by tag', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_actors_by_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    summary: 'Alias of find_by_tag. The bridge dispatches both names to the same handler.',
    whenToUse: ['Preferred when callers use the explicit find_actors_by_tag verb.'],
    whenNotToUse: ['Use find_by_tag to avoid alias normalization.'],
    inputProps: { tag: P.tag },
    required: [],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    exampleInput: { action: 'find_actors_by_tag', tag: 'Pickup' },
    exampleOutput: { success: true, message: 'Found 1 actors by tag', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_by_name',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['find actor', 'lookup actor by name', 'search actor', 'get actor by name'],
    summary: 'Find actors in the level whose name matches a query string.',
    whenToUse: ['One or more actors must be located by name or substring.'],
    whenNotToUse: ['Actors should be located by tag (use find_by_tag).'],
    inputProps: { name: P.name },
    required: ['name'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    exampleInput: { action: 'find_by_name', name: 'Cube' },
    exampleOutput: { success: true, message: 'Found 1 actors: Cube1', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_actors_by_name',
    domain: DOMAIN,
    family: FAMILY_FIND,
    summary: 'Alias of find_by_name. The bridge dispatches both names to the same handler.',
    whenToUse: ['Preferred when callers use the explicit find_actors_by_name verb.'],
    whenNotToUse: ['Use find_by_name to avoid alias normalization.'],
    inputProps: { name: P.name },
    required: ['name'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    exampleInput: { action: 'find_actors_by_name', name: 'Cube' },
    exampleOutput: { success: true, message: 'Found 1 actors: Cube1', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_by_class',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['actors of class', 'find actors by type', 'all actors of type'],
    summary: 'Find all actors in the level matching a Unreal class name or path.',
    whenToUse: ['All instances of a class must be located.'],
    whenNotToUse: ['A tag-based lookup is more appropriate (use find_by_tag).'],
    inputProps: { className: P.className, class: { type: 'string', description: 'Unreal class name or path (alias of className).' }, classPath: P.classPath },
    required: [],
    requiredOneOf: ['className', 'class', 'classPath'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    exampleInput: { action: 'find_by_class', className: 'PointLight' },
    exampleOutput: { success: true, message: 'Found 2 actors by class', actors: [{ label: 'Light1', name: 'Light1' }], count: 2 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_actors_by_class',
    domain: DOMAIN,
    family: FAMILY_FIND,
    summary: 'Alias of find_by_class. The bridge dispatches both names to the same handler.',
    whenToUse: ['Preferred when callers use the explicit find_actors_by_class verb.'],
    whenNotToUse: ['Use find_by_class to avoid alias normalization.'],
    inputProps: { className: P.className, class: { type: 'string', description: 'Unreal class name or path (alias of className).' }, classPath: P.classPath },
    required: [],
    requiredOneOf: ['className', 'class', 'classPath'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    exampleInput: { action: 'find_actors_by_class', className: 'PointLight' },
    exampleOutput: { success: true, message: 'Found 2 actors by class', actors: [{ label: 'Light1', name: 'Light1' }], count: 2 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'audit_placement',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['placement problems', 'overlapping actors', 'sunk actors', 'floating actors', 'tilted actors', 'upside down actors', 'level audit', 'intersecting geometry', 'z-fighting', 'flickering surfaces', 'coplanar faces', 'texture flicker'],
    summary: 'Sweep every actor in the level and report the ones that interpenetrate another actor, sit sunk below the surface under them, float above it, lean off vertical, or have a face in the same plane as another surface (z-fighting flicker).',
    whenToUse: [
      'A level was assembled programmatically and needs checking before anyone looks at it.',
      'Actors appear to clip through each other, stand in the ground, or lie on their side.',
      'A placement pass should be verified without flying the viewport around to eyeball it.',
      'Surfaces flicker, or another material shows through in ragged patches (z-fighting): the coplanar face pairs responsible are listed under coplanarFaces, with the direction to push each one; control_actor fix_coplanar fixes them all in one call.',
    ],
    whenNotToUse: [
      'One actor was just moved; spawn and set_transform already return placementWarning for it.',
      'A finding is a deliberate composition (a keep bedding its towers into its platform, an island meant to hang in the air, a signpost leaning by design): tag that actor mcp.placement.ok with control_actor.add_tag and it drops out of the sweep entirely -- as tilt subject, and as both subject and target for overlap -- rather than being re-reported every time. Coplanar faces are still reported for tagged actors, because they flicker whatever the intent.',
    ],
    inputProps: {
      nameFilter: { type: 'string', description: 'Only examine actors whose label contains this text. Omit to sweep the whole level.' },
      limit: { type: 'number', description: 'Maximum problem entries to return (1-200, default 25). Entries come worst-first, so a small limit still shows the placements that matter; flagged is always the true total.' },
      minSeverity: { type: 'number', description: 'Drop findings whose severity (worst penetration, ground error, tilt displacement, or the side of the largest z-fighting patch, in world units) is below this. Use it to skip cosmetic grazes on a large level.' },
      kinds: { type: 'array', items: { type: 'string', enum: ['sunk', 'floating', 'overlapping', 'unsupported', 'tilted', 'coplanar'] }, description: 'Report only these problem kinds, e.g. ["coplanar"] to list z-fighting alone in a platformer full of platforms that float on purpose. An actor whose worst problem is another kind still counts for coplanar when it has coplanarFaces. Omit for every kind.' },
      maxTilt: { type: 'number', description: 'Degrees off vertical an actor may lean before it is reported as tilted (1-90, default 30). Lean is the angle between the up vector of the actor and world up, so yaw never counts and a fully inverted actor reads 180. Raise it for a level whose props are deliberately strewn about; lower it to catch subtler leans.' },
    },
    required: [],
    outputProps: {
      examined: { type: 'number', description: 'Actors inspected.' },
      flagged: { type: 'number', description: 'Actors with a placement problem, before the limit.' },
      returned: { type: 'number', description: 'Entries included in problems[].' },
      byKind: {
        type: 'object',
        description: 'Count of flagged actors per problem kind: sunk, floating, overlapping, unsupported, tilted, coplanar.',
        additionalProperties: true,
        'x-unreal-reflection-boundary': true,
      },
      problems: {
        type: 'array',
        description: 'Findings worst-first: actorName, kind, severity in world units, the issue in words, suggestedZ when a resting height can be computed, and coplanarFaces when faces z-fight: one entry per pair with direction (the axis both faces point along, e.g. -Y), component, otherActor, otherComponent, gap and overlapU x overlapV. Fix a pair by moving the face about 2 units along direction (this piece shows) or against it (the other shows, right for a piece sunk into it, such as a ramp in the floor), by moving or scaling the actor. Call get_actor_transform on one for its full detail.',
        items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true },
        'x-unreal-reflection-boundary': true,
      },
      truncationNote: { type: 'string', description: 'Present when the limit cut the list short; says how to reach the rest.' },
    },
    outputRequired: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'medium',
    exampleInput: { action: 'audit_placement', nameFilter: 'HubNPC_' },
    exampleOutput: { success: true, message: 'Examined 12 actors, 3 with placement problems', examined: 12, flagged: 3, returned: 3, byKind: {}, problems: [] },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'fix_coplanar',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['fix z-fighting', 'fix flickering', 'coplanar faces', 'texture flicker', 'overlapping faces'],
    summary: 'Fix z-fighting in one call: every actor with a face in the same plane as another surface moves a unit, so one surface is clearly in front, repeating until nothing is left to move. A piece lying wholly inside the other face (a door on a wall) comes forward; one only partly inside (a ramp sunk into the floor) goes back so the other shows.',
    whenToUse: [
      'audit_placement reported coplanar faces, or surfaces flicker between two materials.',
      'A level was built from boxes placed flush against each other and should be cleaned up before anyone looks at it.',
    ],
    whenNotToUse: [
      'The two faces belong to parts of one Blueprint actor: they are listed under skipped; move one part with manage_blueprint edit_scs.',
      'Only some actors may move: limit the call with nameFilter. A tag of mcp.placement.ok does not exempt an actor, because no two faces flicker on purpose.',
    ],
    inputProps: {
      nameFilter: { type: 'string', description: 'Only fix pairs where either actor label contains this text. Omit for the whole level.' },
      distance: { type: 'number', description: 'How far each face moves, in world units (0.1-20, default 1): far enough for the depth buffer, too little to see.' },
      dryRun: { type: 'boolean', description: 'List the moves without making them (default false).' },
    },
    required: [],
    outputProps: {
      pairsFound: { type: 'number', description: 'Coplanar face pairs found before fixing.' },
      actorsMoved: { type: 'number', description: 'Actors moved (0 under dryRun).' },
      remainingPairs: { type: 'number', description: 'Coplanar pairs still found afterwards; run audit_placement with kinds ["coplanar"] to see them.' },
      passes: { type: 'number', description: 'Passes made: a move can line an actor up with a neighbour that moved the same way, so the fix repeats (at most four passes; one under dryRun).' },
      dryRun: { type: 'boolean', description: 'Whether nothing was changed.' },
      moved: { type: 'array', description: 'One entry per actor: actorName, offset {x, y, z} it moved by, resized when both of its faces on one axis moved (for example "grew 2.0 units along X"), and pairs, each face with the other actor and whether it was brought forward or pulled back.', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, 'x-unreal-reflection-boundary': true },
      skipped: { type: 'array', items: { type: 'string' }, description: 'Pairs left alone, each with the reason and what to do instead.' },
    },
    outputRequired: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    exampleInput: { action: 'fix_coplanar', dryRun: true },
    exampleOutput: { success: true, message: 'Would move 3 actors for 4 coplanar pairs; 4 pairs remain', pairsFound: 4, actorsMoved: 0, remainingPairs: 4, dryRun: true, moved: [], skipped: [] },
  }),
];
