/**
 * Tag and search records: add_tag, remove_tag, find_by_tag/find_actors_by_tag,
 * find_by_name/find_actors_by_name, find_by_class/find_actors_by_class.
 *
 * Grounded in actor-basic-handlers.ts (add_tag, remove_tag, find_by_tag,
 * find_by_name) and actor-component-handlers.ts (find_by_class), plus native
 * ControlActor dispatch (find_by_tag -> HandleControlActorFindByTag,
 * add_tag -> HandleControlActorAddTag, remove_tag -> HandleControlActorRemoveTag,
 * find_by_name/find_actors_by_name -> HandleControlActorFindByName,
 * find_by_class/find_actors_by_class -> HandleControlActorFindByClass).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';
import { actorAlias, CANONICAL_NR, DOMAIN, P } from './properties.js';

const FAMILY_TAGS = 'tags';
const FAMILY_FIND = 'find';

const FIND_OUTPUT = { actors: P.actors, count: P.count };

export const SEARCH_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'add_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    topics: ['tag actor', 'actor tag', 'label actor'],
    summary: 'Add a gameplay tag to an actor.',
    whenToUse: ['An actor must be tagged for later lookup or grouping.'],
    whenNotToUse: ['The tag is already present (idempotent re-add is a no-op).'],
    inputProps: { actorName: P.actorName, tag: P.tag },
    required: ['actorName', 'tag'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'add_tag', actorName: 'Cube1', tag: 'Pickup' },
    exampleOutput: { success: true, message: 'Added tag Pickup to Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'remove_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    summary: 'Remove a gameplay tag from an actor.',
    whenToUse: ['A tag must be removed from an actor.'],
    whenNotToUse: ['The tag is not present (no-op).'],
    inputProps: { actorName: P.actorName, tag: P.tag },
    required: ['actorName', 'tag'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'remove_tag', actorName: 'Cube1', tag: 'Pickup' },
    exampleOutput: { success: true, message: 'Removed tag Pickup from Cube1' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_by_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    summary: 'Find all actors in the level matching a gameplay tag.',
    whenToUse: ['Actors sharing a tag must be located.'],
    whenNotToUse: ['A specific actor name is known (use find_by_name).'],
    inputProps: { tag: P.tag },
    required: [],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'find_by_tag', tag: 'Pickup' },
    exampleOutput: { success: true, message: 'Found 1 actors by tag', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_actors_by_tag',
    domain: DOMAIN,
    family: FAMILY_TAGS,
    summary: 'Alias of find_by_tag; normalizeActorAction maps find_actors_by_tag to find_by_tag.',
    whenToUse: ['Preferred when callers use the explicit find_actors_by_tag verb.'],
    whenNotToUse: ['Use find_by_tag to avoid alias normalization.'],
    inputProps: { tag: P.tag },
    required: [],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('find_by_tag'),
    exampleInput: { action: 'find_actors_by_tag', tag: 'Pickup' },
    exampleOutput: { success: true, message: 'Found 1 actors by tag', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_by_name',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['find actor', 'lookup actor by name', 'search actor', 'get actor by name'],
    summary: 'Find actors in the level whose name matches a query string.',
    whenToUse: ['One or more actors must be located by name or substring.'],
    whenNotToUse: ['Actors should be located by tag (use find_by_tag).'],
    inputProps: { name: P.name },
    required: ['name'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'find_by_name', name: 'Cube' },
    exampleOutput: { success: true, message: 'Found 1 actors: Cube1', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_actors_by_name',
    domain: DOMAIN,
    family: FAMILY_FIND,
    summary: 'Alias of find_by_name; normalizeActorAction maps find_actors_by_name to find_by_name.',
    whenToUse: ['Preferred when callers use the explicit find_actors_by_name verb.'],
    whenNotToUse: ['Use find_by_name to avoid alias normalization.'],
    inputProps: { name: P.name },
    required: ['name'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('find_by_name'),
    exampleInput: { action: 'find_actors_by_name', name: 'Cube' },
    exampleOutput: { success: true, message: 'Found 1 actors: Cube1', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_by_class',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['actors of class', 'find actors by type', 'all actors of type'],
    summary: 'Find all actors in the level matching a Unreal class name or path.',
    whenToUse: ['All instances of a class must be located.'],
    whenNotToUse: ['A tag-based lookup is more appropriate (use find_by_tag).'],
    inputProps: { className: P.className, class: { type: 'string', description: 'Unreal class name or path (alias of className).' }, classPath: P.classPath },
    required: [],
    requiredOneOf: ['className', 'class', 'classPath'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'find_by_class', className: 'PointLight' },
    exampleOutput: { success: true, message: 'Found 2 actors by class', actors: [{ label: 'Light1', name: 'Light1' }], count: 2 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'find_actors_by_class',
    domain: DOMAIN,
    family: FAMILY_FIND,
    summary: 'Alias of find_by_class; normalizeActorAction maps find_actors_by_class to find_by_class.',
    whenToUse: ['Preferred when callers use the explicit find_actors_by_class verb.'],
    whenNotToUse: ['Use find_by_class to avoid alias normalization.'],
    inputProps: { className: P.className, class: { type: 'string', description: 'Unreal class name or path (alias of className).' }, classPath: P.classPath },
    required: [],
    requiredOneOf: ['className', 'class', 'classPath'],
    outputProps: FIND_OUTPUT,
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    ...actorAlias('find_by_class'),
    exampleInput: { action: 'find_actors_by_class', className: 'PointLight' },
    exampleOutput: { success: true, message: 'Found 2 actors by class', actors: [{ label: 'Light1', name: 'Light1' }], count: 2 },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'audit_placement',
    domain: DOMAIN,
    family: FAMILY_FIND,
    topics: ['placement problems', 'overlapping actors', 'sunk actors', 'floating actors', 'level audit', 'intersecting geometry'],
    summary: 'Sweep every actor in the level and report the ones that interpenetrate another actor, sit sunk below the surface under them, or float above it.',
    whenToUse: [
      'A level was assembled programmatically and needs checking before anyone looks at it.',
      'Actors appear to clip through each other or stand in the ground.',
      'A placement pass should be verified without flying the viewport around to eyeball it.',
    ],
    whenNotToUse: ['One actor was just moved; spawn and set_transform already return placementWarning for it.'],
    inputProps: {
      nameFilter: { type: 'string', description: 'Only examine actors whose label contains this text. Omit to sweep the whole level.' },
      limit: { type: 'number', description: 'Maximum problem entries to return (1-500, default 60). The flagged count is always the true total.' },
    },
    required: [],
    outputProps: {
      examined: { type: 'number', description: 'Actors inspected.' },
      flagged: { type: 'number', description: 'Actors with a placement problem, before the limit.' },
      returned: { type: 'number', description: 'Entries included in problems[].' },
      problems: {
        type: 'array',
        description: 'Per-actor findings: placementWarning, overlappingActors[] with penetrationDepth, groundClearance, and suggestedLocation when a resting Z can be computed.',
        items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true },
        'x-unreal-reflection-boundary': true,
      },
    },
    outputRequired: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'medium',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: 'Authored after the gateway migration; no pre-gateway occurrence to audit.',
    normalizationProvenance: 'post-migration',
    exampleInput: { action: 'audit_placement', nameFilter: 'HubNPC_' },
    exampleOutput: { success: true, message: 'Examined 12 actors, 3 with placement problems', examined: 12, flagged: 3, returned: 3, problems: [] },
  }),
];
