/**
 * Visibility and query records: set_visibility/set_actor_visible,
 * get_components/get_actor_components, get_actor_bounds, list.
 *
 * Grounded in actor-basic-handlers.ts (list) and the fallback dispatch path
 * for set_visibility and get_components, plus native ControlActor dispatch
 * (set_visibility+aliases -> HandleControlActorSetVisibility,
 * get_components/get_actor_components -> HandleControlActorGetComponents,
 * get_bounding_box/get_actor_bounds -> HandleControlActorGetBoundingBox,
 * list -> HandleControlActorList).
 */
import type { CapabilityRecordSource } from '../../index.js';
import { buildCoreRecord } from '../core/builder.js';
import { aliasNr, CANONICAL_NR, DOMAIN, internalDispatchNr, P } from './properties.js';

const FAMILY_VISIBILITY = 'visibility';
const FAMILY_QUERY = 'query';

export const STATE_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_visibility',
    domain: DOMAIN,
    family: FAMILY_VISIBILITY,
    summary: 'Toggle the visibility of an actor in the level.',
    whenToUse: ['An actor must be shown or hidden without being deleted.'],
    whenNotToUse: ['The actor should be removed (use delete).'],
    inputProps: { actorName: P.actorName, visible: P.visible },
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'set_visibility', actorName: 'Cube1', visible: false },
    exampleOutput: { success: true, message: 'Cube1 visibility set to false' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'set_actor_visible',
    domain: DOMAIN,
    family: FAMILY_VISIBILITY,
    summary: 'Alias of set_visibility; normalizeActorAction maps set_actor_visible to set_visibility.',
    whenToUse: ['Preferred when callers use the explicit set_actor_visible verb.'],
    whenNotToUse: ['Use set_visibility to avoid alias normalization.'],
    inputProps: { actorName: P.actorName, visible: P.visible },
    required: ['actorName'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: aliasNr('set_visibility'),
    exampleInput: { action: 'set_actor_visible', actorName: 'Cube1', visible: true },
    exampleOutput: { success: true, message: 'Cube1 visibility set to true' },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'get_components',
    domain: DOMAIN,
    family: FAMILY_QUERY,
    summary: 'List all components attached to an actor with their relative transforms.',
    whenToUse: ['The component composition of an actor must be inspected.'],
    whenNotToUse: ['A single component property is needed (use get_component_property).'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    outputProps: { components: P.components },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'get_components', actorName: 'Cube1' },
    exampleOutput: { success: true, message: 'Components for Cube1', components: [{ name: 'StaticMesh', class: 'StaticMeshComponent' }] },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'get_actor_components',
    domain: DOMAIN,
    family: FAMILY_QUERY,
    summary: 'Alias of get_components; normalizeActorAction maps get_actor_components to get_components.',
    whenToUse: ['Preferred when callers use the explicit get_actor_components verb.'],
    whenNotToUse: ['Use get_components to avoid alias normalization.'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    outputProps: { components: P.components },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: aliasNr('get_components'),
    exampleInput: { action: 'get_actor_components', actorName: 'Cube1' },
    exampleOutput: { success: true, message: 'Components for Cube1', components: [{ name: 'StaticMesh', class: 'StaticMeshComponent' }] },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'get_actor_bounds',
    domain: DOMAIN,
    family: FAMILY_QUERY,
    summary: 'Read the world-space bounding box of an actor; normalizes to get_bounding_box.',
    whenToUse: ['The spatial extent of an actor must be measured.'],
    whenNotToUse: ['The actor has no renderable components (bounds are undefined).'],
    inputProps: { actorName: P.actorName },
    required: ['actorName'],
    outputProps: { location: P.location, scale: P.scale },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: internalDispatchNr('get_actor_bounds', 'get_bounding_box'),
    exampleInput: { action: 'get_actor_bounds', actorName: 'Cube1' },
    exampleOutput: { success: true, message: 'Bounds for Cube1', location: [0, 0, 0], scale: [1, 1, 1] },
  }),
  buildCoreRecord({
    parentTool: 'control_actor',
    action: 'list',
    domain: DOMAIN,
    family: FAMILY_QUERY,
    summary: 'List actors in the current level with an optional limit and name filter.',
    whenToUse: ['The actors present in the level must be enumerated.'],
    whenNotToUse: ['A specific known actor name is already available (use find_by_name).'],
    inputProps: { limit: P.limit, filter: P.filter },
    required: [],
    outputProps: { actors: P.actors, count: P.count, totalCount: P.totalCount, isPieWorld: P.isPieWorld, worldName: P.worldName, filter: P.filter },
    outputRequired: [],
    effect: 'read',
    costLatency: 'instant',
    costResources: 'low',
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET',
    normalizationRationale: CANONICAL_NR,
    exampleInput: { action: 'list', limit: 50, filter: 'Cube' },
    exampleOutput: { success: true, message: 'Found 1 actors: Cube1', actors: [{ label: 'Cube1', name: 'Cube1' }], count: 1, totalCount: 1 },
  }),
];
