/**
 * Animation/Physics authoring records — part 2 of 3 (IK/retarget, pose lib,
 * asset/sequence, montage, notify). Grounded in animation_physics enum and
 * native HandleAnimationPhysicsAction plus TS special/authoring handlers.
 *
 * The native AnimationAuthoring domain reads `assetPath`; `animationPath` and
 * `montagePath` are accepted aliases normalized by animation-handler-utils.ts.
 * Notify-state and sync-marker ranges are frame-based natively, so they declare
 * startFrame/endFrame/frame rather than time fields.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';
import { bool, num, str, vec3 } from '../../shared/schema-props.js';

const T = 'animation_physics';
const F = 'animation';
const W = ['An animation asset or graph must be authored.'];
const ESU = ['EditorScriptingUtilities'];
const IK = ['ControlRig', 'IKRig', 'EditorScriptingUtilities'];
const BLEND_OPTION = { type: 'string', enum: ['Linear', 'Cubic', 'Sinusoidal'], description: 'Blend curve; left as it is when omitted.' };

export const ANIM_AUTHORED_2: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.create_ik_rig`, action: 'create_ik_rig', family: F,
    summary: 'Create an IK Rig asset.', whenToUse: ['IK retargeting source needed.'], whenNotToUse: ['Use create_control_rig.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: str('Skeletal mesh the IK Rig is built on; its skeleton is used.'), save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: IK,
    exampleInput: { action: 'create_ik_rig', name: 'IKR_Char', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_ik_retargeter`, action: 'create_ik_retargeter', family: F,
    summary: 'Create an IK Retargeter asset.', whenToUse: ['Retarget between two skeletons.'], whenNotToUse: ['Single skeleton.'],
    inputProps: { name: P.name, path: P.path, sourceIKRigPath: P.assetPath, targetIKRigPath: P.assetPath, save: A.save },
    required: ['name'], effect: 'write', latency: 'interactive', resources: 'medium', plugins: IK,
    exampleInput: { action: 'create_ik_retargeter', name: 'IKRT_Char', sourceIKRigPath: '/Game/IKR_A', targetIKRigPath: '/Game/IKR_B', save: true } }),
  buildRecord({ parentTool: T, id: `${T}.setup_ik`, action: 'setup_ik', family: F,
    summary: 'Create a Control Rig Blueprint bound to a skeleton to host IK solvers.', whenToUse: ['IK chains must be authored in a Control Rig.'], whenNotToUse: ['An IK Rig asset is needed (kind rig).'],
    inputProps: { name: P.name, path: str('Folder for the Control Rig (default /Game/Animations).'), skeletonPath: P.skeletonPath }, required: ['name', 'skeletonPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: IK,
    exampleInput: { action: 'setup_ik', name: 'TestIK', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.set_retarget_chain_mapping`, action: 'set_retarget_chain_mapping', family: F,
    topics: ['retarget chain mapping', 'map retarget chains', 'fix retargeted limb'],
    summary: 'Set which source IK Rig chain drives a target chain in an IK Retargeter (None clears it), or auto-map every unmapped chain by name; replies with the whole mapping.',
    whenToUse: ['A limb retargets from the wrong source chain after setup_retargeting or create_ik_retargeter.'], whenNotToUse: ['The retargeter does not exist yet (kind retargeter).'],
    inputProps: {
      assetPath: str('IK Retargeter asset to edit.'),
      targetChain: str('Target IK Rig chain to map; required unless autoMap.'),
      sourceChain: str('Source IK Rig chain that drives it; empty or None clears the mapping.'),
      autoMap: bool('Map every unmapped chain: exact name matches first, then the closest names (default false).'),
      save: A.save,
    },
    required: ['assetPath'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: IK,
    outputProps: {
      mapping: { type: 'array', items: { type: 'object', properties: { targetChain: { type: 'string', description: 'Target IK Rig chain.' }, sourceChain: { type: 'string', description: 'Source chain driving it, or None.' } }, additionalProperties: false }, description: 'Every target chain with the source chain now driving it (None when unmapped).' },
      changed: { type: 'boolean', description: 'Whether any mapping changed.' },
      saved: { type: 'boolean', description: 'Whether the retargeter was saved.' },
    },
    exampleInput: { action: 'set_retarget_chain_mapping', assetPath: '/Game/Retargeting/IKRT_Char', targetChain: 'LeftArm', sourceChain: 'LeftArm' } }),
  buildRecord({ parentTool: T, id: `${T}.create_animation_asset`, action: 'create_animation_asset', family: F,
    summary: 'Create an empty Animation Sequence or Montage on a skeleton.', whenToUse: W, whenNotToUse: ['Use create_animation_sequence.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, assetType: { type: 'string', enum: ['sequence', 'montage'], description: 'Asset class to create (default sequence).' } }, required: ['name', 'skeletonPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_animation_asset', name: 'A_Run', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_pose_library`, action: 'create_pose_library', family: F,
    topics: ['pose asset', 'pose library', 'facial poses'],
    summary: 'Create a Pose Asset from an animation sequence, one pose per key frame, on the sequence\'s skeleton; PoseByName and PoseBlender nodes play its poses.',
    whenToUse: ['Named poses (facial shapes, hand poses, correctives) must be blended by name in an Animation Blueprint.'], whenNotToUse: ['A playable clip is needed; use kind sequence or montage.'],
    inputProps: {
      name: P.name,
      path: str('Folder for the new asset (default /Game/Animations).'),
      sourceAnimationPath: str('AnimSequence whose key frames become the poses; its skeleton is used.'),
      poseNames: { type: 'array', items: { type: 'string' }, description: 'Distinct names for the poses in frame order; frames without a name keep the engine default name.' },
      additive: bool('Make the poses additive against pose 0, as facial and corrective poses are (default false).'),
    },
    required: ['name', 'sourceAnimationPath'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: {
      assetPath: P.assetPath,
      skeletonPath: str('Skeleton the pose asset uses.'),
      poseCount: num('Poses in the asset.'),
      poseNames: { type: 'array', items: { type: 'string' }, description: 'Pose names read back from the asset.' },
      additive: bool('Whether the poses are additive.'),
      saved: bool('Whether the pose asset was saved.'),
      skeletonSaved: bool('UE 5.0 to 5.2: whether the skeleton, which holds the pose curve names there, was saved.'),
    },
    exampleInput: { action: 'create_pose_library', name: 'PA_Face', sourceAnimationPath: '/Game/Animations/A_FacePoses', poseNames: ['Neutral', 'Smile', 'Blink'] } }),
  buildRecord({ parentTool: T, id: `${T}.create_animation_sequence`, action: 'create_animation_sequence', family: F,
    summary: 'Create an Animation Sequence asset.', whenToUse: ['A keyframed clip is needed.'], whenNotToUse: ['Use create_animation_asset.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, numFrames: num('Length in frames (default 30).'), frameRate: num('Frames per second (default 30).'), save: A.save },
    required: ['name'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_animation_sequence', name: 'A_Run', skeletonPath: '/Game/SK_Char', numFrames: 30, frameRate: 30 },
    exampleOutput: { success: true, message: 'Animation sequence created' } }),
  buildRecord({ parentTool: T, id: `${T}.set_sequence_length`, action: 'set_sequence_length', family: F,
    summary: 'Set the length of an Animation Sequence.', whenToUse: ['Clip duration must change.'], whenNotToUse: ['Use create_animation_sequence.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, numFrames: num('New length in frames.'), length: num('New length in seconds, used when numFrames is omitted.'), frameRate: num('Frames per second; the sequence keeps its current rate when omitted.'), save: A.save }, required: [], requiredOneOf: ['numFrames', 'length'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_sequence_length', assetPath: '/Game/A_Run', numFrames: 60 },
    exampleOutput: { success: true, message: 'Sequence length set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_bone_track`, action: 'add_bone_track', family: F,
    summary: 'Add a bone animation track.', whenToUse: ['A bone must be animated.'], whenNotToUse: ['Track exists.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, boneName: P.boneName, save: A.save }, required: ['boneName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_bone_track', assetPath: '/Game/A_Run', boneName: 'spine_01' },
    exampleOutput: { success: true, message: 'Bone track added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_bone_key`, action: 'set_bone_key', family: F,
    summary: 'Set a bone transform key.', whenToUse: ['Keyframe a bone pose.'], whenNotToUse: ['Use add_bone_track.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, boneName: P.boneName, frame: P.frame, location: P.location, rotation: P.rotation, scale: vec3('Bone scale as [x, y, z] (default [1, 1, 1]).'), save: A.save },
    required: ['boneName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_bone_key', assetPath: '/Game/A_Run', boneName: 'spine_01', frame: 0 },
    exampleOutput: { success: true, message: 'Bone key set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_curve_key`, action: 'set_curve_key', family: F,
    summary: 'Set an animation curve key.', whenToUse: ['Animate a curve.'], whenNotToUse: ['Use add_bone_track.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, curveName: P.curveName, frame: P.frame, value: P.value, createIfMissing: bool('Create the curve when the sequence does not have it (default true).'), save: A.save },
    required: ['curveName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_curve_key', assetPath: '/Game/A_Run', curveName: 'Weight', frame: 0, value: 1 },
    exampleOutput: { success: true, message: 'Curve key set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_notify_state`, action: 'add_notify_state', family: F,
    summary: 'Add a notify state spanning a frame range.', whenToUse: ['A ranged notify is needed.'], whenNotToUse: ['Use add_notify.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, notifyClass: A.notifyClass, notifyName: P.notifyName, startFrame: A.startFrame, endFrame: A.endFrame, trackIndex: A.trackIndex, save: A.save },
    required: [], requiredOneOf: ['notifyClass', 'notifyName'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_notify_state', assetPath: '/Game/A_Run', notifyName: 'Windup', startFrame: 1, endFrame: 10, trackIndex: 0 } }),
  buildRecord({ parentTool: T, id: `${T}.add_sync_marker`, action: 'add_sync_marker', family: F,
    summary: 'Add a sync marker to a sequence.', whenToUse: ['Sync groups needed.'], whenNotToUse: ['No sync required.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, markerName: P.markerName, frame: P.frame, save: A.save }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_sync_marker', assetPath: '/Game/A_Run', markerName: 'FootL', frame: 5 } }),
  buildRecord({ parentTool: T, id: `${T}.set_root_motion_settings`, action: 'set_root_motion_settings', family: F,
    summary: 'Configure root motion on a sequence.', whenToUse: ['Root motion locomotion needed.'], whenNotToUse: ['In-place animation.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, enableRootMotion: P.bool_, rootMotionRootLock: P.string_, forceRootLock: A.forceRootLock, save: A.save },
    required: [], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_root_motion_settings', assetPath: '/Game/A_Run', enableRootMotion: true, rootMotionRootLock: 'RefPose' },
    exampleOutput: { success: true, message: 'Root motion settings set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_additive_settings`, action: 'set_additive_settings', family: F,
    summary: 'Configure additive animation settings.', whenToUse: ['Additive layering needed.'], whenNotToUse: ['Absolute pose.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, additiveAnimType: P.string_, basePoseType: A.basePoseType, basePoseFrame: A.basePoseFrame, basePoseAnimation: str('Animation sequence to take the additive base pose from.'), save: A.save }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_additive_settings', assetPath: '/Game/A_Run', additiveAnimType: 'NoAdditive', basePoseType: 'RefPose', basePoseFrame: 0 } }),
  buildRecord({ parentTool: T, id: `${T}.create_montage`, action: 'create_montage', family: F,
    topics: ['anim montage', 'montage asset', 'new montage'],
    summary: 'Create a montage asset, optionally from a sequence.', whenToUse: ['A playable montage is needed.'], whenNotToUse: ['Use create_animation_sequence.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, animationPath: str('Sequence the montage plays; its skeleton is used when skeletonPath is omitted.'), slotName: str('Name of the montage slot (default DefaultSlot).'), save: A.save }, required: ['name'], requiredOneOf: ['skeletonPath', 'animationPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_montage', name: 'MT_Slash', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.add_montage_section`, action: 'add_montage_section', family: F,
    summary: 'Add a section to a montage.', whenToUse: ['Montage needs a section.'], whenNotToUse: ['Use create_montage.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, sectionName: P.sectionName, startTime: P.startTime, save: A.save }, required: ['sectionName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_montage_section', assetPath: '/Game/MT_Slash', sectionName: 'Hit', startTime: 0 },
    exampleOutput: { success: true, message: 'Montage section added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_montage_slot`, action: 'add_montage_slot', family: F,
    summary: 'Add a slot to a montage.', whenToUse: ['Montage must expose a slot.'], whenNotToUse: ['Default slot.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, animationPath: str('Sequence to add as a segment of the slot.'), slotName: P.slotName, startTime: P.startTime, save: A.save }, required: ['animationPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_montage_slot', assetPath: '/Game/MT_Slash', animationPath: '/Game/A_Slash', slotName: 'DefaultSlot' } }),
  buildRecord({ parentTool: T, id: `${T}.set_section_timing`, action: 'set_section_timing', family: F,
    summary: 'Move a montage section to a new start time (a section runs until the next one starts).', whenToUse: ['Section timing must change.'], whenNotToUse: ['Use add_montage_section.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, sectionName: P.sectionName, startTime: P.startTime, save: A.save },
    required: ['sectionName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU,
    exampleInput: { action: 'set_section_timing', assetPath: '/Game/MT_Slash', sectionName: 'Hit', startTime: 0 },
    exampleOutput: { success: true, message: 'Section timing updated' } }),
  buildRecord({ parentTool: T, id: `${T}.add_montage_notify`, action: 'add_montage_notify', family: F,
    summary: 'Add a notify to a montage.', whenToUse: ['Timed event needed in montage.'], whenNotToUse: ['Use add_notify_state.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, notifyClass: A.notifyClass, notifyName: P.notifyName, time: P.time, trackIndex: A.trackIndex, save: A.save }, required: [],
    requiredOneOf: ['notifyClass', 'notifyName'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_montage_notify', assetPath: '/Game/MT_Slash', notifyName: 'Hit', time: 0.5 } }),
  buildRecord({ parentTool: T, id: `${T}.set_blend_in`, action: 'set_blend_in', family: F,
    summary: 'Set montage blend-in time.', whenToUse: ['Smooth entry needed.'], whenNotToUse: ['Use set_blend_out.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, blendTime: P.blendTime, blendOption: BLEND_OPTION, save: A.save }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_blend_in', assetPath: '/Game/MT_Slash', blendTime: 0.2 } }),
  buildRecord({ parentTool: T, id: `${T}.set_blend_out`, action: 'set_blend_out', family: F,
    summary: 'Set montage blend-out time.', whenToUse: ['Smooth exit needed.'], whenNotToUse: ['Use set_blend_in.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, blendTime: P.blendTime, blendOption: BLEND_OPTION, save: A.save }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_blend_out', assetPath: '/Game/MT_Slash', blendTime: 0.2 } }),
  buildRecord({ parentTool: T, id: `${T}.link_sections`, action: 'link_sections', family: F,
    summary: 'Link two montage sections.', whenToUse: ['Sections must chain.'], whenNotToUse: ['Use add_montage_section.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, fromSection: P.fromSection, toSection: P.toSection, save: A.save }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'link_sections', assetPath: '/Game/MT_Slash', fromSection: 'Start', toSection: 'Hit' },
    exampleOutput: { success: true, message: 'Sections linked' } }),
  buildRecord({ parentTool: T, id: `${T}.add_notify`, action: 'add_notify', family: F,
    summary: 'Add a frame notify to a sequence (authoring).', whenToUse: ['Frame event in a sequence.'], whenNotToUse: ['Use add_montage_notify.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, notifyClass: A.notifyClass, notifyName: P.notifyName, frame: P.frame, time: num('Trigger time in seconds, used when frame is omitted.'), trackIndex: A.trackIndex, save: A.save }, required: [],
    requiredOneOf: ['notifyClass', 'notifyName'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_notify', assetPath: '/Game/A_Run', notifyName: 'Step', frame: 10 } }),
];
