/**
 * Animation/Physics authoring records — part 1 of 3 (creation, blend, state).
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';
import { bool, num, str } from '../../shared/schema-props.js';

const T = 'animation_physics';
const F = 'animation';
const W = ['An animation asset or graph must be authored.'];
const ESU = ['EditorScriptingUtilities'];
const CR_ESU = ['ControlRig', 'EditorScriptingUtilities'];
// The transition settings add_transition applies to what it creates and set_transition_rules edits.
const TRANSITION_SETTINGS = { blendTime: P.blendTime, crossfadeDuration: A.crossfadeDuration, priorityOrder: A.priorityOrder, automaticRule: A.automaticRule, bidirectional: A.bidirectional, conditionVariable: A.conditionVariable, conditionComparison: A.conditionComparison, conditionValue: A.conditionValue };
const BS_2D_AXES = {
  horizontalAxisName: str('Horizontal axis label (default Direction).'), horizontalMin: num('Horizontal axis minimum (default -180).'), horizontalMax: num('Horizontal axis maximum (default 180).'),
  verticalAxisName: str('Vertical axis label (default Speed).'), verticalMin: num('Vertical axis minimum (default 0).'), verticalMax: num('Vertical axis maximum (default 600).'),
};

export const ANIM_AUTHORED_1: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.create_animation_blueprint`, action: 'create_animation_blueprint', family: F,
    topics: ['anim blueprint', 'abp', 'animation bp', 'anim graph', 'animbp'],
    summary: 'Create an Animation Blueprint asset.', whenToUse: W, whenNotToUse: ['A SkeletalMesh suffices.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: A.meshSkeleton, parentClass: A.abpParentClass, save: A.save },
    required: ['name'], effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: ['assetPath'],
    exampleInput: { action: 'create_animation_blueprint', name: 'ABP_Char', skeletonPath: '/Game/SK_Char', parentClass: 'AnimInstance' }, exampleOutput: { success: true, message: 'Animation Blueprint created', assetPath: '/Game/ABP_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_animation_bp`, action: 'create_animation_bp', family: F,
    summary: 'Alias of create_animation_blueprint (short form).', whenToUse: ['Caller uses the create_animation_bp verb.'], whenNotToUse: ['Use create_animation_blueprint.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: A.meshSkeleton, parentClass: A.abpParentClass, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    exampleInput: { action: 'create_animation_bp', name: 'ABP_Char', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_anim_blueprint`, action: 'create_anim_blueprint', family: F,
    summary: 'Alias of create_animation_blueprint (short form).', whenToUse: ['Caller uses the create_anim_blueprint verb.'], whenNotToUse: ['Use create_animation_blueprint.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: A.meshSkeleton, parentClass: A.abpParentClass, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    exampleInput: { action: 'create_anim_blueprint', name: 'ABP_Char', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_space`, action: 'create_blend_space', family: F,
    summary: 'Create a 2D Blend Space asset.', whenToUse: W, whenNotToUse: ['Use create_blend_space_1d for one axis.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, ...BS_2D_AXES, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_blend_space', name: 'BS_Locomotion', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Blend Space created', assetPath: '/Game/BS_Locomotion' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_space_1d`, action: 'create_blend_space_1d', family: F,
    summary: 'Create a 1D Blend Space asset.', whenToUse: ['A single-axis blend is needed.'], whenNotToUse: ['Use create_blend_space for 2D.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, axisName: str('Axis label (default Speed).'), axisMin: num('Axis minimum (default 0).'), axisMax: num('Axis maximum (default 600).'), save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_blend_space_1d', name: 'BS1D_Speed', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Blend Space 1D created', assetPath: '/Game/BS1D_Speed' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_space_2d`, action: 'create_blend_space_2d', family: F,
    summary: 'Create a 2D Blend Space asset.', whenToUse: ['A two-axis blend is needed.'], whenNotToUse: ['Use create_blend_space_1d for one axis.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, ...BS_2D_AXES, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_blend_space_2d', name: 'BS2D_DirSpeed', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Blend Space 2D created', assetPath: '/Game/BS2D_DirSpeed' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_tree`, action: 'create_blend_tree', family: F,
    summary: 'Author a blend tree in an AnimBlueprint AnimGraph: a Blend List (by int) node fed by one Sequence Player per animation, optionally wired to the output pose.', whenToUse: ['Several animations must be switchable through one blend node in an AnimBlueprint.'], whenNotToUse: ['A single add_blend_node suffices.'],
    inputProps: { name: P.name, blueprintPath: P.blueprintPath, treeName: { type: 'string', description: 'Comment/name for the blend node (alias of name).' }, animations: { type: 'array', items: { type: 'string' }, description: 'Animation asset paths; one Sequence Player is created and connected per entry.' }, connectToOutput: { type: 'boolean', description: 'Wire the blend node into the AnimGraph output pose (default true).' } }, required: ['blueprintPath'], requiredOneOf: ['name', 'treeName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_blend_tree', name: 'BT_Move', blueprintPath: '/Game/ABP_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_procedural_anim`, action: 'create_procedural_anim', family: F,
    summary: 'Create a procedural anim asset.', whenToUse: ['A runtime-authored animation is needed.'], whenNotToUse: ['Use a static sequence.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, boneTracks: A.boneTracks, numFrames: num('Length in frames (default 30).'), frameRate: P.frameRate, save: A.save }, required: ['name', 'skeletonPath', 'boneTracks'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_procedural_anim', name: 'PA_Wave', skeletonPath: '/Game/SK_Char', frameRate: 30 } }),
  buildRecord({ parentTool: T, id: `${T}.create_aim_offset`, action: 'create_aim_offset', family: F,
    summary: 'Create an Aim Offset asset.', whenToUse: ['Aim blending by look direction is needed.'], whenNotToUse: ['Use a blend space.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_aim_offset', name: 'AO_Aim', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Aim Offset created', assetPath: '/Game/AO_Aim' } }),
  buildRecord({ parentTool: T, id: `${T}.add_aim_offset_sample`, action: 'add_aim_offset_sample', family: F,
    summary: 'Add a sample pose to an Aim Offset.', whenToUse: ['Aim sample must be added.'], whenNotToUse: ['Use create_aim_offset.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, yaw: A.yaw, pitch: A.pitch }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_aim_offset_sample', assetPath: '/Game/AO_Aim', animationPath: '/Game/A_Idle', yaw: 0, pitch: 0 },
    exampleOutput: { success: true, message: 'Aim sample added' } }),
  buildRecord({ parentTool: T, id: `${T}.create_state_machine`, action: 'create_state_machine', family: F,
    summary: 'Create a State Machine graph asset.', whenToUse: ['State-driven animation is needed.'], whenNotToUse: ['A single graph suffices.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, machineName: str('State machine name (default StateMachine).'), states: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { name: { type: 'string' } }, required: ['name'] }, description: 'States to create, as [{ name }].' }, transitions: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { sourceState: { type: 'string' }, targetState: { type: 'string' } }, required: ['sourceState', 'targetState'] }, description: 'Transitions to create between the listed states, as [{ sourceState, targetState }].' } }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { blueprintPath: P.blueprintPath, machineName: P.machineName }, outputRequired: [],
    exampleInput: { action: 'create_state_machine', blueprintPath: '/Game/ABP_Char', machineName: 'SM_Locomotion' }, exampleOutput: { success: true, message: 'State machine created', machineName: 'SM_Locomotion' } }),
  buildRecord({ parentTool: T, id: `${T}.add_state_machine`, action: 'add_state_machine', family: F,
    summary: 'Add a State Machine node to an AnimGraph.', whenToUse: ['A state machine must be embedded.'], whenNotToUse: ['Use create_state_machine.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, machineName: P.machineName, positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { blueprintPath: P.blueprintPath, machineName: P.machineName }, outputRequired: [],
    exampleInput: { action: 'add_state_machine', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco' },
    exampleOutput: { success: true, message: 'State machine node added', machineName: 'SM_Loco' } }),
  buildRecord({ parentTool: T, id: `${T}.add_state`, action: 'add_state', family: F,
    summary: 'Add a state to a State Machine.', whenToUse: ['A new animation state is needed.'], whenNotToUse: ['Use add_transition.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, machineName: { type: 'string', description: 'Alias of stateMachineName. Omitting both matches every state machine in the graph.' }, stateName: P.stateName, animations: { type: 'array', items: { type: 'string' }, description: 'Animation asset paths to play in this state; one Sequence Player is created per entry and the first drives the state Result pose. Without it the state is created empty and the character holds its reference pose.' }, positionX: num('Graph X position of the state (default 200).'), positionY: A.positionY, save: A.save }, required: ['blueprintPath', 'stateName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { blueprintPath: P.blueprintPath, machineName: P.machineName, stateName: P.stateName, animationsApplied: { type: 'array', items: { type: 'object', properties: { animationPath: { type: 'string' }, nodeId: { type: 'string' }, connected: { type: 'boolean' } }, required: ['animationPath', 'nodeId', 'connected'], additionalProperties: false }, description: 'One entry per created Sequence Player. Only the first can be connected to the state Result pose.' }, animationsFailed: { type: 'array', items: { type: 'string' }, description: 'Requested animation paths that could not be loaded.' } }, outputRequired: [],
    exampleInput: { action: 'add_state', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', stateName: 'Idle', animations: ['/Game/Anims/A_Idle'] },
    exampleOutput: { success: true, message: 'State added', stateName: 'Idle' } }),
  buildRecord({ parentTool: T, id: `${T}.add_transition`, action: 'add_transition', family: F,
    summary: 'Add a transition between two states.', whenToUse: ['States must connect.'], whenNotToUse: ['Use add_state.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, fromState: P.fromState, toState: P.toState, ...TRANSITION_SETTINGS, save: A.save }, required: ['blueprintPath', 'fromState', 'toState'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_transition', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', fromState: 'Idle', toState: 'Run' },
    exampleOutput: { success: true, message: 'Transition added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_transition_rules`, action: 'set_transition_rules', family: F,
    summary: 'Set transition rule logic: the condition a transition tests, plus its blend timing.',
    whenToUse: ['Transition condition must change.', 'A state machine must actually be able to leave a state: author the condition here after add_transition.'],
    whenNotToUse: ['Use add_transition.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, fromState: P.fromState, toState: P.toState, ...TRANSITION_SETTINGS, save: A.save }, required: ['blueprintPath', 'fromState', 'toState'],
    outputProps: { condition: { type: 'string', description: 'The rule that was written into the transition graph. Absent means no conditionVariable was given, so the transition stays false and the state is never left.' } },
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_transition_rules', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', fromState: 'Idle', toState: 'Run', conditionVariable: 'Speed', conditionComparison: 'greater', conditionValue: 10 },
    exampleOutput: { success: true, message: 'Transition rules updated', condition: 'Speed greater 10' } }),
  buildRecord({ parentTool: T, id: `${T}.delete_transition`, action: 'delete_transition', family: F,
    summary: 'Delete a transition from a State Machine.',
    whenToUse: ['A transition was authored between the wrong two states.', 'A transition is dead weight and its rule graph should go with it.'],
    whenNotToUse: ['The transition should stay but never fire: use set_transition_rules.', 'The state itself must go, not just the transition.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, fromState: P.fromState, toState: P.toState, save: A.save }, required: ['blueprintPath', 'fromState', 'toState'],
    outputProps: { deleted: { type: 'boolean', description: 'True when the transition and its rule graph were removed.' } },
    effect: 'write', behavior: { idempotency: 'non-idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU, 
    exampleInput: { action: 'delete_transition', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', fromState: 'Jump', toState: 'Idle' },
    exampleOutput: { success: true, message: 'Transition deleted', deleted: true } }),
  buildRecord({ parentTool: T, id: `${T}.add_blend_node`, action: 'add_blend_node', family: F,
    summary: 'Add a blend node to an AnimGraph.', whenToUse: ['Graph needs a blend node.'], whenNotToUse: ['Use create_blend_tree.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, blendType: { type: 'string', enum: ['TwoWayBlend', 'BlendListByBool', 'BlendListByInt', 'LayeredBoneBlend'], description: 'Blend node type (default TwoWayBlend).' }, nodeName: P.nodeName, positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_blend_node', blueprintPath: '/Game/ABP_Char', blendType: 'TwoWayBlend', nodeName: 'Blend_0' } }),
  buildRecord({ parentTool: T, id: `${T}.add_cached_pose`, action: 'add_cached_pose', family: F,
    summary: 'Add a cached pose node.', whenToUse: ['Pose reuse optimization needed.'], whenNotToUse: ['Inline pose suffices.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, cacheName: P.cacheName, positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath', 'cacheName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_cached_pose', blueprintPath: '/Game/ABP_Char', cacheName: 'LocomotionPose' } }),
  buildRecord({ parentTool: T, id: `${T}.add_slot_node`, action: 'add_slot_node', family: F,
    summary: 'Add an animation slot node.', whenToUse: ['Montage slot must be exposed.'], whenNotToUse: ['Use create_montage.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, slotName: P.slotName, groupName: str('Slot group the slot belongs to (default DefaultGroup).'), positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath', 'slotName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_slot_node', blueprintPath: '/Game/ABP_Char', slotName: 'DefaultSlot' },
    exampleOutput: { success: true, message: 'Slot node added' } }),
  buildRecord({ parentTool: T, id: `${T}.create_control_rig`, action: 'create_control_rig', family: F,
    summary: 'Create a Control Rig asset.', whenToUse: ['Procedural rigging/IK needed (ControlRig).'], whenNotToUse: ['Use create_ik_rig.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: str('Skeletal mesh to build the rig from; wins over skeletonPath.'), modularRig: bool('Create a Modular Rig (UE 5.5+; older engines report modularRig false).'), save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: ['ControlRig', 'RigVM', 'EditorScriptingUtilities'],
    exampleInput: { action: 'create_control_rig', name: 'CR_Char', skeletonPath: '/Game/SK_Char' } }),
];
