/**
 * Animation/Physics authoring records — part 2 of 3 (IK/retarget, pose lib,
 * asset/sequence, montage, notify). Grounded in animation_physics enum and
 * native HandleAnimationPhysicsAction plus TS special/authoring handlers.
 *
 * The native AnimationAuthoring domain reads `assetPath`; `animationPath` and
 * `montagePath` are accepted aliases normalized by animation-handler-utils.ts.
 * Notify-state and sync-marker ranges are frame-based natively, so they declare
 * startFrame/endFrame/frame rather than time fields.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';

const T = 'animation_physics';
const F = 'animation';
const W = ['An animation asset or graph must be authored.'];
const ESU = ['EditorScriptingUtilities'];
const IK = ['ControlRig', 'IKRig', 'EditorScriptingUtilities'];

export const ANIM_AUTHORED_2: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.create_ik_rig`, action: 'create_ik_rig', family: F,
    summary: 'Create an IK Rig asset.', whenToUse: ['IK retargeting source needed.'], whenNotToUse: ['Use create_control_rig.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, targetSkeleton: P.skeletonPath, meshPath: P.meshPath }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: IK,
    exampleInput: { action: 'create_ik_rig', name: 'IKR_Char', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_ik_retargeter`, action: 'create_ik_retargeter', family: F,
    summary: 'Create an IK Retargeter asset.', whenToUse: ['Retarget between two skeletons.'], whenNotToUse: ['Single skeleton.'],
    inputProps: { name: P.name, path: P.path, sourceIKRigPath: P.assetPath, targetIKRigPath: P.assetPath, save: P.save },
    required: ['name'], effect: 'write', latency: 'interactive', resources: 'medium', plugins: IK,
    exampleInput: { action: 'create_ik_retargeter', name: 'IKRT_Char', sourceIKRigPath: '/Game/IKR_A', targetIKRigPath: '/Game/IKR_B', save: true } }),
  buildRecord({ parentTool: T, id: `${T}.setup_ik`, action: 'setup_ik', family: F,
    summary: 'Configure IK setup on an AnimBlueprint.', whenToUse: ['IK chains must be enabled.'], whenNotToUse: ['Use create_ik_rig.'],
    inputProps: { name: P.name, assetPath: P.assetPath, skeletonPath: P.skeletonPath }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: IK,
    exampleInput: { action: 'setup_ik', name: 'TestIK', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_animation_asset`, action: 'create_animation_asset', family: F,
    summary: 'Create an Animation asset (slot for sequence).', whenToUse: W, whenNotToUse: ['Use create_animation_sequence.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, targetSkeleton: P.skeletonPath }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_animation_asset', name: 'A_Run', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_animation_sequence`, action: 'create_animation_sequence', family: F,
    summary: 'Create an Animation Sequence asset.', whenToUse: ['A keyframed clip is needed.'], whenNotToUse: ['Use create_animation_asset.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, targetSkeleton: P.skeletonPath, numFrames: P.num_, frameRate: P.frameRate },
    required: ['name'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_animation_sequence', name: 'A_Run', skeletonPath: '/Game/SK_Char', numFrames: 30, frameRate: 30 },
    exampleOutput: { success: true, message: 'Animation sequence created' } }),
  buildRecord({ parentTool: T, id: `${T}.set_sequence_length`, action: 'set_sequence_length', family: F,
    summary: 'Set the length of an Animation Sequence.', whenToUse: ['Clip duration must change.'], whenNotToUse: ['Use create_animation_sequence.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, numFrames: P.num_, length: P.length }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_sequence_length', assetPath: '/Game/A_Run', numFrames: 60 },
    exampleOutput: { success: true, message: 'Sequence length set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_bone_track`, action: 'add_bone_track', family: F,
    summary: 'Add a bone animation track.', whenToUse: ['A bone must be animated.'], whenNotToUse: ['Track exists.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, boneName: P.boneName }, required: ['boneName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_bone_track', assetPath: '/Game/A_Run', boneName: 'spine_01' },
    exampleOutput: { success: true, message: 'Bone track added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_bone_key`, action: 'set_bone_key', family: F,
    summary: 'Set a bone transform key.', whenToUse: ['Keyframe a bone pose.'], whenNotToUse: ['Use add_bone_track.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, boneName: P.boneName, frame: P.frame, location: P.location, rotation: P.rotation },
    required: ['boneName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_bone_key', assetPath: '/Game/A_Run', boneName: 'spine_01', frame: 0 },
    exampleOutput: { success: true, message: 'Bone key set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_curve_key`, action: 'set_curve_key', family: F,
    summary: 'Set an animation curve key.', whenToUse: ['Animate a curve.'], whenNotToUse: ['Use add_bone_track.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, curveName: P.curveName, frame: P.frame, value: P.value },
    required: ['curveName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_curve_key', assetPath: '/Game/A_Run', curveName: 'Weight', frame: 0, value: 1 },
    exampleOutput: { success: true, message: 'Curve key set' } }),
  buildRecord({ parentTool: T, id: `${T}.add_notify_state`, action: 'add_notify_state', family: F,
    summary: 'Add a notify state spanning a frame range.', whenToUse: ['A ranged notify is needed.'], whenNotToUse: ['Use add_notify.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, notifyClass: A.notifyClass, notifyName: P.notifyName, startFrame: A.startFrame, endFrame: A.endFrame, trackIndex: A.trackIndex, save: P.save },
    required: [], requiredOneOf: ['notifyClass', 'notifyName'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_notify_state', assetPath: '/Game/A_Run', notifyName: 'Windup', startFrame: 1, endFrame: 10, trackIndex: 0 } }),
  buildRecord({ parentTool: T, id: `${T}.add_sync_marker`, action: 'add_sync_marker', family: F,
    summary: 'Add a sync marker to a sequence.', whenToUse: ['Sync groups needed.'], whenNotToUse: ['No sync required.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, markerName: P.markerName, frame: P.frame, save: P.save }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_sync_marker', assetPath: '/Game/A_Run', markerName: 'FootL', frame: 5 } }),
  buildRecord({ parentTool: T, id: `${T}.set_root_motion_settings`, action: 'set_root_motion_settings', family: F,
    summary: 'Configure root motion on a sequence.', whenToUse: ['Root motion locomotion needed.'], whenNotToUse: ['In-place animation.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, enableRootMotion: P.bool_, rootMotionRootLock: P.string_, forceRootLock: A.forceRootLock, save: P.save },
    required: [], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_root_motion_settings', assetPath: '/Game/A_Run', enableRootMotion: true, rootMotionRootLock: 'RefPose' },
    exampleOutput: { success: true, message: 'Root motion settings set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_additive_settings`, action: 'set_additive_settings', family: F,
    summary: 'Configure additive animation settings.', whenToUse: ['Additive layering needed.'], whenNotToUse: ['Absolute pose.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, additiveAnimType: P.string_, basePoseType: A.basePoseType, basePoseFrame: A.basePoseFrame, save: P.save }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_additive_settings', assetPath: '/Game/A_Run', additiveAnimType: 'NoAdditive', basePoseType: 'RefPose', basePoseFrame: 0 } }),
  buildRecord({ parentTool: T, id: `${T}.create_montage`, action: 'create_montage', family: F,
    topics: ['anim montage', 'montage asset', 'new montage'],
    summary: 'Create a montage asset from a sequence.', whenToUse: ['A playable montage is needed.'], whenNotToUse: ['Use create_animation_sequence.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, animationPath: P.animationPath }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_montage', name: 'MT_Slash', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.add_montage_section`, action: 'add_montage_section', family: F,
    summary: 'Add a section to a montage.', whenToUse: ['Montage needs a section.'], whenNotToUse: ['Use create_montage.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, sectionName: P.sectionName, startTime: P.startTime }, required: ['sectionName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_montage_section', assetPath: '/Game/MT_Slash', sectionName: 'Hit', startTime: 0 },
    exampleOutput: { success: true, message: 'Montage section added' } }),
  buildRecord({ parentTool: T, id: `${T}.add_montage_slot`, action: 'add_montage_slot', family: F,
    summary: 'Add a slot to a montage.', whenToUse: ['Montage must expose a slot.'], whenNotToUse: ['Default slot.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, animationPath: P.animationPath, slotName: P.slotName, startTime: P.startTime }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_montage_slot', assetPath: '/Game/MT_Slash', animationPath: '/Game/A_Slash', slotName: 'DefaultSlot' } }),
  buildRecord({ parentTool: T, id: `${T}.set_section_timing`, action: 'set_section_timing', family: F,
    summary: 'Set montage section start time and length.', whenToUse: ['Section timing must change.'], whenNotToUse: ['Use add_montage_section.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, sectionName: P.sectionName, startTime: P.startTime, length: P.length },
    required: ['sectionName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, outputProps: { endTime: P.endTime, length: P.length }, outputRequired: [],
    exampleInput: { action: 'set_section_timing', assetPath: '/Game/MT_Slash', sectionName: 'Hit', startTime: 0, length: 1 },
    exampleOutput: { success: true, message: 'Section timing set', endTime: 1, length: 1 } }),
  buildRecord({ parentTool: T, id: `${T}.add_montage_notify`, action: 'add_montage_notify', family: F,
    summary: 'Add a notify to a montage.', whenToUse: ['Timed event needed in montage.'], whenNotToUse: ['Use add_notify_state.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, notifyClass: A.notifyClass, notifyName: P.notifyName, time: P.time }, required: [],
    requiredOneOf: ['notifyClass', 'notifyName'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_montage_notify', assetPath: '/Game/MT_Slash', notifyName: 'Hit', time: 0.5 } }),
  buildRecord({ parentTool: T, id: `${T}.set_blend_in`, action: 'set_blend_in', family: F,
    summary: 'Set montage blend-in time.', whenToUse: ['Smooth entry needed.'], whenNotToUse: ['Use set_blend_out.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, blendTime: P.blendTime }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_blend_in', assetPath: '/Game/MT_Slash', blendTime: 0.2 } }),
  buildRecord({ parentTool: T, id: `${T}.set_blend_out`, action: 'set_blend_out', family: F,
    summary: 'Set montage blend-out time.', whenToUse: ['Smooth exit needed.'], whenNotToUse: ['Use set_blend_in.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, blendTime: P.blendTime }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_blend_out', assetPath: '/Game/MT_Slash', blendTime: 0.2 } }),
  buildRecord({ parentTool: T, id: `${T}.link_sections`, action: 'link_sections', family: F,
    summary: 'Link two montage sections.', whenToUse: ['Sections must chain.'], whenNotToUse: ['Use add_montage_section.'],
    inputProps: { assetPath: P.assetPath, montagePath: P.assetPath, fromSection: P.fromSection, toSection: P.toSection }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'link_sections', assetPath: '/Game/MT_Slash', fromSection: 'Start', toSection: 'Hit' },
    exampleOutput: { success: true, message: 'Sections linked' } }),
  buildRecord({ parentTool: T, id: `${T}.add_notify`, action: 'add_notify', family: F,
    summary: 'Add a frame notify to a sequence (authoring).', whenToUse: ['Frame event in a sequence.'], whenNotToUse: ['Use add_montage_notify.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, notifyClass: A.notifyClass, notifyName: P.notifyName, frame: P.frame }, required: [],
    requiredOneOf: ['notifyClass', 'notifyName'], effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_notify', assetPath: '/Game/A_Run', notifyName: 'Step', frame: 10 } }),
];
