/**
 * Animation/Physics authoring records — part 1 of 3 (creation, blend, state).
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { ANY_EDITOR_STATE } from '../../core/builder.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';
import { bool, num, str, vec3 } from '../../shared/schema-props.js';

const T = 'animation_physics';
const F = 'animation';
const W = ['An animation asset or graph must be authored.'];
const ESU = ['EditorScriptingUtilities'];
const CR_ESU = ['ControlRig', 'EditorScriptingUtilities'];
// The transition settings add_transition applies to what it creates and set_transition_rules edits.
const TRANSITION_SETTINGS = { blendTime: P.blendTime, crossfadeDuration: A.crossfadeDuration, priorityOrder: A.priorityOrder, automaticRule: A.automaticRule, bidirectional: A.bidirectional, conditionVariable: A.conditionVariable, conditionComparison: A.conditionComparison, conditionValue: A.conditionValue };
const BS_2D_AXES = {
  horizontalAxisName: str('Horizontal axis label (default Direction).'), horizontalMin: num('Horizontal axis minimum (default -180).'), horizontalMax: num('Horizontal axis maximum (default 180).'),
  verticalAxisName: str('Vertical axis label (default Speed).'), verticalMin: num('Vertical axis minimum (default 0).'), verticalMax: num('Vertical axis maximum (default 600).'),
};

export const ANIM_AUTHORED_1: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.create_animation_blueprint`, action: 'create_animation_blueprint', family: F,
    topics: ['anim blueprint', 'abp', 'animation bp', 'anim graph', 'animbp'],
    summary: 'Create an Animation Blueprint asset.', whenToUse: W, whenNotToUse: ['A SkeletalMesh suffices.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: A.meshSkeleton, parentClass: A.abpParentClass, save: A.save },
    required: ['name'], effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: ['assetPath'],
    exampleInput: { action: 'create_animation_blueprint', name: 'ABP_Char', skeletonPath: '/Game/SK_Char', parentClass: 'AnimInstance' }, exampleOutput: { success: true, message: 'Animation Blueprint created', assetPath: '/Game/ABP_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_animation_bp`, action: 'create_animation_bp', family: F,
    summary: 'Alias of create_animation_blueprint (short form).', whenToUse: ['Caller uses the create_animation_bp verb.'], whenNotToUse: ['Use create_animation_blueprint.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: A.meshSkeleton, parentClass: A.abpParentClass, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    exampleInput: { action: 'create_animation_bp', name: 'ABP_Char', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_anim_blueprint`, action: 'create_anim_blueprint', family: F,
    summary: 'Alias of create_animation_blueprint (short form).', whenToUse: ['Caller uses the create_anim_blueprint verb.'], whenNotToUse: ['Use create_animation_blueprint.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: A.meshSkeleton, parentClass: A.abpParentClass, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    exampleInput: { action: 'create_anim_blueprint', name: 'ABP_Char', skeletonPath: '/Game/SK_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_space`, action: 'create_blend_space', family: F,
    summary: 'Create a 2D Blend Space asset.', whenToUse: W, whenNotToUse: ['Use create_blend_space_1d for one axis.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, ...BS_2D_AXES, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_blend_space', name: 'BS_Locomotion', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Blend Space created', assetPath: '/Game/BS_Locomotion' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_space_1d`, action: 'create_blend_space_1d', family: F,
    summary: 'Create a 1D Blend Space asset.', whenToUse: ['A single-axis blend is needed.'], whenNotToUse: ['Use create_blend_space for 2D.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, axisName: str('Axis label (default Speed).'), axisMin: num('Axis minimum (default 0).'), axisMax: num('Axis maximum (default 600).'), save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_blend_space_1d', name: 'BS1D_Speed', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Blend Space 1D created', assetPath: '/Game/BS1D_Speed' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_space_2d`, action: 'create_blend_space_2d', family: F,
    summary: 'Create a 2D Blend Space asset.', whenToUse: ['A two-axis blend is needed.'], whenNotToUse: ['Use create_blend_space_1d for one axis.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, ...BS_2D_AXES, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_blend_space_2d', name: 'BS2D_DirSpeed', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Blend Space 2D created', assetPath: '/Game/BS2D_DirSpeed' } }),
  buildRecord({ parentTool: T, id: `${T}.create_blend_tree`, action: 'create_blend_tree', family: F,
    summary: 'Author a blend tree in an AnimBlueprint AnimGraph: a Blend List (by int) node fed by one Sequence Player per animation, optionally wired to the output pose.', whenToUse: ['Several animations must be switchable through one blend node in an AnimBlueprint.'], whenNotToUse: ['A single add_blend_node suffices.'],
    inputProps: { name: P.name, blueprintPath: P.blueprintPath, treeName: { type: 'string', description: 'Comment/name for the blend node (alias of name).' }, animations: { type: 'array', items: { type: 'string' }, description: 'Animation asset paths; one Sequence Player is created and connected per entry.' }, connectToOutput: { type: 'boolean', description: 'Wire the blend node into the AnimGraph output pose (default true).' } }, required: ['blueprintPath'], requiredOneOf: ['name', 'treeName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_blend_tree', name: 'BT_Move', blueprintPath: '/Game/ABP_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.create_procedural_anim`, action: 'create_procedural_anim', family: F,
    summary: 'Create a procedural anim asset.', whenToUse: ['A runtime-authored animation is needed.'], whenNotToUse: ['Use a static sequence.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, boneTracks: A.boneTracks, numFrames: num('Length in frames (default 30).'), frameRate: P.frameRate, save: A.save }, required: ['name', 'skeletonPath', 'boneTracks'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'create_procedural_anim', name: 'PA_Wave', skeletonPath: '/Game/SK_Char', frameRate: 30 } }),
  buildRecord({ parentTool: T, id: `${T}.create_aim_offset`, action: 'create_aim_offset', family: F,
    summary: 'Create an Aim Offset asset.', whenToUse: ['Aim blending by look direction is needed.'], whenNotToUse: ['Use a blend space.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { assetPath: P.assetPath }, outputRequired: [],
    exampleInput: { action: 'create_aim_offset', name: 'AO_Aim', skeletonPath: '/Game/SK_Char' }, exampleOutput: { success: true, message: 'Aim Offset created', assetPath: '/Game/AO_Aim' } }),
  buildRecord({ parentTool: T, id: `${T}.add_aim_offset_sample`, action: 'add_aim_offset_sample', family: F,
    summary: 'Add a sample pose to an Aim Offset.', whenToUse: ['Aim sample must be added.'], whenNotToUse: ['Use create_aim_offset.'],
    inputProps: { assetPath: P.assetPath, animationPath: P.animationPath, yaw: A.yaw, pitch: A.pitch }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_aim_offset_sample', assetPath: '/Game/AO_Aim', animationPath: '/Game/A_Idle', yaw: 0, pitch: 0 },
    exampleOutput: { success: true, message: 'Aim sample added' } }),
  buildRecord({ parentTool: T, id: `${T}.create_state_machine`, action: 'create_state_machine', family: F,
    summary: 'Create a State Machine graph asset.', whenToUse: ['State-driven animation is needed.'], whenNotToUse: ['A single graph suffices.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, machineName: str('State machine name (default StateMachine).'), states: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { name: { type: 'string' } }, required: ['name'] }, description: 'States to create, as [{ name }].' }, transitions: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { sourceState: { type: 'string' }, targetState: { type: 'string' } }, required: ['sourceState', 'targetState'] }, description: 'Transitions to create between the listed states, as [{ sourceState, targetState }].' } }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { blueprintPath: P.blueprintPath, machineName: P.machineName }, outputRequired: [],
    exampleInput: { action: 'create_state_machine', blueprintPath: '/Game/ABP_Char', machineName: 'SM_Locomotion' }, exampleOutput: { success: true, message: 'State machine created', machineName: 'SM_Locomotion' } }),
  buildRecord({ parentTool: T, id: `${T}.add_state_machine`, action: 'add_state_machine', family: F,
    summary: 'Add a State Machine node to an AnimGraph.', whenToUse: ['A state machine must be embedded.'], whenNotToUse: ['Use create_state_machine.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, machineName: P.machineName, positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { blueprintPath: P.blueprintPath, machineName: P.machineName }, outputRequired: [],
    exampleInput: { action: 'add_state_machine', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco' },
    exampleOutput: { success: true, message: 'State machine node added', machineName: 'SM_Loco' } }),
  buildRecord({ parentTool: T, id: `${T}.add_state`, action: 'add_state', family: F,
    summary: 'Add a state to a State Machine.', whenToUse: ['A new animation state is needed.'], whenNotToUse: ['Use add_transition.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, machineName: { type: 'string', description: 'Alias of stateMachineName. Omitting both matches every state machine in the graph.' }, stateName: P.stateName, animations: { type: 'array', items: { type: 'string' }, description: 'Animation asset paths to play in this state; one Sequence Player is created per entry and the first drives the state Result pose. Without it the state is created empty and the character holds its reference pose.' }, positionX: num('Graph X position of the state (default 200).'), positionY: A.positionY, save: A.save }, required: ['blueprintPath', 'stateName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { blueprintPath: P.blueprintPath, machineName: P.machineName, stateName: P.stateName, animationsApplied: { type: 'array', items: { type: 'object', properties: { animationPath: { type: 'string' }, nodeId: { type: 'string' }, connected: { type: 'boolean' } }, required: ['animationPath', 'nodeId', 'connected'], additionalProperties: false }, description: 'One entry per created Sequence Player. Only the first can be connected to the state Result pose.' }, animationsFailed: { type: 'array', items: { type: 'string' }, description: 'Requested animation paths that could not be loaded.' } }, outputRequired: [],
    exampleInput: { action: 'add_state', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', stateName: 'Idle', animations: ['/Game/Anims/A_Idle'] },
    exampleOutput: { success: true, message: 'State added', stateName: 'Idle' } }),
  buildRecord({ parentTool: T, id: `${T}.add_transition`, action: 'add_transition', family: F,
    summary: 'Add a transition between two states.', whenToUse: ['States must connect.'], whenNotToUse: ['Use add_state.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, fromState: P.fromState, toState: P.toState, ...TRANSITION_SETTINGS, save: A.save }, required: ['blueprintPath', 'fromState', 'toState'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_transition', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', fromState: 'Idle', toState: 'Run' },
    exampleOutput: { success: true, message: 'Transition added' } }),
  buildRecord({ parentTool: T, id: `${T}.set_transition_rules`, action: 'set_transition_rules', family: F,
    summary: 'Set transition rule logic: the condition a transition tests, plus its blend timing.',
    whenToUse: ['Transition condition must change.', 'A state machine must actually be able to leave a state: author the condition here after add_transition.'],
    whenNotToUse: ['Use add_transition.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, fromState: P.fromState, toState: P.toState, ...TRANSITION_SETTINGS, save: A.save }, required: ['blueprintPath', 'fromState', 'toState'],
    outputProps: { condition: { type: 'string', description: 'The rule that was written into the transition graph. Absent means no conditionVariable was given, so the transition stays false and the state is never left.' } },
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_transition_rules', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', fromState: 'Idle', toState: 'Run', conditionVariable: 'Speed', conditionComparison: 'greater', conditionValue: 10 },
    exampleOutput: { success: true, message: 'Transition rules updated', condition: 'Speed greater 10' } }),
  buildRecord({ parentTool: T, id: `${T}.delete_transition`, action: 'delete_transition', family: F,
    summary: 'Delete a transition from a State Machine.',
    whenToUse: ['A transition was authored between the wrong two states.', 'A transition is dead weight and its rule graph should go with it.'],
    whenNotToUse: ['The transition should stay but never fire: use set_transition_rules.', 'The state itself must go, not just the transition.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, stateMachineName: A.stateMachineName, fromState: P.fromState, toState: P.toState, save: A.save }, required: ['blueprintPath', 'fromState', 'toState'],
    outputProps: { deleted: { type: 'boolean', description: 'True when the transition and its rule graph were removed.' } },
    effect: 'write', behavior: { idempotency: 'non-idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU, 
    exampleInput: { action: 'delete_transition', blueprintPath: '/Game/ABP_Char', stateMachineName: 'SM_Loco', fromState: 'Jump', toState: 'Idle' },
    exampleOutput: { success: true, message: 'Transition deleted', deleted: true } }),
  buildRecord({ parentTool: T, id: `${T}.add_blend_node`, action: 'add_blend_node', family: F,
    summary: 'Add a blend node to an AnimGraph.', whenToUse: ['Graph needs a blend node.'], whenNotToUse: ['Use create_blend_tree.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, blendType: { type: 'string', enum: ['TwoWayBlend', 'BlendListByBool', 'BlendListByInt', 'LayeredBoneBlend'], description: 'Blend node type (default TwoWayBlend).' }, nodeName: P.nodeName, positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_blend_node', blueprintPath: '/Game/ABP_Char', blendType: 'TwoWayBlend', nodeName: 'Blend_0' } }),
  buildRecord({ parentTool: T, id: `${T}.add_cached_pose`, action: 'add_cached_pose', family: F,
    summary: 'Add a cached pose node.', whenToUse: ['Pose reuse optimization needed.'], whenNotToUse: ['Inline pose suffices.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, cacheName: P.cacheName, positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath', 'cacheName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_cached_pose', blueprintPath: '/Game/ABP_Char', cacheName: 'LocomotionPose' } }),
  buildRecord({ parentTool: T, id: `${T}.add_slot_node`, action: 'add_slot_node', family: F,
    summary: 'Add an animation slot node.', whenToUse: ['Montage slot must be exposed.'], whenNotToUse: ['Use create_montage.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, slotName: P.slotName, groupName: str('Slot group the slot belongs to (default DefaultGroup).'), positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath', 'slotName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_slot_node', blueprintPath: '/Game/ABP_Char', slotName: 'DefaultSlot' },
    exampleOutput: { success: true, message: 'Slot node added' } }),
  buildRecord({ parentTool: T, id: `${T}.create_control_rig`, action: 'create_control_rig', topics: ['control rig blueprint'], family: F,
    summary: 'Create a Control Rig asset.', whenToUse: ['Procedural rigging/IK needed (ControlRig).'], whenNotToUse: ['Use create_ik_rig.'],
    inputProps: { name: P.name, path: P.path, skeletonPath: P.skeletonPath, skeletalMeshPath: str('Skeletal mesh to build the rig from; wins over skeletonPath.'), modularRig: bool('Create a Modular Rig (UE 5.5+; older engines report modularRig false).'), save: A.save }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: ['ControlRig', 'RigVM', 'EditorScriptingUtilities'],
    exampleInput: { action: 'create_control_rig', name: 'CR_Char', skeletonPath: '/Game/SK_Char' } }),
  // A Control Rig could be created but its graph and hierarchy could not be edited or read.
  buildRecord({ parentTool: T, id: `${T}.edit_control_rig`, action: 'edit_control_rig', family: F,
    topics: ['control rig graph', 'rig unit', 'add rig node', 'connect rig pins', 'wire control rig pins', 'control rig hierarchy', 'add control', 'rig bones'],
    summary: 'Edit a Control Rig: add a unit node (list_rig_units finds them), connect or disconnect pins, set a pin value, remove a node, import the skeleton\'s bones, add a bone, null or control, or remove an element; one edit or many steps, then one compile and save. The reply lists what each edit made (a new node with its pins).',
    whenToUse: ['A Control Rig needs its logic built: units such as Get Transform, Two Bone IK or Set Transform wired from the Forwards Solve event (a new rig may have none: add_unit BeginExecution adds it).', 'A rig needs bones from its skeleton, or controls and nulls to drive them.'],
    whenNotToUse: ['The rig asset does not exist yet (use create_control_rig).', 'Only reading the rig (use get_control_rig).', 'An IK Rig or retargeter (use create_ik_rig, setup_ik).'],
    inputProps: {
      assetPath: str('Control Rig asset path, e.g. /Game/Rigs/CR_Arm.'),
      edit: { type: 'string', enum: ['add_unit', 'connect', 'disconnect', 'set_pin', 'remove_node', 'import_bones', 'add_bone', 'add_null', 'add_control', 'remove_element'], description: 'The edit to make (each step of steps names its own).' },
      unit: str('add_unit: the unit, as an object path (/Script/ControlRig.RigUnit_SetTransform), its struct name with or without RigUnit_ (SetTransform), or its display name.'),
      name: str('add_unit: the new node\'s name (default the unit\'s, made unique); add_bone, add_null, add_control, remove_element: the element\'s name.'),
      position: { type: 'array', items: { type: 'number' }, minItems: 2, maxItems: 2, description: 'add_unit: graph position [x, y] (default right of the last node).' },
      from: str('connect, disconnect: the output pin, Node.Pin as get_control_rig lists it; execution runs from the event\'s execute pin to each unit\'s (ExecutePin in UE 5.8).'),
      to: str('connect, disconnect: the input pin, Node.Pin.'),
      pin: str('set_pin: the pin, Node.Pin; a struct member has its own pin (SetTransform.Item.Name, SetTransform.Transform.Translation.X).'),
      value: { type: ['string', 'number', 'boolean'], description: 'set_pin: the value as text (Bone, foot_l), a number, or true/false.' },
      node: str('remove_node: the node\'s name.'),
      skeletonPath: str('import_bones: the skeleton whose bones are imported (default the skeleton of the rig\'s preview mesh).'),
      parent: str('add_bone, add_null, add_control: the parent element\'s name (a bone, null or control); omitted, the top of the hierarchy.'),
      location: vec3('add_bone, add_null, add_control: location [x, y, z] in cm (a control\'s offset), relative to the parent unless global.'),
      rotation: vec3('add_bone, add_null, add_control: rotation [pitch, yaw, roll] in degrees.'),
      scale: vec3('add_bone, add_null, add_control: scale [x, y, z] (default 1).'),
      global: bool('add_bone, add_null: location, rotation and scale are in rig space, not relative to the parent.'),
      controlType: { type: 'string', enum: ['transform', 'float', 'bool', 'position', 'rotator'], description: 'add_control: the value the control drives (default transform).' },
      steps: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Several edits in order, each an object with edit and its own fields as above; the first that fails stops the rest, and those before it stay (failedStep names it).' },
      save: A.save,
    },
    required: ['assetPath'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: CR_ESU,
    exampleInput: { action: 'edit_control_rig', assetPath: '/Game/Rigs/CR_Arm', steps: [{ edit: 'add_unit', unit: 'BeginExecution', name: 'ForwardsSolve' }, { edit: 'add_unit', unit: 'SetTransform', name: 'SetHand' }, { edit: 'set_pin', pin: 'SetHand.Item.Name', value: 'hand_r' }, { edit: 'connect', from: 'ForwardsSolve.ExecutePin', to: 'SetHand.ExecutePin' }] },
    exampleOutput: { success: true, message: 'Applied 4 edit(s) to CR_Arm.', assetPath: '/Game/Rigs/CR_Arm.CR_Arm', applied: 4, compiled: true, saved: true,
      made: [{ node: 'SetHand', unit: '/Script/ControlRig.RigUnit_SetTransform', pins: [{ pin: 'SetHand.Item', direction: 'Input', type: 'FRigElementKey' }] }, { pin: 'SetHand.Item.Name', value: 'hand_r' }] },
    outputProps: {
      assetPath: str('The rig edited.'),
      applied: num('Edits applied.'),
      made: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'What the edits made: {node, unit, pins} for an added unit, {pin, value} for a set pin (the value as stored), {element} for an added element, {importedFrom, bones} for a skeleton\'s bones imported (bones the rig already had are matched in place).' },
      compiled: bool('Whether the rig compiled after the edits.'),
      compileErrors: { type: 'array', items: { type: 'string' }, description: 'The compile errors, when there were any.' },
      saved: bool('Whether the rig was saved.'),
      failedStep: num('steps: the step that failed (0-based); the ones before it were applied, compiled and saved.'),
    },
    outputRequired: ['assetPath', 'applied'] }),
  buildRecord({ parentTool: T, id: `${T}.get_control_rig`, action: 'get_control_rig', family: F,
    topics: ['read control rig', 'control rig nodes', 'rig pins', 'rig hierarchy'],
    summary: 'Read a Control Rig: each node of its graph with its unit and pins (path, direction, type, default, linked), the links between pins, its hierarchy (bones, nulls, controls with their parents) and whether it compiled; node names one node with every struct member pin.',
    whenToUse: ['Before editing a rig: the exact pin paths connect and set_pin take, and what is already wired.', 'To check a rig after edits: links, hierarchy, compile state.'],
    whenNotToUse: ['Finding a unit to add (use list_rig_units).'],
    inputProps: {
      assetPath: str('Control Rig asset path, e.g. /Game/Rigs/CR_Arm.'),
      node: str('One node\'s name: only that node, with every struct member pin by its full path.'),
    },
    required: ['assetPath'],
    effect: 'read', editorStates: ANY_EDITOR_STATE, latency: 'instant', resources: 'low', plugins: CR_ESU,
    exampleInput: { action: 'get_control_rig', assetPath: '/Game/Rigs/CR_Arm' },
    exampleOutput: { success: true, message: 'CR_Arm: 2 node(s), 1 link(s), 3 hierarchy element(s).', assetPath: '/Game/Rigs/CR_Arm.CR_Arm',
      nodes: [{ name: 'ForwardsSolve', title: 'Forwards Solve', unit: '/Script/ControlRig.RigUnit_BeginExecution', position: [0, 0], pins: [{ pin: 'ForwardsSolve.ExecutePin', direction: 'Output', type: 'FRigVMExecuteContext', linked: true }] }],
      links: [{ from: 'ForwardsSolve.ExecutePin', to: 'SetHand.ExecutePin' }], elements: [{ type: 'Bone', name: 'root' }, { type: 'Bone', name: 'hand_r', parent: 'root' }], elementCount: 3, compiled: true },
    outputProps: {
      assetPath: str('The rig read.'),
      nodes: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Each node: name, title, unit (struct path), position [x, y] and pins [{pin, direction, type, default, linked}].' },
      links: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Each link: from (output pin) and to (input pin).' },
      elements: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Hierarchy elements in order (up to 500): type (Bone, Null, Control, Curve ...), name and parent.' },
      elementCount: num('All hierarchy elements.'),
      compiled: bool('Whether the rig is compiled and up to date.'),
      nodeNames: { type: 'array', items: { type: 'string' }, description: 'With a node that is not there: the nodes there are.' },
    },
    outputRequired: ['assetPath', 'nodes'] }),
  buildRecord({ parentTool: T, id: `${T}.list_rig_units`, action: 'list_rig_units', family: F,
    topics: ['rig units', 'find rig unit', 'control rig node types'],
    summary: 'Find the units a Control Rig graph can hold (Get Transform, Two Bone IK, Aim, math and more): each unit\'s object path, name and category, for edit_control_rig add_unit.',
    whenToUse: ['A unit is needed for add_unit and its name is not known.'],
    whenNotToUse: ['Reading what a rig already holds (use get_control_rig).'],
    inputProps: {
      query: str('Words to match in the unit\'s name, display name, category or keywords (spaces ignored), e.g. two bone, aim, set transform.'),
      limit: num('Most units to list (default 50, up to 500); matched counts them all.'),
    },
    required: [],
    effect: 'read', editorStates: ANY_EDITOR_STATE, latency: 'instant', resources: 'low', plugins: CR_ESU,
    exampleInput: { action: 'list_rig_units', query: 'two bone' },
    exampleOutput: { success: true, message: '2 rig unit(s) match.', matched: 2, units: [{ unit: '/Script/ControlRig.RigUnit_TwoBoneIKSimplePerItem', name: 'Basic IK', category: 'Hierarchy' }] },
    outputProps: {
      units: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Matching units sorted by struct name: unit (the object path add_unit takes), name and category.' },
      matched: num('Units that match.'),
    },
    outputRequired: ['units', 'matched'] }),
];
