/**
 * Animation/Physics authoring records — part 3 of 3 (ragdoll, vehicle,
 * physics simulation, blend-space ops, retarget, graph values, cleanup).
 *
 * RAGDOLL: setup_ragdoll and activate_ragdoll both reach the native
 * HandleSetupRagdoll (Animation/Physics/...SetupRagdoll.cpp), which calls
 * SetSimulatePhysics / SetAllBodiesSimulatePhysics on the actor's
 * USkeletalMeshComponent -- a genuine runtime ragdoll, not asset authoring.
 * setup also assigns physicsAssetPath; activate:false switches it back off.
 * The records therefore use PIE/simulate states.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';

const T = 'animation_physics';
const F = 'physics';
const ESU = ['EditorScriptingUtilities'];
const IK = ['ControlRig', 'IKRig', 'EditorScriptingUtilities'];

export const ANIM_AUTHORED_3: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.play_montage`, action: 'play_montage', family: F,
    topics: ['play animation', 'play anim', 'trigger montage'],
    summary: 'Play a montage on a runtime actor (PIE).', whenToUse: ['A montage must play on a live actor.'], whenNotToUse: ['Author the montage asset.'],
    inputProps: { actorName: P.actorName, montagePath: P.assetPath, playRate: P.playRate }, required: ['actorName', 'montagePath'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU,
    exampleInput: { action: 'play_montage', actorName: 'Char_1', montagePath: '/Game/MT_Slash', playRate: 1.25 } }),
  buildRecord({ parentTool: T, id: `${T}.setup_ragdoll`, action: 'setup_ragdoll', family: F,
    summary: 'Enable runtime ragdoll physics on a skeletal actor; requires an assigned PhysicsAsset and an editor build.',
    whenToUse: ['A skeletal actor must enter ragdoll simulation at runtime (editor build).'], whenNotToUse: ['Author the PhysicsAsset (use create_physics_asset).'],
    inputProps: { actorName: P.actorName, skeletalMeshPath: P.skeletalMeshPath, physicsAssetPath: { type: 'string', description: 'Physics asset to assign before simulating; the mesh default is used when omitted.' } }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent', longRunning: false },
    latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { ragdollActive: P.bool_, hasPhysicsAsset: P.bool_ }, outputRequired: ['ragdollActive'],
    exampleInput: { action: 'setup_ragdoll', actorName: 'Char_1' }, exampleOutput: { success: true, message: 'Ragdoll setup completed', ragdollActive: true, hasPhysicsAsset: true } }),
  buildRecord({ parentTool: T, id: `${T}.activate_ragdoll`, action: 'activate_ragdoll', family: F,
    summary: 'Switch ragdoll simulation on/off at runtime on a skeletal actor via the distinct native activate_ragdoll action (editor build).',
    whenToUse: ['Ragdoll must be switched on/off at runtime (editor build).'], whenNotToUse: ['Use setup_ragdoll for initial enable/physics asset assignment.'],
    inputProps: { actorName: P.actorName, activate: P.activate }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent', longRunning: false },
    latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { ragdollActive: P.bool_, hasPhysicsAsset: P.bool_ }, outputRequired: ['ragdollActive'],
    exampleInput: { action: 'activate_ragdoll', actorName: 'Char_1', activate: true }, exampleOutput: { success: true, message: 'Ragdoll activation state changed', ragdollActive: true, hasPhysicsAsset: true } }),
  buildRecord({ parentTool: T, id: `${T}.configure_vehicle`, action: 'configure_vehicle', family: F,
    summary: 'Configure vehicle movement on a skeletal actor.', whenToUse: ['A vehicle must be set up (ChaosVehicles).'], whenNotToUse: ['Use configure_physics_simulation.'],
    inputProps: { actorName: P.actorName, vehicleType: P.vehicleType, mass: P.mass, dragCoefficient: P.dragCoefficient }, required: ['actorName'],
    effect: 'write', editorStates: ['edit'], latency: 'interactive', resources: 'medium', plugins: ['ChaosVehiclesPlugin', 'EditorScriptingUtilities'],
    exampleInput: { action: 'configure_vehicle', actorName: 'Car_1', vehicleType: 'WheeledVehicle4W', dragCoefficient: 0.32 } }),
  buildRecord({ parentTool: T, id: `${T}.setup_physics_simulation`, action: 'setup_physics_simulation', family: F,
    summary: 'Generate and assign a Physics Asset so a skeletal mesh can simulate.', whenToUse: ['A skeletal mesh must simulate physics.'], whenNotToUse: ['Use configure_vehicle.'],
    inputProps: { actorName: P.actorName, skeletonPath: P.skeletonPath, skeletalMeshPath: P.skeletalMeshPath, savePath: A.savePath, physicsAssetName: A.physicsAssetName, assignToMesh: A.assignToMesh }, required: [],
    effect: 'write', editorStates: ['edit', 'pie'], behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, outputProps: { existingAsset: P.bool_, meshPath: P.meshPath }, outputRequired: [],
    exampleInput: { action: 'setup_physics_simulation', skeletalMeshPath: '/Game/SKM_Char', savePath: '/Game/Physics', physicsAssetName: 'PHYS_Char', assignToMesh: false },
    exampleOutput: { success: true, message: 'Physics simulation set', existingAsset: false } }),
  buildRecord({ parentTool: T, id: `${T}.add_blend_sample`, action: 'add_blend_sample', family: F,
    summary: 'Add a blend sample to a Blend Space.', whenToUse: ['Blend sample needed.'], whenNotToUse: ['Use create_blend_space.'],
    inputProps: { assetPath: P.assetPath, sampleValue: P.sampleValue, animationPath: P.animationPath }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_blend_sample', assetPath: '/Game/BS_Locomotion', animationPath: '/Game/A_Run', sampleValue: 100 } }),
  buildRecord({ parentTool: T, id: `${T}.force_rebuild_blend_space`, action: 'force_rebuild_blend_space', family: F,
    summary: 'Force a Blend Space rebuild and recompile referencers.', whenToUse: ['Axis bounds changed and dependents must recompile.'], whenNotToUse: ['Normal save suffices.'],
    inputProps: { assetPath: P.assetPath, compileReferencers: P.compileReferencers, rebuildBlendParameters: P.rebuildBlendParameters, save: P.save }, required: ['assetPath'],
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'medium', plugins: ESU,
    outputProps: { rebuiltBlendParameters: P.bool_, referencersCompiled: P.num_, compiledAnimBlueprints: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'force_rebuild_blend_space', assetPath: '/Game/BS_Locomotion', compileReferencers: true, rebuildBlendParameters: true },
    exampleOutput: { success: true, message: 'Blend space rebuilt', referencersCompiled: 3 } }),
  buildRecord({ parentTool: T, id: `${T}.set_axis_settings`, action: 'set_axis_settings', family: F,
    summary: 'Set Blend Space axis settings.', whenToUse: ['Axis labels/ranges must change.'], whenNotToUse: ['Use add_blend_sample.'],
    inputProps: { assetPath: P.assetPath, axis: A.axis, axisName: P.axisName, minValue: P.minValue, maxValue: P.maxValue }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_axis_settings', assetPath: '/Game/BS_Locomotion', axis: 'X', axisName: 'Speed', minValue: 0, maxValue: 600 } }),
  buildRecord({ parentTool: T, id: `${T}.set_interpolation_settings`, action: 'set_interpolation_settings', family: F,
    summary: 'Set Blend Space interpolation settings.', whenToUse: ['Interpolation must change.'], whenNotToUse: ['Use set_axis_settings.'],
    inputProps: { assetPath: P.assetPath, interpolationType: P.interpolationType }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_interpolation_settings', assetPath: '/Game/BS_Locomotion', interpolationType: 'Lerp' } }),
  buildRecord({ parentTool: T, id: `${T}.setup_retargeting`, action: 'setup_retargeting', family: F,
    summary: 'Retarget animation onto another skeleton through an IK Retargeter, baking new AnimSequences.', whenToUse: ['Cross-skeleton retarget needed.', 'Mocap or marketplace clips must play on a different rig.'], whenNotToUse: ['Use create_ik_retargeter to build the retargeter asset without baking.'],
    inputProps: { sourceSkeleton: P.skeletonPath, targetSkeleton: P.skeletonPath, assets: A.assets, savePath: A.savePath, suffix: A.suffix, overwrite: P.overwrite, sourceMesh: { type: 'string', description: 'SkeletalMesh giving the source proportions. Defaults to the skeleton preview mesh, then any mesh in the project built on it.' }, targetMesh: { type: 'string', description: 'SkeletalMesh to retarget onto. Defaults the same way as sourceMesh.' }, retargeterPath: { type: 'string', description: 'An existing IK Retargeter to bake through. Omit to auto-build one by characterizing both skeletons and mapping their chains.' } }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: IK,
    exampleInput: { action: 'setup_retargeting', sourceSkeleton: '/Game/SK_A', targetSkeleton: '/Game/SK_B', assets: ['/Game/A_Run'], savePath: '/Game/Retargeted', suffix: '_Retargeted', overwrite: true },
    exampleOutput: { success: true, message: 'Retargeting completed' } }),
  buildRecord({ parentTool: T, id: `${T}.skin_mesh_to_skeleton`, action: 'skin_mesh_to_skeleton', family: F,
    summary: 'Skin a static mesh to a skeleton so it deforms with the animation, producing a SkeletalMesh.', whenToUse: ['Clothing, armour or a prop must move with the body instead of holding its shape.', 'A garment downloaded as a static mesh needs to be worn.'], whenNotToUse: ['The mesh is already a SkeletalMesh on the right skeleton.'],
    inputProps: { staticMeshPath: { type: 'string', description: 'StaticMesh to skin, e.g. a coat downloaded as a rigid mesh.' }, skeletalMeshPath: { type: 'string', description: 'SkeletalMesh whose geometry to re-skin, for a dressed character whose own rig will not retarget. Its materials carry over. Use instead of staticMeshPath.' }, skeletonPath: P.skeletonPath, outputPath: { type: 'string', description: 'Canonical /Game path for the SkeletalMesh this writes.' },
      sourceSkeletalMesh: { type: 'string', description: 'An already-skinned mesh on the same skeleton to copy weights from, such as the body the garment is worn over. Beats computing weights fresh wherever the garment hugs the body. Falls back to smooth binding when omitted.' }, save: P.save }, required: ['skeletonPath', 'outputPath'], requiredOneOf: ['staticMeshPath', 'skeletalMeshPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'medium', plugins: ESU, 
    outputProps: { assetPath: P.assetPath, weights: { type: 'string', description: "Which binding ran: 'transferred' from sourceSkeletalMesh, or 'smooth'." } }, outputRequired: [],
    exampleInput: { action: 'skin_mesh_to_skeleton', staticMeshPath: '/Game/Fab/coat', skeletonPath: '/Game/Chars/SK_Hero_Skeleton', outputPath: '/Game/Chars/SKM_Coat', sourceSkeletalMesh: '/Game/Chars/SKM_Hero' },
    exampleOutput: { success: true, message: 'Mesh skinned to skeleton' } }),
  buildRecord({ parentTool: T, id: `${T}.add_layered_blend_per_bone`, action: 'add_layered_blend_per_bone', family: F,
    summary: 'Add a per-bone layered blend node.', whenToUse: ['Partial-skeleton layering needed.'], whenNotToUse: ['Use add_blend_node.'],
    inputProps: { assetPath: P.assetPath, blueprintPath: P.blueprintPath, layerSetup: A.layerSetup }, required: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_layered_blend_per_bone', blueprintPath: '/Game/ABP_Char', layerSetup: [{ branchFilters: [{ boneName: 'spine_01', blendDepth: 1 }] }] } }),
  buildRecord({ parentTool: T, id: `${T}.set_anim_graph_node_value`, action: 'set_anim_graph_node_value', family: F,
    summary: 'Set a value on an AnimGraph node.', whenToUse: ['A graph node property must change.'], whenNotToUse: ['Use add_blend_node.'],
    inputProps: { assetPath: P.assetPath, blueprintPath: P.blueprintPath, nodeName: P.nodeName, propertyName: P.propertyName, value: P.value }, required: ['nodeName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_anim_graph_node_value', blueprintPath: '/Game/ABP_Char', nodeName: 'Blend', propertyName: 'NodeComment', value: 'Updated' } }),
  buildRecord({ parentTool: T, id: `${T}.get_animation_info`, action: 'get_animation_info', family: F,
    summary: 'Read animation asset metadata.', whenToUse: ['Inspect animation assets.'], whenNotToUse: ['Mutate assets.'],
    inputProps: { assetPath: P.assetPath }, required: ['assetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: ESU,
    outputProps: { length: P.num_, frameRate: P.num_ }, outputRequired: [],
    exampleInput: { action: 'get_animation_info', assetPath: '/Game/A_Run' }, exampleOutput: { success: true, message: 'Animation info', length: 1.0, frameRate: 30 } }),
  buildRecord({ parentTool: T, id: `${T}.cleanup`, action: 'cleanup', family: F,
    summary: 'Delete the listed transient animation authoring assets.', whenToUse: ['Reset authoring session.'], whenNotToUse: ['Persist work.'],
    inputProps: { artifacts: A.artifacts }, required: ['artifacts'],
    effect: 'destructive', behavior: { safeToRetry: true }, latency: 'instant', resources: 'low',
    plugins: ESU, exampleInput: { action: 'cleanup', artifacts: ['/Game/MCPTest/ABP_Temp'] } }),
];
