/**
 * Animation/Physics authoring records — part 3 of 3 (ragdoll, vehicle,
 * physics simulation, blend-space ops, retarget, graph values, cleanup).
 *
 * RAGDOLL: setup_ragdoll and activate_ragdoll both reach the native
 * HandleSetupRagdoll (Animation/Physics/...SetupRagdoll.cpp), which calls
 * SetSimulatePhysics / SetAllBodiesSimulatePhysics on the actor's
 * USkeletalMeshComponent -- a genuine runtime ragdoll, not asset authoring.
 * setup also assigns physicsAssetPath; activate:false switches it back off.
 * The records therefore use PIE/simulate states.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';
import { num, str } from '../../shared/schema-props.js';

const T = 'animation_physics';
const F = 'physics';
const ESU = ['EditorScriptingUtilities'];
const IK = ['ControlRig', 'IKRig', 'EditorScriptingUtilities'];

export const ANIM_AUTHORED_3: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.play_montage`, action: 'play_montage', family: F,
    topics: ['play animation', 'play anim', 'trigger montage'],
    summary: 'Play a montage on a runtime actor (PIE).', whenToUse: ['A montage must play on a live actor.'], whenNotToUse: ['Author the montage asset.'],
    inputProps: { actorName: P.actorName, montagePath: P.assetPath, playRate: P.playRate }, required: ['actorName', 'montagePath'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU,
    exampleInput: { action: 'play_montage', actorName: 'Char_1', montagePath: '/Game/MT_Slash', playRate: 1.25 } }),
  buildRecord({ parentTool: T, id: `${T}.setup_ragdoll`, action: 'setup_ragdoll', family: F,
    summary: 'Enable runtime ragdoll physics on a skeletal actor; requires an assigned PhysicsAsset and an editor build.',
    whenToUse: ['A skeletal actor must enter ragdoll simulation at runtime (editor build).'], whenNotToUse: ['Author the PhysicsAsset (use create_physics_asset).'],
    inputProps: { actorName: P.actorName, physicsAssetPath: { type: 'string', description: 'Physics asset to assign before simulating; the mesh default is used when omitted.' } }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent', longRunning: false },
    latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { ragdollActive: P.bool_, hasPhysicsAsset: P.bool_ }, outputRequired: ['ragdollActive'],
    exampleInput: { action: 'setup_ragdoll', actorName: 'Char_1' }, exampleOutput: { success: true, message: 'Ragdoll setup completed', ragdollActive: true, hasPhysicsAsset: true } }),
  buildRecord({ parentTool: T, id: `${T}.activate_ragdoll`, action: 'activate_ragdoll', family: F,
    summary: 'Switch ragdoll simulation on/off at runtime on a skeletal actor via the distinct native activate_ragdoll action (editor build).',
    whenToUse: ['Ragdoll must be switched on/off at runtime (editor build).'], whenNotToUse: ['Use setup_ragdoll for initial enable/physics asset assignment.'],
    inputProps: { actorName: P.actorName, activate: P.activate }, required: ['actorName'],
    effect: 'write', editorStates: ['pie', 'simulate'], behavior: { idempotency: 'idempotent', longRunning: false },
    latency: 'interactive', resources: 'low', plugins: ESU,
    outputProps: { ragdollActive: P.bool_, hasPhysicsAsset: P.bool_ }, outputRequired: ['ragdollActive'],
    exampleInput: { action: 'activate_ragdoll', actorName: 'Char_1', activate: true }, exampleOutput: { success: true, message: 'Ragdoll activation state changed', ragdollActive: true, hasPhysicsAsset: true } }),
  buildRecord({ parentTool: T, id: `${T}.configure_vehicle`, action: 'configure_vehicle', topics: ['set up vehicle'], family: F,
    summary: 'Configure vehicle movement on a skeletal actor.', whenToUse: ['A vehicle must be set up (ChaosVehicles).'], whenNotToUse: ['Use configure_physics_simulation.'],
    inputProps: { actorName: P.actorName, vehicleType: { type: 'string', enum: ['WheeledVehicle4W', 'WheeledVehicle'], description: 'Vehicle movement to set up; only a wheeled vehicle is supported (default WheeledVehicle4W).' }, mass: P.mass, dragCoefficient: P.dragCoefficient,
      wheels: { type: 'array', items: { type: 'object', additionalProperties: false, properties: { boneName: { type: 'string' }, offset: { type: 'object', additionalProperties: false, properties: { x: { type: 'number' }, y: { type: 'number' }, z: { type: 'number' } } }, radius: { type: 'number' }, width: { type: 'number' }, friction: { type: 'number' } } }, description: 'Wheel setups, replacing the existing ones: [{ boneName, offset {x,y,z}, radius, width, friction }].' },
      engine: { type: 'object', additionalProperties: false, properties: { maxRPM: { type: 'number' }, maxTorque: { type: 'number' }, gears: { type: 'number' } }, description: 'Engine settings: maxRPM, maxTorque, gears (forward gear count).' },
      transmission: { type: 'object', additionalProperties: false, properties: { finalDrive: { type: 'number' }, finalDriveRatio: { type: 'number' }, gearRatios: { type: 'array', items: { type: 'number' } } }, description: 'Transmission settings: finalDrive and forward gearRatios.' } }, required: ['actorName'],
    effect: 'write', editorStates: ['edit'], latency: 'interactive', resources: 'medium', plugins: ['ChaosVehiclesPlugin', 'EditorScriptingUtilities'],
    exampleInput: { action: 'configure_vehicle', actorName: 'Car_1', vehicleType: 'WheeledVehicle4W', dragCoefficient: 0.32 } }),
  buildRecord({ parentTool: T, id: `${T}.setup_physics_simulation`, action: 'setup_physics_simulation', topics: ['simulate physics', 'enable skeletal mesh physics'], family: F,
    summary: 'Generate and assign a Physics Asset so a skeletal mesh can simulate.', whenToUse: ['A skeletal mesh must simulate physics.'], whenNotToUse: ['Use configure_vehicle.'],
    inputProps: { actorName: P.actorName, skeletonPath: P.skeletonPath, skeletalMeshPath: P.skeletalMeshPath, savePath: A.savePath, physicsAssetName: A.physicsAssetName, assignToMesh: A.assignToMesh }, required: [],
    effect: 'write', editorStates: ['edit', 'pie'], behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, outputProps: { existingAsset: P.bool_, meshPath: P.meshPath }, outputRequired: [],
    exampleInput: { action: 'setup_physics_simulation', skeletalMeshPath: '/Game/SKM_Char', savePath: '/Game/Physics', physicsAssetName: 'PHYS_Char', assignToMesh: false },
    exampleOutput: { success: true, message: 'Physics simulation set', existingAsset: false } }),
  buildRecord({ parentTool: T, id: `${T}.add_blend_sample`, action: 'add_blend_sample', family: F,
    summary: 'Add a blend sample to a Blend Space.', whenToUse: ['Blend sample needed.'], whenNotToUse: ['Use create_blend_space.'],
    inputProps: { assetPath: P.assetPath, sampleValue: { description: 'Sample position: a number on a 1D blend space, or {x, y} (or [x, y]) on a 2D one.' }, animationPath: str('Sequence to place at sampleValue.'), save: A.save }, required: ['assetPath', 'animationPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_blend_sample', assetPath: '/Game/BS_Locomotion', animationPath: '/Game/A_Run', sampleValue: 100 } }),
  buildRecord({ parentTool: T, id: `${T}.force_rebuild_blend_space`, action: 'force_rebuild_blend_space', family: F,
    summary: 'Force a Blend Space rebuild and recompile referencers.', whenToUse: ['Axis bounds changed and dependents must recompile.'], whenNotToUse: ['Normal save suffices.'],
    inputProps: { assetPath: P.assetPath, compileReferencers: P.compileReferencers, rebuildBlendParameters: P.rebuildBlendParameters, save: A.save }, required: ['assetPath'],
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'medium', plugins: ESU,
    outputProps: { rebuiltBlendParameters: P.bool_, referencersCompiled: P.num_, compiledAnimBlueprints: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'force_rebuild_blend_space', assetPath: '/Game/BS_Locomotion', compileReferencers: true, rebuildBlendParameters: true },
    exampleOutput: { success: true, message: 'Blend space rebuilt', referencersCompiled: 3 } }),
  buildRecord({ parentTool: T, id: `${T}.set_axis_settings`, action: 'set_axis_settings', family: F,
    summary: 'Set Blend Space axis settings.', whenToUse: ['Axis labels/ranges must change.'], whenNotToUse: ['Use add_blend_sample.'],
    inputProps: { assetPath: P.assetPath, axis: str('Axis to change: X or Horizontal (default), Y or Vertical.'), axisName: P.axisName, minValue: P.minValue, maxValue: P.maxValue, gridDivisions: num('Number of grid divisions on the axis.'), save: A.save }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_axis_settings', assetPath: '/Game/BS_Locomotion', axis: 'X', axisName: 'Speed', minValue: 0, maxValue: 600 } }),
  buildRecord({ parentTool: T, id: `${T}.set_interpolation_settings`, action: 'set_interpolation_settings', family: F,
    summary: 'Set Blend Space input smoothing and sample weight speed; only the fields sent change.', whenToUse: ['Interpolation must change.'], whenNotToUse: ['Use set_axis_settings.'],
    inputProps: { assetPath: P.assetPath, interpolationType: { type: 'string', enum: ['Average', 'Linear', 'Cubic', 'EaseInOut', 'ExponentialDecay', 'SpringDamper'], description: 'Input smoothing type for every axis; it only acts while interpolationTime is above 0.' }, interpolationTime: num('Input smoothing time in seconds for every axis (0 turns smoothing off).'), targetWeightInterpolationSpeed: num('Sample weight speed per second (0 turns weight smoothing off).'), save: A.save }, required: ['assetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_interpolation_settings', assetPath: '/Game/BS_Locomotion', interpolationType: 'SpringDamper', interpolationTime: 0.2 } }),
  buildRecord({ parentTool: T, id: `${T}.setup_retargeting`, action: 'setup_retargeting', topics: ['retarget to mannequin', 'bake retargeted animations', 'copy animation between characters'], family: F,
    summary: 'Retarget animation onto another skeleton through an IK Retargeter, baking new AnimSequences.', whenToUse: ['Cross-skeleton retarget needed.', 'Mocap or marketplace clips must play on a different rig.'], whenNotToUse: ['Use create_ik_retargeter to build the retargeter asset without baking.'],
    inputProps: { sourceSkeleton: P.skeletonPath, targetSkeleton: P.skeletonPath, assets: A.assets, savePath: A.savePath, suffix: A.suffix, overwrite: P.overwrite, sourceMesh: { type: 'string', description: 'SkeletalMesh giving the source proportions. Defaults to the skeleton preview mesh, then any mesh in the project built on it.' }, targetMesh: { type: 'string', description: 'SkeletalMesh to retarget onto. Defaults the same way as sourceMesh.' }, retargeterPath: { type: 'string', description: 'An existing IK Retargeter to bake through. Omit to auto-build one by characterizing both skeletons and mapping their chains.' } }, required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: IK,
    exampleInput: { action: 'setup_retargeting', sourceSkeleton: '/Game/SK_A', targetSkeleton: '/Game/SK_B', assets: ['/Game/A_Run'], savePath: '/Game/Retargeted', suffix: '_Retargeted', overwrite: true },
    exampleOutput: { success: true, message: 'Retargeting completed' } }),
  buildRecord({ parentTool: T, id: `${T}.skin_mesh_to_skeleton`, action: 'skin_mesh_to_skeleton', topics: ['rig static mesh', 'bind mesh to skeleton'], family: F,
    summary: 'Skin a static mesh to a skeleton so it deforms with the animation, producing a SkeletalMesh.', whenToUse: ['Clothing, armour or a prop must move with the body instead of holding its shape.', 'A garment downloaded as a static mesh needs to be worn.'], whenNotToUse: ['The mesh is already a SkeletalMesh on the right skeleton.'],
    inputProps: { staticMeshPath: { type: 'string', description: 'StaticMesh to skin, e.g. a coat downloaded as a rigid mesh.' }, skeletalMeshPath: { type: 'string', description: 'SkeletalMesh whose geometry to re-skin, for a dressed character whose own rig will not retarget. Its materials carry over. Use instead of staticMeshPath.' }, skeletonPath: P.skeletonPath, outputPath: { type: 'string', description: 'Canonical /Game path for the SkeletalMesh this writes.' },
      sourceSkeletalMesh: { type: 'string', description: 'An already-skinned mesh on the same skeleton to copy weights from, such as the body the garment is worn over. Beats computing weights fresh wherever the garment hugs the body. Falls back to smooth binding when omitted.' }, save: A.save }, required: ['skeletonPath', 'outputPath'], requiredOneOf: ['staticMeshPath', 'skeletalMeshPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'medium', plugins: ESU, 
    outputProps: { assetPath: P.assetPath, weights: { type: 'string', description: "Which binding ran: 'transferred' from sourceSkeletalMesh, or 'smooth'." } }, outputRequired: [],
    exampleInput: { action: 'skin_mesh_to_skeleton', staticMeshPath: '/Game/Fab/coat', skeletonPath: '/Game/Chars/SK_Hero_Skeleton', outputPath: '/Game/Chars/SKM_Coat', sourceSkeletalMesh: '/Game/Chars/SKM_Hero' },
    exampleOutput: { success: true, message: 'Mesh skinned to skeleton' } }),
  buildRecord({ parentTool: T, id: `${T}.add_layered_blend_per_bone`, action: 'add_layered_blend_per_bone', family: F,
    summary: 'Add a Layered Blend Per Bone node with its branch filters.', whenToUse: ['Partial-skeleton layering needed.'], whenNotToUse: ['Use add_blend_node.'],
    inputProps: { blueprintPath: A.graphBlueprintPath, layerSetup: A.layerSetup, boneName: str('Shorthand for one layer filtering this bone and its children; ignored when layerSetup is sent.'), positionX: A.positionX, positionY: A.positionY, save: A.save }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_layered_blend_per_bone', blueprintPath: '/Game/ABP_Char', layerSetup: [{ branchFilters: [{ boneName: 'spine_01', blendDepth: 1 }] }] } }),
  buildRecord({ parentTool: T, id: `${T}.set_anim_graph_node_value`, action: 'set_anim_graph_node_value', family: F,
    summary: 'Set a value on an AnimGraph node: a setting of the node (Alpha, PlayRate, bLoopAnimation, NodeComment), or the animation an asset player plays (Sequence on a Sequence Player, BlendSpace on a Blend Space Player) by its asset path; the reply reads the stored value back.',
    whenToUse: ['A graph node property must change.', 'A Sequence Player or Blend Space Player must play a different animation.'], whenNotToUse: ['Use add_blend_node.'],
    inputProps: {
      blueprintPath: A.graphBlueprintPath,
      nodeName: str('The node: its object name (AnimGraphNode_SequencePlayer_0), its GUID (the nodeId create_node, add_state and inspect_graph report), or a custom name set in its NodeComment or its title when one node has it. Looks in the AnimGraph and in the state machines and states under it; a name that matches nothing answers NODE_NOT_FOUND listing every node (nodes), and one that matches several AMBIGUOUS_NODE listing them (candidates).'),
      nodeId: str('The node GUID; an alternative to nodeName.'),
      propertyName: str('The property: a member of the node\'s settings struct (Alpha, PlayRate, bLoopAnimation, Sequence) or of the graph node (NodeComment), with dots for a nested one (Node.PlayRate). On an asset player the asset property (Sequence, BlendSpace) is written through the node\'s own setter and read back, and fails when the node did not take it; any other property is written by reflection and its stored value read back.'),
      value: { description: 'The value: a number, boolean or string, an {x,y,z} or {r,g,b,a} object for a struct, or for an asset property the asset path (/Game/Anims/A_Idle).' },
      save: A.save,
    },
    required: ['blueprintPath', 'propertyName', 'value'], requiredOneOf: ['nodeName', 'nodeId'],
    outputProps: {
      nodeName: str('Object name of the node that was set.'),
      nodeId: str('GUID of the node that was set.'),
      propertyName: str('Echoes propertyName.'),
      value: str('The value now stored, read back from the node: the asset path for an asset property.'),
    }, outputRequired: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'set_anim_graph_node_value', blueprintPath: '/Game/ABP_Char', nodeName: 'Blend', propertyName: 'NodeComment', value: 'Updated' } }),
  buildRecord({ parentTool: T, id: `${T}.get_animation_info`, action: 'get_animation_info', family: F,
    topics: ['length and frame rate', 'notifies and curves', 'list montage sections', 'blend space axes'],
    summary: 'Read an animation asset: sequence or montage length, frame rate, notifies, curves, root motion and additive flags; montage sections and slots; blend space axes; anim Blueprint skeleton and parent class.',
    whenToUse: ['The length, notifies or curves of an animation sequence or montage must be read.', 'A montage\'s sections and slots, or a blend space\'s axes, must be checked before editing.'], whenNotToUse: ['Mutate assets.'],
    inputProps: { assetPath: P.assetPath }, required: ['assetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: ESU,
    outputProps: { length: P.num_, frameRate: P.num_ }, outputRequired: [],
    exampleInput: { action: 'get_animation_info', assetPath: '/Game/A_Run' }, exampleOutput: { success: true, message: 'Animation info', length: 1.0, frameRate: 30 } }),
  // get_animation_info gave an animation's length, notifies and curves, never how it moves.
  buildRecord({ parentTool: T, id: `${T}.analyze_animation`, action: 'analyze_animation', family: F,
    topics: ['analyze animation', 'foot contacts', 'foot sliding', 'root motion speed', 'loop seam', 'animation pops', 'footstep timing'],
    summary: 'Analyze an Animation Sequence\'s motion from its own frames: how far and fast the root travels and turns, when each foot is planted and how fast a planted foot still moves, how closely the last frame meets the first, and the bones with the sharpest rotation spikes.',
    whenToUse: ['Footstep notifies must go where the feet land (feet[].contacts are the planted intervals in seconds).', 'A walk or run must match the character\'s movement speed: an in-place clip\'s plantedSpeed is the ground speed it implies; a root-motion clip\'s should be near 0.', 'A clip must be checked for a clean loop or for pops before it is used.'],
    whenNotToUse: ['Only the length, notifies or curves are needed (use get_animation_info).', 'A character playing in a running game must be measured (use control_actor get_transform motion).'],
    inputProps: {
      assetPath: str('Animation Sequence asset path, e.g. /Game/Anims/A_Run (a montage or blend space is refused: analyze the sequences it plays).'),
      feet: { type: 'array', items: { type: 'string' }, description: 'Foot bones to check (default every bone whose name holds foot but not ik, e.g. foot_l and foot_r).' },
      contactHeight: num('cm above a foot\'s lowest point that still counts as planted (default 5).'),
      maxSamples: num('Frames sampled, spread evenly with the first and last always in (default 300, at most 2000; a shorter clip samples every frame).'),
    },
    required: ['assetPath'],
    outputProps: {
      length: num('Length in seconds.'), frames: num('Frames (sampled keys) in the sequence.'), frameRate: num('Frames per second.'), samples: num('Frames sampled.'),
      rootMotion: { type: 'object', additionalProperties: false, description: 'The root bone\'s path in component space (in-place clips stay at 0).', properties: {
        enabled: { type: 'boolean', description: 'Whether the sequence has root motion enabled.' },
        displacement: { type: 'array', items: { type: 'number' }, description: 'From the first to the last frame, [x, y, z] in cm.' },
        distance: num('Path length in cm.'), averageSpeed: num('cm/s over the clip.'), peakSpeed: num('Fastest frame-to-frame speed in cm/s.'), turn: num('Yaw change in degrees.') } },
      loop: { type: 'object', additionalProperties: false, description: 'Last frame against the first, every bone but the root in its parent\'s space: near 0 is a clean loop.', properties: {
        positionError: num('Largest bone offset in cm.'), rotationError: num('Largest bone rotation in degrees.'), worstBone: { type: 'string', description: 'The bone with the largest rotation.' } } },
      feet: { type: 'array', description: 'One entry per foot bone.', items: { type: 'object', additionalProperties: false, properties: {
        bone: { type: 'string', description: 'Foot bone.' }, lowest: num('Its lowest height in cm.'),
        contacts: { type: 'array', items: { type: 'array', items: { type: 'number' } }, description: 'Planted intervals as [start, end] in seconds (at most 32).' },
        plantedRatio: num('Share of sampled frames the foot is planted (0-1).'),
        plantedSpeed: num('Average horizontal speed of the planted foot in cm/s: the ground speed an in-place clip implies, or foot slide on a root-motion clip.') } } },
      pops: { type: 'array', description: 'The three bones whose rotation spikes fastest: a pop shows as one far above the rest.', items: { type: 'object', additionalProperties: false, properties: {
        bone: { type: 'string', description: 'Bone.' }, time: num('When, in seconds.'), degreesPerSecond: num('Its rotation speed there.') } } },
    },
    outputRequired: [],
    effect: 'read', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'analyze_animation', assetPath: '/Game/Anims/A_Run' },
    exampleOutput: { success: true, message: 'A_Run: 0.70 s, 22 frames; the root travels 0.0 cm (0.0 cm/s); 2 foot bone(s); loop seam 0.05 cm, 0.4 deg.', length: 0.7, frames: 22, frameRate: 30, samples: 22,
      rootMotion: { enabled: false, displacement: [0, 0, 0], distance: 0, averageSpeed: 0, peakSpeed: 0, turn: 0 },
      loop: { positionError: 0.05, rotationError: 0.4, worstBone: 'hand_r' },
      feet: [{ bone: 'foot_l', lowest: 2.1, contacts: [[0, 0.27]], plantedRatio: 0.41, plantedSpeed: 381.5 }, { bone: 'foot_r', lowest: 2.1, contacts: [[0.33, 0.6]], plantedRatio: 0.41, plantedSpeed: 379.9 }],
      pops: [{ bone: 'foot_l', time: 0.3, degreesPerSecond: 912 }] } }),
  buildRecord({ parentTool: T, id: `${T}.cleanup`, action: 'cleanup', topics: ['clean up test animation assets'], family: F,
    summary: 'Delete the listed transient animation authoring assets.', whenToUse: ['Reset authoring session.'], whenNotToUse: ['Persist work.'],
    inputProps: { artifacts: A.artifacts }, required: ['artifacts'],
    effect: 'destructive', behavior: { safeToRetry: true }, latency: 'instant', resources: 'low',
    plugins: ESU, exampleInput: { action: 'cleanup', artifacts: ['/Game/MCPTest/ABP_Temp'] } }),
];
