/**
 * Skeleton family records (29 actions, SKELETON_ACTIONS spread).
 *
 * Grounded in animation_physics action enum (...SKELETON_ACTIONS) and native
 * HandleManageSkeleton (Plugins/.../Private/Domains/Skeleton/
 * McpAutomationBridge_SkeletonHandlers.cpp). These route through the
 * manage_skeleton bridge tool (skeleton-handlers.ts:155). All 29 are editor
 * authoring mutations on skeleton/physics-asset assets. The 16 hidden native
 * skeleton routes (add_socket, modify_socket, modify_physics_body,
 * set_physics_asset, remove_physics_body, get_physics_asset_info,
 * list_morph_targets, delete_morph_target, delete_socket, remove_socket,
 * get_bone_transform, list_virtual_bones, delete_virtual_bone,
 * set_morph_target_value, set_physics_constraint, preview_physics) are
 * dispositioned separately in ../../hidden-routes.ts, not here.
 */
import type { CapabilityRecordSource } from '../../../index.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { A } from './animation-properties.js';

const T = 'animation_physics';
const F = 'skeleton';
const W = ['A skeleton, bone, socket, physics body or morph target must be authored.'];
const ESU = ['EditorScriptingUtilities'];
const SKEL_BONE_REQUIRED = ['action', 'skeletonPath', 'boneName'];
const MESH_REQUIRED = ['action', 'skeletalMeshPath'];

export const SKELETON_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.create_skeleton`, action: 'create_skeleton', family: F,
    summary: 'Create a new Skeleton asset.', whenToUse: W, whenNotToUse: ['A SkeletalMesh already exists.'],
    inputProps: { action: P.action, name: P.name, path: P.path, rootBoneName: A.rootBoneName, save: P.save }, required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: ESU,
    exampleInput: { action: 'create_skeleton', path: '/Game/SK_Char', rootBoneName: 'Root', save: true }, exampleOutput: { success: true, message: 'Skeleton created' } }),
  buildRecord({ parentTool: T, id: `${T}.add_bone`, action: 'add_bone', family: F,
    summary: 'Add a bone to a skeleton.', whenToUse: W, whenNotToUse: ['Bone already exists.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, boneName: P.boneName, parentBoneName: P.parentBoneName, location: P.location, rotation: P.rotation, scale: A.scale, save: P.save },
    required: SKEL_BONE_REQUIRED, effect: 'write', latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'add_bone', skeletonPath: '/Game/SK_Char', boneName: 'spine_01', parentBoneName: 'Root', location: [10, 0, 0], save: true },
    exampleOutput: { success: true, message: 'Bone added' } }),
  buildRecord({ parentTool: T, id: `${T}.remove_bone`, action: 'remove_bone', family: F,
    summary: 'Remove a bone from a skeleton.', whenToUse: ['A bone must be removed.'], whenNotToUse: ['Keep the bone.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, boneName: P.boneName, removeChildren: A.removeChildren, save: P.save }, required: SKEL_BONE_REQUIRED,
    effect: 'destructive', behavior: { safeToRetry: false, supportsUndo: false }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'remove_bone', skeletonPath: '/Game/SK_Char', boneName: 'tail_01', removeChildren: true, save: true },
    exampleOutput: { success: true, message: 'Bone removed' } }),
  buildRecord({ parentTool: T, id: `${T}.rename_bone`, action: 'rename_bone', family: F,
    summary: 'Rename a bone on a skeleton.', whenToUse: ['A bone needs renaming.'], whenNotToUse: ['Name is correct.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, boneName: P.boneName, newBoneName: P.newBoneName, save: P.save },
    required: SKEL_BONE_REQUIRED, effect: 'write', latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'rename_bone', skeletonPath: '/Game/SK_Char', boneName: 'old', newBoneName: 'new', save: true },
    exampleOutput: { success: true, message: 'Bone renamed' } }),
  buildRecord({ parentTool: T, id: `${T}.set_bone_transform`, action: 'set_bone_transform', family: F,
    summary: 'Set the rest transform of a bone.', whenToUse: ['A bone rest pose must change.'], whenNotToUse: ['Use runtime animation.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, skeletalMeshPath: P.skeletalMeshPath, boneName: P.boneName, location: P.location, rotation: P.rotation, scale: A.scale, save: P.save },
    required: ['action', 'boneName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_bone_transform', skeletalMeshPath: '/Game/SM_Char', boneName: 'spine_01', location: [0, 0, 0], scale: [1, 1, 1] },
    exampleOutput: { success: true, message: 'Bone transform set' } }),
  buildRecord({ parentTool: T, id: `${T}.set_bone_parent`, action: 'set_bone_parent', family: F,
    summary: 'Reparent a bone under a new parent.', whenToUse: ['Bone hierarchy must change.'], whenNotToUse: ['Hierarchy is correct.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, boneName: P.boneName, parentBoneName: P.parentBoneName, save: P.save },
    required: SKEL_BONE_REQUIRED, effect: 'write', latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'set_bone_parent', skeletonPath: '/Game/SK_Char', boneName: 'tail_01', parentBoneName: 'spine_03', save: true },
    exampleOutput: { success: true, message: 'Bone parent set' } }),
  buildRecord({ parentTool: T, id: `${T}.create_virtual_bone`, action: 'create_virtual_bone', family: F,
    summary: 'Create a virtual bone between two bones.', whenToUse: ['A virtual bone is needed for IK.'], whenNotToUse: ['Use a real bone.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, boneName: P.boneName, sourceBoneName: P.sourceBoneName, targetBoneName: P.targetBoneName, save: P.save },
    required: ['action', 'skeletonPath', 'sourceBoneName'], effect: 'write', latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'create_virtual_bone', skeletonPath: '/Game/SK_Char', sourceBoneName: 'hand_l', targetBoneName: 'hand_r', boneName: 'VB_Hands', save: true },
    exampleOutput: { success: true, message: 'Virtual bone created' } }),
  buildRecord({ parentTool: T, id: `${T}.create_socket`, action: 'create_socket', family: F,
    summary: 'Create a socket on a bone.', whenToUse: ['An attach point is needed.'], whenNotToUse: ['Use an existing socket.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, socketName: P.socketName, attachBoneName: A.attachBoneName, relativeLocation: A.relativeLocation, relativeRotation: A.relativeRotation, relativeScale: A.relativeScale, save: P.save },
    required: ['action', 'skeletonPath', 'socketName'], effect: 'write', latency: 'interactive', resources: 'low',
    plugins: ESU, outputProps: { socketName: P.socketName, boneName: P.boneName, skeletonPath: P.skeletonPath }, outputRequired: [],
    exampleInput: { action: 'create_socket', skeletonPath: '/Game/SK_Char', socketName: 'Weapon', attachBoneName: 'hand_r', relativeLocation: [1, 2, 3], save: true },
    exampleOutput: { success: true, message: 'Socket created' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_socket`, action: 'configure_socket', family: F,
    summary: 'Configure an existing socket transform.', whenToUse: ['Socket offset must change.'], whenNotToUse: ['Use create_socket.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, socketName: P.socketName, attachBoneName: A.attachBoneName, relativeLocation: A.relativeLocation, relativeRotation: A.relativeRotation, relativeScale: A.relativeScale, save: P.save },
    required: ['action', 'skeletonPath', 'socketName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, outputProps: { socketName: P.socketName, skeletonPath: P.skeletonPath }, outputRequired: [],
    exampleInput: { action: 'configure_socket', skeletonPath: '/Game/SK_Char', socketName: 'Weapon', relativeLocation: [4, 5, 6], save: true },
    exampleOutput: { success: true, message: 'Socket configured' } }),
  buildRecord({ parentTool: T, id: `${T}.auto_skin_weights`, action: 'auto_skin_weights', family: F,
    summary: 'Auto-generate skin weights for a mesh against the skeleton.', whenToUse: ['A mesh needs skinning.'], whenNotToUse: ['Weights already exist.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high', plugins: ESU,
    exampleInput: { action: 'auto_skin_weights', skeletalMeshPath: '/Game/SM_Char', save: false }, exampleOutput: { success: true, message: 'Skin weights generated' } }),
  buildRecord({ parentTool: T, id: `${T}.set_vertex_weights`, action: 'set_vertex_weights', family: F,
    summary: 'Set explicit vertex skin weights.', whenToUse: ['Manual weight painting is required.'], whenNotToUse: ['Auto-skin suffices.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, profileName: A.profileName, lodIndex: A.lodIndex, weights: A.weights, save: P.save },
    required: MESH_REQUIRED, effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high',
    plugins: ESU, exampleInput: { action: 'set_vertex_weights', skeletalMeshPath: '/Game/SM_Char', profileName: 'Default', lodIndex: 0, weights: [{ vertexIndex: 0, influences: [{ boneIndex: 0, weight: 1 }] }] },
    exampleOutput: { success: true, message: 'Vertex weights set' } }),
  buildRecord({ parentTool: T, id: `${T}.normalize_weights`, action: 'normalize_weights', family: F,
    summary: 'Normalize skin weights to sum to one.', whenToUse: ['Weights must be normalized.'], whenNotToUse: ['Weights already normalized.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', behavior: { idempotency: 'idempotent', longRunning: true }, latency: 'long-running', resources: 'high',
    plugins: ESU, exampleInput: { action: 'normalize_weights', skeletalMeshPath: '/Game/SM_Char', save: false },
    exampleOutput: { success: true, message: 'Weights normalized' } }),
  buildRecord({ parentTool: T, id: `${T}.prune_weights`, action: 'prune_weights', family: F,
    summary: 'Prune low-influence bone weights.', whenToUse: ['Influences must be reduced.'], whenNotToUse: ['Keep all influences.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, threshold: P.threshold, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', behavior: { idempotency: 'idempotent', longRunning: true }, latency: 'long-running', resources: 'high',
    plugins: ESU, exampleInput: { action: 'prune_weights', skeletalMeshPath: '/Game/SM_Char', threshold: 0.01, save: false },
    exampleOutput: { success: true, message: 'Weights pruned' } }),
  buildRecord({ parentTool: T, id: `${T}.copy_weights`, action: 'copy_weights', family: F,
    summary: 'Copy skin weights from a source mesh.', whenToUse: ['Reuse weights from another mesh.'], whenNotToUse: ['Generate fresh weights.'],
    inputProps: { action: P.action, sourceMeshPath: P.meshPath, targetMeshPath: A.targetMeshPath, profileName: A.profileName, lodIndex: A.lodIndex }, required: ['action', 'sourceMeshPath'],
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high', plugins: ESU,
    exampleInput: { action: 'copy_weights', sourceMeshPath: '/Game/SM_Source', targetMeshPath: '/Game/SM_Char', profileName: 'Default', lodIndex: 0 },
    exampleOutput: { success: true, message: 'Weights copied' } }),
  buildRecord({ parentTool: T, id: `${T}.mirror_weights`, action: 'mirror_weights', family: F,
    summary: 'Mirror skin weights across a symmetry axis.', whenToUse: ['Symmetric mesh needs mirrored weights.'], whenNotToUse: ['Asymmetric rig.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, axis: A.axis, profileName: A.profileName, lodIndex: A.lodIndex, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high', plugins: ESU,
    exampleInput: { action: 'mirror_weights', skeletalMeshPath: '/Game/SM_Char', axis: 'X', profileName: 'Mirror', lodIndex: 0 },
    exampleOutput: { success: true, message: 'Weights mirrored' } }),
  buildRecord({ parentTool: T, id: `${T}.create_physics_asset`, action: 'create_physics_asset', family: F,
    summary: 'Create a PhysicsAsset for a skeletal mesh.', whenToUse: ['Ragdoll/physics needed.'], whenNotToUse: ['PhysicsAsset exists.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath, skeletalMeshPath: P.skeletalMeshPath, outputPath: A.outputPath, save: P.save }, required: ['action'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: ESU,
    outputProps: { assetPath: P.assetPath, physicsAssetPath: P.physicsAssetPath }, outputRequired: [],
    exampleInput: { action: 'create_physics_asset', skeletalMeshPath: '/Game/SM_Char', outputPath: '/Game/PA_Char', save: true }, exampleOutput: { success: true, message: 'PhysicsAsset created', assetPath: '/Game/PA_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.add_physics_body`, action: 'add_physics_body', family: F,
    summary: 'Add a physics body to a PhysicsAsset.', whenToUse: ['A bone needs a collision body.'], whenNotToUse: ['Body exists.'],
    inputProps: { action: P.action, physicsAssetPath: P.physicsAssetPath, boneName: P.boneName, bodyType: A.bodyType, radius: P.radius, center: A.center, save: P.save }, required: ['action', 'physicsAssetPath', 'boneName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_physics_body', physicsAssetPath: '/Game/PA_Char', boneName: 'spine_01', bodyType: 'Sphere', radius: 12, center: [0, 0, 0] },
    exampleOutput: { success: true, message: 'Physics body added' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_physics_body`, action: 'configure_physics_body', family: F,
    summary: 'Configure a physics body mass/damping/collision.', whenToUse: ['Body parameters must change.'], whenNotToUse: ['Use add_physics_body.'],
    inputProps: { action: P.action, physicsAssetPath: P.physicsAssetPath, boneName: P.boneName, mass: P.mass, linearDamping: P.linearDamping, angularDamping: P.angularDamping, collisionEnabled: P.collisionEnabled, simulatePhysics: P.simulatePhysics, save: P.save },
    required: ['action', 'physicsAssetPath', 'boneName'], effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low',
    plugins: ESU, exampleInput: { action: 'configure_physics_body', physicsAssetPath: '/Game/PA_Char', boneName: 'spine_01', mass: 5, linearDamping: 0.25, collisionEnabled: true },
    exampleOutput: { success: true, message: 'Physics body configured' } }),
  buildRecord({ parentTool: T, id: `${T}.add_physics_constraint`, action: 'add_physics_constraint', family: F,
    summary: 'Add a physics constraint between two bodies.', whenToUse: ['Bodies must be jointed.'], whenNotToUse: ['Rigid bodies suffice.'],
    inputProps: { action: P.action, physicsAssetPath: P.physicsAssetPath, bodyA: P.bodyA, bodyB: P.bodyB, constraintName: A.constraintName, save: P.save }, required: ['action', 'physicsAssetPath'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'add_physics_constraint', physicsAssetPath: '/Game/PA_Char', bodyA: 'spine_01', bodyB: 'spine_02', constraintName: 'Spine' },
    exampleOutput: { success: true, message: 'Constraint added' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_constraint_limits`, action: 'configure_constraint_limits', family: F,
    summary: 'Configure constraint angular/linear limits.', whenToUse: ['Joint limits must change.'], whenNotToUse: ['Use add_physics_constraint.'],
    inputProps: { action: P.action, physicsAssetPath: P.physicsAssetPath, bodyA: P.bodyA, bodyB: P.bodyB, limits: P.properties, save: P.save }, required: ['action', 'physicsAssetPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: ESU,
    exampleInput: { action: 'configure_constraint_limits', physicsAssetPath: '/Game/PA_Char', bodyA: 'spine_01', bodyB: 'spine_02', limits: { swing1LimitAngle: 30 } },
    exampleOutput: { success: true, message: 'Constraint limits configured' } }),
  buildRecord({ parentTool: T, id: `${T}.bind_cloth_to_skeletal_mesh`, action: 'bind_cloth_to_skeletal_mesh', family: F,
    summary: 'Bind a cloth asset to a skeletal mesh.', whenToUse: ['Cloth simulation is needed (Chaos Cloth).'], whenNotToUse: ['No cloth.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high', plugins: ['ChaosCloth', 'EditorScriptingUtilities'],
    exampleInput: { action: 'bind_cloth_to_skeletal_mesh', skeletalMeshPath: '/Game/SM_Char', save: false },
    exampleOutput: { success: true, message: 'Cloth bound' } }),
  buildRecord({ parentTool: T, id: `${T}.assign_cloth_asset_to_mesh`, action: 'assign_cloth_asset_to_mesh', family: F,
    summary: 'Assign a cloth asset to a skeletal mesh section.', whenToUse: ['A cloth asset must be assigned.'], whenNotToUse: ['Use bind_cloth_to_skeletal_mesh.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', latency: 'interactive', resources: 'low', plugins: ['ChaosCloth', 'EditorScriptingUtilities'],
    normalizationClass: 'C_SAME_VERB_DIFFERENT_TARGET', normalizationRationale: 'Cloth assignment variant; raw branch documented in route-disposition ledger.',
    exampleInput: { action: 'assign_cloth_asset_to_mesh', skeletalMeshPath: '/Game/SM_Char', save: false },
    exampleOutput: { success: true, message: 'Cloth asset assigned' } }),
  buildRecord({ parentTool: T, id: `${T}.create_morph_target`, action: 'create_morph_target', family: F,
    summary: 'Create a morph target on a skeletal mesh.', whenToUse: ['Facial/shape blending needed.'], whenNotToUse: ['No morph targets.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, morphTargetName: P.morphTargetName, deltas: A.deltas, save: P.save }, required: ['action', 'skeletalMeshPath', 'morphTargetName'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: ESU,
    exampleInput: { action: 'create_morph_target', skeletalMeshPath: '/Game/SM_Char', morphTargetName: 'smile', deltas: [{ vertexIndex: 0, positionDelta: { x: 0, y: 0, z: 1 } }] },
    exampleOutput: { success: true, message: 'Morph target created' } }),
  buildRecord({ parentTool: T, id: `${T}.set_morph_target_deltas`, action: 'set_morph_target_deltas', family: F,
    summary: 'Set vertex deltas for a morph target.', whenToUse: ['Morph shape must be authored.'], whenNotToUse: ['Use create_morph_target.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, morphTargetName: P.morphTargetName, deltas: A.deltas, save: P.save },
    required: ['action', 'skeletalMeshPath', 'morphTargetName'], effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high',
    plugins: ESU, exampleInput: { action: 'set_morph_target_deltas', skeletalMeshPath: '/Game/SM_Char', morphTargetName: 'smile', deltas: [{ vertexIndex: 0, positionDelta: { x: 0, y: 0, z: 2 } }] },
    exampleOutput: { success: true, message: 'Morph deltas set' } }),
  buildRecord({ parentTool: T, id: `${T}.import_morph_targets`, action: 'import_morph_targets', family: F,
    summary: 'Import morph targets from another mesh asset.', whenToUse: ['Morph targets come from an external mesh.'], whenNotToUse: ['Author in-editor.'],
    inputProps: { action: P.action, skeletalMeshPath: P.skeletalMeshPath, morphTargetPath: A.morphTargetPath, save: P.save }, required: MESH_REQUIRED,
    effect: 'write', behavior: { longRunning: true }, latency: 'long-running', resources: 'high', plugins: ['EditorScriptingUtilities', 'Interchange'],
    exampleInput: { action: 'import_morph_targets', skeletalMeshPath: '/Game/SM_Char', morphTargetPath: '/Game/SM_Ext', save: false },
    exampleOutput: { success: true, message: 'Morph targets imported' } }),
  buildRecord({ parentTool: T, id: `${T}.get_skeleton_info`, action: 'get_skeleton_info', family: F,
    summary: 'Read skeleton bone/socket info.', whenToUse: ['Inspect skeleton structure.'], whenNotToUse: ['Mutate the skeleton.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath }, required: ['action', 'skeletonPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: ESU,
    outputProps: { boneCount: P.num_, virtualBoneCount: P.num_, socketCount: P.num_ }, outputRequired: [],
    exampleInput: { action: 'get_skeleton_info', skeletonPath: '/Game/SK_Char' },
    exampleOutput: { success: true, message: 'Skeleton info', boneCount: 50, socketCount: 2 } }),
  buildRecord({ parentTool: T, id: `${T}.list_bones`, action: 'list_bones', family: F,
    summary: 'List bones of a skeleton.', whenToUse: ['Enumerate bones.'], whenNotToUse: ['Mutate bones.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath }, required: ['action', 'skeletonPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: ESU,
    outputProps: { bones: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'list_bones', skeletonPath: '/Game/SK_Char' },
    exampleOutput: { success: true, message: 'Bones listed', bones: ['root', 'spine_01'] } }),
  buildRecord({ parentTool: T, id: `${T}.list_sockets`, action: 'list_sockets', family: F,
    summary: 'List sockets of a skeleton.', whenToUse: ['Enumerate sockets.'], whenNotToUse: ['Mutate sockets.'],
    inputProps: { action: P.action, skeletonPath: P.skeletonPath }, required: ['action', 'skeletonPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: ESU,
    outputProps: { sockets: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'list_sockets', skeletonPath: '/Game/SK_Char' },
    exampleOutput: { success: true, message: 'Sockets listed', sockets: ['Weapon'] } }),
  buildRecord({ parentTool: T, id: `${T}.list_physics_bodies`, action: 'list_physics_bodies', family: F,
    summary: 'List physics bodies of a PhysicsAsset.', whenToUse: ['Enumerate physics bodies.'], whenNotToUse: ['Mutate bodies.'],
    inputProps: { action: P.action, physicsAssetPath: P.physicsAssetPath }, required: ['action', 'physicsAssetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: ESU,
    outputProps: { bodies: P.arrayOfStrings }, outputRequired: [],
    exampleInput: { action: 'list_physics_bodies', physicsAssetPath: '/Game/PA_Char' },
    exampleOutput: { success: true, message: 'Bodies listed', bodies: ['spine_01'] } }),
];
