/**
 * Insights/trace records (10): start_session, start_unreal_insights,
 * capture_insights_trace, get_trace_status, pause_session, resume_session,
 * stop_session, write_snapshot, send_snapshot, analyze_trace.
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';
const DOM = 'insights';
const FAM = 'insights';

export const INSIGHTS_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'start_session',
    domain: DOM,
    family: FAM,
    summary: 'Start an Unreal Insights trace session.',
    whenToUse: ['A new trace session must be started.'],
    whenNotToUse: ['A session is already running (use pause/resume/stop).'],
    inputProps: {
      channels: { type: 'string', description: 'Trace channels (validated: letters, digits, underscore, comma, space, hyphen).' },
      connectionType: { type: 'string', enum: ['file', 'network'], description: 'Trace connection type; network is restricted to loopback.' },
      host: { type: 'string', description: 'Trace host (loopback for network).' },
      port: { type: 'number', description: 'Trace port.' },
      traceFile: { type: 'string', description: 'File mode: .utrace file name, resolved inside Saved/Profiling (default a generated McpInsights_<time>.utrace).' },
      overwrite: { type: 'boolean', description: 'Replace an existing trace file of that name (default false: an existing file is refused).' },
      launchViewer: { type: 'boolean', description: 'Open the Unreal Insights application on the trace: default true for control=launch_viewer (start_unreal_insights), false for the other variants.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'start_session', connectionType: 'file' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'start_unreal_insights',
    domain: DOM,
    family: FAM,
    summary: 'Open the Unreal Insights application on a trace: starts a trace session when none is running (the same inputs as start_session) and launches the viewer; pass launchViewer: false to only start the trace.',
    whenToUse: ['The Insights GUI must be launched for trace analysis.'],
    whenNotToUse: ['Only a trace session is needed (use start_session).'],
    inputProps: {
      channels: { type: 'string', description: 'Trace channels (validated: letters, digits, underscore, comma, space, hyphen).' },
      connectionType: { type: 'string', enum: ['file', 'network'], description: 'Trace connection type; network is restricted to loopback.' },
      traceFile: { type: 'string', description: 'File mode: .utrace file name, resolved inside Saved/Profiling (default a generated name).' },
      host: { type: 'string', description: 'Trace host (loopback for network).' },
      port: { type: 'number', description: 'Trace port.' },
      overwrite: { type: 'boolean', description: 'Overwrite existing trace files.' },
      launchViewer: { type: 'boolean', description: 'Open the Unreal Insights application on the trace: default true for control=launch_viewer (start_unreal_insights), false for the other variants.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'start_unreal_insights' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'capture_insights_trace',
    domain: DOM,
    family: FAM,
    summary: 'Capture an Unreal Insights trace to a .utrace file under Saved/Profiling (use start_session for a network trace).',
    whenToUse: ['A trace must be captured for later analysis.'],
    whenNotToUse: ['A live session without capture is sufficient (use start_session).'],
    inputProps: {
      traceFile: { type: 'string', description: '.utrace file name, resolved inside Saved/Profiling (default a generated name).' },
      channels: { type: 'string', description: 'Trace channels (validated).' },
      overwrite: { type: 'boolean', description: 'Overwrite existing trace files.' },
      launchViewer: { type: 'boolean', description: 'Open the Unreal Insights application on the trace: default true for control=launch_viewer (start_unreal_insights), false for the other variants.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'capture_insights_trace', traceFile: 'cap.utrace' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'get_trace_status',
    domain: DOM,
    family: FAM,
    summary: 'Query the current trace session status.',
    whenToUse: ['The active trace session status must be read.'],
    whenNotToUse: ['A new session must be started (use start_session).'],
    inputProps: {},
    required: [],
    // Native HandleGetTraceStatus (InsightsTraceState.cpp:118-131) emits the
    // AddTraceStatus block (InsightsRequests.cpp:176-235): connected, destination,
    // sessionGuid/traceGuid (when connected), activeChannels, connectionType,
    // traceSystemStatus, paused, statusQuerySupported. Declared exactly — the
    // empty schema previously made a real status response look like a bare ack.
    outputProps: {
      connected: { type: 'boolean', description: 'Whether a trace consumer is connected.' },
      destination: { type: 'string', description: 'Trace destination string.' },
      sessionGuid: { type: 'string', description: 'Session guid (when connected).' },
      traceGuid: { type: 'string', description: 'Trace guid (when connected).' },
      activeChannels: { type: 'string', description: 'Active trace channels.' },
      connectionType: { type: 'string', description: 'Connection type: none, file, network, relay, or secure_network.' },
      traceSystemStatus: { type: 'string', description: 'Trace system status (e.g. available, tracing_to_file).' },
      paused: { type: 'boolean', description: 'Whether tracing is paused.' },
      statusQuerySupported: { type: 'boolean', description: 'Whether this engine version supports status queries.' },
    },
    outputRequired: [],
    effect: 'read',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'get_trace_status' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'pause_session',
    domain: DOM,
    family: FAM,
    summary: 'Pause the active trace session.',
    whenToUse: ['Trace capture must be temporarily suspended.'],
    whenNotToUse: ['The session should be stopped entirely (use stop_session).'],
    inputProps: {},
    required: [],
    effect: 'write',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'pause_session' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'resume_session',
    domain: DOM,
    family: FAM,
    summary: 'Resume a paused trace session.',
    whenToUse: ['A paused trace session must continue capturing.'],
    whenNotToUse: ['No session is paused.'],
    inputProps: {},
    required: [],
    effect: 'write',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'resume_session' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'stop_session',
    domain: DOM,
    family: FAM,
    summary: 'Stop the active trace session.',
    whenToUse: ['The trace session must be terminated.'],
    whenNotToUse: ['The session should only be paused (use pause_session).'],
    inputProps: {},
    required: [],
    effect: 'write',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'stop_session' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'write_snapshot',
    domain: DOM,
    family: FAM,
    summary: 'Write a trace snapshot to a snapshot path.',
    whenToUse: ['A point-in-time trace snapshot must be written to disk.'],
    whenNotToUse: ['The snapshot should be sent to a running trace (use send_snapshot).'],
    inputProps: {
      snapshotPath: { type: 'string', description: 'Snapshot .utrace file name, resolved inside Saved/Profiling (default a generated name).' },
      overwrite: { type: 'boolean', description: 'Overwrite existing trace files.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'write_snapshot', snapshotPath: 'snap.utrace' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'send_snapshot',
    domain: DOM,
    family: FAM,
    summary: 'Send a trace snapshot to a trace server (Unreal Insights) on this machine.',
    whenToUse: ['A snapshot must be forwarded to an active trace session.'],
    whenNotToUse: ['The snapshot should be persisted to disk (use write_snapshot).'],
    inputProps: {
      host: { type: 'string', description: 'Trace server host, loopback only (default localhost).' },
      port: { type: 'number', description: 'Trace server port (default the trace system default).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'send_snapshot' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'analyze_trace',
    domain: DOM,
    family: FAM,
    summary: 'Read a captured trace file\'s metadata: whether it exists, its size, extension, .utrace flag and modified time.',
    whenToUse: ['A captured .utrace file must be checked for existence, size and modified time.'],
    whenNotToUse: ['A live session status is needed (use get_trace_status).'],
    inputProps: { traceFile: { type: 'string', description: 'Trace file to analyze.' } },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    costResources: 'medium',
    dispatchAction: 'manage_insights',
    exampleInput: { action: 'analyze_trace', traceFile: 'cap.utrace' },
  }),
];
