/**
 * Widget/audio/viewport records (5): create_widget, show_widget,
 * add_widget_child, play_sound, screenshot.
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';

export const WIDGET_AUDIO_VIEWPORT_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'create_widget',
    domain: 'widget',
    family: 'widget',
    summary: 'Create a widget asset via the manage_widget_authoring bridge action.',
    whenToUse: ['A new UMG widget asset must be created.'],
    whenNotToUse: ['An existing widget should be shown (use show_widget).'],
    inputProps: {
      name: { type: 'string', description: 'Widget name (derived from widgetPath if absent).' },
      widgetPath: { type: 'string', description: 'Full widget path; name and savePath are derived when name is absent.' },
      widgetType: { type: 'string', description: 'Widget type.' },
      savePath: { type: 'string', description: 'Destination /Game folder.' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_widget_authoring',
    exampleInput: { action: 'create_widget', name: 'WBP_Menu', savePath: '/Game/UI' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'show_widget',
    domain: 'widget',
    family: 'widget',
    summary: 'Show a widget by path or render a notification via the manage_widget_authoring bridge action.',
    whenToUse: ['An existing widget must be displayed or a notification shown.'],
    whenNotToUse: ['A new widget must be authored first (use create_widget).'],
    inputProps: {
      widgetId: { type: 'string', description: 'Widget id; "notification" renders a notification.' },
      widgetPath: { type: 'string', description: 'Widget path (or name) to show.' },
      name: { type: 'string', description: 'Alternate widget path selector.' },
      message: { type: 'string', description: 'Notification message text.' },
      duration: { type: 'number', description: 'Notification duration.' },
    },
    required: [],
    effect: 'write',
    dispatchAction: 'manage_widget_authoring',
    exampleInput: { action: 'show_widget', widgetId: 'notification', message: 'Saved' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'add_widget_child',
    domain: 'widget',
    family: 'widget',
    summary: 'Add a child widget component to a parent widget via the manage_widget_authoring bridge action.',
    whenToUse: ['A child component must be added to an existing widget.'],
    whenNotToUse: ['A top-level widget must be created (use create_widget).'],
    inputProps: {
      widgetPath: { type: 'string', description: 'Parent widget path (required).' },
      childClass: { type: 'string', description: 'Child component class (required).' },
      parentName: { type: 'string', description: 'Optional parent panel name.' },
      name: { type: 'string', description: 'Optional component name.' },
      text: { type: 'string', description: 'Optional text for text-bearing components.' },
    },
    required: ['widgetPath', 'childClass'],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_widget_authoring',
    exampleInput: { action: 'add_widget_child', widgetPath: '/Game/UI/WBP_Menu', childClass: 'TextBlock' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'play_sound',
    domain: 'audio',
    family: 'audio',
    summary: 'Play a 2D sound by path via the play_sound_2d bridge action, with an engine fallback sound.',
    whenToUse: ['A 2D (non-spatial) sound must be played at runtime.'],
    whenNotToUse: ['A spatial sound at a location is needed (use manage_audio).'],
    inputProps: {
      soundPath: { type: 'string', description: 'Sound asset path.' },
      volume: { type: 'number', description: 'Volume multiplier (0 silences the request).' },
      pitch: { type: 'number', description: 'Pitch multiplier.' },
    },
    required: [],
    effect: 'write',
    dispatchAction: 'play_sound_2d',
    exampleInput: { action: 'play_sound', soundPath: '/Game/Audio/SFX_Click', volume: 1.0 },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'screenshot',
    domain: 'viewport',
    family: 'viewport',
    summary: 'Capture a screenshot of the editor viewport, game viewport, or full editor window.',
    whenToUse: ['A viewport or window screenshot must be captured, optionally as base64.'],
    whenNotToUse: ['A PIE session screenshot with camera control is needed (use control_editor).'],
    inputProps: {
      filename: { type: 'string', description: 'Screenshot filename base.' },
      mode: { type: 'string', enum: ['editor_viewport', 'game_viewport', 'full_editor_window'], description: 'Screenshot target mode.' },
      window: { type: 'string', description: 'With mode full_editor_window, which window to capture: a list index ("2") or a case-insensitive substring of its title ("WBP_HubUI"). Omit for the main editor frame; responses list the open windows under windows[].' },
      resolution: { type: 'string', description: 'Resolution as WxH.' },
      width: { type: 'number', description: 'Width in pixels.' },
      height: { type: 'number', description: 'Height in pixels.' },
      returnBase64: { type: 'boolean', description: 'Return PNG as base64. Defaults to false — a plain capture returns path + metadata. Set true for inline image data; pair with resolution= (e.g. "1280x720") to keep the PNG under the base64 size cap.' },
      includeMetadata: { type: 'boolean', description: 'Include capture metadata.' },
      metadata: { type: 'object', description: 'Optional metadata payload.', additionalProperties: true, 'x-unreal-reflection-boundary': true },
    },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    dispatchAction: 'control_editor',
    exampleInput: { action: 'screenshot', mode: 'editor_viewport', filename: 'Shot1' },
  }),
];
