/**
 * Widget/audio/viewport records (5): create_widget, show_widget,
 * add_widget_child, play_sound, screenshot.
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildCoreRecord } from '../core/builder.js';

const PT = 'system_control';

export const WIDGET_AUDIO_VIEWPORT_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: PT,
    action: 'create_widget',
    domain: 'widget',
    family: 'widget',
    summary: 'Create a widget asset via the manage_widget_authoring bridge action.',
    whenToUse: ['A new UMG widget asset must be created.'],
    whenNotToUse: ['An existing widget should be shown (use show_widget).'],
    inputProps: {
      name: { type: 'string', description: 'Widget name (derived from widgetPath if absent).' },
      widgetPath: { type: 'string', description: 'Full widget asset path such as /Game/UI/WBP_Menu; supplies name and savePath when they are omitted.' },
      widgetType: { type: 'string', description: 'Parent class: UserWidget (default) or another UserWidget subclass by name or path; anything else is refused.' },
      savePath: { type: 'string', description: 'Destination /Game folder (default /Game/UI/Widgets).' },
    },
    required: [],
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_widget_authoring',
    exampleInput: { action: 'create_widget', name: 'WBP_Menu', savePath: '/Game/UI' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'show_widget',
    domain: 'widget',
    family: 'widget',
    summary: 'Show an editor toast notification with a message; it cannot put a widget Blueprint on screen.',
    whenToUse: ['A short message must be shown to the person at the editor.'],
    whenNotToUse: ['A widget Blueprint must be displayed in game (add it to the viewport from Blueprint logic).'],
    inputProps: {
      widgetId: { type: 'string', description: 'Only "notification" (the default); any other value is refused.' },
      name: { type: 'string', description: 'Same as widgetId.' },
      message: { type: 'string', description: 'Notification message text.' },
      duration: { type: 'number', description: 'Seconds the notification stays up (default 4, 0.5 to 60).' },
    },
    required: [],
    effect: 'write',
    dispatchAction: 'manage_widget_authoring',
    exampleInput: { action: 'show_widget', widgetId: 'notification', message: 'Saved' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'add_widget_child',
    domain: 'widget',
    family: 'widget',
    summary: 'Add a child widget component to a parent widget via the manage_widget_authoring bridge action.',
    whenToUse: ['A child component must be added to an existing widget.'],
    whenNotToUse: ['A top-level widget must be created (use create_widget).'],
    inputProps: {
      widgetPath: { type: 'string', description: 'Parent widget path (required).' },
      childClass: { type: 'string', description: 'Child component class (required).' },
      parentName: { type: 'string', description: 'Panel to add the child under (get_widget_info lists the panels); omitted, the root panel. A name that is not a panel fails with PARENT_NOT_FOUND.' },
      name: { type: 'string', description: 'Name of the new widget; omitted, a generated one.' },
      text: { type: 'string', description: 'Optional text for text-bearing components.' },
    },
    required: ['widgetPath', 'childClass'],
    outputProps: {
      componentName: { type: 'string', description: 'Name the new widget got.' },
      parentName: { type: 'string', description: 'Panel it was added under.' },
    },
    effect: 'write',
    costLatency: 'interactive',
    dispatchAction: 'manage_widget_authoring',
    exampleInput: { action: 'add_widget_child', widgetPath: '/Game/UI/WBP_Menu', childClass: 'TextBlock' },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'play_sound',
    domain: 'audio',
    family: 'audio',
    summary: 'Play a 2D sound by path via the play_sound_2d bridge action, with an engine fallback sound.',
    whenToUse: ['A 2D (non-spatial) sound must be played at runtime.'],
    whenNotToUse: ['A spatial sound at a location is needed (use manage_audio).'],
    inputProps: {
      soundPath: { type: 'string', description: 'Sound asset path (default the editor CompileSuccess cue).' },
      volume: { type: 'number', description: 'Volume multiplier (0 silences the request).' },
      pitch: { type: 'number', description: 'Pitch multiplier.' },
      startTime: { type: 'number', description: 'Seconds into the sound to start playing from (default 0).' },
    },
    required: [],
    effect: 'write',
    dispatchAction: 'play_sound_2d',
    exampleInput: { action: 'play_sound', soundPath: '/Game/Audio/SFX_Click', volume: 1.0 },
  }),
  buildCoreRecord({
    parentTool: PT,
    action: 'screenshot',
    domain: 'viewport',
    family: 'viewport',
    summary: 'Capture a screenshot of the editor viewport, game viewport, or full editor window.',
    whenToUse: ['A viewport or window screenshot must be captured, optionally as base64.'],
    whenNotToUse: ['A PIE session screenshot with camera control is needed (use control_editor).'],
    inputProps: {
      filename: { type: 'string', description: 'Screenshot filename base.' },
      mode: { type: 'string', enum: ['editor_viewport', 'game_viewport', 'full_editor_window'], description: 'Screenshot target mode.' },
      window: { type: ['integer', 'string'], description: 'With mode full_editor_window, which window to capture: a list index (2, or "2") or a case-insensitive substring of its title ("WBP_HubUI"). Omit for the main editor frame; responses list the open windows under windows[].' },
      resolution: { type: 'string', description: 'Maximum WxH for the PNG (e.g. "1280x720"), aspect ratio kept, never upscaled. Without it an image returned inline fits 1600x900.' },
      width: { type: 'number', description: 'Width in pixels.' },
      height: { type: 'number', description: 'Height in pixels.' },
      keepFile: { type: 'boolean', description: 'false: hand the image back without leaving a file in Saved/Screenshots (refused with returnBase64 false, which would leave no output at all). Default true. Files already written are listed by list_output_files and removed by delete_output_file.' },
      path: { type: 'string', description: 'game_viewport mode only: project-relative folder to write the PNG into (default Saved/Screenshots/WindowsEditor).' },
      returnBase64: { type: 'boolean', description: 'Return the PNG inline as an image (default true); a capture also saves a file unless keepFile is false. With no resolution, an inline image is downscaled to fit 1600x900. false returns only the saved path and metadata, at the full viewport size.' },
      includeMetadata: { type: 'boolean', description: 'Include capture metadata.' },
      metadata: { type: 'object', description: 'Optional metadata payload.', additionalProperties: true, 'x-unreal-reflection-boundary': true },
    },
    required: [],
    effect: 'read',
    costLatency: 'interactive',
    dispatchAction: 'control_editor',
    exampleInput: { action: 'screenshot', mode: 'editor_viewport', filename: 'Shot1' },
  }),
];
