/**
 * Component and actor inspection records (14 actions).
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildCoreRecord } from '../core/builder.js';
import { P } from './properties.js';

const D = 'inspect';

export const COMPONENT_ACTOR_RECORDS: readonly CapabilityRecordSource[] = [
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_components', dispatchAction: 'get_components', domain: D, family: 'components',
    topics: ['list components', 'actor components', 'component list', 'components of actor'],
    aliases: ['inspect.list_components'],
    summary: 'List components on a world actor (or a Blueprint CDO when blueprintPath is supplied).',
    whenToUse: ['An actor\'s component list must be enumerated.'],
    whenNotToUse: ['A single component\'s properties are needed; use get_component_property.'],
    inputProps: {
      objectPath: P.objectPath, actorName: P.actorName, name: P.name, blueprintPath: P.blueprintPath,
      componentNames: { type: 'array', items: { type: 'string' }, description: 'Return only these components, by name (case-insensitive); a name that matches none is listed under missingComponents.' },
    },
    required: [],
    effect: 'read',
    exampleInput: { action: 'get_components', actorName: 'PlayerStart_1' },
    exampleOutput: { success: true, message: 'Components listed', components: [] },
    outputProps: {
      components: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Component info objects: name, class, parent, source. A mesh component also carries staticMesh and materials (the material drawn in each slot, overrides included); a Blueprint component also carries its relative location/rotation/scale and visible.' },
      missingComponents: { type: 'array', items: { type: 'string' }, description: 'componentNames that matched no component.' },
    },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_component_property', dispatchAction: 'control_actor', domain: D, family: 'components',
    summary: 'Read a property on a world actor component (cross-parent to control_actor).',
    whenToUse: ['A single component property value must be read.'],
    whenNotToUse: ['The whole component is needed; use get_component_details.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, componentName: P.componentName, propertyName: P.propertyName, propertyPath: P.propertyPath, blueprintPath: P.blueprintPath },
    required: ['componentName'],
    requiredOneOf: ['propertyName', 'propertyPath'],
    effect: 'read',
    exampleInput: { action: 'get_component_property', actorName: 'PlayerStart_1', componentName: 'Billboard', propertyName: 'Sprite' },
    exampleOutput: { success: true, message: 'Component property read', value: null },
    outputProps: { value: P.value },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'set_component_property', dispatchAction: 'control_actor', domain: D, family: 'components',
    summary: 'Write a property on a world actor component (cross-parent to control_actor).',
    whenToUse: ['A single component property value must be written.'],
    whenNotToUse: ['The component does not own the property; use get_components to enumerate.'],
    inputProps: {
      objectPath: P.objectPath, actorName: P.actorName, name: P.name, componentName: P.componentName, propertyName: P.propertyName, propertyPath: P.propertyPath, value: P.value,
      properties: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true, description: 'Several component properties at once, name or dotted path to value, in place of propertyName and value.' },
    },
    required: ['componentName'],
    requiredOneOf: ['properties', 'propertyName', 'propertyPath'],
    effect: 'write', costLatency: 'interactive',
    exampleInput: { action: 'set_component_property', actorName: 'PlayerStart_1', componentName: 'Billboard', propertyName: 'Sprite', value: null },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_component_details', dispatchAction: 'control_actor', domain: D, family: 'components',
    summary: 'Return a single component of a world actor (TS dispatches get_components to control_actor and filters locally).',
    whenToUse: ['One component\'s full details must be read.'],
    whenNotToUse: ['All components are needed; use get_components.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, componentName: P.componentName, blueprintPath: P.blueprintPath, propertyNames: P.propertyNames },
    required: ['componentName'],
    effect: 'read',
    exampleInput: { action: 'get_component_details', actorName: 'PlayerStart_1', componentName: 'Billboard' },
    exampleOutput: { success: true, message: 'Component details', componentName: 'Billboard' },
    outputProps: { componentName: P.componentName },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_metadata', dispatchAction: 'control_actor', domain: D, family: 'actor',
    summary: 'Read metadata key/value pairs from a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s metadata must be inspected.'],
    whenNotToUse: ['Metadata must be written; use manage_asset or control_actor set_metadata.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name },
    required: [],
    effect: 'read',
    exampleInput: { action: 'get_metadata', actorName: 'PlayerStart_1' },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'add_tag', dispatchAction: 'control_actor', domain: D, family: 'actor',
    summary: 'Add a tag to a world actor (cross-parent to control_actor).',
    whenToUse: ['A tag must be added to an actor for grouping or queries.'],
    whenNotToUse: ['The actor already has the tag.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, actorNames: P.actorNames, name: P.name, tag: P.tag },
    required: ['tag'],
    effect: 'write', behavior: { idempotency: 'idempotent' },
    exampleInput: { action: 'add_tag', actorName: 'PlayerStart_1', tag: 'Spawn' },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'find_by_tag', dispatchAction: 'control_actor', domain: D, family: 'actor',
    summary: 'Find world actors by tag (cross-parent to control_actor).',
    whenToUse: ['All actors with a given tag must be enumerated.'],
    whenNotToUse: ['Actors must be found by class; use find_by_class.'],
    inputProps: { tag: P.tag },
    required: [],
    effect: 'read',
    exampleInput: { action: 'find_by_tag', tag: 'Spawn' },
    exampleOutput: { success: true, message: 'Actors found', actors: [] },
    outputProps: { actors: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Matching actor info objects.' } },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'create_snapshot', dispatchAction: 'control_actor', domain: D, family: 'snapshot',
    summary: 'Create a property snapshot of a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s state must be captured for later restore.'],
    whenNotToUse: ['No restore is planned.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, snapshotName: P.snapshotName },
    required: [],
    effect: 'write', costLatency: 'interactive',
    exampleInput: { action: 'create_snapshot', actorName: 'PlayerStart_1', snapshotName: 'snap_01' },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'restore_snapshot', dispatchAction: 'control_actor', domain: D, family: 'snapshot',
    summary: 'Restore a previously created property snapshot onto a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s state must be restored from a snapshot.'],
    whenNotToUse: ['No snapshot exists for the actor.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, snapshotName: P.snapshotName },
    required: [],
    effect: 'write', behavior: { idempotency: 'idempotent' }, costLatency: 'interactive',
    exampleInput: { action: 'restore_snapshot', actorName: 'PlayerStart_1', snapshotName: 'snap_01' },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'export', dispatchAction: 'control_actor', domain: D, family: 'actor',
    summary: 'Export a world actor or object as text (T3D by default), returned inline as exportedText and, with outputPath, also written to a file inside the project.',
    whenToUse: ['An actor must be serialized to text or to an external file.'],
    whenNotToUse: ['The actor should be duplicated in-scene; use control_actor duplicate.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name, format: P.format, outputPath: P.outputPath },
    required: [],
    effect: 'read', costLatency: 'interactive',
    exampleInput: { action: 'export', actorName: 'PlayerStart_1' },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'delete_object', dispatchAction: 'control_actor', domain: D, family: 'actor',
    summary: 'Delete a world actor by name (cross-parent to control_actor; dispatches action delete).',
    whenToUse: ['A world actor must be permanently removed from the level.'],
    whenNotToUse: ['The target is an asset path; use manage_asset delete (TS returns a NOT_FOUND hint).'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, actorNames: P.actorNames, name: P.name },
    required: [],
    effect: 'destructive', costLatency: 'interactive',
    exampleInput: { action: 'delete_object', actorName: 'PlayerStart_1' },
    exampleOutput: { success: true, message: 'Actor deleted', deleted: 'PlayerStart_1' },
    outputProps: { deleted: { type: 'string', description: 'Name of the deleted actor.' } },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'list_objects', dispatchAction: 'control_actor', domain: D, family: 'actor',
    outputProps: {
      count: { type: 'number', description: 'Number of actors returned.' },
      totalCount: { type: 'number', description: 'Total actor count in the world.' },
      isPieWorld: { type: 'boolean', description: 'Whether the world is a PIE world.' },
      worldName: { type: 'string', description: 'Name of the current world.' },
      actors: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Actor info objects.' },
    },
    topics: ['world objects', 'enumerate objects'],
    summary: 'List world actors (cross-parent to control_actor; dispatches action list_actors).',
    whenToUse: ['All actors in the current level must be enumerated.'],
    whenNotToUse: ['Only tagged actors are needed; use find_by_tag.'],
    inputProps: { filter: P.filter, limit: P.limit, offset: P.offset },
    required: [],
    effect: 'read',
    exampleInput: { action: 'list_objects' },
    exampleOutput: { success: true, message: 'Actors listed', actors: [] },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'find_by_class', dispatchAction: 'find_by_class', domain: D, family: 'actor',
    topics: ['all actors of a type', 'every instance'],
    summary: 'Find the actors of a class in the level, by class name or /Script path: returns each match\'s name, path and class plus a count. Searches the PIE world while a game runs.',
    whenToUse: ['All actors of a specific class must be enumerated.'],
    whenNotToUse: ['Actors must be found by tag; use find_by_tag.'],
    inputProps: { className: P.className, classPath: P.classPath },
    required: [],
    requiredOneOf: ['className', 'classPath'],
    effect: 'read',
    exampleInput: { action: 'find_by_class', className: 'PointLight' },
    exampleOutput: { success: true, message: 'Actors found', objects: [] },
    outputProps: { objects: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Matching object info.' } },
  }),
  buildCoreRecord({
    parentTool: 'inspect', action: 'get_bounding_box', dispatchAction: 'control_actor', domain: D, family: 'actor',
    summary: 'Return the world-space bounding box of a world actor (cross-parent to control_actor).',
    whenToUse: ['An actor\'s bounds must be read.'],
    whenNotToUse: ['The actor does not have a visible mesh.'],
    inputProps: { objectPath: P.objectPath, actorName: P.actorName, name: P.name },
    required: [],
    effect: 'read',
    exampleInput: { action: 'get_bounding_box', actorName: 'Cube_1' },
  }),
];
