#!/usr/bin/env node
/**
 * manage_effect Tool Integration Tests
 * Covers all 58 actions with real optional-parameter coverage.
 */

import { runToolTests } from '../../test-runner.mjs';

const ts = Date.now();
const TEST_FOLDER = `/Game/MCPTest/ManageEffect_${ts}`;
const TEST_ACTOR = `TestActor_${ts}`;
const EFFECT_ACTOR = `TestEffectActor_${ts}`;
const SPAWNED_EFFECT_ACTOR = `TestSpawnedEffectActor_${ts}`;
const SYSTEM_NAME = `Testniagara_system_${ts}`;
const EMITTER_ASSET_NAME = `Testniagara_emitter_${ts}`;
const SYSTEM_PATH = `${TEST_FOLDER}/${SYSTEM_NAME}.${SYSTEM_NAME}`;
const EMITTER_PATH = `${TEST_FOLDER}/${EMITTER_ASSET_NAME}.${EMITTER_ASSET_NAME}`;
const DEFAULT_EMITTER = '${captured:niagaraEmitterName}';
const USER_PARAM = `MCPUserParam_${ts}`;
const USER_PARAM_B = `MCPUserParamB_${ts}`;
const BOUND_PARAM = `MCPBoundParam_${ts}`;
const EVENT_NAME = `MCPEvent_${ts}`;
const STAGE_NAME = `MCPStage_${ts}`;
const BASIC_MATERIAL = '/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial';
const CUBE_MESH = '/Engine/BasicShapes/Cube.Cube';

const testCases = [
  // === SETUP ===
  { scenario: 'Setup: spawn test actor', toolName: 'control_actor', arguments: { action: 'spawn', classPath: '/Engine/BasicShapes/Cube', actorName: TEST_ACTOR, location: { x: 0, y: 0, z: 100 } }, expected: 'success' },

  // === CREATE ===
  { scenario: 'CREATE: create_niagara_system', toolName: 'manage_effect', arguments: { action: 'create_niagara_system', name: SYSTEM_NAME, path: TEST_FOLDER, savePath: TEST_FOLDER, save: true }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_niagara_emitter', toolName: 'manage_effect', arguments: { action: 'create_niagara_emitter', name: EMITTER_ASSET_NAME, path: TEST_FOLDER, savePath: TEST_FOLDER, save: true }, expected: 'success|already exists' },
  { scenario: 'ADD: add_emitter_to_system', toolName: 'manage_effect', arguments: { action: 'add_emitter_to_system', systemPath: SYSTEM_PATH, emitterPath: EMITTER_PATH, emitterName: `MCPEmitter_${ts}`, save: false }, expected: 'success|already exists', captureResult: { key: 'niagaraEmitterName', fromField: 'result.emitterName' } },

  // === ACTION ===
  { scenario: 'ACTION: particle from a preset', toolName: 'manage_effect', arguments: { action: 'particle', preset: 'Default', name: `TestParticle_${ts}`, location: { x: 0, y: 0, z: 100 }, rotation: [0, 45, 0] }, expected: 'success', timeoutMs: 30000 },
  { scenario: 'ACTION: particle from a system asset', toolName: 'manage_effect', arguments: { action: 'particle', systemPath: SYSTEM_PATH, name: `TestParticleAsset_${ts}`, location: [0, 40, 100] }, expected: 'success' },
  { scenario: 'ACTION: niagara with actor attachment', toolName: 'manage_effect', arguments: { action: 'niagara', systemPath: SYSTEM_PATH, actorName: EFFECT_ACTOR, attachToActor: TEST_ACTOR, location: { x: 0, y: 0, z: 120 }, rotation: { pitch: 0, yaw: 90, roll: 0 }, scale: 2 }, expected: 'success', assertions: [{ path: 'structuredContent.result.attachedTo', equals: TEST_ACTOR, label: 'niagara attached to the named actor' }] },
  { scenario: 'ACTION: niagara with a missing attach target spawns nothing', toolName: 'manage_effect', arguments: { action: 'niagara', systemPath: SYSTEM_PATH, actorName: `${EFFECT_ACTOR}_Orphan`, attachToActor: `Missing_${ts}`, location: { x: 0, y: 0, z: 120 } }, expected: 'error|ACTOR_NOT_FOUND' },
  { scenario: 'ACTION: debug_shape alias shape', toolName: 'manage_effect', arguments: { action: 'debug_shape', shape: 'box', location: { x: 20, y: 0, z: 100 }, radius: 25, boxSize: { x: 10, y: 20, z: 30 }, color: { r: 0, g: 128, b: 255, a: 255 }, duration: 0.1, thickness: 3 }, expected: 'success', assertions: [{ path: 'structuredContent.result.shapeType', equals: 'box', label: 'shape alias reached native shapeType' }] },
  { scenario: 'ACTION: debug_shape line', toolName: 'manage_effect', arguments: { action: 'debug_shape', shapeType: 'line', location: [0, 0, 100], endLocation: [200, 0, 100], color: [255, 0, 0], duration: 0.1 }, expected: 'success' },
  { scenario: 'ACTION: debug_shape cone', toolName: 'manage_effect', arguments: { action: 'debug_shape', shapeType: 'cone', location: [0, 0, 100], direction: [0, 0, 1], length: 150, angle: 30, duration: 0.1 }, expected: 'success' },
  { scenario: 'ACTION: debug_shape capsule', toolName: 'manage_effect', arguments: { action: 'debug_shape', shapeType: 'capsule', location: [0, 0, 100], radius: 20, halfHeight: 60, rotation: [0, 0, 90], duration: 0.1 }, expected: 'success' },
  { scenario: 'CREATE: spawn_niagara with system alias', toolName: 'manage_effect', arguments: { action: 'spawn_niagara', system: SYSTEM_PATH, actorName: SPAWNED_EFFECT_ACTOR, attachToActor: TEST_ACTOR, location: { x: 40, y: 0, z: 120 }, rotation: [0, 0, 0], scale: [1, 1, 2] }, expected: 'success' },
  { scenario: 'CREATE: create_dynamic_light with light properties', toolName: 'manage_effect', arguments: { action: 'create_dynamic_light', name: `Testdynamic_light_${ts}`, location: { x: 80, y: 0, z: 250 }, lightType: 'Point', intensity: 750, color: [1, 0.8, 0.4, 1] }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_volumetric_fog with fog properties', toolName: 'manage_effect', arguments: { action: 'create_volumetric_fog', name: `Testvolumetric_fog_${ts}`, location: [0, 0, 500], density: 0.02, scattering: 0.6, extinction: 0.4 }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_particle_trail', toolName: 'manage_effect', arguments: { action: 'create_particle_trail', name: `Testparticle_trail_${ts}`, systemPath: SYSTEM_PATH, location: { x: 120, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_environment_effect', toolName: 'manage_effect', arguments: { action: 'create_environment_effect', name: `Testenvironment_effect_${ts}`, systemPath: SYSTEM_PATH, location: { x: 160, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_impact_effect', toolName: 'manage_effect', arguments: { action: 'create_impact_effect', name: `Testimpact_effect_${ts}`, systemPath: SYSTEM_PATH, location: { x: 200, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_niagara_ribbon', toolName: 'manage_effect', arguments: { action: 'create_niagara_ribbon', name: `Testniagara_ribbon_${ts}`, systemPath: SYSTEM_PATH, location: { x: 240, y: 0, z: 120 } }, expected: 'success|already exists' },
  { scenario: 'CREATE: create_niagara_ribbon authored from a template', toolName: 'manage_effect', arguments: { action: 'create_niagara_ribbon', name: `NS_TestAuthoredRibbon_${ts}`, path: TEST_FOLDER, templateEmitterPath: '/Niagara/DefaultAssets/Templates/Emitters/LocationBasedRibbon.LocationBasedRibbon', location: [280, 0, 120], save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.templateEmitterFound', equals: true, label: 'template emitter used' }] },
  { scenario: 'CREATE: create_impact_effect with a missing template is refused', toolName: 'manage_effect', arguments: { action: 'create_impact_effect', name: `NS_TestBadTemplate_${ts}`, path: TEST_FOLDER, templateEmitterPath: `/Game/MCPTest/NoSuchEmitter_${ts}` }, expected: 'error|TEMPLATE_NOT_FOUND' },

  // === PLAYBACK ===
  { scenario: 'ACTION: activate', toolName: 'manage_effect', arguments: { action: 'activate', actorName: EFFECT_ACTOR, reset: false }, expected: 'success' },
  { scenario: 'ACTION: activate_effect by systemName', toolName: 'manage_effect', arguments: { action: 'activate_effect', systemName: EFFECT_ACTOR }, expected: 'success' },
  { scenario: 'ACTION: activate_effect by system asset', toolName: 'manage_effect', arguments: { action: 'activate_effect', assetPath: SYSTEM_PATH, reset: true }, expected: 'success' },
  { scenario: 'ACTION: deactivate', toolName: 'manage_effect', arguments: { action: 'deactivate', actorName: EFFECT_ACTOR }, expected: 'success' },
  { scenario: 'ACTION: reset', toolName: 'manage_effect', arguments: { action: 'reset', actorName: EFFECT_ACTOR }, expected: 'success' },
  { scenario: 'PLAYBACK: advance_simulation', toolName: 'manage_effect', arguments: { action: 'advance_simulation', actorName: EFFECT_ACTOR, deltaTime: 0.016, steps: 2 }, expected: 'success', assertions: [{ path: 'structuredContent.result.steps', equals: 2, label: 'native simulation step count applied' }] },

  // === GRAPH ===
  { scenario: 'ADD: add_niagara_module', toolName: 'manage_effect', arguments: { action: 'add_niagara_module', assetPath: SYSTEM_PATH, systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, modulePath: '/Niagara/Modules/Emitter/EmitterState.EmitterState', scriptType: 'Update', save: false }, expected: 'success|already exists', captureResult: { key: 'niagaraModuleNodeId', fromField: 'result.nodeId' } },
  { scenario: 'CONNECT: connect_niagara_pins', toolName: 'manage_effect', arguments: { action: 'connect_niagara_pins', assetPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, scriptType: 'Update', autoConnect: true, save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.connected', equals: true, label: 'real Niagara graph pins connected' }, { path: 'structuredContent.result.autoConnected', equals: true, label: 'native auto-connect path executed' }], captureResult: [{ key: 'pinFromNode', fromField: 'result.fromNode' }, { key: 'pinFromPin', fromField: 'result.fromPin' }, { key: 'pinToNode', fromField: 'result.toNode' }, { key: 'pinToPin', fromField: 'result.toPin' }] },
  // Re-making the pair the auto-connect reported proves the explicit endpoints resolve.
  { scenario: 'CONNECT: connect_niagara_pins by explicit endpoints', toolName: 'manage_effect', arguments: { action: 'connect_niagara_pins', assetPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, scriptType: 'Update', fromNode: '${captured:pinFromNode}', fromPin: '${captured:pinFromPin}', toNode: '${captured:pinToNode}', toPin: '${captured:pinToPin}', save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.connected', equals: true, label: 'explicit Niagara pins connected' }] },
  { scenario: 'DELETE: remove_niagara_node', toolName: 'manage_effect', arguments: { action: 'remove_niagara_node', assetPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, scriptType: 'Update', nodeId: '${captured:niagaraModuleNodeId}', save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.removed', equals: true, label: 'captured Niagara graph node removed' }] },

  // === RUNTIME PARAMETER ===
  { scenario: 'CONFIG: set_niagara_parameter', toolName: 'manage_effect', arguments: { action: 'set_niagara_parameter', actorName: EFFECT_ACTOR, parameterName: 'MCPParameter', parameterType: 'Float', value: 1.25 }, expected: 'success', assertions: [{ path: 'structuredContent.result.applied', equals: true, label: 'runtime Niagara parameter value applied' }] },
  { scenario: 'DELETE: clear_debug_shapes', toolName: 'manage_effect', arguments: { action: 'clear_debug_shapes' }, expected: 'success|not found' },
  { scenario: 'ACTION: cleanup with explicit filter', toolName: 'manage_effect', arguments: { action: 'cleanup', filter: `NoSuchManageEffectActor_${ts}` }, expected: 'success|not found' },
  { scenario: 'INFO: list_debug_shapes', toolName: 'manage_effect', arguments: { action: 'list_debug_shapes' }, expected: 'success' },

  // === NIAGARA AUTHORING ===
  { scenario: 'CONFIG: set_emitter_properties', toolName: 'manage_effect', arguments: { action: 'set_emitter_properties', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, emitterProperties: { enabled: true }, save: false }, expected: 'success' },
  // moduleEnabled switches stack modules on or off by name (EmitterState was added to this emitter above).
  { scenario: 'CONFIG: set_emitter_properties turns a module on by name', toolName: 'manage_effect', arguments: { action: 'set_emitter_properties', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, emitterProperties: { moduleEnabled: { EmitterState: true } }, save: false }, expected: 'success' },
  { scenario: 'CONFIG: set_emitter_properties refuses a module the emitter lacks', toolName: 'manage_effect', arguments: { action: 'set_emitter_properties', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, emitterProperties: { moduleEnabled: { NoSuchModule: false } }, save: false }, expected: 'error|MODULE_NOT_FOUND' },
  { scenario: 'CONFIG: set_emitter_properties refuses an unsupported key',toolName: 'manage_effect', arguments: { action: 'set_emitter_properties', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, emitterProperties: { enabled: true, localSpace: true }, save: false }, expected: 'error|UNSUPPORTED_PROPERTY' },
  { scenario: 'ADD: add_spawn_rate_module', toolName: 'manage_effect', arguments: { action: 'add_spawn_rate_module', systemPath: SYSTEM_PATH, emitter: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'spawn_rate module added to the stack' }] },
  { scenario: 'ADD: add_spawn_burst_module', toolName: 'manage_effect', arguments: { action: 'add_spawn_burst_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'spawn_burst module added to the stack' }] },
  { scenario: 'ADD: add_spawn_per_unit_module', toolName: 'manage_effect', arguments: { action: 'add_spawn_per_unit_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'spawn_per_unit module added to the stack' }] },
  { scenario: 'ADD: add_initialize_particle_module', toolName: 'manage_effect', arguments: { action: 'add_initialize_particle_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'initialize_particle module added to the stack' }] },
  { scenario: 'ADD: add_particle_state_module', toolName: 'manage_effect', arguments: { action: 'add_particle_state_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_force_module', toolName: 'manage_effect', arguments: { action: 'add_force_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, forceType: 'Gravity', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'force module added to the stack' }, { path: 'structuredContent.result.forceType', equals: 'Gravity', label: 'forceType selected the gravity module' }] },
  { scenario: 'ADD: add_velocity_module', toolName: 'manage_effect', arguments: { action: 'add_velocity_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, velocityMode: 'Linear', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'velocity module added to the stack' }, { path: 'structuredContent.result.velocityMode', equals: 'Linear', label: 'velocityMode selected the linear module' }] },
  { scenario: 'ADD: add_acceleration_module', toolName: 'manage_effect', arguments: { action: 'add_acceleration_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'acceleration module added to the stack' }] },
  { scenario: 'ADD: add_size_module', toolName: 'manage_effect', arguments: { action: 'add_size_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'size module added to the stack' }] },
  { scenario: 'ADD: add_color_module', toolName: 'manage_effect', arguments: { action: 'add_color_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'color module added to the stack' }] },
  { scenario: 'ADD: add_sprite_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_sprite_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, materialPath: BASIC_MATERIAL, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_sprite_renderer_module with a missing material is refused', toolName: 'manage_effect', arguments: { action: 'add_sprite_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, materialPath: `/Game/MCPTest/NoSuchMaterial_${ts}.NoSuchMaterial_${ts}`, save: false }, expected: 'error|ASSET_NOT_FOUND' },
  { scenario: 'ADD: add_mesh_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_mesh_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, meshPath: CUBE_MESH, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_ribbon_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_ribbon_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, materialPath: BASIC_MATERIAL, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_light_renderer_module', toolName: 'manage_effect', arguments: { action: 'add_light_renderer_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, lightRadius: 1.5, save: false }, expected: 'success|already exists' },
  { scenario: 'ADD: add_collision_module', toolName: 'manage_effect', arguments: { action: 'add_collision_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'collision module added to the stack' }] },
  { scenario: 'ADD: add_kill_particles_module', toolName: 'manage_effect', arguments: { action: 'add_kill_particles_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'kill_particles module added to the stack' }] },
  { scenario: 'ADD: add_camera_offset_module', toolName: 'manage_effect', arguments: { action: 'add_camera_offset_module', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.moduleAdded', equals: true, label: 'camera_offset module added to the stack' }] },
  { scenario: 'ADD: add_user_parameter', toolName: 'manage_effect', arguments: { action: 'add_user_parameter', systemPath: SYSTEM_PATH, parameterName: USER_PARAM, parameterType: 'Float', save: false }, expected: 'success|already exists' },
  { scenario: 'CONFIG: set_parameter_value', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', systemPath: SYSTEM_PATH, parameterName: USER_PARAM, parameterValue: 2.5, save: false }, expected: 'success' },
  // The system is named by systemPath or assetPath on every edit (the handlers read both); the record used to declare one per variant.
  { scenario: 'CONFIG: set_parameter_value names the system as assetPath', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', assetPath: SYSTEM_PATH, parameterName: USER_PARAM, parameterValue: 3, save: false }, expected: 'success' },
  { scenario: 'CONFIG: set_parameter_value on one emitter\'s module input', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: 'SpawnRate.SpawnRate', parameterValue: 40, save: false }, expected: 'success|not found' },
  // A list of values in one call: every entry written and reported, the system saved once.
  { scenario: 'ADD: add_user_parameter for the parameters list', toolName: 'manage_effect', arguments: { action: 'add_user_parameter', systemPath: SYSTEM_PATH, parameterName: USER_PARAM_B, parameterType: 'Float', save: false }, expected: 'success|already exists' },
  { scenario: 'CONFIG: set_parameter_value with a parameters list writes every entry', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', systemPath: SYSTEM_PATH, parameters: [{ parameterName: USER_PARAM, parameterValue: 4 }, { parameterName: USER_PARAM_B, parameterValue: 5 }], save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.applied', equals: 2, label: 'both values were written' }, { path: 'structuredContent.result.parameters', length: 2, label: 'each entry is reported' }, { path: 'structuredContent.result.parameters.1.parameterName', equals: USER_PARAM_B, label: 'in the order sent' }, { path: 'structuredContent.result.parameters.1.applied', equals: true, label: 'as applied' }] },
  { scenario: 'ERROR: set_parameter_value with a parameters list names the entry that did not apply', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', systemPath: SYSTEM_PATH, parameters: [{ parameterName: USER_PARAM, parameterValue: 1 }, { parameterName: `MCPMissingParam_${ts}`, parameterValue: 1 }], save: false }, expected: 'error|PARAMETER_BATCH_INCOMPLETE' },
  { scenario: 'ERROR: set_parameter_value refuses parameters beside a parameterName', toolName: 'manage_effect', arguments: { action: 'set_parameter_value', systemPath: SYSTEM_PATH, parameterName: USER_PARAM, parameterValue: 1, parameters: [{ parameterName: USER_PARAM, parameterValue: 2 }], save: false }, expected: 'error|not both' },
  // The asset form of set_niagara_parameter sets the user parameter default (it used to answer "Actor '' not found").
  { scenario: 'CONFIG: set_niagara_parameter on the system asset', toolName: 'manage_effect', arguments: { action: 'set_niagara_parameter', assetPath: SYSTEM_PATH, parameterName: USER_PARAM, value: 3.5 }, expected: 'success', assertions: [{ path: 'structuredContent.result.parameterName', equals: USER_PARAM, label: 'user parameter default set on the asset' }] },
  { scenario: 'CONNECT: bind_parameter_to_source applies real assignment binding', toolName: 'manage_effect', arguments: { action: 'bind_parameter_to_source', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: BOUND_PARAM, parameterType: 'Float', sourceBinding: 'Emitter.Age', save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.bindingApplied', equals: true, label: 'real Niagara parameter binding applied' }, { path: 'structuredContent.result.assignmentModuleAdded', equals: true, label: 'assignment module added to Niagara stack' }, { path: 'structuredContent.result.niagaraDefaultSource', equals: 'Emitter Age', label: 'Emitter.Age normalized to Niagara engine constant' }] },
  { scenario: 'CONNECT: add fresh module for dynamic input test', toolName: 'manage_effect', arguments: { action: 'add_niagara_module', assetPath: SYSTEM_PATH, systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, modulePath: '/Niagara/Modules/Emitter/EmitterState.EmitterState', scriptType: 'Update', name: `Testniagara_module_di_${ts}` }, expected: 'success|already exists', captureResult: { key: 'niagaraDIModuleNodeId', fromField: 'result.nodeId' } },
  { scenario: 'CONNECT: set_niagara_dynamic_input attaches DI to module input', toolName: 'manage_effect', arguments: { action: 'set_niagara_dynamic_input', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, targetNodeId: '${captured:niagaraDIModuleNodeId}', inputName: 'EmitterState.ScaleSpawnCountCurve', dynamicInputScriptPath: '/Niagara/DynamicInputs/Add/Add_Float.Add_Float', replaceExisting: false, save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.dynamicInputNodeId', label: 'dynamic input node GUID returned for recursive chaining' }], captureResult: { key: 'niagaraDynamicInputNodeId', fromField: 'result.dynamicInputNodeId' } },
  // Targets the suite's OWN system, whose SpawnRate module was added above.
  // This was pinned to a hardcoded '/Game/FX/NS_Test' that no suite creates and
  // nothing else references, so it always short-circuited on not-found and never
  // reached the moduleName resolution it exists to cover. `not found` stays
  // allowed, so retargeting cannot introduce a failure.
  { scenario: 'NIAGARA: set_niagara_dynamic_input by module name', toolName: 'manage_effect', arguments: { action: 'set_niagara_dynamic_input', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, moduleName: 'SpawnRate', inputName: 'SpawnRate', dynamicInputScriptPath: '/Niagara/DynamicInputs/Add/Add_Float.Add_Float', save: false }, expected: 'success|not found' },
  { scenario: 'ADD: add_skeletal_mesh_data_interface', toolName: 'manage_effect', arguments: { action: 'add_skeletal_mesh_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPSkelDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'skeletal mesh data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_static_mesh_data_interface', toolName: 'manage_effect', arguments: { action: 'add_static_mesh_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPStaticDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'static mesh data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_spline_data_interface', toolName: 'manage_effect', arguments: { action: 'add_spline_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPSplineDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'spline data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_audio_spectrum_data_interface', toolName: 'manage_effect', arguments: { action: 'add_audio_spectrum_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPAudioDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'audio spectrum data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_collision_query_data_interface', toolName: 'manage_effect', arguments: { action: 'add_collision_query_data_interface', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, parameterName: `MCPCollisionDI_${ts}`, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.dataInterfaceAdded', equals: true, label: 'collision query data interface added to exposed parameters' }] },
  { scenario: 'ADD: add_event_generator', toolName: 'manage_effect', arguments: { action: 'add_event_generator', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, eventName: EVENT_NAME, eventType: 'Location', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.eventGeneratorAdded', equals: true, label: 'event generator mutation recorded' }] },
  { scenario: 'ADD: add_event_receiver', toolName: 'manage_effect', arguments: { action: 'add_event_receiver', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, eventName: EVENT_NAME, spawnOnEvent: true, eventSpawnCount: 2, save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.eventHandlerAdded', equals: true, label: 'event handler added to Niagara emitter' }, { path: 'structuredContent.result.eventGraphCreated', equals: true, label: 'event handler output graph created' }, { path: 'structuredContent.result.spawnOnEvent', equals: true, label: 'spawnOnEvent reached native event receiver' }] },
  { scenario: 'TOGGLE: enable_gpu_simulation names the system as assetPath', toolName: 'manage_effect', arguments: { action: 'enable_gpu_simulation', assetPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, fixedBoundsEnabled: true, save: false }, expected: 'success' },
  { scenario: 'TOGGLE: enable_gpu_simulation', toolName: 'manage_effect', arguments: { action: 'enable_gpu_simulation', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, fixedBoundsEnabled: true, deterministicEnabled: true, save: false }, expected: 'success', assertions: [{ path: 'structuredContent.result.fixedBoundsEnabled', equals: true, label: 'fixedBoundsEnabled reached native GPU configuration' }, { path: 'structuredContent.result.deterministicEnabled', equals: true, label: 'deterministicEnabled reached native GPU configuration' }] },
  { scenario: 'ADD: add_simulation_stage', toolName: 'manage_effect', arguments: { action: 'add_simulation_stage', systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, stageName: STAGE_NAME, stageIterationSource: 'Particles', save: false }, expected: 'success|already exists', assertions: [{ path: 'structuredContent.result.simulationStageAdded', equals: true, label: 'simulation stage added to Niagara emitter' }, { path: 'structuredContent.result.simulationStageGraphCreated', equals: true, label: 'simulation stage output graph created' }, { path: 'structuredContent.result.iterationSource', equals: 'Particles', label: 'stageIterationSource reached native stage configuration' }] },
  { scenario: 'INFO: get_niagara_info', toolName: 'manage_effect', arguments: { action: 'get_niagara_info', assetPath: SYSTEM_PATH }, expected: 'success' },
  { scenario: 'INFO: get_niagara_info through params envelope', toolName: 'manage_effect', arguments: { action: 'get_niagara_info', params: { assetPath: SYSTEM_PATH } }, expected: 'success', assertions: [{ path: 'structuredContent.result.emitterCount', gte: 0, label: 'params envelope merged into the action arguments' }] },
  { scenario: 'INFO: get_niagara_info by systemPath, which validate takes as well', toolName: 'manage_effect', arguments: { action: 'get_niagara_info', systemPath: SYSTEM_PATH }, expected: 'success', assertions: [{ path: 'structuredContent.result.niagaraInfo.assetType', equals: 'System', label: 'the system was read, not validated, through its systemPath' }] },
  { scenario: 'INFO: get_niagara_info by system', toolName: 'manage_effect', arguments: { action: 'get_niagara_info', system: SYSTEM_PATH }, expected: 'success', assertions: [{ path: 'structuredContent.result.niagaraInfo.assetType', equals: 'System', label: 'the system alias reaches the inspector too' }] },
  { scenario: 'ACTION: validate_niagara_system', toolName: 'manage_effect', arguments: { action: 'validate_niagara_system', system: SYSTEM_PATH }, expected: 'success' },

  // === CLEANUP ===
  { scenario: 'Cleanup: remove dynamic input node', toolName: 'manage_effect', arguments: { action: 'remove_niagara_node', assetPath: SYSTEM_PATH, systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, scriptType: 'Update', nodeId: '${captured:niagaraDynamicInputNodeId}' }, expected: 'success|not found' },
  { scenario: 'Cleanup: remove dynamic input test module', toolName: 'manage_effect', arguments: { action: 'remove_niagara_node', assetPath: SYSTEM_PATH, systemPath: SYSTEM_PATH, emitterName: DEFAULT_EMITTER, scriptType: 'Update', nodeId: '${captured:niagaraDIModuleNodeId}' }, expected: 'success|not found' },
  { scenario: 'Cleanup: delete spawned Niagara actor', toolName: 'control_actor', arguments: { action: 'delete', actorName: SPAWNED_EFFECT_ACTOR }, expected: 'success|not found' },
  { scenario: 'Cleanup: delete primary Niagara actor', toolName: 'control_actor', arguments: { action: 'delete', actorName: EFFECT_ACTOR }, expected: 'success|not found' },
  { scenario: 'Cleanup: delete test actor', toolName: 'control_actor', arguments: { action: 'delete', actorName: TEST_ACTOR }, expected: 'success|not found' },
];

runToolTests('manage-effect', testCases, { folder: TEST_FOLDER });
