// scripts/generate-native-headers.ts
// Deterministic generator for the native headers that mirror TypeScript data:
//   - ConsoleCommand/McpAutomationBridge_ConsoleCommandPolicy.generated.h
//       from src/utils/commands/console-command-policy-rules.ts
//   - Foundation/McpTelemetrySchema.h
//       from src/services/telemetry-schema.ts
//
// Run:
//   npm run headers:generate   (generate)
//   npm run headers:check      (CI gate: fails when a header drifts)
//
// The TypeScript side evaluates its own data directly; the C++ compiles these.

import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { reportDrift, writeGeneratedFiles } from './lib/generated-files.js';
import { CONSOLE_COMMAND_POLICY_RULES } from '../src/utils/commands/console-command-policy-rules.js';
import {
  TELEMETRY_ACTION_CLASSES,
  TELEMETRY_FAILURE_CLASSES,
  TELEMETRY_LABEL_NAMES,
  TELEMETRY_LATENCY_BUCKETS_SECONDS,
  TELEMETRY_METRIC_NAMES,
  TELEMETRY_OUTCOMES,
  TELEMETRY_QUANTILES,
  TELEMETRY_READINESS_COMPONENTS,
  TELEMETRY_SURFACES,
} from '../src/services/telemetry-schema.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const PRIVATE = resolve(root, 'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private');
const POLICY_PATH = resolve(PRIVATE, 'Domains/ConsoleCommand/McpAutomationBridge_ConsoleCommandPolicy.generated.h');
const TELEMETRY_PATH = resolve(PRIVATE, 'Foundation/McpTelemetrySchema.h');

const GENERATED_HEADER = `// GENERATED by scripts/generate-native-headers.ts -- do not edit.
`;

function emitNativeArray(name: string, items: readonly string[]): string {
  if (items.length === 0) {
    return `    static const TCHAR* const ${name}[] = {};\n`;
  }
  return (
    `    static const TCHAR* const ${name}[] = {\n` +
    items.map((item) => `        TEXT(${JSON.stringify(item)})`).join(',\n') +
    ',\n    };\n'
  );
}

function buildNativeContent(): string {
  // Native artifact sources ONLY rules that apply to the native surface
  // (appliesTo === 'native' || 'both'). This guarantees zero runtime delta:
  // TS-only rules (flexible-import, flexible-call, dunder, os-system, etc.)
  // must never leak into the native validator.
  const nativeRules = CONSOLE_COMMAND_POLICY_RULES.filter((r) => r.appliesTo !== 'typescript');

  const collectFirstToken = (reason: string): string[] => {
    const out: string[] = [];
    for (const r of nativeRules) {
      if (r.reasonCode === reason && r.matcher.kind === 'first-token') {
        out.push(...r.matcher.values);
      }
    }
    return Array.from(new Set(out));
  };
  const collectContains = (reason: string): string[] => {
    const out: string[] = [];
    for (const r of nativeRules) {
      if (r.reasonCode === reason && r.matcher.kind === 'contains-any') {
        out.push(...r.matcher.values);
      }
    }
    return Array.from(new Set(out));
  };

  // UNSAFE_SEPARATORS come from the shared.unsafe-separator rule (applies to both).
  const separatorRule = CONSOLE_COMMAND_POLICY_RULES.find(
    (r) => r.id === 'shared.unsafe-separator',
  );
  const tsUnsafeSeparators =
    separatorRule && separatorRule.matcher.kind === 'contains-any'
      ? Array.from(separatorRule.matcher.values)
      : [];
  // PYTHON first-token ('both') folds into BLOCKED_COMMANDS so the native
  // validator can drop its separate py/python Equals check without behavior change.
  const blocked = collectFirstToken('DANGEROUS_ENGINE_COMMAND')
    .concat(collectFirstToken('PYTHON_EXECUTION'));
  const restricted = collectFirstToken('RESTRICTED_ENGINE_COMMAND');
  const forbiddenNames = collectFirstToken('SHELL_COMMAND');
  const forbiddenTokens = collectContains('UNSAFE_TOKEN');

  return (
    GENERATED_HEADER +
    '// One canonical console-command policy shared by the native validator.\n' +
    '// Source of truth: src/utils/commands/console-command-policy-rules.ts.\n' +
    '// GENERATED artifacts are never hand-edited; re-run the generator after a rule change.\n' +
    '#pragma once\n' +
    '#include "CoreMinimal.h"\n\n' +
    'namespace McpGeneratedConsoleCommandPolicy\n{\n' +
    '    // Unsafe separators checked on both surfaces.\n' +
    '    static const TCHAR* const UNSAFE_SEPARATORS[] = {\n' +
    tsUnsafeSeparators.map((sep) => `        TEXT(${JSON.stringify(sep)})`).join(',\n') +
    ',\n    };\n\n' +
    '    // Commands blocked for security (DANGEROUS/RESTRICTED engine commands, py/python).\n' +
    emitNativeArray('BLOCKED_COMMANDS', blocked) +
    '\n' +
    emitNativeArray('RESTRICTED_COMMANDS', restricted) +
    '\n' +
    emitNativeArray('FORBIDDEN_COMMAND_NAMES', forbiddenNames) +
    '\n' +
    emitNativeArray('FORBIDDEN_TOKENS', forbiddenTokens) +
    '}\n'
  );
}

// ----------------------------------------------------------------------------
// Telemetry schema: the whole native header comes from src/services/telemetry-schema.ts.
// ----------------------------------------------------------------------------

const upperFirst = (key: string): string => key.charAt(0).toUpperCase() + key.slice(1);

function emitStringSet(name: string, values: readonly string[]): string {
  return (
    `\tinline const TArray<FString>& ${name}()\n\t{\n\t\tstatic const TArray<FString> Values = {\n` +
    values.map((value) => `\t\t\tTEXT(${JSON.stringify(value)}),`).join('\n') +
    '\n\t\t};\n\t\treturn Values;\n\t}\n'
  );
}

function emitNumberSet(name: string, values: readonly number[]): string {
  return (
    `\tinline const TArray<double>& ${name}()\n\t{\n\t\tstatic const TArray<double> Values = {\n` +
    `\t\t\t${values.map(String).join(', ')},\n\t\t};\n\t\treturn Values;\n\t}\n`
  );
}

function buildTelemetryContent(): string {
  const metricNames = Object.entries(TELEMETRY_METRIC_NAMES)
    .map(([key, value]) => `\tinline const TCHAR* Metric${upperFirst(key)}() { return TEXT(${JSON.stringify(value)}); }`)
    .join('\n');
  const labelNames = Object.entries(TELEMETRY_LABEL_NAMES)
    .map(([key, value]) => `\tinline const TCHAR* Label${upperFirst(key)}() { return TEXT(${JSON.stringify(value)}); }`)
    .join('\n');
  return `${GENERATED_HEADER}// Source of truth: src/services/telemetry-schema.ts (the TypeScript surface
// exports the same metric names, labels, value sets, buckets and quantiles).
//
// Cardinality is a SECURITY boundary. Every label value below comes from a
// closed set, and Coerce* maps anything unresolved to "unknown" rather than
// passing it through. Capability ids, asset/file paths, tokens, prompts, project
// content, session ids and request ids are never dimensions.
#pragma once

#include "CoreMinimal.h"

namespace McpTelemetrySchema
{
${metricNames}

${labelNames}

${emitStringSet('SurfaceValues', TELEMETRY_SURFACES)}
${emitStringSet('ActionClassValues', TELEMETRY_ACTION_CLASSES)}
${emitStringSet('OutcomeValues', TELEMETRY_OUTCOMES)}
${emitStringSet('FailureClassValues', TELEMETRY_FAILURE_CLASSES)}
${emitStringSet('ReadinessComponentValues', TELEMETRY_READINESS_COMPONENTS)}
${emitNumberSet('LatencyBucketUpperBoundsSeconds', TELEMETRY_LATENCY_BUCKETS_SECONDS)}
${emitNumberSet('Quantiles', TELEMETRY_QUANTILES)}
\tinline FString UnknownValue() { return TEXT("unknown"); }

\tinline FString CoerceFromSet(const TArray<FString>& Allowed, const FString& Candidate, const FString& Fallback)
\t{
\t\tconst FString Normalized = Candidate.TrimStartAndEnd().ToLower();
\t\treturn Allowed.Contains(Normalized) ? Normalized : Fallback;
\t}

\tinline FString CoerceSurface(const FString& Candidate)
\t{
\t\treturn CoerceFromSet(SurfaceValues(), Candidate, TEXT("native"));
\t}

\t/** Unresolved input becomes "unknown"; it is never passed through as a label. */
\tinline FString CoerceActionClass(const FString& Candidate)
\t{
\t\treturn CoerceFromSet(ActionClassValues(), Candidate, UnknownValue());
\t}

\tinline FString CoerceOutcome(const FString& Candidate)
\t{
\t\treturn CoerceFromSet(OutcomeValues(), Candidate, TEXT("success"));
\t}

\t/** Accepts the shared refusal codes in any case/dash form, else "unknown". */
\tinline FString CoerceFailureClass(const FString& Candidate)
\t{
\t\tFString Normalized = Candidate.TrimStartAndEnd().ToLower();
\t\tNormalized.ReplaceInline(TEXT("-"), TEXT("_"));
\t\treturn CoerceFromSet(FailureClassValues(), Normalized, UnknownValue());
\t}
}
`;
}

const targets = (): readonly [string, string][] => [
  [POLICY_PATH, buildNativeContent()],
  [TELEMETRY_PATH, buildTelemetryContent()],
];

function main(): void {
  if (process.argv.slice(2).includes('--check')) {
    if (reportDrift(targets(), 'native-headers', 'npm run headers:generate')) {
      console.error('\n[native-headers] CHECK EXIT=1 (generated headers drifted)');
      process.exit(1);
    }
    console.error('[native-headers] CHECK EXIT=0 (generated headers up to date)');
    process.exit(0);
  }
  writeGeneratedFiles(targets());
  console.error('[native-headers] GENERATED console policy and telemetry schema headers');
  process.exit(0);
}

try {
  main();
} catch (error: unknown) {
  const message = error instanceof Error ? (error.stack ?? error.message) : String(error);
  console.error('[native-headers] generator failed:', message);
  process.exit(1);
}
