// scripts/generate-gateway-manifest.ts
// Deterministic generator for the neutral gateway manifest.
// Source of truth: src/tools/catalog/consolidated-tool-definitions.ts
// Emits three artifacts from one in-memory model (no hand-maintained drift):
//   - src/gateway/gateway-manifest.generated.ts  (runtime import; compiled into dist)
//   - src/gateway/gateway-manifest.generated.json (neutral asset; parity/test source)
//   - plugins/.../Gateway/McpNativeGatewayManifest.h (compact embedded JSON for native)
// Run: node --loader ts-node/esm scripts/generate-gateway-manifest.ts [generate|check]

import { writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { consolidatedToolDefinitions, type ToolDefinition } from '../src/tools/catalog/consolidated-tool-definitions.js';
import { isRecord } from '../src/utils/validation/type-guards.js';

export type GatewayManifestTool = {
  name: string;
  category: string | null;
  description: string;
  actions: string[];
  parameterNames: string[];
  inputSchema: Record<string, unknown>;
  perActionSchemas: boolean;
};
export type GatewayManifest = { version: number; source: string; tools: GatewayManifestTool[] };

function actionValues(tool: ToolDefinition): string[] {
  const props = isRecord(tool.inputSchema.properties) ? tool.inputSchema.properties : {};
  const action = isRecord(props.action) ? props.action : undefined;
  return Array.isArray(action?.enum)
    ? action.enum.filter((v): v is string => typeof v === 'string')
    : [];
}
function parameterNames(tool: ToolDefinition): string[] {
  const props = isRecord(tool.inputSchema.properties) ? tool.inputSchema.properties : {};
  return Object.keys(props).filter((n) => n !== 'action' && n !== 'subAction' && n !== 'params').sort();
}

export function buildGatewayManifest(defs: readonly ToolDefinition[]): GatewayManifest {
  return {
    version: 1,
    source: 'consolidatedToolDefinitions',
    tools: defs.map((tool) => ({
      name: tool.name,
      category: tool.category ?? null,
      description: tool.description,
      actions: actionValues(tool),
      parameterNames: parameterNames(tool),
      inputSchema: tool.inputSchema as Record<string, unknown>,
      perActionSchemas: false,
    })),
  };
}

export const prettyManifest = (defs: readonly ToolDefinition[]): string => JSON.stringify(buildGatewayManifest(defs), null, 2);
export const compactManifest = (defs: readonly ToolDefinition[]): string => JSON.stringify(buildGatewayManifest(defs));

const MANIFEST_H = (compact: string): string =>
`// GENERATED by scripts/generate-gateway-manifest.ts -- do not edit.
// Mirrors src/gateway/gateway-manifest.generated.json for native MCP consumption.
// Include AFTER McpNativeGatewayCatalog.h so GatewayError/GatewayStringArray resolve.
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"

class FMcpDynamicToolManager;

struct FGatewayManifestTool
{
	FString Name;
	FString Category;
	FString Description;
	TArray<FString> Actions;
	TArray<FString> ParameterNames;
	TSharedPtr<FJsonObject> InputSchema;
};

inline bool TryLoadGatewayManifest(TArray<FGatewayManifestTool>& OutTools)
{
	static constexpr const TCHAR* GatewayManifestJson = TEXT(R"MCPGWMANIFEST(
${compact}
)MCPGWMANIFEST");
	OutTools.Reset();
	const FString Json(GatewayManifestJson);
	TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Json);
	TSharedPtr<FJsonObject> Root;
	if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid()) return false;
	const TArray<TSharedPtr<FJsonValue>>* Tools = nullptr;
	if (!Root->TryGetArrayField(TEXT("tools"), Tools) || !Tools) return false;
	for (const TSharedPtr<FJsonValue>& V : *Tools)
	{
		const TSharedPtr<FJsonObject>* Obj = nullptr;
		if (!V->TryGetObject(Obj) || !Obj || !(*Obj).IsValid()) return false;
		const TSharedPtr<FJsonObject>& T = *Obj;
		FGatewayManifestTool M;
		T->TryGetStringField(TEXT("name"), M.Name);
		FString Cat;
		if (T->TryGetStringField(TEXT("category"), Cat)) M.Category = Cat;
		T->TryGetStringField(TEXT("description"), M.Description);
		const TArray<TSharedPtr<FJsonValue>>* A = nullptr;
		if (T->TryGetArrayField(TEXT("actions"), A) && A)
			for (const TSharedPtr<FJsonValue>& E : *A) { FString S; if (E->TryGetString(S)) M.Actions.AddUnique(S); }
		const TArray<TSharedPtr<FJsonValue>>* P = nullptr;
		if (T->TryGetArrayField(TEXT("parameterNames"), P) && P)
			for (const TSharedPtr<FJsonValue>& E : *P) { FString S; if (E->TryGetString(S)) M.ParameterNames.AddUnique(S); }
		const TSharedPtr<FJsonObject>* Sch = nullptr;
		if (T->TryGetObjectField(TEXT("inputSchema"), Sch) && Sch) M.InputSchema = *Sch;
		OutTools.Add(MoveTemp(M));
	}
	return OutTools.Num() > 0;
}

// Catalog (search) sourced from the neutral manifest; null -> caller falls back to registry.
inline TSharedPtr<FJsonObject> GatewaySearchFromManifest(
	const FString& Query, int32 Limit, int32 Offset, const FMcpDynamicToolManager& ToolManager)
{
	TArray<FGatewayManifestTool> Tools;
	if (!TryLoadGatewayManifest(Tools)) return nullptr;
	const FString Q = Query.ToLower();
	TArray<TSharedPtr<FJsonObject>> Matches;
	for (const FGatewayManifestTool& M : Tools)
	{
		if (!Q.IsEmpty())
		{
			FString S = M.Name + TEXT(" ") + M.Category + TEXT(" ") + M.Description;
			for (const FString& A : M.Actions) S += TEXT(" ") + A;
			if (!S.ToLower().Contains(Q)) continue;
		}
		auto D = MakeShared<FJsonObject>();
		D->SetStringField(TEXT("name"), M.Name);
		D->SetStringField(TEXT("category"), M.Category);
		D->SetStringField(TEXT("description"), M.Description);
		D->SetArrayField(TEXT("actions"), GatewayStringArray(M.Actions));
		D->SetArrayField(TEXT("parameterNames"), GatewayStringArray(M.ParameterNames));
		D->SetBoolField(TEXT("enabled"), ToolManager.IsToolEnabled(M.Name));
		Matches.Add(D);
	}
	const int32 Total = Matches.Num();
	TArray<TSharedPtr<FJsonObject>> Results;
	for (int32 i = Offset; i < Total && Results.Num() < Limit; ++i) Results.Add(Matches[i]);
	auto Out = MakeShared<FJsonObject>();
	Out->SetBoolField(TEXT("success"), true);
	Out->SetStringField(TEXT("operation"), TEXT("search"));
	Out->SetStringField(TEXT("query"), Query);
	TArray<TSharedPtr<FJsonValue>> RV;
	for (const TSharedPtr<FJsonObject>& R : Results) RV.Add(MakeShared<FJsonValueObject>(R));
	Out->SetArrayField(TEXT("results"), RV);
	Out->SetNumberField(TEXT("total"), Total);
	Out->SetNumberField(TEXT("offset"), Offset);
	Out->SetNumberField(TEXT("limit"), Limit);
	Out->SetBoolField(TEXT("hasMore"), Offset + Results.Num() < Total);
	Out->SetStringField(TEXT("message"),
		TEXT("Search results are compact. Call describe with an exact tool and action before execute."));
	return Out;
}

// Definition (describe) sourced from the neutral manifest; null -> caller falls back to registry.
inline TSharedPtr<FJsonObject> GatewayDescribeFromManifest(
	const FString& ToolName, const FString& Action, const FMcpDynamicToolManager& ToolManager)
{
	TArray<FGatewayManifestTool> Tools;
	if (!TryLoadGatewayManifest(Tools)) return nullptr;
	const FGatewayManifestTool* M = Tools.FindByPredicate(
		[&](const FGatewayManifestTool& X) { return X.Name == ToolName; });
	if (!M) return nullptr;
	const TArray<FString>& Actions = M->Actions;
	if (!Action.IsEmpty() && !Actions.Contains(Action))
	{
		TSharedPtr<FJsonObject> Err = GatewayError(TEXT("describe"), TEXT("UNKNOWN_ACTION"),
			FString::Printf(TEXT("Unknown action '%s' for %s."), *Action, *ToolName));
		Err->SetStringField(TEXT("tool"), ToolName);
		Err->SetArrayField(TEXT("availableActions"), GatewayStringArray(Actions));
		return Err;
	}
	TArray<FString> OutActions = Action.IsEmpty() ? Actions : TArray<FString>{ Action };
	auto Out = MakeShared<FJsonObject>();
	Out->SetBoolField(TEXT("success"), true);
	Out->SetStringField(TEXT("operation"), TEXT("describe"));
	Out->SetStringField(TEXT("tool"), ToolName);
	Out->SetStringField(TEXT("action"), Action);
	Out->SetStringField(TEXT("category"), M->Category);
	Out->SetStringField(TEXT("description"), M->Description);
	Out->SetBoolField(TEXT("enabled"), ToolManager.IsToolEnabled(ToolName));
	Out->SetArrayField(TEXT("actions"), GatewayStringArray(OutActions));
	Out->SetArrayField(TEXT("parameterNames"), GatewayStringArray(M->ParameterNames));
	Out->SetObjectField(TEXT("inputSchema"), M->InputSchema.IsValid() ? M->InputSchema.ToSharedRef() : MakeShared<FJsonObject>());
	Out->SetBoolField(TEXT("perActionSchemas"), false);
	Out->SetStringField(TEXT("message"),
		TEXT("The canonical catalog does not register per-action parameter schemas. "
			"parameterNames is the union across all actions - pass only parameters "
			"relevant to the selected action. Use the exact casing shown in inputSchema."));
	return Out;
}
`;

function main(): void {
  const pretty = prettyManifest(consolidatedToolDefinitions);
  const compact = compactManifest(consolidatedToolDefinitions);
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const targets: Array<[string, string]> = [
    [resolve(root, 'src/gateway/gateway-manifest.generated.ts'), `/* eslint-disable */\n// GENERATED by scripts/generate-gateway-manifest.ts -- do not edit.\n// Re-run the generator after changing canonical tool definitions.\nexport const gatewayManifest = ${pretty};\n`],
    [resolve(root, 'src/gateway/gateway-manifest.generated.json'), pretty + '\n'],
    [resolve(root, 'plugins/McpAutomationBridge/Source/McpAutomationBridge/Private/MCP/Gateway/McpNativeGatewayManifest.h'), MANIFEST_H(compact)],
  ];
  const mode = process.argv.includes('--check') ? 'check' : 'generate';
  let drift = false;
  for (const [path, content] of targets) {
    if (mode === 'check') {
      if (readFileSync(path, 'utf8') !== content) {
        console.error(`[gateway-manifest] DRIFT: ${path} is stale. Run scripts/generate-gateway-manifest.ts`);
        drift = true;
      }
    } else {
      writeFileSync(path, content);
    }
  }
  if (mode === 'check') {
    if (drift) process.exitCode = 1;
    else console.log('[gateway-manifest] check: manifest artifacts are up to date.');
  } else {
    console.log(`[gateway-manifest] wrote ${targets.length} manifest artifacts.`);
  }
}

if (process.argv[1] && process.argv[1].endsWith('generate-gateway-manifest.ts')) main();
