/**
 * manage_gas capability records: editor authoring of GAS assets, gated by the
 * GameplayAbilities plugin (native returns EDITOR_ONLY when it is absent).
 *
 * Each record declares exactly the parameters its own action accepts, from the
 * fields the matching native handler reads. Action-specific parameters live in
 * ./gas.props.ts; only genuinely shared ones come from ../properties.js.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { buildRecord } from '../helpers.js';
import { P } from '../properties.js';
import { GAS_P as G } from './gas.props.js';

const T = 'manage_gas';
const F = 'gas';
const W = ['A Gameplay Ability System asset must be authored.'];
const GAS_PLUGIN = ['GameplayAbilities'];

export const GAS_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({ parentTool: T, id: `${T}.add_ability_system_component`, action: 'add_ability_system_component', family: F,
    summary: 'Add an AbilitySystemComponent to a Blueprint.', whenToUse: W, whenNotToUse: ['Component exists.'],
    inputProps: { blueprintPath: P.blueprintPath, componentName: G.componentName }, required: ['blueprintPath'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_ability_system_component', blueprintPath: '/Game/BP_Char', componentName: 'AbilitySystemComponent' } }),
  buildRecord({ parentTool: T, id: `${T}.configure_asc`, action: 'configure_asc', family: F,
    summary: 'Configure an AbilitySystemComponent.', whenToUse: ['ASC defaults must change.'], whenNotToUse: ['Use add_ability_system_component.'],
    inputProps: { blueprintPath: P.blueprintPath, componentName: G.componentName, replicationMode: G.replicationMode }, required: ['blueprintPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'configure_asc', blueprintPath: '/Game/BP_Char', replicationMode: 'Mixed' } }),
  buildRecord({ parentTool: T, id: `${T}.create_attribute_set`, action: 'create_attribute_set', family: F,
    summary: 'Create an AttributeSet class/asset.', whenToUse: W, whenNotToUse: ['Use add_attribute.'],
    inputProps: { name: P.name, path: P.path }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_attribute_set', name: 'AS_Char' } }),
  buildRecord({ parentTool: T, id: `${T}.add_attribute`, action: 'add_attribute', family: F,
    summary: 'Add an attribute to an AttributeSet.', whenToUse: ['An attribute is needed.'], whenNotToUse: ['Use create_attribute_set.'],
    inputProps: { attributeSetPath: P.attributeSetPath, attributeName: P.attributeName, attributeType: G.attributeType, defaultValue: G.defaultValue }, required: ['attributeSetPath', 'attributeName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_attribute', attributeSetPath: '/Game/AS_Char', attributeName: 'Health', attributeType: 'Health', defaultValue: 100 } }),
  buildRecord({ parentTool: T, id: `${T}.set_attribute_base_value`, action: 'set_attribute_base_value', family: F,
    summary: 'Set an attribute base value.', whenToUse: ['Default value must change.'], whenNotToUse: ['Use add_attribute.'],
    inputProps: { attributeSetPath: P.attributeSetPath, attributeName: P.attributeName, baseValue: G.baseValue }, required: ['attributeSetPath', 'attributeName'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_attribute_base_value', attributeSetPath: '/Game/AS_Char', attributeName: 'Health', baseValue: 100 } }),
  buildRecord({ parentTool: T, id: `${T}.create_gameplay_ability`, action: 'create_gameplay_ability', family: F,
    topics: ['gameplay ability', 'ability', 'gas ability', 'new ability', 'skill'],
    summary: 'Create a Gameplay Ability asset.', whenToUse: W, whenNotToUse: ['Use add_ability_task.'],
    inputProps: { name: P.name, path: P.path }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    outputProps: { assetPath: P.assetPath }, outputRequired: ['assetPath'],
    exampleInput: { action: 'create_gameplay_ability', name: 'GA_Fire' }, exampleOutput: { success: true, message: 'Ability created', assetPath: '/Game/GA_Fire' } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_tags`, action: 'set_ability_tags', family: F,
    summary: 'Configure ability tag requirements/granted.', whenToUse: ['Ability tags must change.'], whenNotToUse: ['Use create_gameplay_ability.'],
    inputProps: { abilityPath: P.abilityPath, abilityTags: G.abilityTags, cancelAbilitiesWithTag: G.cancelAbilitiesWithTag, blockAbilitiesWithTag: G.blockAbilitiesWithTag, activationRequiredTags: G.activationRequiredTags, activationBlockedTags: G.activationBlockedTags }, required: ['abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_tags', abilityPath: '/Game/GA_Fire', abilityTags: ['Ability.Fire'] } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_costs`, action: 'set_ability_costs', family: F,
    summary: 'Configure ability cost (attribute spend).', whenToUse: ['Ability has a cost.'], whenNotToUse: ['Use set_ability_cooldown.'],
    inputProps: { abilityPath: P.abilityPath, costEffectPath: G.costEffectPath }, required: ['abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_costs', abilityPath: '/Game/GA_Fire', costEffectPath: '/Game/GE_ManaCost' } }),
  buildRecord({ parentTool: T, id: `${T}.set_ability_cooldown`, action: 'set_ability_cooldown', family: F,
    summary: 'Configure ability cooldown.', whenToUse: ['Ability needs cooldown.'], whenNotToUse: ['Use set_ability_costs.'],
    inputProps: { abilityPath: P.abilityPath, cooldownEffectPath: G.cooldownEffectPath }, required: ['abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_ability_cooldown', abilityPath: '/Game/GA_Fire', cooldownEffectPath: '/Game/GE_Cooldown' } }),
  buildRecord({ parentTool: T, id: `${T}.set_activation_policy`, action: 'set_activation_policy', family: F,
    summary: 'Configure ability activation policy.', whenToUse: ['Activation trigger must change.'], whenNotToUse: ['Default policy.'],
    inputProps: { abilityPath: P.abilityPath, activationPolicy: G.activationPolicy }, required: ['abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_activation_policy', abilityPath: '/Game/GA_Fire', activationPolicy: 'OnInputPressed' } }),
  buildRecord({ parentTool: T, id: `${T}.set_instancing_policy`, action: 'set_instancing_policy', family: F,
    summary: 'Configure ability instancing policy.', whenToUse: ['Instancing must change.'], whenNotToUse: ['Use set_activation_policy.'],
    inputProps: { abilityPath: P.abilityPath, instancingPolicy: G.instancingPolicy }, required: ['abilityPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_instancing_policy', abilityPath: '/Game/GA_Fire', instancingPolicy: 'InstancedPerActor' } }),
  buildRecord({ parentTool: T, id: `${T}.create_gameplay_effect`, action: 'create_gameplay_effect', family: F,
    summary: 'Create a Gameplay Effect asset.', whenToUse: W, whenNotToUse: ['Use add_effect_modifier.'],
    inputProps: { name: P.name, path: P.path, durationType: G.durationType }, required: ['name'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_gameplay_effect', name: 'GE_Damage', durationType: 'Instant' } }),
  buildRecord({ parentTool: T, id: `${T}.set_effect_duration`, action: 'set_effect_duration', family: F,
    summary: 'Set a Gameplay Effect duration.', whenToUse: ['Effect has a duration.'], whenNotToUse: ['Use create_gameplay_effect.'],
    inputProps: { effectPath: P.effectPath, durationType: G.durationType, duration: P.duration, period: G.period }, required: ['effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_effect_duration', effectPath: '/Game/GE_Damage', durationType: 'HasDuration', duration: 5, period: 1 } }),
  buildRecord({ parentTool: T, id: `${T}.add_effect_modifier`, action: 'add_effect_modifier', family: F,
    summary: 'Add a modifier to a Gameplay Effect.', whenToUse: ['Effect modifies an attribute.'], whenNotToUse: ['Use set_effect_duration.'],
    inputProps: { effectPath: P.effectPath, attributeName: P.attributeName, modifierOperation: G.modifierOperation, modifierMagnitude: G.modifierMagnitude, targetAttribute: G.targetAttribute }, required: ['effectPath', 'attributeName'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_effect_modifier', effectPath: '/Game/GE_Damage', attributeName: 'Health', modifierOperation: 'Add', modifierMagnitude: -10 } }),
  buildRecord({ parentTool: T, id: `${T}.set_modifier_magnitude`, action: 'set_modifier_magnitude', family: F,
    summary: 'Set a modifier magnitude.', whenToUse: ['Modifier amount must change.'], whenNotToUse: ['Use add_effect_modifier.'],
    inputProps: { effectPath: P.effectPath, modifierIndex: G.modifierIndex, modifierMagnitude: G.modifierMagnitude, magnitudeCalculationType: G.magnitudeCalculationType, setByCallerTag: G.setByCallerTag }, required: ['effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_modifier_magnitude', effectPath: '/Game/GE_Damage', modifierIndex: 0, modifierMagnitude: -15 } }),
  buildRecord({ parentTool: T, id: `${T}.add_effect_execution_calculation`, action: 'add_effect_execution_calculation', family: F,
    summary: 'Add an execution calculation to an effect.', whenToUse: ['Complex magnitude calc needed.'], whenNotToUse: ['Simple modifier suffices.'],
    inputProps: { effectPath: P.effectPath, calculationClass: P.string_ }, required: ['effectPath', 'calculationClass'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_effect_execution_calculation', effectPath: '/Game/GE_Damage', calculationClass: '/Script/Game.DamageExecCalc' } }),
  buildRecord({ parentTool: T, id: `${T}.add_effect_cue`, action: 'add_effect_cue', family: F,
    summary: 'Add a gameplay cue to an effect.', whenToUse: ['Effect needs a cue.'], whenNotToUse: ['Use create_gameplay_cue_notify.'],
    inputProps: { effectPath: P.effectPath, cueTag: P.tag }, required: ['effectPath', 'cueTag'],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_effect_cue', effectPath: '/Game/GE_Damage', cueTag: 'GameplayCue.Damage' } }),
  buildRecord({ parentTool: T, id: `${T}.set_effect_stacking`, action: 'set_effect_stacking', family: F,
    summary: 'Configure effect stacking rules.', whenToUse: ['Effects must stack.'], whenNotToUse: ['Use set_effect_duration.'],
    inputProps: { effectPath: P.effectPath, stackingType: G.stackingType, stackLimitCount: G.stackLimitCount, stackDurationRefreshPolicy: G.stackDurationRefreshPolicy, stackPeriodResetPolicy: G.stackPeriodResetPolicy, stackExpirationPolicy: G.stackExpirationPolicy }, required: ['effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_effect_stacking', effectPath: '/Game/GE_Damage', stackingType: 'AggregateByTarget', stackLimitCount: 3 } }),
  buildRecord({ parentTool: T, id: `${T}.set_effect_tags`, action: 'set_effect_tags', family: F,
    summary: 'Configure effect granted, required, removal and immunity tags.', whenToUse: ['Effect tags must change.'], whenNotToUse: ['Use add_effect_cue.'],
    inputProps: { effectPath: P.effectPath, grantedTags: G.grantedTags, applicationRequiredTags: G.applicationRequiredTags, removalTags: G.removalTags, immunityTags: G.immunityTags }, required: ['effectPath'],
    effect: 'write', behavior: { idempotency: 'idempotent' }, latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'set_effect_tags', effectPath: '/Game/GE_Damage', grantedTags: ['State.Burning'] } }),
  buildRecord({ parentTool: T, id: `${T}.create_gameplay_cue_notify`, action: 'create_gameplay_cue_notify', family: F,
    summary: 'Create a Gameplay Cue Notify asset.', whenToUse: W, whenNotToUse: ['Use add_effect_cue.'],
    inputProps: { name: P.name, path: P.path, cueType: P.string_, cueTag: P.tag }, required: ['name', 'cueType'],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_gameplay_cue_notify', name: 'GC_Damage', cueType: 'Static', cueTag: 'GameplayCue.Damage' } }),
  buildRecord({ parentTool: T, id: `${T}.get_gas_info`, action: 'get_gas_info', family: F,
    summary: 'Read GAS asset metadata.', whenToUse: ['Inspect GAS assets.'], whenNotToUse: ['Mutate assets.'],
    inputProps: { assetPath: P.assetPath }, required: ['assetPath'],
    effect: 'read', latency: 'instant', resources: 'low', plugins: GAS_PLUGIN,
    // `abilityCount` was declared but is never set by the handler
    // (McpAutomationBridge_GASHandlersInfo.cpp), so output projection produced
    // an empty payload and get_gas_info reported success carrying nothing.
    // Declared below is exactly what the handler emits.
    outputProps: {
      gasType: P.string_, assetName: P.string_, assetPath: P.assetPath,
      class: P.string_, parentClass: P.string_, generatedClass: P.string_,
      durationPolicy: P.string_, instancingPolicy: P.string_,
      netExecutionPolicy: P.string_, stackingType: P.string_,
      modifierCount: P.num_, cueCount: P.num_,
    }, outputRequired: [],
      exampleInput: { action: 'get_gas_info', assetPath: '/Game/BP_Char' }, exampleOutput: { success: true, message: 'GAS info', gasType: 'GameplayAbility', assetName: 'GA_Dash', instancingPolicy: 'InstancedPerActor' } }),
  buildRecord({ parentTool: T, id: `${T}.add_ability`, action: 'add_ability', family: F,
    summary: 'Add an ability to an existing Gameplay Ability Set.',
    whenToUse: ['An ability must join a set that already exists.'],
    whenNotToUse: ['The ability is granted directly to an actor; use grant_ability.'],
    inputProps: { setPath: G.setPath, abilityPath: P.abilityPath, abilityClass: G.abilityClass },
    required: ['setPath'], requiredOneOf: ['abilityPath', 'abilityClass'],
    outputProps: { setPath: G.setPath, abilityPath: P.abilityPath, abilityClass: G.abilityClass, note: P.string_ }, outputRequired: [],
    effect: 'write', latency: 'interactive', resources: 'low', plugins: GAS_PLUGIN,
    exampleInput: { action: 'add_ability', setPath: '/Game/GAS/AS_Hero', abilityPath: '/Game/GAS/GA_Dash' },
    exampleOutput: { success: true, message: 'Ability added', setPath: '/Game/GAS/AS_Hero', abilityPath: '/Game/GAS/GA_Dash' } }),
  buildRecord({ parentTool: T, id: `${T}.create_execution_calculation`, action: 'create_execution_calculation', family: F,
    summary: 'Create a GameplayEffectExecutionCalculation blueprint for custom effect math.',
    whenToUse: ['Effect magnitude needs code the modifier curve cannot express.'],
    whenNotToUse: ['A scalable float or attribute-based modifier is enough.'],
    inputProps: { name: P.name, path: P.path },
    required: ['name'],
    outputProps: { assetPath: P.assetPath, name: P.name, parentClass: P.string_, reusedExisting: P.bool_, note: P.string_ }, outputRequired: [],
    effect: 'write', latency: 'interactive', resources: 'medium', plugins: GAS_PLUGIN,
    exampleInput: { action: 'create_execution_calculation', name: 'GEEC_Damage', path: '/Game/GAS' },
    exampleOutput: { success: true, message: 'Execution calculation created', assetPath: '/Game/GAS/GEEC_Damage', name: 'GEEC_Damage', reusedExisting: false } }),
];
