#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
FString MakeGuardrailsLocalPathSection()
{
    return FString()
        + TEXT("const UNREAL_BINARY_ASSET_PATTERN = /\\.(uasset|umap)(?:$|[?#\\s\"'])/iu\n")
        + TEXT("const UNREAL_PROJECT_STATE_PATH_PATTERN = /(?:^|[=\\s\"'`])(?:\\.\\/)?(?:[^\\s\"'`]+\\.uproject|Config[\\\\/][^\\s\"'`]+\\.ini|\\.opencode(?:[\\\\/][^\\s\"'`]*)?)(?:$|[?#\\s\"'`])/iu\n")
        + TEXT("const UNREAL_CONTENT_TARGET_PATTERN = /(?:^|[=\\s\"'`])(?:\\.\\/)?(?:Content(?:[\\\\/]|(?=[\\s;&|]|$))|Plugins[\\\\/][^\\s\"'`]+[\\\\/]Content(?:[\\\\/]|(?=[\\s;&|]|$))|\\/(?:Game|Engine)(?:[\\\\/]|(?=[\\s;&|]|$)))/iu\n")
        + TEXT("const PATH_KEY_PATTERN = /(path|file|filename|patch|command|cmd|arg|script|source|target|destination|location|directory|cwd|root|input|output)/iu\n")
        + TEXT("const UNREAL_PROJECT_DIRECTORY_PATTERN = /(?:^|[\\s\"'`])(?:\\.\\/)?(?:\\.opencode|Content|Config|Source|Plugins|Binaries|Intermediate|Saved)(?:$|[\\\\/\\s\"'`])/iu\n")
        + TEXT("const DIRECT_PROJECT_STATE_WRITE_TOOLS = new Set([\"edit\", \"write\", \"patch\", \"apply_patch\"])\n")
        + TEXT("const LOCAL_COMMAND_TOOLS = new Set([\"bash\", \"shell\", \"command\", \"execute\", \"execute_command\"])\n")
        + TEXT("const COMMAND_PAYLOAD_KEY_PATTERN = /(?:command|cmd|script|arg)|^(?:binary|executable|program|run|exec|execute|shell|invocation|invoke)$/iu\n")
        + TEXT("const MUTATION_PAYLOAD_KEY_PATTERN = /^(?:append(?:[_-]?text)?|body|changes?|contents?|diff|edits?|new[_-]?(?:content|text)|patch(?:[_-]?text)?|replacement(?:[_-]?text)?|writes?)$/iu\n")
        + TEXT("const READ_ONLY_LOCAL_COMMAND_PATTERN = /^\\s*(?:(?:\\/usr)?\\/bin\\/)?(?:rg|grep|fd|ls|tree|pwd|realpath|readlink|stat|file|head|tail|cat)\\b/iu\n")
        + TEXT("const READ_ONLY_COMMAND_ESCAPE_PATTERN = /[\\r\\n|&;<>`]|\\$\\(|\\bfind\\b[^\\n]*(?:-delete|-exec|-execdir|-ok|-okdir)\\b/iu\n")
        + TEXT("const UNREAL_PYTHON_MUTATION_PATTERN = /\\bunreal(?:\\.[a-z_][a-z0-9_]*)*\\.(?:add|attach|change|create|delete|destroy|detach|duplicate|execute|import|load|modify|move|open|remove|rename|replace|save|set|spawn|start|stop|update)[a-z0-9_]*\\s*\\(/iu\n")
        + TEXT("const UNREAL_SEMANTIC_MUTATION_PATTERN = /\\b(?:add|attach|change|create|delete|destroy|detach|duplicate|import|load|modify|move|open|remove|rename|replace|save|set|spawn|update)\\b[^\\n]{0,96}\\b(?:actor|asset|blueprint|component|content browser|level|map|material|niagara|outliner|sequence|viewport|world)\\b/iu\n")
        + TEXT("const SCRIPT_INTERPRETER_PATTERN = /(?:^|[\\s\"'`])(?:(?:\\/usr)?\\/bin\\/)?(?:python(?:3(?:\\.\\d+)?)?|node(?:js)?|ruby|perl|php|lua|deno|bun|pwsh|powershell|bash|dash|zsh|ksh|fish|sh|cmd(?:\\.exe)?|wscript(?:\\.exe)?|cscript(?:\\.exe)?)\\b/iu\n")
        + TEXT("const DYNAMIC_SHELL_ASSIGNMENT_PATTERN = /(?:^|[\\s;&|])(?:export\\s+)?[A-Za-z_][A-Za-z0-9_]*\\s*=/u\n")
        + TEXT("const SHELL_VARIABLE_EXPANSION_PATTERN = /\\$(?:[A-Za-z_][A-Za-z0-9_]*|\\{[^}\\r\\n]+\\})/u\n")
        + TEXT("const SHELL_COMMAND_SUBSTITUTION_PATTERN = /\\$\\(|`/u\n")
        + TEXT("const DYNAMIC_INTERPRETER_PAYLOAD_PATTERN = /\\b(?:base64|b64decode|fromhex|exec|eval|compile|__import__|getattr|invoke-expression)\\b|buffer\\.from\\s*\\([^\\n]{0,160}\\bbase64\\b/iu\n")
        + TEXT("const INTERPRETER_MUTATION_PATTERN = /\\b(?:shutil\\.rmtree|os\\.(?:chmod|chown|link|makedirs|mkdir|remove|rename|replace|rmdir|symlink|system|truncate|unlink)|pathlib\\.[a-z_][a-z0-9_]*\\.(?:chmod|mkdir|open|rename|replace|rmdir|symlink_to|touch|unlink|write_bytes|write_text)|fs\\.(?:appendFile|appendFileSync|chmod|chmodSync|chown|chownSync|copyFile|copyFileSync|cp|cpSync|createWriteStream|link|linkSync|mkdir|mkdirSync|rename|renameSync|rm|rmSync|rmdir|rmdirSync|symlink|symlinkSync|truncate|truncateSync|unlink|unlinkSync|writeFile|writeFileSync)|deno\\.(?:chmod|chown|copyFile|create|link|mkdir|remove|rename|symlink|truncate|writeFile|writeTextFile)|file\\.(?:open|write)|io\\.write|file_put_contents|new-item|set-content|add-content|out-file)\\s*\\(|\\.(?:append|createWriteStream|save|touch|truncate|write)\\s*\\(|\\bopen\\s*\\([^\\r\\n]{0,240}(?:,\\s*[\"'][wax+][^\"']*[\"']|\\bmode\\s*=\\s*[\"'][wax+][^\"']*[\"'])/iu\n")
        + TEXT("const UNREAL_INTERPRETER_API_PATTERN = /(?:\\bimport\\s+unreal\\b|\\bfrom\\s+unreal\\b|\\bunreal\\s*\\.|__import__\\s*\\(\\s*[\"']unreal[\"'])/iu\n")
        + TEXT("const SHELL_PATH_EXPANSION_PATTERN = /(?:\\{[^{}\\r\\n]*,[^{}\\r\\n]*\\}|\\[[^\\]\\r\\n]+\\])/u\n")
        + TEXT("const FILESYSTEM_MUTATION_COMMAND_PATTERN = /(?:^|[\\s;&|])(?:cp|install|mkdir|mv|rm|rmdir|tee|touch|truncate)\\b|(?:^|[^<])(?:>>?|\\|\\s*(?:sponge|tee)\\b)/iu\n")
        + TEXT("const DESTRUCTIVE_INTERPRETER_PATTERN = /\\b(?:shutil\\.rmtree|os\\.(?:remove|unlink|rmdir|removedirs)|pathlib\\.[a-z_][a-z0-9_]*\\.(?:unlink|rmdir)|fs\\.(?:rmSync|rmdirSync|unlinkSync)|deno\\.remove|fileutils\\.rm_rf)\\s*\\(|\\bremove-item\\b[^\\n]*(?:-recurse|-force)/iu\n")
        + TEXT("const UNREAL_EDITOR_EXECUTABLE_PATTERN = /(?:^|[\\s\"'`])(?:[^\\s\"'`]*[\\\\/])?UnrealEditor(?:-Cmd)?(?:\\.exe)?(?:$|[\\s\"'`])/iu\n")
        + TEXT("const INDIRECT_PROJECT_MUTATION_PATTERN = /\\b(?:git[\"']?(?:\\s+(?:(?:-C|-c|--git-dir|--work-tree|--namespace|--exec-path)(?:=\\S+|\\s+\\S+)|--?[A-Za-z][A-Za-z-]*))*\\s+apply|git[\"']?\\b[^\\n]*-c\\s+alias\\.[^\\s=]+=[\"']?apply[\"']?\\b|patch[\"']?\\s+(?:-[^\\s]+\\s+)*|unzip[\"']?\\b|7z[\"']?\\s+x\\b)/iu\n")
        + TEXT("const DESTRUCTIVE_ROOT_FIND_PATTERN = /\\bfind\\s+(?:\\.|\\.\\/|\\*|\\.\\/\\*|[\"']?\\$PWD[\"']?|[\"']?\\$\\{PWD\\}[\"']?)(?:\\s|$)[^\\n]*(?:-delete|-exec|-execdir|-ok|-okdir)\\b/iu\n")
        + TEXT("let GUARDRAIL_PROJECT_DIRECTORY = \"\"\n\n")
        + TEXT("function setGuardrailProjectDirectory(directory: string): void {\n")
        + TEXT("  GUARDRAIL_PROJECT_DIRECTORY = realpathSync(resolvePath(directory))\n")
        + TEXT("}\n\n")
        + TEXT("function normalizeLocalToolName(value: unknown): string {\n")
        + TEXT("  return typeof value === \"string\" ? value.trim().toLowerCase() : \"\"\n")
        + TEXT("}\n\n")
        + TEXT("function isReadOnlyLocalTool(tool: string): boolean {\n")
        + TEXT("  return /(?:^|[_-])(?:read|reader|glob|grep|list)(?:$|[_-])/iu.test(tool)\n")
        + TEXT("}\n\n")
        + TEXT("function containsPathLikeValue(value: unknown, pattern: RegExp, pathContext = false): boolean {\n")
        + TEXT("  if (typeof value === \"string\") return pathContext && pattern.test(value)\n")
        + TEXT("  if (Array.isArray(value)) return value.some((item) => containsPathLikeValue(item, pattern, pathContext))\n")
        + TEXT("  if (value && typeof value === \"object\") {\n")
        + TEXT("    return Object.entries(value as Record<string, unknown>).some(([key, item]) => {\n")
        + TEXT("      return containsPathLikeValue(item, pattern, pathContext || PATH_KEY_PATTERN.test(key))\n")
        + TEXT("    })\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function pathCandidatesFromText(value: string): string[] {\n")
        + TEXT("  const candidates: string[] = []\n")
        + TEXT("  const trimmed = value.trim()\n")
        + TEXT("  if (trimmed.length > 0) candidates.push(trimmed)\n")
        + TEXT("  for (const match of value.matchAll(/^\\*\\*\\* (?:Add|Update|Delete|Move to) File:\\s*(.+)$/gmu)) candidates.push(match[1].trim())\n")
        + TEXT("  for (const match of value.matchAll(/\"([^\"]+)\"/gu)) candidates.push(match[1])\n")
        + TEXT("  for (const match of value.matchAll(/'([^']+)'/gu)) candidates.push(match[1])\n")
        + TEXT("  for (const match of value.matchAll(/(?:^|[=\\s\"'`])((?:[A-Za-z]:[\\\\/]|\\/|\\.{1,2}[\\\\/]|[A-Za-z0-9_.-]+[\\\\/])[^\\s\"'`|;&<>]+)/gu)) candidates.push(match[1])\n")
        + TEXT("  return candidates.map((candidate) => candidate.replace(/[),\\]}]+$/u, \"\"))\n")
        + TEXT("}\n\n")
        + TEXT("function resolveThroughExistingAncestor(candidate: string): string | undefined {\n")
        + TEXT("  if (!GUARDRAIL_PROJECT_DIRECTORY || candidate.startsWith(\"/Game\") || candidate.startsWith(\"/Engine\")) return undefined\n")
        + TEXT("  let current = resolvePath(GUARDRAIL_PROJECT_DIRECTORY, candidate)\n")
        + TEXT("  const missing: string[] = []\n")
        + TEXT("  while (!existsSync(current)) {\n")
        + TEXT("    const parent = dirnamePath(current)\n")
        + TEXT("    if (parent === current) return undefined\n")
        + TEXT("    missing.unshift(basenamePath(current))\n")
        + TEXT("    current = parent\n")
        + TEXT("  }\n")
        + TEXT("  try { return resolvePath(realpathSync(current), ...missing) } catch { return undefined }\n")
        + TEXT("}\n\n")
        + TEXT("function resolvesIntoProtectedProjectState(candidate: string): boolean {\n")
        + TEXT("  const resolved = resolveThroughExistingAncestor(candidate)\n")
        + TEXT("  if (!resolved) return false\n")
        + TEXT("  const relative = relativePath(GUARDRAIL_PROJECT_DIRECTORY, resolved)\n")
        + TEXT("  if (!relative || relative === \"..\" || relative.startsWith(`..${pathSeparator}`) || isAbsolutePath(relative)) return false\n")
        + TEXT("  const segments = relative.split(/[\\\\/]/u).map((segment) => segment.toLowerCase())\n")
        + TEXT("  return segments[0] === \"content\" || (segments[0] === \"plugins\" && segments.length >= 3 && segments[2] === \"content\") || segments[0] === \"config\" || segments[0] === \".opencode\" || (segments.length === 1 && resolved.toLowerCase().endsWith(\".uproject\"))\n")
        + TEXT("}\n\n")
        + TEXT("function containsResolvedProtectedPath(value: unknown, pathContext = false): boolean {\n")
        + TEXT("  if (typeof value === \"string\") return pathContext && pathCandidatesFromText(value).some(resolvesIntoProtectedProjectState)\n")
        + TEXT("  if (Array.isArray(value)) return value.some((item) => containsResolvedProtectedPath(item, pathContext))\n")
        + TEXT("  if (value && typeof value === \"object\") {\n")
        + TEXT("    return Object.entries(value as Record<string, unknown>).some(([key, item]) => containsResolvedProtectedPath(item, pathContext || PATH_KEY_PATTERN.test(key)))\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function resolvesToUnrealBinaryAsset(candidate: string): boolean {\n")
        + TEXT("  const resolved = resolveThroughExistingAncestor(candidate)\n")
        + TEXT("  return Boolean(resolved && /\\.(?:uasset|umap)$/iu.test(resolved))\n")
        + TEXT("}\n\n")
        + TEXT("function containsResolvedBinaryAssetPath(value: unknown, pathContext = false): boolean {\n")
        + TEXT("  if (typeof value === \"string\") return pathContext && pathCandidatesFromText(value).some(resolvesToUnrealBinaryAsset)\n")
        + TEXT("  if (Array.isArray(value)) return value.some((item) => containsResolvedBinaryAssetPath(item, pathContext))\n")
        + TEXT("  if (value && typeof value === \"object\") {\n")
        + TEXT("    return Object.entries(value as Record<string, unknown>).some(([key, item]) => containsResolvedBinaryAssetPath(item, pathContext || PATH_KEY_PATTERN.test(key)))\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function pathTraversesSymbolicLink(candidate: string): boolean {\n")
        + TEXT("  if (!GUARDRAIL_PROJECT_DIRECTORY || candidate.startsWith(\"/Game\") || candidate.startsWith(\"/Engine\")) return false\n")
        + TEXT("  const normalizedCandidate = candidate.replace(/\\\\/gu, pathSeparator)\n")
        + TEXT("  const normalizedProject = GUARDRAIL_PROJECT_DIRECTORY.replace(/\\\\/gu, pathSeparator)\n")
        + TEXT("  let relative = normalizedCandidate\n")
        + TEXT("  if (isAbsolutePath(relative)) {\n")
        + TEXT("    const comparableCandidate = pathSeparator === \"\\\\\" ? relative.toLowerCase() : relative\n")
        + TEXT("    const comparableProject = pathSeparator === \"\\\\\" ? normalizedProject.toLowerCase() : normalizedProject\n")
        + TEXT("    const projectPrefix = `${comparableProject}${pathSeparator}`\n")
        + TEXT("    if (!comparableCandidate.startsWith(projectPrefix)) return false\n")
        + TEXT("    relative = relative.slice(normalizedProject.length + 1)\n")
        + TEXT("  }\n")
        + TEXT("  if (!relative) return false\n")
        + TEXT("  let current = GUARDRAIL_PROJECT_DIRECTORY\n")
        + TEXT("  for (const segment of relative.split(/[\\\\/]/u)) {\n")
        + TEXT("    if (!segment || segment === \".\") continue\n")
        + TEXT("    if (segment === \"..\") {\n")
        + TEXT("      if (current === GUARDRAIL_PROJECT_DIRECTORY) return false\n")
        + TEXT("      current = dirnamePath(current)\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    current = resolvePath(current, segment)\n")
        + TEXT("    if (!existsSync(current)) continue\n")
        + TEXT("    try { if (lstatSync(current).isSymbolicLink()) return true } catch { return true }\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function containsLinkedPath(value: unknown, pathContext = false): boolean {\n")
        + TEXT("  if (typeof value === \"string\") return pathContext && pathCandidatesFromText(value).some(pathTraversesSymbolicLink)\n")
        + TEXT("  if (Array.isArray(value)) return value.some((item) => containsLinkedPath(item, pathContext))\n")
        + TEXT("  if (value && typeof value === \"object\") {\n")
        + TEXT("    return Object.entries(value as Record<string, unknown>).some(([key, item]) => containsLinkedPath(item, pathContext || PATH_KEY_PATTERN.test(key)))\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function collectCommandFragments(value: unknown, commandContext = false, fragments: string[] = []): string[] {\n")
        + TEXT("  if (typeof value === \"string\") {\n")
        + TEXT("    if (commandContext) fragments.push(value)\n")
        + TEXT("    return fragments\n")
        + TEXT("  }\n")
        + TEXT("  if (Array.isArray(value)) {\n")
        + TEXT("    for (const item of value) collectCommandFragments(item, commandContext, fragments)\n")
        + TEXT("    return fragments\n")
        + TEXT("  }\n")
        + TEXT("  if (value && typeof value === \"object\") {\n")
        + TEXT("    const entries = Object.entries(value as Record<string, unknown>).sort(([left], [right]) => commandPayloadPriority(left) - commandPayloadPriority(right) || left.localeCompare(right))\n")
        + TEXT("    for (const [key, item] of entries) collectCommandFragments(item, commandContext || COMMAND_PAYLOAD_KEY_PATTERN.test(key), fragments)\n")
        + TEXT("  }\n")
        + TEXT("  return fragments\n")
        + TEXT("}\n\n")
        + TEXT("function hasExplicitMutationPayload(value: unknown): boolean {\n")
        + TEXT("  if (Array.isArray(value)) return value.some(hasExplicitMutationPayload)\n")
        + TEXT("  if (!value || typeof value !== \"object\") return false\n")
        + TEXT("  return Object.entries(value as Record<string, unknown>).some(([key, item]) => {\n")
        + TEXT("    return (MUTATION_PAYLOAD_KEY_PATTERN.test(key) && item !== null && item !== undefined) || hasExplicitMutationPayload(item)\n")
        + TEXT("  })\n")
        + TEXT("}\n\n")
        + TEXT("function isExplicitReadOnlyCommand(command: string): boolean {\n")
        + TEXT("  return READ_ONLY_LOCAL_COMMAND_PATTERN.test(command) && !READ_ONLY_COMMAND_ESCAPE_PATTERN.test(command) && !hasExecutionCapableReadOption(command)\n")
        + TEXT("}\n\n")
        + TEXT("function normalizeShellForSafety(command: string): string {\n")
        + TEXT("  return command.replace(/''|\"\"/gu, \"\").replace(/'\\s*\\+\\s*'|\"\\s*\\+\\s*\"/gu, \"\").replace(/(?<=[a-z0-9_])[\"'](?=[a-z0-9_])/giu, \"\").replace(/\\^/gu, \"\")\n")
        + TEXT("}\n\n")
        + TEXT("function decodeAnsiCShellEscape(command: string, index: number): readonly [string, number] {\n")
        + TEXT("  const escape = command[index + 1]\n")
        + TEXT("  if (!escape) return [\"\\\\\", index]\n")
        + TEXT("  const simple: Record<string, string> = { a: \"\\x07\", b: \"\\b\", e: \"\\x1b\", E: \"\\x1b\", f: \"\\f\", n: \"\\n\", r: \"\\r\", t: \"\\t\", v: \"\\v\" }\n")
        + TEXT("  if (escape in simple) return [simple[escape], index + 1]\n")
        + TEXT("  if (![\"x\", \"u\", \"U\"].includes(escape) && !/[0-7]/u.test(escape)) return [escape, index + 1]\n")
        + TEXT("  const radix = /[0-7]/u.test(escape) ? 8 : 16\n")
        + TEXT("  const maximum = radix === 8 ? 3 : escape === \"x\" ? 2 : escape === \"u\" ? 4 : 8\n")
        + TEXT("  let digits = radix === 8 ? escape : \"\"\n")
        + TEXT("  let cursor = index + 2\n")
        + TEXT("  while (digits.length < maximum && cursor < command.length && (radix === 8 ? /[0-7]/u : /[0-9a-f]/iu).test(command[cursor])) { digits += command[cursor]; cursor += 1 }\n")
        + TEXT("  const value = Number.parseInt(digits, radix)\n")
        + TEXT("  return digits && value > 0 && value <= 0x10ffff ? [String.fromCodePoint(value), cursor - 1] : [\"*\", cursor - 1]\n")
        + TEXT("}\n\n")
        + TEXT("function tokenizeShellCommand(command: string): string[] {\n")
        + TEXT("  const tokens: string[] = []\n")
        + TEXT("  let current = \"\"\n")
        + TEXT("  let quote = \"\"\n")
        + TEXT("  let ansiCQuote = false\n")
        + TEXT("  const flush = (): void => {\n")
        + TEXT("    if (!current) return\n")
        + TEXT("    tokens.push(normalizeShellForSafety(current))\n")
        + TEXT("    current = \"\"\n")
        + TEXT("  }\n")
        + TEXT("  for (let index = 0; index < command.length; index += 1) {\n")
        + TEXT("    const character = command[index]\n")
        + TEXT("    if (quote) {\n")
        + TEXT("      if (character === quote) {\n")
        + TEXT("        quote = \"\"\n")
        + TEXT("        ansiCQuote = false\n")
        + TEXT("      } else if (ansiCQuote && character === \"\\\\\") {\n")
        + TEXT("        const [decoded, consumedIndex] = decodeAnsiCShellEscape(command, index)\n")
        + TEXT("        current += decoded; index = consumedIndex\n")
        + TEXT("      } else current += character\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    if (character === \"'\" || character === \"\\\"\") {\n")
        + TEXT("      if (current.endsWith(\"$\")) { current = current.slice(0, -1); ansiCQuote = character === \"'\" }\n")
        + TEXT("      quote = character\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    if (character === \"\\\\\" && index + 1 < command.length) {\n")
        + TEXT("      current += command[index + 1]\n")
        + TEXT("      index += 1\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    if (/\\s/u.test(character)) { flush(); continue }\n")
        + TEXT("    current += character\n")
        + TEXT("  }\n")
        + TEXT("  flush()\n")
        + TEXT("  return tokens\n")
        + TEXT("}\n\n");
}
}
