#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
FString MakeGuardrailsLocalMutationSection()
{
    return FString()
        + TEXT("function rejectDirectUnrealBinaryAssetAccess(input: { tool?: string }, output: unknown): void {\n")
        + TEXT("  if (!output || typeof output !== \"object\" || !(\"args\" in output)) return\n")
        + TEXT("  const args = (output as { args?: unknown }).args\n")
        + TEXT("  const tool = normalizeLocalToolName(input.tool)\n")
        + TEXT("  const rootPathContext = typeof args === \"string\" || Array.isArray(args)\n")
        + TEXT("  const pathContext = rootPathContext || DIRECT_PROJECT_STATE_WRITE_TOOLS.has(tool) || isReadOnlyLocalTool(tool) || LOCAL_COMMAND_TOOLS.has(tool) || shouldTreatAllStringsAsMutationPaths(input, output)\n")
        + TEXT("  const command = extractPotentialShellCommand(input, output)\n")
        + TEXT("  const normalizedCommand = command ? normalizeShellForSafety(command) : undefined\n")
        + TEXT("  const containsBinaryPath = containsPathLikeValue(args, UNREAL_BINARY_ASSET_PATTERN, pathContext) || containsResolvedBinaryAssetPath(args, pathContext) || Boolean(normalizedCommand && (UNREAL_BINARY_ASSET_PATTERN.test(normalizedCommand) || containsUnrealBinaryAssetGlob(normalizedCommand)))\n")
        + TEXT("  if (!containsBinaryPath) return\n")
        + TEXT("  if (command && isHarmlessBinaryExtensionMention(command)) return\n")
        + TEXT("  throw new Error(\"Unreal Agent blocked direct .uasset/.umap filesystem access. Use /Game package paths through unreal-engine MCP inspect, manage_asset, manage_level, or control_editor instead.\")\n")
        + TEXT("}\n\n")
        + TEXT("function extractShellCommand(_input: { tool?: string }, output: unknown): string | undefined {\n")
        + TEXT("  if (!output || typeof output !== \"object\" || !(\"args\" in output)) return undefined\n")
        + TEXT("  const args = (output as { args?: unknown }).args\n")
        + TEXT("  const fragments = collectCommandFragments(args, typeof args === \"string\" || Array.isArray(args))\n")
        + TEXT("  return fragments.length > 0 ? fragments.join(\" \") : undefined\n")
        + TEXT("}\n\n")
        + TEXT("function isLocalMutationCall(input: { tool?: string }, output: unknown): boolean {\n")
        + TEXT("  const tool = normalizeLocalToolName(input.tool)\n")
        + TEXT("  if (DIRECT_PROJECT_STATE_WRITE_TOOLS.has(tool) || /(?:^|[_-])(?:edit|write|patch|save|create|delete|remove|move|rename)(?:$|[_-])/iu.test(tool)) return true\n")
        + TEXT("  const command = extractShellCommand(input, output)\n")
        + TEXT("  if (command) return !isExplicitReadOnlyCommand(command)\n")
        + TEXT("  if (hasExplicitMutationPayload(readObjectProperty(output, \"args\"))) return true\n")
        + TEXT("  return !isReadOnlyLocalTool(tool)\n")
        + TEXT("}\n\n")
        + TEXT("function shouldTreatAllStringsAsMutationPaths(input: { tool?: string }, output: unknown): boolean {\n")
        + TEXT("  if (!isLocalMutationCall(input, output)) return false\n")
        + TEXT("  const tool = normalizeLocalToolName(input.tool)\n")
        + TEXT("  const args = readObjectProperty(output, \"args\")\n")
        + TEXT("  if (isReadOnlyLocalTool(tool)) return hasExplicitMutationPayload(args)\n")
        + TEXT("  return !DIRECT_PROJECT_STATE_WRITE_TOOLS.has(tool) && !LOCAL_COMMAND_TOOLS.has(tool)\n")
        + TEXT("}\n\n")
        + TEXT("function rejectLinkedLocalMutationTarget(input: { tool?: string }, output: unknown): void {\n")
        + TEXT("  if (!output || typeof output !== \"object\" || !(\"args\" in output) || !isLocalMutationCall(input, output)) return\n")
        + TEXT("  const args = (output as { args?: unknown }).args\n")
        + TEXT("  const tool = normalizeLocalToolName(input.tool)\n")
        + TEXT("  const pathContext = typeof args === \"string\" || Array.isArray(args) || LOCAL_COMMAND_TOOLS.has(tool) || shouldTreatAllStringsAsMutationPaths(input, output)\n")
        + TEXT("  if (!containsLinkedPath(args, pathContext)) return\n")
        + TEXT("  throw new Error(\"Unreal Agent blocked direct local mutation through a symbolic link. Use a real source path or the matching unreal-engine MCP route.\")\n")
        + TEXT("}\n\n")
        + TEXT("function rejectDirectUnrealProjectStateWrite(input: { tool?: string }, output: unknown): void {\n")
        + TEXT("  if (!output || typeof output !== \"object\" || !(\"args\" in output)) return\n")
        + TEXT("  const args = (output as { args?: unknown }).args\n")
        + TEXT("  const tool = normalizeLocalToolName(input.tool)\n")
        + TEXT("  const rootPathContext = typeof args === \"string\" || Array.isArray(args) || LOCAL_COMMAND_TOOLS.has(tool) || shouldTreatAllStringsAsMutationPaths(input, output)\n")
        + TEXT("  const command = extractPotentialShellCommand(input, output)\n")
        + TEXT("  const normalizedCommand = command ? normalizeShellForSafety(command) : undefined\n")
        + TEXT("  const targetsProjectState = containsPathLikeValue(args, UNREAL_PROJECT_STATE_PATH_PATTERN, rootPathContext) || containsResolvedProtectedPath(args, rootPathContext) || Boolean(normalizedCommand && UNREAL_PROJECT_STATE_PATH_PATTERN.test(normalizedCommand))\n")
        + TEXT("  if (targetsProjectState && isLocalMutationCall(input, output)) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked direct Unreal project-state file write. Use unreal-engine MCP system_control with inspect read-back instead of direct .uproject or Config/*.ini edits.\")\n")
        + TEXT("  }\n")
        + TEXT("}\n\n")
        + TEXT("function rejectDirectUnrealContentMutation(input: { tool?: string }, output: unknown): void {\n")
        + TEXT("  if (!output || typeof output !== \"object\" || !(\"args\" in output)) return\n")
        + TEXT("  const args = (output as { args?: unknown }).args\n")
        + TEXT("  const tool = normalizeLocalToolName(input.tool)\n")
        + TEXT("  const rootPathContext = typeof args === \"string\" || Array.isArray(args) || LOCAL_COMMAND_TOOLS.has(tool) || shouldTreatAllStringsAsMutationPaths(input, output)\n")
        + TEXT("  const command = extractPotentialShellCommand(input, output)\n")
        + TEXT("  const normalizedCommand = command ? normalizeShellForSafety(command) : undefined\n")
        + TEXT("  const targetsContent = containsPathLikeValue(args, UNREAL_CONTENT_TARGET_PATTERN, rootPathContext) || containsResolvedProtectedPath(args, rootPathContext) || Boolean(normalizedCommand && UNREAL_CONTENT_TARGET_PATTERN.test(normalizedCommand))\n")
        + TEXT("  if (targetsContent && isLocalMutationCall(input, output)) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked direct Unreal content/package mutation. Use /Game package paths through unreal-engine MCP Content Browser, manage_asset, manage_level, or control_editor routes.\")\n")
        + TEXT("  }\n")
        + TEXT("}\n\n")
        + TEXT("function rejectDirectUnrealEditorStateMutation(input: { tool?: string }, output: unknown): void {\n")
        + TEXT("  const command = extractPotentialShellCommand(input, output)\n")
        + TEXT("  if (!command || isExplicitReadOnlyCommand(command)) return\n")
        + TEXT("  const normalizedCommand = normalizeShellForSafety(command)\n")
        + TEXT("  const compactCommand = normalizedCommand.toLowerCase().replace(/[^a-z0-9_]/gu, \"\")\n")
        + TEXT("  const usesScriptInterpreter = SCRIPT_INTERPRETER_PATTERN.test(normalizedCommand)\n")
        + TEXT("  const reachesUnrealPython = usesScriptInterpreter && UNREAL_INTERPRETER_API_PATTERN.test(normalizedCommand)\n")
        + TEXT("  const executesDynamicPayload = usesScriptInterpreter && DYNAMIC_INTERPRETER_PAYLOAD_PATTERN.test(normalizedCommand)\n")
        + TEXT("  const mutatesThroughInterpreter = usesScriptInterpreter && INTERPRETER_MUTATION_PATTERN.test(normalizedCommand)\n")
        + TEXT("  const expandsMutationPath = SHELL_PATH_EXPANSION_PATTERN.test(normalizedCommand) && FILESYSTEM_MUTATION_COMMAND_PATTERN.test(normalizedCommand)\n")
        + TEXT("  if (!launchesUnrealEditorExecutable(normalizedCommand) && !UNREAL_EDITOR_EXECUTABLE_PATTERN.test(normalizedCommand) && !reachesUnrealPython && !executesDynamicPayload && !mutatesThroughInterpreter && !expandsMutationPath && !UNREAL_PYTHON_MUTATION_PATTERN.test(normalizedCommand) && !UNREAL_SEMANTIC_MUTATION_PATTERN.test(normalizedCommand)) return\n")
        + TEXT("  throw new Error(\"Unreal Agent blocked direct local Unreal editor-state access. Use the matching unreal-engine MCP inspect, actor, component, level, map, asset, or editor-control action.\")\n")
        + TEXT("}\n\n")
        + TEXT("function rejectDestructiveLocalShellAccess(input: { tool?: string }, output: unknown): void {\n")
        + TEXT("  const command = extractPotentialShellCommand(input, output)\n")
        + TEXT("  if (!command) return\n")
        + TEXT("  const normalizedCommand = normalizeShellForSafety(command)\n")
        + TEXT("  const pythonTarExtraction = /\\bpython(?:3(?:\\.\\d+)?)?\\b[^\\n]*\\s-m\\s+tarfile\\b[^\\n]*(?:\\s-e\\s|\\s--extract\\s)/iu.test(normalizedCommand)\n")
        + TEXT("  if (INDIRECT_PROJECT_MUTATION_PATTERN.test(normalizedCommand) || containsTarExtractionCommand(normalizedCommand) || pythonTarExtraction || ARCHIVE_EXTRACTION_API_PATTERN.test(normalizedCommand) || PYTHON_MUTATION_IMPORT_ALIAS_PATTERN.test(normalizedCommand) || hasExecutionCapableReadOption(normalizedCommand) || containsDynamicShellMutation(normalizedCommand) || SHELL_COMMAND_SUBSTITUTION_PATTERN.test(normalizedCommand)) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked indirect Unreal project mutation. Use scoped source edits or the matching unreal-engine MCP project/content route instead.\")\n")
        + TEXT("  }\n")
        + TEXT("  const destructiveRecursiveRemove = containsDestructiveRecursiveRemove(command)\n")
        + TEXT("  const destroysProjectRootWithFind = DESTRUCTIVE_ROOT_FIND_PATTERN.test(normalizedCommand)\n")
        + TEXT("  if (!destructiveRecursiveRemove && !destroysProjectRootWithFind && !containsDestructiveGitCommand(command) && !containsStdinExecutedShell(normalizedCommand) && !containsProcessSpawningInterpreter(normalizedCommand) && !DESTRUCTIVE_INTERPRETER_PATTERN.test(normalizedCommand)) return\n")
        + TEXT("  throw new Error(\"Unreal Agent blocked destructive local shell command. Use explicit source-control/recovery workflow and Unreal MCP tools for editor assets instead.\")\n")
        + TEXT("}\n\n")
        + TEXT("function redact(value: unknown): unknown {\n")
        + TEXT("  if (typeof value === \"string\") {\n")
        + TEXT("    if (SECRET_PATTERNS.some((pattern) => pattern.test(value))) return \"[REDACTED]\"\n")
        + TEXT("    return value\n")
        + TEXT("  }\n")
        + TEXT("  if (Array.isArray(value)) return value.map(redact)\n")
        + TEXT("  if (value && typeof value === \"object\") {\n")
        + TEXT("    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => {\n")
        + TEXT("      if (SECRET_PATTERNS.some((pattern) => pattern.test(key))) return [key, \"[REDACTED]\"]\n")
        + TEXT("      return [key, redact(item)]\n")
        + TEXT("    }))\n")
        + TEXT("  }\n")
        + TEXT("  return value\n")
        + TEXT("}\n\n");
}
}
