#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
FString MakeGuardrailsLocalShellSection()
{
    return FString()
        + TEXT("function expandBracePatterns(pattern: string): string[] | undefined {\n")
        + TEXT("  let patterns = [pattern]\n")
        + TEXT("  for (let pass = 0; pass < 16; pass += 1) {\n")
        + TEXT("    let expandedAny = false\n")
        + TEXT("    const next: string[] = []\n")
        + TEXT("    for (const candidate of patterns) {\n")
        + TEXT("      let openIndex = candidate.indexOf(\"{\")\n")
        + TEXT("      let closeIndex = -1\n")
        + TEXT("      let body = \"\"\n")
        + TEXT("      while (openIndex >= 0) {\n")
        + TEXT("        closeIndex = candidate.indexOf(\"}\", openIndex + 1)\n")
        + TEXT("        if (closeIndex < 0) { openIndex = -1; break }\n")
        + TEXT("        body = candidate.slice(openIndex + 1, closeIndex)\n")
        + TEXT("        if (body.includes(\",\")) break\n")
        + TEXT("        if (body.includes(\"..\")) return undefined\n")
        + TEXT("        openIndex = candidate.indexOf(\"{\", closeIndex + 1)\n")
        + TEXT("      }\n")
        + TEXT("      if (openIndex < 0) { next.push(candidate); continue }\n")
        + TEXT("      const alternatives = body.split(\",\")\n")
        + TEXT("      if (next.length + alternatives.length > 64) return undefined\n")
        + TEXT("      for (const alternative of alternatives) {\n")
        + TEXT("        const expanded = candidate.slice(0, openIndex) + alternative + candidate.slice(closeIndex + 1)\n")
        + TEXT("        if (expanded.length > 512) return undefined\n")
        + TEXT("        next.push(expanded)\n")
        + TEXT("      }\n")
        + TEXT("      expandedAny = true\n")
        + TEXT("    }\n")
        + TEXT("    patterns = next\n")
        + TEXT("    if (!expandedAny) return patterns\n")
        + TEXT("  }\n")
        + TEXT("  return undefined\n")
        + TEXT("}\n\n")
        + TEXT("function wildcardPatternMatchesLiteral(pattern: string, literal: string): boolean {\n")
        + TEXT("  if (pattern.length > 512) return true\n")
        + TEXT("  const pending: Array<readonly [number, number]> = [[0, 0]]\n")
        + TEXT("  const visited = new Set<string>()\n")
        + TEXT("  while (pending.length > 0) {\n")
        + TEXT("    const state = pending.pop()\n")
        + TEXT("    if (!state) break\n")
        + TEXT("    const [patternIndex, literalIndex] = state\n")
        + TEXT("    const key = `${patternIndex}:${literalIndex}`\n")
        + TEXT("    if (visited.has(key)) continue\n")
        + TEXT("    visited.add(key)\n")
        + TEXT("    if (patternIndex === pattern.length) {\n")
        + TEXT("      if (literalIndex === literal.length) return true\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    const patternCharacter = pattern[patternIndex]\n")
        + TEXT("    if (patternCharacter === \"*\") {\n")
        + TEXT("      pending.push([patternIndex + 1, literalIndex])\n")
        + TEXT("      if (literalIndex < literal.length) pending.push([patternIndex, literalIndex + 1])\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    if (literalIndex >= literal.length) continue\n")
        + TEXT("    if (patternCharacter === \"?\") { pending.push([patternIndex + 1, literalIndex + 1]); continue }\n")
        + TEXT("    if (patternCharacter === \"[\") {\n")
        + TEXT("      const closeIndex = pattern.indexOf(\"]\", patternIndex + 1)\n")
        + TEXT("      if (closeIndex < 0) {\n")
        + TEXT("        if (patternCharacter === literal[literalIndex]) pending.push([patternIndex + 1, literalIndex + 1])\n")
        + TEXT("        continue\n")
        + TEXT("      }\n")
        + TEXT("      let cursor = patternIndex + 1\n")
        + TEXT("      const negated = pattern[cursor] === \"!\" || pattern[cursor] === \"^\"\n")
        + TEXT("      if (negated) cursor += 1\n")
        + TEXT("      let matched = false\n")
        + TEXT("      while (cursor < closeIndex) {\n")
        + TEXT("        if (cursor + 2 < closeIndex && pattern[cursor + 1] === \"-\") {\n")
        + TEXT("          matched ||= literal[literalIndex] >= pattern[cursor] && literal[literalIndex] <= pattern[cursor + 2]\n")
        + TEXT("          cursor += 3\n")
        + TEXT("        } else {\n")
        + TEXT("          matched ||= pattern[cursor] === literal[literalIndex]\n")
        + TEXT("          cursor += 1\n")
        + TEXT("        }\n")
        + TEXT("      }\n")
        + TEXT("      if (negated ? !matched : matched) pending.push([closeIndex + 1, literalIndex + 1])\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    if (patternCharacter === literal[literalIndex]) pending.push([patternIndex + 1, literalIndex + 1])\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function shellPatternMayMatchLiteral(pattern: string, literal: string): boolean {\n")
        + TEXT("  const expandedPatterns = expandBracePatterns(pattern)\n")
        + TEXT("  return !expandedPatterns || expandedPatterns.some((expanded) => wildcardPatternMatchesLiteral(expanded, literal))\n")
        + TEXT("}\n\n")
        + TEXT("function normalizeBinaryAssetShellSyntax(token: string): string | undefined {\n")
        + TEXT("  const normalized = normalizeShellForSafety(token)\n")
        + TEXT("  let result = \"\"\n")
        + TEXT("  for (let index = 0; index < normalized.length; index += 1) {\n")
        + TEXT("    if (normalized[index] !== \"$\" || index + 1 >= normalized.length || (normalized[index + 1] !== \"'\" && normalized[index + 1] !== \"\\\"\")) {\n")
        + TEXT("      result += normalized[index]\n")
        + TEXT("      continue\n")
        + TEXT("    }\n")
        + TEXT("    const quote = normalized[index + 1]\n")
        + TEXT("    let closeIndex = index + 2\n")
        + TEXT("    let escaped = false\n")
        + TEXT("    for (; closeIndex < normalized.length; closeIndex += 1) {\n")
        + TEXT("      if (normalized[closeIndex] === \"\\\\\") {\n")
        + TEXT("        escaped = true\n")
        + TEXT("        closeIndex += 1\n")
        + TEXT("        if (closeIndex >= normalized.length) return undefined\n")
        + TEXT("        continue\n")
        + TEXT("      }\n")
        + TEXT("      if (normalized[closeIndex] === quote) break\n")
        + TEXT("    }\n")
        + TEXT("    if (closeIndex >= normalized.length) return undefined\n")
        + TEXT("    result += escaped ? \"*\" : normalized.slice(index + 2, closeIndex)\n")
        + TEXT("    index = closeIndex\n")
        + TEXT("  }\n")
        + TEXT("  return result\n")
        + TEXT("}\n\n")
        + TEXT("function tokenMayResolveToUnrealBinaryAsset(token: string): boolean {\n")
        + TEXT("  if (!token.includes(\".\")) return false\n")
        + TEXT("  const shellNormalizedToken = normalizeBinaryAssetShellSyntax(token)\n")
        + TEXT("  if (shellNormalizedToken === undefined) return true\n")
        + TEXT("  const expandedTokens = expandBracePatterns(shellNormalizedToken)\n")
        + TEXT("  if (!expandedTokens) return true\n")
        + TEXT("  return expandedTokens.some((expanded) => {\n")
        + TEXT("    const candidates = new Set([\n")
        + TEXT("      expanded.replace(/\\\\/gu, \"/\"),\n")
        + TEXT("      expanded.replace(/\\\\(.)/gu, \"$1\"),\n")
        + TEXT("      expanded.replace(/\\\\(?:x[0-9a-f]{2}|u[0-9a-f]{4}|[0-7]{1,3}|.)/giu, \"*\"),\n")
        + TEXT("    ])\n")
        + TEXT("    return [...candidates].some((candidate) => {\n")
        + TEXT("      if (/\\.(?:uasset|umap)(?:$|[?#])/u.test(candidate)) return true\n")
        + TEXT("      const extensionIndex = candidate.lastIndexOf(\".\")\n")
        + TEXT("      if (extensionIndex < 0) return false\n")
        + TEXT("      const extension = candidate.slice(extensionIndex)\n")
        + TEXT("      return /[*?\\[]/u.test(extension) && (shellPatternMayMatchLiteral(extension, \".uasset\") || shellPatternMayMatchLiteral(extension, \".umap\"))\n")
        + TEXT("    })\n")
        + TEXT("  })\n")
        + TEXT("}\n\n")
        + TEXT("function containsUnrealBinaryAssetGlob(command: string): boolean {\n")
        + TEXT("  return tokenizeShellCommand(command).some((token) => {\n")
        + TEXT("    const normalized = token.toLowerCase().replace(/[),;:]+$/u, \"\")\n")
        + TEXT("    return tokenMayResolveToUnrealBinaryAsset(normalized)\n")
        + TEXT("  })\n")
        + TEXT("}\n\n")
        + TEXT("function launchesUnrealEditorExecutable(command: string): boolean {\n")
        + TEXT("  return tokenizeShellCommand(command).some((token) => {\n")
        + TEXT("    const executable = basenamePath(token.replace(/\\\\/gu, \"/\")).toLowerCase()\n")
        + TEXT("    return executable === \"unrealeditor\" || executable === \"unrealeditor-cmd\" || executable === \"unrealeditor.exe\" || executable === \"unrealeditor-cmd.exe\"\n")
        + TEXT("  })\n")
        + TEXT("}\n\n")
        + TEXT("function hasExecutionCapableReadOption(command: string): boolean {\n")
        + TEXT("  const tokens = tokenizeShellCommand(command)\n")
        + TEXT("  for (let executableIndex = 0; executableIndex < tokens.length; executableIndex += 1) {\n")
        + TEXT("    const executable = basenamePath(tokens[executableIndex]).toLowerCase()\n")
        + TEXT("    if (/^(?:bash|dash|zsh|ksh|fish|sh|cmd(?:\\.exe)?|pwsh|powershell(?:\\.exe)?)$/u.test(executable)) {\n")
        + TEXT("      const payloadIndex = tokens.slice(executableIndex + 1).findIndex((token) => /^(?:-[a-z]*c|\\/c)$/iu.test(token))\n")
        + TEXT("      if (payloadIndex >= 0) {\n")
        + TEXT("        const payload = tokens[executableIndex + payloadIndex + 2]\n")
        + TEXT("        if (payload && hasExecutionCapableReadOption(payload)) return true\n")
        + TEXT("      }\n")
        + TEXT("    }\n")
        + TEXT("    if (executable === \"rg\" && tokens.slice(executableIndex + 1).some((token) => token === \"--pre\" || token.startsWith(\"--pre=\") || token === \"--hostname-bin\" || token.startsWith(\"--hostname-bin=\"))) return true\n")
        + TEXT("    if (executable === \"fd\" && tokens.slice(executableIndex + 1).some((token) => token === \"-x\" || token === \"-X\" || token === \"--exec\" || token.startsWith(\"--exec=\") || token === \"--exec-batch\" || token.startsWith(\"--exec-batch=\"))) return true\n")
        + TEXT("    if (executable === \"tree\" && tokens.slice(executableIndex + 1).some((token) => token === \"-o\" || token === \"--output\" || token.startsWith(\"--output=\"))) return true\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function containsDynamicShellMutation(command: string): boolean {\n")
        + TEXT("  return DYNAMIC_SHELL_ASSIGNMENT_PATTERN.test(command) && SHELL_VARIABLE_EXPANSION_PATTERN.test(command) && !isExplicitReadOnlyCommand(command)\n")
        + TEXT("}\n\n")
        + TEXT("function containsDestructiveGitCommand(command: string, depth = 0): boolean {\n")
        + TEXT("  if (depth > 4) return true\n")
        + TEXT("  const tokens = tokenizeShellCommand(command)\n")
        + TEXT("  for (let executableIndex = 0; executableIndex < tokens.length; executableIndex += 1) {\n")
        + TEXT("    const executable = basenamePath(tokens[executableIndex].replace(/[\"']/gu, \"\")).toLowerCase()\n")
        + TEXT("    if (/^(?:bash|dash|zsh|ksh|fish|sh|cmd(?:\\.exe)?|pwsh|powershell(?:\\.exe)?)$/u.test(executable)) {\n")
        + TEXT("      const payloadIndex = tokens.slice(executableIndex + 1).findIndex((token) => /^(?:-[a-z]*c|\\/c)$/iu.test(token))\n")
        + TEXT("      const payload = payloadIndex >= 0 ? tokens[executableIndex + payloadIndex + 2] : undefined\n")
        + TEXT("      if (payload && containsDestructiveGitCommand(payload, depth + 1)) return true\n")
        + TEXT("    }\n")
        + TEXT("    if (executable !== \"git\") continue\n")
        + TEXT("    let index = executableIndex + 1\n")
        + TEXT("    while (index < tokens.length && tokens[index].startsWith(\"-\")) {\n")
        + TEXT("      const option = tokens[index].toLowerCase()\n")
        + TEXT("      if (option === \"-c\" && /^alias\\.[^=]+=!/iu.test(tokens[index + 1] ?? \"\")) return true\n")
        + TEXT("      if (/^-c=alias\\.[^=]+=!/iu.test(option)) return true\n")
        + TEXT("      if (/^--config-env=alias\\./iu.test(option)) return true\n")
        + TEXT("      if ([\"-c\", \"-C\", \"--git-dir\", \"--work-tree\", \"--namespace\", \"--exec-path\"].includes(tokens[index]) && !option.includes(\"=\")) index += 1\n")
        + TEXT("      index += 1\n")
        + TEXT("    }\n")
        + TEXT("    const subcommand = tokens[index]?.toLowerCase()\n")
        + TEXT("    const args = tokens.slice(index + 1).map((token) => token.toLowerCase())\n")
        + TEXT("    if (subcommand === \"apply\") return true\n")
        + TEXT("    if ([\"reset\", \"restore\", \"checkout\"].includes(subcommand ?? \"\")) return true\n")
        + TEXT("    if (subcommand === \"clean\") {\n")
        + TEXT("      const dryRun = args.some((arg) => arg === \"--dry-run\" || (/^-[^-]/u.test(arg) && arg.includes(\"n\")))\n")
        + TEXT("      if (!dryRun) return true\n")
        + TEXT("    }\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n")
        + TEXT("function containsStdinExecutedShell(command: string): boolean {\n")
        + TEXT("  return /\\|\\s*(?:bash|dash|zsh|ksh|fish|sh|pwsh|powershell)(?:\\s|$)/iu.test(command)\n")
        + TEXT("}\n\n")
        + TEXT("function containsProcessSpawningInterpreter(command: string): boolean {\n")
        + TEXT("  return /\\b(?:child_process|execFileSync|execSync|spawnSync|subprocess\\.|Process\\.(?:run|start)\\s*\\()/iu.test(command)\n")
        + TEXT("}\n\n")
        + TEXT("function isHarmlessBinaryExtensionMention(command: string): boolean {\n")
        + TEXT("  const normalized = command.trim().toLowerCase()\n")
        + TEXT("  const searchPattern = /^(?:(?:\\/usr)?\\/bin\\/)?(?:rg|grep)\\b/iu.test(normalized) && /\\\\\\.(?:uasset|umap)\\b/iu.test(normalized)\n")
        + TEXT("  if (searchPattern && tokenizeShellCommand(normalized).some((token) => !/\\\\\\.(?:uasset|umap)\\b/iu.test(token) && tokenMayResolveToUnrealBinaryAsset(token))) return false\n")
        + TEXT("  const printedLiteral = /^(?:python|python3)\\b/iu.test(normalized) && /\\bprint\\s*\\(/iu.test(normalized) && !/\\b(?:open|read)\\s*\\(|readfilesync\\s*\\(/iu.test(normalized)\n")
        + TEXT("  return searchPattern || printedLiteral\n")
        + TEXT("}\n\n")
        + TEXT("function containsTarExtractionCommand(command: string): boolean {\n")
        + TEXT("  const tokens = command.match(/\"[^\"]*\"|'[^']*'|\\S+/gu)?.map((token) => token.replace(/^[\"']|[\"']$/gu, \"\")) ?? []\n")
        + TEXT("  for (let executableIndex = 0; executableIndex + 1 < tokens.length; executableIndex += 1) {\n")
        + TEXT("    if (!/(?:^|[\\\\/])(?:tar|bsdtar|gtar)$/iu.test(tokens[executableIndex])) continue\n")
        + TEXT("    const firstOption = tokens[executableIndex + 1].toLowerCase()\n")
        + TEXT("    if (!firstOption.startsWith(\"-\") && firstOption.startsWith(\"x\")) return true\n")
        + TEXT("    for (const option of tokens.slice(executableIndex + 1)) {\n")
        + TEXT("      const normalized = option.toLowerCase()\n")
        + TEXT("      if (normalized === \"--extract\" || (/^-[^-]/u.test(normalized) && normalized.includes(\"x\"))) return true\n")
        + TEXT("    }\n")
        + TEXT("  }\n")
        + TEXT("  return false\n")
        + TEXT("}\n\n");
}
}
