#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
FString MakeGuardrailsMutationAdmissionSection()
{
    return FString()
        + TEXT("function parseStructuredToolOutput(value: string): unknown {\n")
        + TEXT("  const trimmed = value.trim()\n")
        + TEXT("  if (!trimmed.startsWith(\"{\") && !trimmed.startsWith(\"[\")) return undefined\n")
        + TEXT("  try { return JSON.parse(trimmed) } catch { return undefined }\n")
        + TEXT("}\n\n")
        + TEXT("type ToolResultSummary = { sawSuccess: boolean; sawFailure: boolean }\n\n")
        + TEXT("function summarizeStructuredToolResults(value: unknown, depth = 0): ToolResultSummary {\n")
        + TEXT("  if (depth > 10) return { sawSuccess: false, sawFailure: false }\n")
        + TEXT("  if (typeof value === \"string\") {\n")
        + TEXT("    const parsed = parseStructuredToolOutput(value)\n")
        + TEXT("    return parsed === undefined ? { sawSuccess: false, sawFailure: false } : summarizeStructuredToolResults(parsed, depth + 1)\n")
        + TEXT("  }\n")
        + TEXT("  if (Array.isArray(value)) {\n")
        + TEXT("    const summary = { sawSuccess: false, sawFailure: false }\n")
        + TEXT("    for (const item of value) {\n")
        + TEXT("      const itemSummary = summarizeStructuredToolResults(item, depth + 1)\n")
        + TEXT("      summary.sawSuccess ||= itemSummary.sawSuccess\n")
        + TEXT("      summary.sawFailure ||= itemSummary.sawFailure\n")
        + TEXT("    }\n")
        + TEXT("    return summary\n")
        + TEXT("  }\n")
        + TEXT("  if (!value || typeof value !== \"object\") return { sawSuccess: false, sawFailure: false }\n")
        + TEXT("  const success = readObjectProperty(value, \"success\")\n")
        + TEXT("  const status = readStringProperty(value, \"status\") ?? readStringProperty(value, \"state\")\n")
        + TEXT("  const hasError = success === false || Boolean(status && /^(?:error|failed|failure|cancelled|canceled|timeout|timed_out)$/iu.test(status)) || readBooleanProperty(value, \"isError\") || readObjectProperty(value, \"error\") !== undefined || readObjectProperty(value, \"errors\") !== undefined || readObjectProperty(value, \"exception\") !== undefined\n")
        + TEXT("  const summary = {\n")
        + TEXT("    sawSuccess: success === true || Boolean(status && /^(?:ok|success|succeeded|completed)$/iu.test(status)),\n")
        + TEXT("    sawFailure: hasError,\n")
        + TEXT("  }\n")
        + TEXT("  for (const key of [\"structuredContent\", \"content\", \"output\", \"text\"] as const) {\n")
        + TEXT("    const childSummary = summarizeStructuredToolResults(readObjectProperty(value, key), depth + 1)\n")
        + TEXT("    summary.sawSuccess ||= childSummary.sawSuccess\n")
        + TEXT("    summary.sawFailure ||= childSummary.sawFailure\n")
        + TEXT("  }\n")
        + TEXT("  for (const key of [\"result\", \"data\"] as const) {\n")
        + TEXT("    summary.sawFailure ||= summarizeStructuredToolResults(readObjectProperty(value, key), depth + 1).sawFailure\n")
        + TEXT("  }\n")
        + TEXT("  return summary\n")
        + TEXT("}\n\n")
        + TEXT("function summarizeToolOutputEnvelope(output: unknown): ToolResultSummary {\n")
        + TEXT("  if (!output || typeof output !== \"object\" || Array.isArray(output)) return summarizeStructuredToolResults(output)\n")
        + TEXT("  const summary = { sawSuccess: false, sawFailure: false }\n")
        + TEXT("  let sawEnvelopeBranch = false\n")
        + TEXT("  for (const key of [\"structuredContent\", \"content\", \"output\", \"text\"] as const) {\n")
        + TEXT("    const branch = readObjectProperty(output, key)\n")
        + TEXT("    if (branch === undefined) continue\n")
        + TEXT("    sawEnvelopeBranch = true\n")
        + TEXT("    const branchSummary = summarizeStructuredToolResults(branch)\n")
        + TEXT("    summary.sawSuccess ||= branchSummary.sawSuccess\n")
        + TEXT("    summary.sawFailure ||= branchSummary.sawFailure\n")
        + TEXT("  }\n")
        + TEXT("  return sawEnvelopeBranch ? summary : summarizeStructuredToolResults(output)\n")
        + TEXT("}\n\n")
        + TEXT("function toolOutputHasAuthoritativeError(value: unknown, depth = 0): boolean {\n")
        + TEXT("  if (depth > 10 || !value || typeof value !== \"object\" || Array.isArray(value)) return false\n")
        + TEXT("  const status = readStringProperty(value, \"status\") ?? readStringProperty(value, \"state\")\n")
        + TEXT("  if (readObjectProperty(value, \"success\") === false || Boolean(status && /^(?:error|failed|failure|cancelled|canceled|timeout|timed_out)$/iu.test(status)) || readBooleanProperty(value, \"isError\") || readObjectProperty(value, \"error\") !== undefined || readObjectProperty(value, \"errors\") !== undefined || readObjectProperty(value, \"exception\") !== undefined) return true\n")
        + TEXT("  const metadata = readObjectProperty(value, \"metadata\")\n")
        + TEXT("  return metadata !== undefined && toolOutputHasAuthoritativeError(metadata, depth + 1)\n")
        + TEXT("}\n\n")
        + TEXT("function toolOutputSucceeded(output: unknown): boolean {\n")
        + TEXT("  if (toolOutputHasAuthoritativeError(output)) return false\n")
        + TEXT("  const summary = summarizeToolOutputEnvelope(output)\n")
        + TEXT("  return summary.sawSuccess && !summary.sawFailure\n")
        + TEXT("}\n\n")
        + TEXT("function normalizeToolName(value: unknown): string | undefined {\n")
        + TEXT("  if (typeof value !== \"string\") return undefined\n")
        + TEXT("  const normalized = value.trim().toLowerCase()\n")
        + TEXT("  return normalized.length > 0 ? normalized : undefined\n")
        + TEXT("}\n\n")
        + TEXT("function getExactMcpParentTool(input: unknown): string | undefined {\n")
        + TEXT("  const tool = normalizeToolName(readStringProperty(input, \"tool\"))\n")
        + TEXT("  if (!tool?.startsWith(\"unreal-engine_\")) return undefined\n")
        + TEXT("  return tool.slice(\"unreal-engine_\".length)\n")
        + TEXT("}\n\n")
        + TEXT("function getExactToolAction(input: unknown, output: unknown): string | undefined {\n")
        + TEXT("  const inputArgs = readObjectProperty(input, \"args\")\n")
        + TEXT("  const beforeHookArgs = readObjectProperty(output, \"args\")\n")
        + TEXT("  return normalizeToolName(readStringProperty(inputArgs, \"action\") ?? readStringProperty(beforeHookArgs, \"action\"))\n")
        + TEXT("}\n\n")
        + TEXT("function getToolCallID(input: unknown): string | undefined {\n")
        + TEXT("  return readStringProperty(input, \"callID\") ?? readStringProperty(input, \"callId\")\n")
        + TEXT("}\n\n")
        + TEXT("function isProtectedMcpMutation(input: unknown, output: unknown): boolean {\n")
        + TEXT("  const tool = getExactMcpParentTool(input)\n")
        + TEXT("  if (!tool) return false\n")
        + TEXT("  const action = getExactToolAction(input, output)\n")
        + TEXT("  for (const [tool, actions] of Object.entries(MCP_ACTION_SCOPED_MUTATION_TOOLS)) {\n")
        + TEXT("    if (getExactMcpParentTool(input) !== tool) continue\n")
        + TEXT("    if (!action) return true\n")
        + TEXT("    if (actions.includes(action)) return true\n")
        + TEXT("    if (tool === \"manage_tools\") return !MCP_INVENTORY_ACTIONS.has(action)\n")
        + TEXT("    if (tool === \"inspect\") return !MCP_INSPECTION_ACTIONS.has(action)\n")
        + TEXT("    return !/^(?:get|list|find|inspect|query|validate|check|analyze)_/u.test(action)\n")
        + TEXT("  }\n")
        + TEXT("  if (!MCP_PROTECTED_PARENT_TOOLS.includes(tool as (typeof MCP_PROTECTED_PARENT_TOOLS)[number])) {\n")
        + TEXT("    return true\n")
        + TEXT("  }\n")
        + TEXT("  if (!action) return true\n")
        + TEXT("  return !MCP_KNOWN_READ_ONLY_ACTIONS.has(action)\n")
        + TEXT("}\n\n")
        + TEXT("function recordMcpPreflightSuccess(input: unknown, output: unknown): void {\n")
        + TEXT("  if (!toolOutputSucceeded(output)) return\n")
        + TEXT("  const tool = getExactMcpParentTool(input)\n")
        + TEXT("  const action = getExactToolAction(input, output)\n")
        + TEXT("  const state = getMcpPreflightState(input)\n")
        + TEXT("  if (tool === \"manage_tools\" && action && MCP_INVENTORY_ACTIONS.has(action)) state.sawToolInventory = true\n")
        + TEXT("  if (tool === \"inspect\" && action && MCP_INSPECTION_ACTIONS.has(action)) {\n")
        + TEXT("    state.sawInspection = true\n")
        + TEXT("    state.sawRouteCard = false\n")
        + TEXT("    state.routeParent = undefined\n")
        + TEXT("    state.routeAction = undefined\n")
        + TEXT("    state.inspectionGeneration += 1\n")
        + TEXT("    state.mutationsSinceInspection = 0\n")
        + TEXT("    state.mutationsSinceRouteCard = 0\n")
        + TEXT("    state.pendingMutationCallGenerations.clear()\n")
        + TEXT("  }\n")
        + TEXT("}\n\n")
        + TEXT("function enforceMcpMutationPreflight(input: unknown, output: unknown): void {\n")
        + TEXT("  if (!isProtectedMcpMutation(input, output)) return\n")
        + TEXT("  const state = getMcpPreflightState(input)\n")
        + TEXT("  if (!state.sawToolInventory || !state.sawInspection) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked MCP editor mutation before completed preflight. Run /unreal-tool-inventory and inspect current editor state successfully first.\")\n")
        + TEXT("  }\n")
        + TEXT("  if (!state.sawRouteCard) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked MCP editor mutation before route-card preflight. Run /unreal-route-card or provide Intent, Evidence, Tool route, Mutation bounds, Safety, Validation, and Rollback fields after the current inspect.\")\n")
        + TEXT("  }\n")
        + TEXT("  const tool = getExactMcpParentTool(input)\n")
        + TEXT("  const action = getExactToolAction(input, output)\n")
        + TEXT("  if (!tool || !action || state.routeParent !== tool || state.routeAction !== action) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked MCP editor mutation because the current route card does not match the exact parent tool/action.\")\n")
        + TEXT("  }\n")
        + TEXT("  const callID = getToolCallID(input)\n")
        + TEXT("  if (!callID) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked MCP editor mutation without a stable tool call ID.\")\n")
        + TEXT("  }\n")
        + TEXT("  if (state.pendingMutationCallGenerations.has(callID)) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked duplicate MCP editor mutation admission for the same tool call ID.\")\n")
        + TEXT("  }\n")
        + TEXT("  if (state.mutationsSinceInspection + state.pendingMutationCallGenerations.size >= MAX_MCP_MUTATIONS_AFTER_INSPECTION) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked MCP editor mutation after stale inspection. Run inspect again and validate current editor state before continuing mutations.\")\n")
        + TEXT("  }\n")
        + TEXT("  if (state.mutationsSinceRouteCard + state.pendingMutationCallGenerations.size >= MAX_MCP_MUTATIONS_AFTER_ROUTE_CARD) {\n")
        + TEXT("    throw new Error(\"Unreal Agent blocked MCP editor mutation after stale route card. Run /unreal-route-card again with current evidence, validation, and rollback before continuing mutations.\")\n")
        + TEXT("  }\n")
        + TEXT("  state.pendingMutationCallGenerations.set(callID, state.inspectionGeneration)\n")
        + TEXT("}\n\n")
        + TEXT("function recordMcpMutationResult(input: unknown, output: unknown): void {\n")
        + TEXT("  const state = getMcpPreflightState(input)\n")
        + TEXT("  const callID = getToolCallID(input)\n")
        + TEXT("  const reservationGeneration = callID ? state.pendingMutationCallGenerations.get(callID) : undefined\n")
        + TEXT("  if (callID) state.pendingMutationCallGenerations.delete(callID)\n")
        + TEXT("  if (reservationGeneration === undefined) {\n")
        + TEXT("    if (callID && isProtectedMcpMutation(input, output) && toolOutputSucceeded(output)) {\n")
        + TEXT("      state.sawInspection = false\n")
        + TEXT("      state.sawRouteCard = false\n")
        + TEXT("      state.routeParent = undefined\n")
        + TEXT("      state.routeAction = undefined\n")
        + TEXT("    }\n")
        + TEXT("    return\n")
        + TEXT("  }\n")
        + TEXT("  if (!toolOutputSucceeded(output)) return\n")
        + TEXT("  if (reservationGeneration !== state.inspectionGeneration) {\n")
        + TEXT("    state.sawInspection = false\n")
        + TEXT("    state.sawRouteCard = false\n")
        + TEXT("    state.routeParent = undefined\n")
        + TEXT("    state.routeAction = undefined\n")
        + TEXT("    return\n")
        + TEXT("  }\n")
        + TEXT("  state.mutationsSinceInspection += 1\n")
        + TEXT("  state.mutationsSinceRouteCard += 1\n")
        + TEXT("}\n\n");
}
}
