#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
FString MakeGuardrailsPreflightStateSection()
{
    return FString()
        + TEXT("const SECRET_PATTERNS = [/x-mcp-capability-token/iu, /capability[_-]?token/iu, /authorization\\s*:/iu, /bearer\\s+[a-z0-9._\\-]+/iu, /api[_-]?key/iu, /access[_-]?token/iu, /refresh[_-]?token/iu, /password/iu, /secret/iu]\n\n")
        + TEXT("const MCP_PROTECTED_PARENT_TOOLS = [\"manage_asset\", \"manage_blueprint\", \"control_actor\", \"manage_level\", \"manage_level_structure\", \"build_environment\", \"manage_geometry\", \"manage_pcg\", \"manage_sequence\", \"manage_effect\", \"manage_audio\", \"manage_character\", \"manage_combat\", \"manage_ai\", \"manage_gas\", \"manage_networking\", \"manage_inventory\", \"manage_interaction\", \"animation_physics\", \"control_editor\", \"system_control\"] as const\n")
        + TEXT("const MCP_INVENTORY_ACTIONS = new Set([\"list_tools\", \"list_categories\", \"get_status\"])\n")
        + TEXT("const MCP_INSPECTION_ACTIONS = new Set([\"inspect_object\", \"get_actor_details\", \"get_blueprint_details\", \"get_mesh_details\", \"get_texture_details\", \"get_material_details\", \"get_level_details\", \"get_component_details\", \"get_property\", \"get_components\", \"get_component_property\", \"inspect_class\", \"inspect_cdo\", \"runtime_report\", \"pie_report\", \"list_objects\", \"get_metadata\", \"find_by_tag\", \"find_by_class\", \"get_bounding_box\", \"get_project_settings\", \"get_world_settings\", \"get_viewport_info\", \"get_content_browser_state\", \"get_selected_actors\", \"get_scene_stats\", \"get_performance_stats\", \"get_memory_stats\", \"get_editor_settings\"])\n")
        + TEXT("const MCP_KNOWN_READ_ONLY_ACTIONS = new Set([\"analyze_graph\", \"analyze_trace\", \"find_actors_by_class\", \"find_actors_by_name\", \"find_actors_by_tag\", \"find_by_class\", \"find_by_name\", \"find_by_tag\", \"get_actor_bounds\", \"get_actor_components\", \"get_actor_details\", \"get_actor_transform\", \"get_animation_info\", \"get_asset_graph\", \"get_audio_info\", \"get_bindings\", \"get_blueprint_details\", \"get_bounding_box\", \"get_character_info\", \"get_combat_info\", \"get_combat_stats\", \"get_component_details\", \"get_component_property\", \"get_components\", \"get_content_browser_state\", \"get_current_level\", \"get_dependencies\", \"get_editor_settings\", \"get_foliage_instances\", \"get_gas_info\", \"get_interaction_info\", \"get_inventory_info\", \"get_level_details\", \"get_level_structure_info\", \"get_material_details\", \"get_material_stats\", \"get_memory_stats\", \"get_mesh_details\", \"get_mesh_info\", \"get_metadata\", \"get_niagara_info\", \"get_performance_stats\", \"get_project_settings\", \"get_properties\", \"get_property\", \"get_scene_stats\", \"get_selected_actors\", \"get_source_control_state\", \"get_status\", \"get_summary\", \"get_texture_details\", \"get_trace_status\", \"get_transform\", \"get_viewport_info\", \"get_world_settings\", \"inspect_cdo\", \"inspect_class\", \"inspect_object\", \"list_categories\", \"list_debug_shapes\", \"list_instances\", \"list_levels\", \"list_objects\", \"list_tools\", \"list_track_types\", \"list_tracks\", \"pie_report\", \"runtime_report\", \"validate_assets\", \"validate_level\", \"validate_niagara_system\"])\n")
        + TEXT("const MCP_ACTION_SCOPED_MUTATION_TOOLS: Record<string, readonly string[]> = {\n")
        + TEXT("  manage_tools: [\"enable_tools\", \"disable_tools\", \"enable_category\", \"disable_category\", \"reset\"],\n")
        + TEXT("  inspect: [\"set_property\", \"set_component_property\", \"add_tag\", \"create_snapshot\", \"restore_snapshot\", \"delete_object\"],\n")
        + TEXT("  system_control: [\"set_project_setting\", \"set_cvar\", \"set_quality\", \"set_resolution\", \"set_fullscreen\", \"execute_command\", \"console_command\", \"execute_python\", \"run_ubt\", \"run_tests\", \"spawn_category\", \"lumen_update_scene\", \"play_sound\", \"create_widget\", \"show_widget\", \"add_widget_child\", \"start_session\", \"start_unreal_insights\", \"capture_insights_trace\", \"pause_session\", \"resume_session\", \"stop_session\", \"write_snapshot\", \"send_snapshot\", \"profile\", \"start_profiling\", \"stop_profiling\", \"run_benchmark\", \"generate_memory_report\", \"set_scalability\", \"set_resolution_scale\", \"set_vsync\", \"set_frame_rate_limit\", \"configure_texture_streaming\", \"configure_lod\", \"apply_baseline_settings\", \"optimize_draw_calls\", \"merge_actors\", \"configure_occlusion_culling\", \"optimize_shaders\", \"configure_nanite\", \"configure_world_partition\"],\n")
        + TEXT("}\n\n")
        + TEXT("type McpPreflightState = { sawToolInventory: boolean; sawInspection: boolean; sawRouteCard: boolean; routeParent?: string; routeAction?: string; inspectionGeneration: number; mutationsSinceInspection: number; mutationsSinceRouteCard: number; pendingMutationCallGenerations: Map<string, number> }\n\n")
        + TEXT("const MCP_PREFLIGHT_STATE = new Map<string, McpPreflightState>()\n")
        + TEXT("const MCP_ASSISTANT_MESSAGE_SESSIONS = new Map<string, string>()\n")
        + TEXT("const MCP_ASSISTANT_MESSAGE_INSPECTION_GENERATIONS = new Map<string, number>()\n")
        + TEXT("const MAX_MCP_MUTATIONS_AFTER_INSPECTION = 3\n")
        + TEXT("const MAX_MCP_MUTATIONS_AFTER_ROUTE_CARD = 3\n")
        + TEXT("const ROUTE_CARD_FIELD_PATTERNS = [/(^|\\n)\\s*Intent\\s*:\\s*\\S[^\\n]*/iu, /(^|\\n)\\s*Evidence\\s*:\\s*\\S[^\\n]*/iu, /(^|\\n)\\s*(Tool route|parent tool\\/action)\\s*:\\s*\\S[^\\n]*/iu, /(^|\\n)\\s*(Mutation bounds|target)\\s*:\\s*\\S[^\\n]*/iu, /(^|\\n)\\s*Safety\\s*:\\s*\\S[^\\n]*/iu, /(^|\\n)\\s*Validation\\s*:\\s*\\S[^\\n]*/iu, /(^|\\n)\\s*(Rollback|stop condition)\\s*:\\s*\\S[^\\n]*/iu] as const\n\n")
        + TEXT("function readStringProperty(value: unknown, key: string): string | undefined {\n")
        + TEXT("  if (!value || typeof value !== \"object\" || Array.isArray(value)) return undefined\n")
        + TEXT("  const match = Object.entries(value).find(([candidate]) => candidate === key)\n")
        + TEXT("  const raw = match?.[1]\n")
        + TEXT("  if (typeof raw !== \"string\") return undefined\n")
        + TEXT("  const normalized = raw.trim()\n")
        + TEXT("  return normalized.length > 0 ? normalized : undefined\n")
        + TEXT("}\n\n")
        + TEXT("function readObjectProperty(value: unknown, key: string): unknown {\n")
        + TEXT("  if (!value || typeof value !== \"object\" || Array.isArray(value)) return undefined\n")
        + TEXT("  return Object.entries(value).find(([candidate]) => candidate === key)?.[1]\n")
        + TEXT("}\n\n")
        + TEXT("function readBooleanProperty(value: unknown, key: string): boolean {\n")
        + TEXT("  return readObjectProperty(value, key) === true\n")
        + TEXT("}\n\n")
        + TEXT("function getSessionKey(input: unknown): string {\n")
        + TEXT("  return readStringProperty(input, \"sessionID\") ?? readStringProperty(input, \"sessionId\") ?? \"global\"\n")
        + TEXT("}\n\n")
        + TEXT("function getMcpPreflightState(input: unknown): McpPreflightState {\n")
        + TEXT("  const sessionKey = getSessionKey(input)\n")
        + TEXT("  const existing = MCP_PREFLIGHT_STATE.get(sessionKey)\n")
        + TEXT("  if (existing) return existing\n")
        + TEXT("  const created = { sawToolInventory: false, sawInspection: false, sawRouteCard: false, routeParent: undefined, routeAction: undefined, inspectionGeneration: 0, mutationsSinceInspection: 0, mutationsSinceRouteCard: 0, pendingMutationCallGenerations: new Map<string, number>() }\n")
        + TEXT("  MCP_PREFLIGHT_STATE.set(sessionKey, created)\n")
        + TEXT("  return created\n")
        + TEXT("}\n\n")
        + TEXT("function clearMcpSessionState(sessionKey: string): void {\n")
        + TEXT("  MCP_PREFLIGHT_STATE.delete(sessionKey)\n")
        + TEXT("  for (const [messageID, messageSession] of MCP_ASSISTANT_MESSAGE_SESSIONS.entries()) {\n")
        + TEXT("    if (messageSession !== sessionKey) continue\n")
        + TEXT("    MCP_ASSISTANT_MESSAGE_SESSIONS.delete(messageID)\n")
        + TEXT("    MCP_ASSISTANT_MESSAGE_INSPECTION_GENERATIONS.delete(messageID)\n")
        + TEXT("  }\n")
        + TEXT("}\n\n")
        + TEXT("function textContainsRouteCard(text: string): boolean {\n")
        + TEXT("  return ROUTE_CARD_FIELD_PATTERNS.every((pattern) => pattern.test(text))\n")
        + TEXT("}\n\n")
        + TEXT("function parseRouteCardRoute(text: string): { parent: string; action: string } | undefined {\n")
        + TEXT("  const match = /(?:^|\\n)\\s*(?:Tool route|parent tool\\/action)\\s*:\\s*(?:unreal-engine_)?([a-z0-9_]+)\\s*\\/\\s*([a-z0-9_]+)/iu.exec(text)\n")
        + TEXT("  return match ? { parent: match[1].toLowerCase(), action: match[2].toLowerCase() } : undefined\n")
        + TEXT("}\n\n")
        + TEXT("function recordRouteCard(input: unknown, text: string): void {\n")
        + TEXT("  const route = parseRouteCardRoute(text)\n")
        + TEXT("  if (!route) return\n")
        + TEXT("  const state = getMcpPreflightState(input)\n")
        + TEXT("  state.sawRouteCard = true\n")
        + TEXT("  state.routeParent = route.parent\n")
        + TEXT("  state.routeAction = route.action\n")
        + TEXT("  state.mutationsSinceRouteCard = 0\n")
        + TEXT("}\n\n")
        + TEXT("function recordRouteCardFromEvent(event: unknown): void {\n")
        + TEXT("  if (!event || typeof event !== \"object\") return\n")
        + TEXT("  const eventRecord = event as Record<string, unknown>\n")
        + TEXT("  const eventType = readStringProperty(eventRecord, \"type\")\n")
        + TEXT("  const properties = readObjectProperty(eventRecord, \"properties\")\n")
        + TEXT("  if (eventType === \"session.deleted\") {\n")
        + TEXT("    const info = readObjectProperty(properties, \"info\")\n")
        + TEXT("    const sessionID = readStringProperty(properties, \"sessionID\") ?? readStringProperty(info, \"id\")\n")
        + TEXT("    if (sessionID) clearMcpSessionState(sessionID)\n")
        + TEXT("    return\n")
        + TEXT("  }\n")
        + TEXT("  if (eventType === \"message.updated\") {\n")
        + TEXT("    const info = readObjectProperty(properties, \"info\")\n")
        + TEXT("    const messageID = readStringProperty(info, \"id\")\n")
        + TEXT("    const role = readStringProperty(info, \"role\")\n")
        + TEXT("    const sessionID = getSessionKey(info)\n")
        + TEXT("    if (messageID && role === \"assistant\" && !MCP_ASSISTANT_MESSAGE_SESSIONS.has(messageID)) {\n")
        + TEXT("      MCP_ASSISTANT_MESSAGE_SESSIONS.set(messageID, sessionID)\n")
        + TEXT("      MCP_ASSISTANT_MESSAGE_INSPECTION_GENERATIONS.set(messageID, getMcpPreflightState(info).inspectionGeneration)\n")
        + TEXT("    }\n")
        + TEXT("    return\n")
        + TEXT("  }\n")
        + TEXT("  if (eventType === \"message.removed\") {\n")
        + TEXT("    const messageID = readStringProperty(properties, \"messageID\")\n")
        + TEXT("    if (messageID) {\n")
        + TEXT("      MCP_ASSISTANT_MESSAGE_SESSIONS.delete(messageID)\n")
        + TEXT("      MCP_ASSISTANT_MESSAGE_INSPECTION_GENERATIONS.delete(messageID)\n")
        + TEXT("    }\n")
        + TEXT("    return\n")
        + TEXT("  }\n")
        + TEXT("  if (eventType !== \"message.part.updated\") return\n")
        + TEXT("  const part = readObjectProperty(properties, \"part\")\n")
        + TEXT("  if (readStringProperty(part, \"type\") !== \"text\") return\n")
        + TEXT("  const messageID = readStringProperty(part, \"messageID\")\n")
        + TEXT("  const sessionID = getSessionKey(part)\n")
        + TEXT("  const state = getMcpPreflightState(part)\n")
        + TEXT("  const text = readStringProperty(part, \"text\")\n")
        + TEXT("  if (!messageID || !text || !state.sawInspection || readBooleanProperty(part, \"ignored\") || readBooleanProperty(part, \"synthetic\")) return\n")
        + TEXT("  if (MCP_ASSISTANT_MESSAGE_SESSIONS.get(messageID) !== sessionID) return\n")
        + TEXT("  if (MCP_ASSISTANT_MESSAGE_INSPECTION_GENERATIONS.get(messageID) !== state.inspectionGeneration) return\n")
        + TEXT("  if (!textContainsRouteCard(text)) return\n")
        + TEXT("  recordRouteCard(part, text)\n")
        + TEXT("}\n\n");
}
}
