#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
    FString MakeCommandMarkdown(const FString& Description, const FString& Body)
    {
        return FString()
            + TEXT("---\n")
            + FString::Printf(TEXT("description: %s\n"), *Description)
            + FString::Printf(TEXT("%s\n"), StudioKitVersionMarker)
            + TEXT("agent: unreal-agent\n")
            + TEXT("---\n")
            + Body
            + TEXT("\n");
    }

    void AppendCommandTemplates(TArray<FStudioKitTemplateFile>& Templates)
    {
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-start.md"), MakeCommandMarkdown(TEXT("Start or reset the Unreal project production plan."), TEXT("Use the Unreal project bootstrap skill. Inspect available context, identify the current production stage, and propose the smallest playable next milestone with acceptance criteria.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-getting-started.md"), MakeCommandMarkdown(TEXT("Guide a first Unreal session from official docs to inspected editor action."), TEXT("Use the unreal-official-getting-started skill. Anchor the explanation in Epic's Create your First Project, Unreal Editor Interface, Content Browser, and In-Editor Testing docs, then run /unreal-tool-inventory and inspect current project/editor state before claiming live facts or making one reversible MCP-backed change.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-project-setup-plan.md"), MakeCommandMarkdown(TEXT("Plan Unreal template, project defaults, first-map, and starter-content setup with MCP evidence."), TEXT("Use the unreal-project-setup-template-discipline skill. Run /unreal-tool-inventory; inspect project and engine context, system_control get_project_settings read-back, current/default maps and modes, GameMode/GameInstance defaults, enabled plugins/modules, target platform and quality preset, Content Browser state, starter/sample or migrated content, dependencies, dirty packages, source-control risk, and logs; then name the system_control get_project_settings before set_project_setting route, manage_level/manage_level_structure map route, supported manage_asset package route, control_editor open/save route, approval needs, restart or migration risk, validation, and rollback before changing project defaults or adding template-derived content.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-editor-tour.md"), MakeCommandMarkdown(TEXT("Orient a new or returning user to the current Unreal Editor project."), TEXT("Use the Unreal editor orientation skill. Run /unreal-tool-inventory, inspect the current project, level, viewport, selection, Content Browser, PIE state, and dirty packages, then guide the user through one evidence-backed editor loop without guessing about live state.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-first-playable.md"), MakeCommandMarkdown(TEXT("Run a beginner-friendly first playable Unreal editor loop."), TEXT("Use the unreal-first-playable-loop skill. Run /unreal-tool-inventory, inspect Project Browser/template context, viewport, selection, World Outliner, Details, Content Browser, PIE state, dirty packages, and logs, then make one small reversible MCP-backed change, validate it in PIE or editor checks, and report evidence plus unverified risks.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-inspect.md"), MakeCommandMarkdown(TEXT("Inspect current Unreal project, editor, map, selection, and risks."), TEXT("Use the MCP tool playbook. Discover available `unreal-engine` MCP tools, inspect the project/editor state, include `get_content_browser_state` when selected assets or folders matter, summarize what is known, and list anything still unverified.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-tool-inventory.md"), MakeCommandMarkdown(TEXT("Inventory the connected Unreal MCP tool surface before broad production work."), TEXT("Use `manage_tools` to enumerate canonical parent tools, enabled categories, disabled or missing capabilities, and the narrowest domain tools expected for the current request. Produce a compact inventory, name any capability gaps, and refresh it after reconnects or MCP configuration changes. Do not claim live editor state from the inventory; use `inspect` for project and editor facts.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-route-card.md"), MakeCommandMarkdown(TEXT("Draft the required MCP route card before mutating Unreal editor or project state."),             TEXT("Use the unreal-mcp-route-card skill and emit the card as your own reply text (not tool input), after /unreal-tool-inventory and a successful inspect, in the same session, before the mutation. The card must be plain lines with these exact labels: intent:, evidence:, tool route: (as parent tool/action, e.g. manage_level/save_level_as), mutation bounds:, safety:, validation:, rollback: - no bullet markers. One card per parent/action; re-emit after every inspect. If the needed MCP route is missing, mark it blocked instead of using direct .uasset/.umap file edits.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-pie-sie-check.md"), MakeCommandMarkdown(TEXT("Check PIE/SIE runtime evidence against persisted Unreal editor state."), TEXT("Use the unreal-pie-sie-safety skill. Inspect PIE/SIE state before and after preview, identify whether evidence came from the editor world, PIE world, SIE session, viewport, logs, or post-stop inspect, and do not claim persistence until save, compile, Keep Simulation Changes, or fresh post-stop inspect/log evidence proves it.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-editor-control-plan.md"), MakeCommandMarkdown(TEXT("Plan editor viewport, selection, screenshot, tab, save, PIE/SIE, and modal operations with MCP evidence."), TEXT("Use the unreal-editor-control-discipline skill. Inspect editor world, viewport, selection, Content Browser context, active asset or tab, PIE/SIE state, dirty packages, modal risk, and logs; then name the narrow control_editor route plus any needed inspect/domain route, mutation bounds, screenshot or save evidence, editor-world versus preview-world distinction, validation, and rollback before mutating editor state.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-content-plan.md"), MakeCommandMarkdown(TEXT("Plan Content Browser asset and folder work with MCP package paths."), TEXT("Use the unreal-content-browser-asset-discipline skill. Inspect Content Browser state with get_content_browser_state, name selected folders/assets, intended /Game package paths, source and destination, dependency or redirector risk, narrow MCP parent tool/action, validation, and rollback before creating, importing, moving, renaming, duplicating, deleting, migrating, or reorganizing assets.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-blueprint-plan.md"), MakeCommandMarkdown(TEXT("Plan Blueprint edits with compile, save, and runtime evidence."), TEXT("Use the unreal-blueprint-compile-discipline skill. Inspect the Blueprint asset path, class/CDO facts, parent class, components, variables, selected graph when available, compile status, dirty packages, and recent compiler/log output; then name the manage_blueprint route, intended graph/default/component change, validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-level-actor-plan.md"), MakeCommandMarkdown(TEXT("Plan level and Actor edits with inspected ownership, transforms, save, and runtime evidence."), TEXT("Use the unreal-level-actor-discipline skill. Inspect the current map/editor world, PIE state, selected Actor(s), Outliner hierarchy, class/root component, transform, attachments, mobility, collision, level/Data Layer/World Partition ownership, dirty packages, and logs; then name the narrow control_actor/manage_level/manage_level_structure/build_environment route, mutation bounds, save/viewport/PIE validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-world-building-plan.md"), MakeCommandMarkdown(TEXT("Plan landscape, foliage, PCG, geometry, and world-partition edits with viewport and runtime evidence."), TEXT("Use the unreal-world-building-discipline skill. Inspect the current map, World Partition/Data Layers, landscape actor/material/layers, foliage types/instances, PCG graph/component, spline roads/rivers/fences, Modeling Mode or procedural geometry targets, collision/nav/performance risk, dirty packages, and logs; then name the narrow build_environment/manage_pcg/manage_geometry/manage_level_structure MCP route, save requirements, viewport screenshot, PIE streaming/collision/navigation/performance validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-gameplay-input-plan.md"), MakeCommandMarkdown(TEXT("Plan gameplay framework and Enhanced Input edits with runtime evidence."), TEXT("Use the unreal-gameplay-input-discipline skill. Inspect GameMode or World Settings override, Default Pawn/Class, PlayerController, HUD, GameState, PlayerState, selected Pawn/Character, Input Actions, Mapping Contexts, priority/triggers/modifiers, dirty packages, and logs; then name the narrow gameplay/input MCP route, compile/save requirements, PIE possession/input/camera/HUD validation, multiplayer authority assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-animation-physics-plan.md"), MakeCommandMarkdown(TEXT("Plan animation and physics edits with runtime evidence."), TEXT("Use the unreal-animation-physics-discipline skill. Inspect Skeletal Mesh, Skeleton, Animation Blueprint, AnimGraph/state machine, Blend Space, Montage, Notifies, Control Rig/IK/retarget assets, Physics Asset, collision bodies/channels, constraints, root-motion settings, dirty packages, and logs; then name the narrow animation_physics MCP route, compile/save requirements, PIE animation/notify/collision/physics/root-motion validation, multiplayer authority assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-vfx-material-plan.md"), MakeCommandMarkdown(TEXT("Plan Niagara, VFX, material, and texture edits with runtime evidence."), TEXT("Use the unreal-vfx-material-discipline skill. Inspect Actor/component ownership, Niagara System, emitter stack, modules, user parameters, attached sockets/components, Material or Material Instance, texture assets, shader compile state, bounds/culling, scalability, viewport state, dirty packages, and logs; then name the narrow manage_effect/material MCP route, compile/save requirements, PIE spawn/parameter/material/bounds/screenshot validation, performance assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-audio-plan.md"), MakeCommandMarkdown(TEXT("Plan audio, MetaSound, attenuation, concurrency, and mix edits with runtime evidence."), TEXT("Use the unreal-audio-discipline skill. Inspect Sound Waves, Sound Cues, MetaSound Sources or Presets, Audio Components, attenuation, concurrency, Submix/Sound Class routing, Audio Volumes/Reverb, listener context, trigger path, dirty packages, and logs; then name the narrow manage_audio MCP route, save requirements, PIE audible playback/spatialization/mix/concurrency validation, multiplayer listener assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-cinematic-sequence-plan.md"), MakeCommandMarkdown(TEXT("Plan Sequencer, Level Sequence, camera, shot, and Movie Render Queue edits with playback evidence."), TEXT("Use the unreal-cinematic-sequence-discipline skill. Inspect Level Sequence Asset, Level Sequence Actor, bound actors, spawnables/possessables, tracks, keyframes, Camera Cut track, CineCameraActors, playback settings, Movie Render Queue plugin/config/output, dirty packages, and logs; then name the narrow manage_sequence MCP route, save requirements, editor/PIE playback, camera-cut, binding, render-queue validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-networking-gas-plan.md"), MakeCommandMarkdown(TEXT("Plan multiplayer networking and Gameplay Ability System edits with server/client evidence."), TEXT("Use the unreal-networking-gas-discipline skill. Inspect NetMode, PIE client count, GameMode/GameState/PlayerState ownership, replicated Actors/components/properties, RPC paths, Ability System Component owner/avatar, Attribute Sets, Gameplay Abilities, Gameplay Effects, Gameplay Tags/Cues, dirty packages, and logs; then name the narrow manage_networking/manage_gas MCP route, compile/save requirements, multiplayer PIE authority/replication/RPC/GAS prediction validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-character-systems-plan.md"), MakeCommandMarkdown(TEXT("Plan Character movement, combat, inventory, equipment, and interaction edits with runtime evidence."), TEXT("Use the unreal-character-systems-discipline skill. Inspect Character/Pawn, PlayerController, Character Movement Component, camera/spring arm, capsule/collision, mesh/Animation Blueprint, health/damage, weapon/projectile assets, inventory/equipment data, interactable Actor/interface/trace or overlap path, dirty packages, and logs; then name the narrow manage_character/manage_combat/manage_inventory/manage_interaction MCP route, compile/save requirements, PIE movement/combat/inventory/interaction/UI validation, authority assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-ui-hud-plan.md"), MakeCommandMarkdown(TEXT("Plan UI, HUD, UMG, and CommonUI edits with runtime evidence."), TEXT("Use the unreal-ui-hud-discipline skill. Inspect HUD class, PlayerController, Widget Blueprint/UserWidget ownership, widget hierarchy, bindings, animations, CommonUI activatable widget stack, input mode/focus target, DPI/anchors, localization/accessibility risk, dirty packages, and logs; then name the narrow UI/HUD MCP route, compile/save requirements, PIE viewport/input/focus/layout validation, local-player assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-ai-navigation-plan.md"), MakeCommandMarkdown(TEXT("Plan AI behavior and navigation edits with runtime evidence."), TEXT("Use the unreal-ai-navigation-discipline skill. Inspect AIController/Pawn ownership, Behavior Tree, Blackboard keys, Perception, EQS, Nav Mesh Bounds Volume, RecastNavMesh/build settings, collision, movement component, patrol targets, dirty packages, and logs; then name the narrow manage_ai/navigation MCP route, compile/save requirements, PIE AIController/Blackboard/NavMesh validation, multiplayer authority assumptions, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-data-save-accessibility-plan.md"), MakeCommandMarkdown(TEXT("Plan SaveGame, data assets, localization, user settings, and accessibility edits with evidence."), TEXT("Use the unreal-data-save-accessibility-discipline skill. Inspect SaveGame class or slot schema, GameInstance/subsystem owner, Data Assets, Data Tables, String Tables, user settings/config, Widget text, localization keys, accessibility requirements, dirty packages, and logs; then name the narrow manage_asset/manage_inventory/manage_blueprint/system_control route plus any needed UI/editor route, migration risk, save/load or read-back evidence, validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-source-control-plan.md"), MakeCommandMarkdown(TEXT("Plan Unreal package source-control checkout, submit, and collaboration-safe asset work."), TEXT("Use the unreal-source-control-collaboration-discipline skill. Inspect Content Browser state, dirty packages, current map/external actor packages, selected assets, dependencies, redirectors, source-control provider availability, and logs; then read manage_asset get_source_control_state for exact /Game assetPaths, name the source_control_checkout/source_control_submit route when available, approval needs, changelist description, conflict/out-of-date/checked-out-by-other risk, validation, and rollback before mutating shared packages.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-performance-insights-plan.md"), MakeCommandMarkdown(TEXT("Plan FPS, frame-time, memory, scalability, and Unreal Insights trace work with measured evidence."), TEXT("Use the unreal-performance-insights-discipline skill. Inspect project/map/PIE state, target platform, scalability/device profile context, performance stats, memory stats, scene stats, logs, and the reproducible scenario; then name the system_control manage_performance route, manage_insights capture_insights_trace/get_trace_status/analyze_trace route when needed, baseline and after metrics, traceFile or memory report path, quality tradeoff, approval needs, validation, and rollback before claiming optimization.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-system-project-plan.md"), MakeCommandMarkdown(TEXT("Plan project settings, console/Python automation, profiling, packaging, cook, and build work with evidence."), TEXT("Use the unreal-system-project-discipline skill. Inspect project settings, enabled plugins/modules, maps and modes, config/scalability/device/platform settings, console variables, Python/editor utility automation surface, profiling targets, packaging/cook/build settings, dirty packages, source-control risk, and recent logs; then name the narrow system_control route plus any needed inspect/control_editor route, approval needs, exact output/log evidence, validation, and rollback before mutating.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-diagnostics-plan.md"), MakeCommandMarkdown(TEXT("Plan Unreal crash, log, compiler, build, and runtime diagnostics with MCP evidence."), TEXT("Use the unreal-diagnostics-crash-recovery-discipline skill. Run /unreal-tool-inventory, then inspect project/map/selection/Blueprint/asset/PIE/runtime/log facts, preserve exact error text, call stack, crash report or Saved/Logs path, reproduction step, recent changes, dirty packages, and Output Log or Message Log evidence; classify the failure, name the narrow inspect/system_control/manage_blueprint/manage_asset/control_editor/domain route, run_tests/validate_assets/run_ubt or Blueprint compile validation, approval needs, rollback, and retest path before changing anything.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-prototype.md"), MakeCommandMarkdown(TEXT("Build the smallest playable Unreal prototype loop."), TEXT("Use the Unreal prototype skill. Create or plan the minimum playable loop, then validate with editor/MCP evidence before expanding scope.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-validate.md"), MakeCommandMarkdown(TEXT("Run a focused Unreal validation pass."), TEXT("Use the Unreal validation loop skill. State acceptance criteria, run the strongest available checks, record evidence, and report blockers separately from warnings.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-ship-check.md"), MakeCommandMarkdown(TEXT("Check release readiness for an Unreal feature or game."), TEXT("Use the Unreal release readiness skill. Review packaging, platform settings, maps, inputs, logs, performance, accessibility/localization, known issues, source-control state, and release blockers.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-fix-errors.md"), MakeCommandMarkdown(TEXT("Diagnose and fix Unreal errors with baseline-fix-retest discipline."), TEXT("Use the unreal-diagnostics-crash-recovery-discipline skill first, then the Unreal debug fix skill for the smallest baseline-fix-retest loop. Preserve exact errors, inspect likely causes through MCP, make the smallest fix, and retest the original failure path.")));
        AddTemplate(Templates, TEXT(".opencode/commands/unreal-cpp-context.md"), MakeCommandMarkdown(TEXT("Review Unreal C++ lifecycle, reflection, and runtime-safety context."), TEXT("Use the Unreal C++ UObject lifecycle integrity skill. Check reflection macros, UPROPERTY ownership, constructor/CDO safety, subsystem lifetime, delegate/timer cleanup, async game-thread boundaries, soft-reference loading, and validation evidence before implementing or approving C++ changes.")));
    }
}
