#include "Acp/StudioKit/UnrealAgentStudioKitPrivate.h"

namespace UnrealAgentStudioKit
{
    FString MakeGuardrailsCommandSafetySection()
    {
        return FString()
            + TEXT("const ARCHIVE_EXTRACTION_API_PATTERN = /(?:\\b(?:tarfile|zipfile|rarfile|py7zr)\\b[^\\r\\n]*\\.extractall\\s*\\(|\\bshutil\\.unpack_archive\\s*\\(|\\bpatoolib\\.extract_archive\\s*\\()/iu\n")
            + TEXT("const PYTHON_MUTATION_IMPORT_ALIAS_PATTERN = /\\bfrom\\s+[a-z_][a-z0-9_.]*\\s+import\\s+(?:\\(\\s*)?(?:(?:[a-z_][a-z0-9_]*)(?:\\s+as\\s+[a-z_][a-z0-9_]*)?\\s*,\\s*)*(?:chmod|chown|copy|copy2|copyfile|copytree|extract_archive|link|makedirs|mkdir|move|remove|removedirs|rename|replace|rmdir|rmtree|symlink|system|truncate|unlink|unpack_archive)\\s+as\\s+[a-z_][a-z0-9_]*/iu\n\n")
            + TEXT("function commandPayloadPriority(key: string): number {\n")
            + TEXT("  const normalized = key.toLowerCase().replace(/[-_]/gu, \"\")\n")
            + TEXT("  if (/^(?:binary|cmd|command|exec|executable|execute|invocation|invoke|program|run)$/u.test(normalized)) return 0\n")
            + TEXT("  if (normalized.includes(\"arg\")) return 1\n")
            + TEXT("  if (normalized === \"script\" || normalized === \"shell\") return 2\n")
            + TEXT("  return 3\n")
            + TEXT("}\n\n")
            + TEXT("function collectAllStringFragments(value: unknown, fragments: string[] = []): string[] {\n")
            + TEXT("  if (typeof value === \"string\") { fragments.push(value); return fragments }\n")
            + TEXT("  if (Array.isArray(value)) { for (const item of value) collectAllStringFragments(item, fragments); return fragments }\n")
            + TEXT("  if (value && typeof value === \"object\") {\n")
            + TEXT("    for (const key of Object.keys(value as Record<string, unknown>).sort()) collectAllStringFragments((value as Record<string, unknown>)[key], fragments)\n")
            + TEXT("  }\n")
            + TEXT("  return fragments\n")
            + TEXT("}\n\n")
            + TEXT("function isProjectRootRemoveTarget(target: string): boolean {\n")
            + TEXT("  const normalized = target.trim().replace(/^[\"']|[\"']$/gu, \"\").replace(/[\\\\/]+$/u, \"\") || \"/\"\n")
            + TEXT("  const lower = normalized.toLowerCase()\n")
            + TEXT("  if ([\".\", \"*\", \"..\", \"../*\", \"/\", \"$pwd\", \"$pwd/*\", \"${pwd}\", \"${pwd}/*\"].includes(lower)) return true\n")
            + TEXT("  if (!GUARDRAIL_PROJECT_DIRECTORY || /[$*?\\[]/u.test(normalized)) return false\n")
            + TEXT("  try { return resolvePath(GUARDRAIL_PROJECT_DIRECTORY, normalized) === GUARDRAIL_PROJECT_DIRECTORY } catch { return true }\n")
            + TEXT("}\n\n")
            + TEXT("function containsDestructiveRecursiveRemove(command: string, depth = 0): boolean {\n")
            + TEXT("  if (depth > 4) return true\n")
            + TEXT("  const tokens = tokenizeShellCommand(command)\n")
            + TEXT("  for (let executableIndex = 0; executableIndex < tokens.length; executableIndex += 1) {\n")
            + TEXT("    const executable = basenamePath(tokens[executableIndex]).toLowerCase().replace(/[\"']/gu, \"\")\n")
            + TEXT("    if (/^(?:bash|dash|zsh|ksh|fish|sh|cmd(?:\\.exe)?|pwsh|powershell(?:\\.exe)?)$/u.test(executable)) {\n")
            + TEXT("      const payloadIndex = tokens.slice(executableIndex + 1).findIndex((token) => /^(?:-[a-z]*c|\\/c)$/iu.test(token))\n")
            + TEXT("      const payload = payloadIndex >= 0 ? tokens[executableIndex + payloadIndex + 2] : undefined\n")
            + TEXT("      if (payload && containsDestructiveRecursiveRemove(payload, depth + 1)) return true\n")
            + TEXT("    }\n")
            + TEXT("    if (executable !== \"rm\") continue\n")
            + TEXT("    const commandTokens = tokens.slice(executableIndex + 1)\n")
            + TEXT("    const targets = commandTokens.filter((token) => !token.startsWith(\"-\") && token !== \"--\")\n")
            + TEXT("    if (targets.some((target) => isProjectRootRemoveTarget(target) || UNREAL_PROJECT_DIRECTORY_PATTERN.test(target))) return true\n")
            + TEXT("  }\n")
            + TEXT("  return false\n")
            + TEXT("}\n\n")
            + TEXT("function extractPotentialShellCommand(input: { tool?: string }, output: unknown): string | undefined {\n")
            + TEXT("  const structured = extractShellCommand(input, output)\n")
            + TEXT("  const args = readObjectProperty(output, \"args\")\n")
            + TEXT("  const allStrings = collectAllStringFragments(args).filter((fragment) => fragment !== structured)\n")
            + TEXT("  if (structured) allStrings.unshift(structured)\n")
            + TEXT("  return allStrings.length > 0 ? allStrings.join(\"\\n\") : undefined\n")
            + TEXT("}\n\n");
    }
}
