/**
 * Graph handles: create_node returns `nodeGuid` (string) which is the
 * correlation key for subsequent get_node_details, connect_pins, and
 * get_pin_details calls. Pin handles are `pinName` (string) on a given node.
 * create_struct_make_break_nodes also returns `nodeGuid` and compiles the
 * Blueprint, surfacing pin/diagnostic detail for the created Make/Break node.
 */
import type { CapabilityRecordSource } from '../../model.js';
import { BP_PLUGINS, buildRecord } from './helpers.js';
import { P } from './properties.js';

const FAMILY = 'graph';
const DOMAIN = 'blueprint';

export const GRAPH_NODES_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'blueprint.create_node',
    action: 'create_node',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['add node', 'place node', 'graph node', 'call function node', 'print string node'],
    summary: 'Create a graph node (function call, event, variable, branch, etc.) in a Blueprint graph.',
    whenToUse: ['A new node must be placed in a Blueprint event or function graph.'],
    whenNotToUse: ['A reroute node for wire organization is needed (use create_reroute_node).'],
    // `parameters` gives a CustomEvent typed inputs ([{name, type}]). The
    // handler always read it; the contract never declared it, so the gateway
    // refused the one way to make an event that takes arguments.
    inputProps: { blueprintPath: P.blueprintPath, graphName: P.graphName, nodeType: P.nodeType, memberName: P.memberName, posX: P.posX, posY: P.posY, functionName: P.nodeFunctionName, pure: P.pure, eventName: P.eventName, customEventName: P.customEventName, memberClass: P.memberClass, targetClass: P.targetClass, inputAxisName: P.inputAxisName, inputActionPath: P.inputActionPath, inputActionAssetPath: P.inputActionAssetPath, actionPath: P.actionPath, structPath: { ...P.structPath, description: 'For MakeStruct or BreakStruct: the struct, a Blueprint Struct asset (/Game/Data/F_Item) or a native one (/Script/SlateCore.SlateColor, /Script/CoreUObject.Vector); without it the node is refused.' }, parameters: { ...P.parameters, description: 'CustomEvent inputs, each {name, type}: float, double, int, int64, bool, byte, string, name, text, object, class, or a struct (Vector, /Script/CoreUObject.Vector).' } },
    required: ['blueprintPath', 'nodeType', 'posX', 'posY'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Unique node identifier for subsequent graph operations.' },
      graphName: P.graphName,
      nodeClass: { type: 'string', description: 'Resolved UK2Node class name.' },
      nodeName: P.nodeName,
      // Placement is echoed back because callers position nodes by coordinate
      // and previously got nothing to lay out against, so successive creates
      // silently stacked.
      posX: { type: 'number', description: 'X coordinate the node was placed at.' },
      posY: { type: 'number', description: 'Y coordinate the node was placed at.' },
      estimatedWidth: { type: 'number', description: 'Approximate node width. Slate computes the real size at draw time, so this is derived from title length and is an estimate, not a measurement.' },
      estimatedHeight: { type: 'number', description: 'Approximate node height, derived from pin-row count. Offset the next node by at least this much to avoid overlap.' },
      overlappingNodes: { type: 'array', items: { type: 'string' }, description: 'Titles of existing nodes whose estimated bounds intersect this one. Empty or absent when placement is clear.' },
      placementWarning: { type: 'string', description: 'Human-readable overlap warning, present only when overlappingNodes is non-empty.' },
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeType: 'CallFunction', memberName: 'PrintString', posX: 100, posY: 200 },
    exampleOutput: { success: true, nodeGuid: 'A1B2C3D4', graphName: 'EventGraph', nodeClass: 'UK2Node_CallFunction', nodeName: 'Print String' },
  }),
  buildRecord({
    id: 'blueprint.add_node',
    action: 'add_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Add a node to a Blueprint graph (alias of create_node with simplified type resolution).',
    whenToUse: ['A node must be added using a friendly type alias (e.g. Branch, Cast, GetVariable).'],
    whenNotToUse: ['Full member-class control is needed (use create_node).'],
    inputProps: { blueprintPath: P.blueprintPath, graphName: P.graphName, nodeType: P.nodeType, posX: P.posX, posY: P.posY, memberName: P.memberName, functionName: P.nodeFunctionName, eventName: P.eventName, nodeName: P.nodeName, targetClass: P.targetClass },
    required: ['blueprintPath', 'nodeType'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Unique node identifier for subsequent graph operations.' },
      graphName: P.graphName,
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'add_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeType: 'Branch', posX: 50, posY: 50 },
    exampleOutput: { success: true, nodeGuid: 'E5F6G7H8', graphName: 'EventGraph' },
  }),
  buildRecord({
    id: 'blueprint.delete_node',
    action: 'delete_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Delete a node from a Blueprint graph by its nodeGuid, or many nodes at once with nodeIds (one consent, one compile, all or nothing).',
    whenToUse: ['A graph node must be permanently removed.', 'A whole dead chain of nodes must be removed in one call.'],
    whenNotToUse: ['The node should be moved rather than deleted.'],
    inputProps: {
      blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, nodeGuid: P.nodeGuid,
      nodeIds: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 500, description: 'Several node ids or guids to delete in one call, in place of nodeId. Every id must resolve to a deletable node or nothing is deleted.' },
    },
    outputProps: {
      removed: { type: 'array', items: { type: 'string' }, description: 'Guids of the nodes that were deleted.' },
      removedCount: { type: 'number', description: 'How many nodes were deleted.' },
    },
    required: ['blueprintPath'],
    requiredOneOf: ['nodeId', 'nodeGuid', 'nodeIds'],
    effect: 'destructive',
    behavior: { safeToRetry: false },
    latency: 'interactive',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'delete_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4' },
  }),
  buildRecord({
    id: 'blueprint.create_reroute_node',
    action: 'create_reroute_node',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a reroute node for organizing exec/data wire paths in a Blueprint graph.',
    whenToUse: ['Wire paths need a reroute node for cleaner layout.'],
    whenNotToUse: ['A functional node is needed (use create_node).'],
    inputProps: { blueprintPath: P.blueprintPath, graphName: P.graphName, posX: P.posX, posY: P.posY },
    required: ['blueprintPath', 'posX', 'posY'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Reroute node identifier.' },
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_reroute_node', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', posX: 300, posY: 300 },
    exampleOutput: { success: true, nodeGuid: 'R9S0T1U2' },
  }),
  buildRecord({
    id: 'blueprint.get_node_details',
    action: 'get_node_details',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read details for one graph node, including its pins and linked connections; with followExec, also what runs after it along its exec wires.',
    whenToUse: [
      'A single node\'s pins, type, and links must be inspected.',
      'What an event or function does must be read: followExec on its entry node lists every node its exec wires reach, with their inputs, in one call.',
    ],
    whenNotToUse: ['All nodes in a graph are needed (use get_graph_details).'],
    inputProps: {
      blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, nodeGuid: P.nodeGuid,
      followExec: { type: 'number', minimum: 0, maximum: 50, description: 'Also walk this many nodes (1-50) along the exec wires leaving the node, depth-first (a Branch\'s then side before its else), and list each under chain with its inputs.' },
    },
    required: ['blueprintPath'],
    requiredOneOf: ['nodeId', 'nodeGuid'],
    outputProps: {
      nodeId: P.nodeId,
      nodeName: P.nodeName,
      nodeTitle: { type: 'string', description: 'Display title of the node.' },
      nodeComment: { type: 'string', description: 'Node comment, empty when it has none.' },
      x: { type: 'number', description: 'Node X position in the graph.' },
      y: { type: 'number', description: 'Node Y position in the graph.' },
      pins: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Pin descriptors (name, direction, type, links).', 'x-unreal-reflection-boundary': true },
      // An animation node's pins say nothing of what it plays or how: those are settings of the node itself.
      animationAsset: { type: 'string', description: 'An animation graph node that plays an asset (a Sequence Player, a Blend Space Player ...): the path of the animation it plays. Absent on other nodes and on a player with no asset.' },
      animationAssetClass: { type: 'string', description: 'The class of that animation asset (AnimSequence, BlendSpace ...).' },
      settings: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true, description: 'An animation graph node\'s editable settings, name to value (a Sequence Player: Sequence, PlayRate, StartPosition, bLoopAnimation ...; at most 24, lists left out). Absent on any other node. graphName is the AnimGraph, or the name of the state whose graph holds the node.' },
      chain: {
        type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true },
        description: 'With followExec: each node the exec wires reach, in walk order: nodeId, nodeTitle, via (the "Title.Pin" exec output that led to it) and inputs (each input pin as its literal value, or "<- Title.Pin" for the node feeding it).',
      },
    },
    outputRequired: ['nodeId'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_node_details', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4' },
    exampleOutput: { success: true, nodeId: 'A1B2C3D4', nodeName: 'Print String', nodeTitle: 'Print String', pins: [] },
  }),
  buildRecord({
    id: 'blueprint.get_graph_details',
    action: 'get_graph_details',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read all nodes in a Blueprint graph, optionally including per-node pins and links; filter and page a large graph.',
    whenToUse: ['The full node list of a graph must be inspected in one call.', 'A large graph must be read in parts: filter by node title or by what a pin holds, page with offset/limit.', 'The node that builds or uses a given asset, class or literal must be found, e.g. the Create Widget node for WBP_MainMenu.'],
    whenNotToUse: ['A single node\'s details are needed (use get_node_details).'],
    inputProps: {
      blueprintPath: P.blueprintPath, graphName: P.graphName, includePins: P.includePins,
      filter: { type: 'string', description: 'Only nodes whose title or name, or whose pin default value or default object path, contains this text (case-insensitive, spaces ignored), e.g. "IA_Move", "Set bLocked", or "WBP_MainMenu" for the Create Widget node whose Class pin holds /Game/UI/WBP_MainMenu.WBP_MainMenu_C.' },
      offset: { type: 'number', description: 'Skip this many matching nodes (paging).' },
      limit: { type: 'number', description: 'Return at most this many nodes; totalCount and hasMore say what is left. Use it with includePins on a big graph.' },
    },
    required: ['blueprintPath'],
    outputProps: {
      nodes: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Node descriptors (nodeId, nodeName, nodeTitle, and position x and y; pins if includePins=true).', 'x-unreal-reflection-boundary': true },
      totalCount: { type: 'number', description: 'Nodes matching filter, before offset/limit.' },
      hasMore: { type: 'boolean', description: 'More matching nodes lie past this page.' },
    },
    outputRequired: ['nodes'],
    effect: 'read',
    latency: 'interactive',
    resources: 'medium',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_graph_details', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', includePins: true },
    exampleOutput: { success: true, nodes: [{ nodeId: 'A1B2C3D4', nodeName: 'Print String' }] },
  }),
  buildRecord({
    id: 'blueprint.get_pin_details',
    action: 'get_pin_details',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Read pin details (direction, type, links, defaults) for one node in a Blueprint graph.',
    whenToUse: ['Pin-level details including linkedTo connections must be inspected for a single node.'],
    whenNotToUse: ['All nodes with pins are needed (use get_graph_details with includePins).'],
    inputProps: {
      blueprintPath: P.blueprintPath, graphName: P.graphName, nodeId: P.nodeId, nodeGuid: P.nodeGuid,
      pinName: { ...P.pinName, description: 'Report only this pin; omitted, every pin on the node.' },
    },
    required: ['blueprintPath'],
    requiredOneOf: ['nodeId', 'nodeGuid'],
    outputProps: {
      nodeId: P.nodeId,
      pins: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Pin descriptors (pinName, direction, pinType, pinSubType, linkedTo[] of {nodeId, pinName, nodeTitle}, defaults).', 'x-unreal-reflection-boundary': true },
    },
    outputRequired: ['pins'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'get_pin_details', blueprintPath: '/Game/Blueprints/BP_Test', graphName: 'EventGraph', nodeId: 'A1B2C3D4' },
    exampleOutput: { success: true, nodeId: 'A1B2C3D4', pins: [{ pinName: 'InExec', direction: 'EGPD_Input', pinType: 'exec' }] },
  }),
  buildRecord({
    id: 'blueprint.list_node_types',
    action: 'list_node_types',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'List available Blueprint node types that can be created via create_node or add_node.',
    whenToUse: ['The set of creatable node types must be enumerated before node creation.'],
    whenNotToUse: ['A specific node type is already known.'],
    inputProps: { blueprintPath: P.blueprintPath },
    outputProps: {
      nodeTypes: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            className: { type: 'string', description: 'Blueprint node class name (e.g. UK2Node_CallFunction).' },
            displayName: { type: 'string', description: 'Localized node display name shown in the Blueprint palette.' },
          },
          required: ['className', 'displayName'],
        },
        description: 'Available Blueprint node types, each an object with className and displayName.',
      },
      count: { type: 'number', description: 'Total number of node types listed.' },
    },
    outputRequired: ['nodeTypes', 'count'],
    effect: 'read',
    latency: 'instant',
    resources: 'low',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'list_node_types', blueprintPath: '/Game/Blueprints/BP_Test' },
    exampleOutput: { success: true, nodeTypes: [{ className: 'UK2Node_CallFunction', displayName: 'Call Function' }], count: 1 },
  }),
  buildRecord({
    id: 'blueprint.create_struct_make_break_nodes',
    action: 'create_struct_make_break_nodes',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Create a Make or Break Struct node in a Blueprint graph from a UserDefinedStruct or native UScriptStruct.',
    whenToUse: ['A MakeStruct or BreakStruct node must be placed for a known struct type.'],
    whenNotToUse: ['A general CallFunction or event node is needed (use create_node).'],
    inputProps: {
      blueprintPath: P.blueprintPath,
      structPath: P.structPath,
      nodeType: { type: 'string', enum: ['make', 'break'], description: 'Struct node kind: make (UK2Node_MakeStruct) or break (UK2Node_BreakStruct).' },
      graphName: P.graphName,
      posX: P.posX,
      posY: P.posY,
    },
    required: ['blueprintPath', 'structPath', 'nodeType'],
    outputProps: {
      nodeGuid: { type: 'string', description: 'Unique node identifier for subsequent graph operations.' },
      nodeType: { type: 'string', enum: ['make', 'break'], description: 'Echoed struct node kind.' },
      structPath: { type: 'string', description: 'Resolved struct object path.' },
      pinNames: { type: 'array', items: { type: 'string' }, description: 'Pin display names (legacy).' },
      pinTypes: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Per-pin objects: { name, direction, type, category, subCategory }.', 'x-unreal-reflection-boundary': true },
      diagnostics: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Compile messages: { severity, message }.', 'x-unreal-reflection-boundary': true },
      compilerStatus: { type: 'string', description: 'Blueprint status after compile (UpToDate, UpToDateWithWarnings, Error, Dirty, BeingCreated).' },
      compiled: { type: 'boolean', description: 'True when the Blueprint is up-to-date (warnings allowed).' },
      assetPath: { type: 'string', description: 'Asset path of the created node (verification).' },
      assetName: { type: 'string', description: 'Name of the created node (verification).' },
      existsAfter: { type: 'boolean', description: 'Whether the node exists after creation (verification).' },
      assetClass: { type: 'string', description: 'Class of the created node (verification).' },
    },
    outputRequired: ['nodeGuid'],
    effect: 'write',
    behavior: { longRunning: false },
    latency: 'interactive',
    resources: 'medium',
    plugins: BP_PLUGINS,
    exampleInput: { action: 'create_struct_make_break_nodes', blueprintPath: '/Game/Blueprints/BP_Test', structPath: '/Game/Blueprints/Structs/FMyStruct', nodeType: 'make', graphName: 'EventGraph', posX: 100, posY: 200 },
    exampleOutput: { success: true, nodeGuid: 'A1B2C3D4', nodeType: 'make', structPath: '/Game/Blueprints/Structs/FMyStruct', pinNames: ['A', 'B'], pinTypes: [{ name: 'A', direction: 'input', type: 'Float', category: 'float', subCategory: '' }], diagnostics: [], compilerStatus: 'UpToDate', compiled: true, assetPath: '/Game/Blueprints/BP_Test', assetName: 'Make MyStruct', existsAfter: true, assetClass: 'UK2Node_MakeStruct' },
  }),
];
