/**
 * Widget lifecycle records: create_widget_blueprint, set_widget_parent_class,
 * preview_widget.
 *
 * create_widget_blueprint is the canonical Widget Blueprint creation action.
 * The native route `create_widget` (reachable via system_control) maps to it
 * as an alias (route disposition: map -> cap:manage_blueprint:create_widget_blueprint).
 * Widget handles: `widgetPath` (asset path) identifies the Widget Blueprint.
 */
import type { CapabilityRecordSource } from '../../model.js';
import { buildRecord, WIDGET_PLUGINS } from './helpers.js';
import { P } from './properties.js';
import { LAYOUT_OUT } from './widget-layout.js';

const FAMILY = 'widget-lifecycle';
const DOMAIN = 'widget';

export const WIDGET_LIFECYCLE_RECORDS: readonly CapabilityRecordSource[] = [
  buildRecord({
    id: 'blueprint.create_widget_blueprint',
    action: 'create_widget_blueprint',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['umg widget', 'user widget', 'ui widget', 'hud', 'new widget', 'menu widget'],
    summary: 'Create a new Widget Blueprint (UMG) asset with an optional parent class, named by name and path or by its full widgetPath.',
    whenToUse: ['A new UMG Widget Blueprint must be created.'],
    whenNotToUse: ['A non-widget Blueprint is needed (use create or create_blueprint).'],
    inputProps: {
      name: P.name, path: P.path, folder: P.folder,
      widgetPath: { type: 'string', description: 'Full asset path of the new Widget Blueprint (/Game/UI/WBP_Title), in place of name and path.' },
      parentClass: P.parentClass,
    },
    required: [],
    requiredOneOf: ['name', 'widgetPath'],
    outputProps: { widgetPath: P.widgetPath },
    outputRequired: ['widgetPath'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'create_widget_blueprint', name: 'WBP_MainUI', path: '/Game/UI', parentClass: '/Script/UMG.UserWidget' },
    exampleOutput: { success: true, widgetPath: '/Game/UI/WBP_MainUI' },
    aliases: ['blueprint.create_widget'],
  }),
  buildRecord({
    id: 'blueprint.set_widget_parent_class',
    action: 'set_widget_parent_class',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Set the parent class of a Widget Blueprint.',
    whenToUse: ['A Widget Blueprint must inherit from a specific UserWidget subclass.'],
    whenNotToUse: ['The Widget Blueprint already has the correct parent.'],
    inputProps: { widgetPath: P.widgetPath, parentClass: P.parentClass },
    required: ['widgetPath', 'parentClass'],
    effect: 'write',
    behavior: { idempotency: 'idempotent' },
    latency: 'interactive',
    resources: 'low',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'set_widget_parent_class', widgetPath: '/Game/UI/WBP_MainUI', parentClass: '/Game/Blueprints/WBP_BaseUI' },
  }),
  buildRecord({
    id: 'blueprint.preview_widget',
    action: 'preview_widget',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['preview widget', 'render widget', 'see widget', 'widget screenshot', 'widget image', 'preview ui'],
    summary: 'Look at a Widget Blueprint without running the game: it is drawn offscreen for a screen size and returned as a PNG image, as the game creates it: Construct graphs do not run, so texts are the designer defaults, and widgets set Collapsed or Hidden stay hidden.',
    whenToUse: ['A Widget Blueprint must be seen after an edit (layout, colours, fonts) without running PIE.'],
    whenNotToUse: ['What the running game shows is needed, runtime texts included (play, then control_editor screenshot mode full_editor_window).'],
    inputProps: {
      widgetPath: P.widgetPath,
      resolution: { type: 'string', description: 'Screen size the widget is drawn for, "WxH" (default "1280x720"); the project DPI scaling for that size applies, as in the game.' },
      openEditor: { type: 'boolean', description: 'Also open it in the Widget Blueprint editor, which takes focus (default false).' },
      // The editor compiles a material's UI shaders the first time it is drawn: the first preview after the editor
      // starts, or after a material edit, drew panels and button faces blank.
      waitForShaders: { type: 'boolean', description: 'true: when the drawing left shaders compiling (the editor compiles a material\'s UI shaders the first time it is drawn: right after the editor starts, or after a material edit), wait for them, at most 25 seconds, and draw again; shaderWait in the reply says how long it waited. Default false: draw once and report shadersCompiling.' },
    },
    required: ['widgetPath'],
    outputProps: {
      widgetPath: P.widgetPath,
      imageBase64: { type: 'string', description: 'The drawn widget as PNG, base64; returned as an image.' },
      mimeType: { type: 'string', description: 'image/png.' },
      width: { type: 'number', description: 'Image width in pixels.' },
      height: { type: 'number', description: 'Image height in pixels.' },
      sizeBytes: { type: 'number', description: 'PNG size in bytes.' },
      editorOpened: { type: 'boolean', description: 'Whether the Widget Blueprint editor was opened (openEditor).' },
      shadersCompiling: { type: 'number', description: 'Shader compile jobs still outstanding when the widget was drawn. Above 0, images and borders that use a material may be drawn blank and a warning says so; pass waitForShaders to draw after they finish.' },
      shaderWait: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true, description: 'With waitForShaders while shaders compiled: waitedSeconds, jobsLeft (still outstanding when the wait ended) and timedOut (true when jobs were left after the 25 second cap).' },
    },
    outputRequired: ['widgetPath'],
    // Read, and its own record: the widget and render target are transient, and
    // openEditor only opens a tab. Folded with the edit_widget_blueprint writes it
    // demanded Write scope for a picture.
    effect: 'read',
    latency: 'interactive',
    resources: 'medium',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'preview_widget', widgetPath: '/Game/UI/WBP_MainUI' },
    exampleOutput: { success: true, message: 'Widget drawn at 1280x720 as the game creates it (Construct graphs do not run)', widgetPath: '/Game/UI/WBP_MainUI', mimeType: 'image/png', width: 1280, height: 720 },
  }),
  buildRecord({
    id: 'blueprint.remove_widget',
    action: 'remove_widget',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['delete widget', 'remove widget', 'delete button', 'remove button', 'remove label'],
    summary: 'Remove a widget from the widget tree of a Widget Blueprint.',
    whenToUse: ['A widget must be deleted from a Widget Blueprint layout.'],
    whenNotToUse: ['The widget should stay but be hidden (use set_visibility).'],
    inputProps: { widgetPath: P.widgetPath, slotName: P.slotName },
    required: ['widgetPath', 'slotName'],
    outputProps: {
      widgetPath: P.widgetPath,
      removedWidget: { type: 'string', description: 'Name of the widget that was removed from the widget tree.' },
    },
    outputRequired: ['widgetPath', 'removedWidget'],
    effect: 'destructive',
    latency: 'interactive',
    resources: 'low',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'remove_widget', widgetPath: '/Game/UI/WBP_MainUI', slotName: 'TitleText' },
    exampleOutput: { success: true, widgetPath: '/Game/UI/WBP_MainUI', removedWidget: 'TitleText' },
  }),
  buildRecord({
    id: 'blueprint.rename_widget',
    action: 'rename_widget',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Rename a widget inside the widget tree of a Widget Blueprint.',
    whenToUse: ['A widget name must change so bindings and lookups can address it.'],
    whenNotToUse: ['A Blueprint or Widget Blueprint asset itself should be renamed (use asset.rename).'],
    inputProps: { widgetPath: P.widgetPath, slotName: P.slotName, newName: P.newName },
    required: ['widgetPath', 'slotName', 'newName'],
    outputProps: { widgetPath: P.widgetPath, oldName: P.oldName, newName: P.newName },
    outputRequired: ['widgetPath', 'oldName', 'newName'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'rename_widget', widgetPath: '/Game/UI/WBP_MainUI', slotName: 'TitleText', newName: 'HeaderText' },
    exampleOutput: { success: true, widgetPath: '/Game/UI/WBP_MainUI', oldName: 'TitleText', newName: 'HeaderText' },
  }),
  buildRecord({
    id: 'blueprint.reparent_widget',
    action: 'reparent_widget',
    family: FAMILY,
    domain: DOMAIN,
    summary: 'Move a widget under a different parent widget inside a Widget Blueprint, or to another position in its own parent, keeping its slot layout.',
    whenToUse: ['An existing widget must move into another panel without being recreated.', 'Children of a panel must be reordered (same newParent, with index).'],
    whenNotToUse: ['The widget is being added for the first time (use the matching add action).'],
    inputProps: {
      widgetPath: P.widgetPath, slotName: P.slotName, newParent: P.newParent,
      index: { type: 'integer', minimum: 0, description: 'Position among the children of the new parent after the move (0 = first). Without it the widget goes last.' },
    },
    required: ['widgetPath', 'slotName', 'newParent'],
    outputProps: {
      widgetPath: P.widgetPath,
      slotName: LAYOUT_OUT.slotName,
      newParent: P.newParent,
      index: { type: 'integer', description: 'Where the widget now sits among the children of the new parent (0 = first).' },
      applied: LAYOUT_OUT.applied,
      saved: LAYOUT_OUT.saved,
    },
    outputRequired: ['widgetPath', 'slotName', 'newParent', 'index', 'applied'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'reparent_widget', widgetPath: '/Game/UI/WBP_MainUI', slotName: 'TitleText', newParent: 'HeaderBox' },
    exampleOutput: { success: true, widgetPath: '/Game/UI/WBP_MainUI', slotName: 'TitleText', newParent: 'HeaderBox', index: 0 },
  }),
  buildRecord({
    id: 'blueprint.duplicate_widget',
    action: 'duplicate_widget',
    family: FAMILY,
    domain: DOMAIN,
    topics: ['duplicate widget', 'copy widget', 'clone widget', 'duplicate button', 'copy button', 'repeat row'],
    summary: 'Copy a widget and everything under it (a list row with its label, icon and button) inside a Widget Blueprint: same properties, slot layout and children, placed right after the original or under another panel.',
    whenToUse: ['A widget or a whole panel subtree is needed again, e.g. the next row of a list or a second button like the first.'],
    whenNotToUse: ['The widget should move rather than be copied (use reparent_widget).'],
    inputProps: {
      widgetPath: P.widgetPath,
      slotName: { type: 'string', description: 'Widget to copy; everything under it is copied too.' },
      newName: { type: 'string', description: 'Name of the copy (default the original name with _Copy; _1, _2... is added when that name is taken). Every widget under it is copied as <its own name>_Copy, made unique the same way: copying QuitButton gives QuitButton_Copy and its label QuitButtonText_Copy. copiedWidgets lists the pairs.' },
      newParent: { type: 'string', description: 'Panel the copy goes under (default the parent of the original).' },
      index: { type: 'integer', minimum: 0, description: 'Position among the children of that panel (0 = first). Default: right after the original, or last under another panel.' },
    },
    required: ['widgetPath', 'slotName'],
    outputProps: {
      widgetPath: P.widgetPath,
      slotName: { type: 'string', description: 'Name of the copy, for later calls.' },
      newParent: { type: 'string', description: 'Panel the copy sits under.' },
      index: { type: 'integer', description: 'Where the copy sits among the children of that panel (0 = first).' },
      copiedWidgets: { type: 'array', description: 'Every widget copied, as {source, copy} name pairs: the children come first, each copied as <source>_Copy, and the copy of the original comes last.', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true } },
    },
    outputRequired: ['widgetPath', 'slotName', 'newParent', 'index'],
    effect: 'write',
    latency: 'interactive',
    resources: 'low',
    plugins: WIDGET_PLUGINS,
    exampleInput: { action: 'duplicate_widget', widgetPath: '/Game/UI/WBP_Shop', slotName: 'Row_1', newName: 'Row_2' },
    exampleOutput: { success: true, widgetPath: '/Game/UI/WBP_Shop', slotName: 'Row_2', newParent: 'RowList', index: 1, copiedWidgets: [{ source: 'RowLabel', copy: 'RowLabel_Copy' }, { source: 'Row_1', copy: 'Row_2' }] },
  }),
];
