// GENERATED by scripts/generate-native-headers.ts -- do not edit.
// Source of truth: src/services/telemetry-schema.ts (the TypeScript surface
// exports the same metric names, labels, value sets, buckets and quantiles).
//
// Cardinality is a SECURITY boundary. Every label value below comes from a
// closed set, and Coerce* maps anything unresolved to "unknown" rather than
// passing it through. Capability ids, asset/file paths, tokens, prompts, project
// content, session ids and request ids are never dimensions.
#pragma once

#include "CoreMinimal.h"

namespace McpTelemetrySchema
{
	inline const TCHAR* MetricRequestDurationSeconds() { return TEXT("unreal_mcp_request_duration_seconds"); }
	inline const TCHAR* MetricRequestDurationQuantileSeconds() { return TEXT("unreal_mcp_request_duration_quantile_seconds"); }
	inline const TCHAR* MetricQueueWaitSeconds() { return TEXT("unreal_mcp_queue_wait_seconds"); }
	inline const TCHAR* MetricQueueWaitQuantileSeconds() { return TEXT("unreal_mcp_queue_wait_quantile_seconds"); }
	inline const TCHAR* MetricRequestsByClassTotal() { return TEXT("unreal_mcp_requests_by_class_total"); }
	inline const TCHAR* MetricFailuresByClassTotal() { return TEXT("unreal_mcp_failures_by_class_total"); }
	inline const TCHAR* MetricReadinessComponent() { return TEXT("unreal_mcp_readiness_component"); }
	inline const TCHAR* MetricReady() { return TEXT("unreal_mcp_ready"); }

	inline const TCHAR* LabelSurface() { return TEXT("surface"); }
	inline const TCHAR* LabelActionClass() { return TEXT("action_class"); }
	inline const TCHAR* LabelOutcome() { return TEXT("outcome"); }
	inline const TCHAR* LabelFailureClass() { return TEXT("failure_class"); }
	inline const TCHAR* LabelComponent() { return TEXT("component"); }
	inline const TCHAR* LabelQuantile() { return TEXT("quantile"); }
	inline const TCHAR* LabelLe() { return TEXT("le"); }

	inline const TArray<FString>& SurfaceValues()
	{
		static const TArray<FString> Values = {
			TEXT("native"),
			TEXT("typescript"),
		};
		return Values;
	}

	inline const TArray<FString>& ActionClassValues()
	{
		static const TArray<FString> Values = {
			TEXT("admin"),
			TEXT("destructive"),
			TEXT("read"),
			TEXT("unknown"),
			TEXT("write"),
		};
		return Values;
	}

	inline const TArray<FString>& OutcomeValues()
	{
		static const TArray<FString> Values = {
			TEXT("failure"),
			TEXT("success"),
		};
		return Values;
	}

	inline const TArray<FString>& FailureClassValues()
	{
		static const TArray<FString> Values = {
			TEXT("command_blocked"),
			TEXT("consent_required"),
			TEXT("internal"),
			TEXT("path_not_permitted"),
			TEXT("project_not_permitted"),
			TEXT("quota_exceeded"),
			TEXT("scope_not_granted"),
			TEXT("timeout"),
			TEXT("transport"),
			TEXT("unknown"),
			TEXT("validation"),
		};
		return Values;
	}

	inline const TArray<FString>& ReadinessComponentValues()
	{
		static const TArray<FString> Values = {
			TEXT("editor"),
			TEXT("registry"),
			TEXT("transport"),
		};
		return Values;
	}

	inline const TArray<double>& LatencyBucketUpperBoundsSeconds()
	{
		static const TArray<double> Values = {
			0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30,
		};
		return Values;
	}

	inline const TArray<double>& Quantiles()
	{
		static const TArray<double> Values = {
			0.5, 0.9, 0.95, 0.99,
		};
		return Values;
	}

	inline FString UnknownValue() { return TEXT("unknown"); }

	inline FString CoerceFromSet(const TArray<FString>& Allowed, const FString& Candidate, const FString& Fallback)
	{
		const FString Normalized = Candidate.TrimStartAndEnd().ToLower();
		return Allowed.Contains(Normalized) ? Normalized : Fallback;
	}

	inline FString CoerceSurface(const FString& Candidate)
	{
		return CoerceFromSet(SurfaceValues(), Candidate, TEXT("native"));
	}

	/** Unresolved input becomes "unknown"; it is never passed through as a label. */
	inline FString CoerceActionClass(const FString& Candidate)
	{
		return CoerceFromSet(ActionClassValues(), Candidate, UnknownValue());
	}

	inline FString CoerceOutcome(const FString& Candidate)
	{
		return CoerceFromSet(OutcomeValues(), Candidate, TEXT("success"));
	}

	/** Accepts the shared refusal codes in any case/dash form, else "unknown". */
	inline FString CoerceFailureClass(const FString& Candidate)
	{
		FString Normalized = Candidate.TrimStartAndEnd().ToLower();
		Normalized.ReplaceInline(TEXT("-"), TEXT("_"));
		return CoerceFromSet(FailureClassValues(), Normalized, UnknownValue());
	}
}
