/**
 * manage_inventory records. get_inventory_info is the only read action and the
 * only one whose native shard reads no `save` flag, so it declares none.
 */
import type { CapabilityRecordSource } from '../../../model.js';
import { IP, inventoryRecord } from './schema.js';
import { P } from '../properties.js';

export const INVENTORY_RECORDS: readonly CapabilityRecordSource[] = [
  inventoryRecord({
    action: 'add_loot_entry',
    summary: 'Add an entry to a loot table asset.',
    whenToUse: [
      'A loot table needs another item entry with a drop weight and a quantity range.',
      'The entry is stored under the key LootEntry_<n>, one past the highest n in use, and n comes back as entryIndex; an earlier removal never makes a new entry overwrite a surviving one.',
    ],
    whenNotToUse: [
      'The loot table asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The table only needs to be read (use manage_inventory.get_inventory_info).',
    ],
    inputProps: {
      lootTablePath: IP.lootTablePath,
      itemPath: IP.itemPath,
      lootWeight: IP.lootWeight,
      minQuantity: IP.minQuantity,
      maxQuantity: IP.maxQuantity,
      save: IP.save,
    },
    required: ['lootTablePath', 'itemPath'],
    exampleInput: {
      action: 'add_loot_entry',
      lootTablePath: '/Game/Data/LootTables/LT_Common',
      itemPath: '/Game/Items/DA_Potion',
      lootWeight: 1,
    },
  }),
  inventoryRecord({
    action: 'add_recipe_ingredient',
    summary: 'Add an ingredient to a crafting recipe asset.',
    whenToUse: [
      'A recipe needs one more ingredient item with the quantity it consumes.',
      'The ingredient is stored under the key Ingredient_<n>, one past the highest n in use (the first is Ingredient_0).',
    ],
    whenNotToUse: [
      'The recipe asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The recipe is a custom class, not one made by manage_inventory.create_inventory_asset (use inspect.set_property).',
    ],
    inputProps: {
      recipePath: IP.recipePath,
      ingredientItemPath: IP.ingredientItemPath,
      quantity: IP.quantity,
      save: IP.save,
    },
    required: ['recipePath', 'ingredientItemPath'],
    exampleInput: {
      action: 'add_recipe_ingredient',
      recipePath: '/Game/Data/Recipes/R_Potion',
      ingredientItemPath: '/Game/Items/DA_Herb',
      quantity: 2,
    },
  }),
  inventoryRecord({
    action: 'assign_item_category',
    summary: 'Assign a category to an item asset.',
    whenToUse: ['An item must be filed under an existing item category asset.'],
    whenNotToUse: [
      'The item asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The category asset does not exist yet, and its path is stored without a check (use manage_inventory.create_inventory_asset, kind=item_category).',
    ],
    inputProps: { itemPath: IP.itemPath, categoryPath: IP.categoryPath, save: IP.save },
    required: ['itemPath', 'categoryPath'],
    exampleInput: {
      action: 'assign_item_category',
      itemPath: '/Game/Items/DA_Potion',
      categoryPath: '/Game/Items/Categories/DA_Consumable',
      save: true,
    },
  }),
  inventoryRecord({
    action: 'configure_item_stacking',
    summary: 'Configure persistent item stacking rules.',
    whenToUse: [
      'An item must be marked stackable with a maximum stack size, or flagged as unique.',
      'All three stacking fields should be given together, since an omitted one resets to stackable, 99 or not unique.',
    ],
    whenNotToUse: [
      'The item asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The item is a custom class with no stacking properties such as bStackable or MaxStackSize: the call fails with PROPERTY_NOT_FOUND and writes nothing (use inspect.set_property).',
    ],
    inputProps: {
      itemPath: IP.itemPath,
      stackable: IP.stackable,
      maxStackSize: IP.maxStackSize,
      uniqueItems: IP.uniqueItems,
      save: IP.save,
    },
    required: ['itemPath'],
    exampleInput: {
      action: 'configure_item_stacking',
      itemPath: '/Game/Items/DA_Potion',
      stackable: true,
      maxStackSize: 99,
    },
  }),
  inventoryRecord({
    action: 'configure_recipe_requirements',
    summary: 'Configure persistent crafting requirements.',
    whenToUse: [
      'A recipe must require a minimum character level or a named crafting station.',
      'Level and station should be given together, since an omitted one resets to level 0 or station None.',
    ],
    whenNotToUse: [
      'The recipe asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The recipe is a custom class, not one made by manage_inventory.create_inventory_asset (use inspect.set_property).',
    ],
    inputProps: {
      recipePath: IP.recipePath,
      requiredLevel: IP.requiredLevel,
      requiredStation: IP.requiredStation,
      save: IP.save,
    },
    required: ['recipePath'],
    exampleInput: {
      action: 'configure_recipe_requirements',
      recipePath: '/Game/Data/Recipes/R_Potion',
      requiredLevel: 5,
    },
  }),
  inventoryRecord({
    action: 'create_crafting_recipe',
    summary: 'Create a crafting recipe asset.',
    whenToUse: ['A recipe is needed that produces an output item in a set quantity and craft time.'],
    whenNotToUse: ['Ingredients or requirements must be added to an existing recipe (use manage_inventory.configure_crafting).'],
    inputProps: {
      name: IP.name,
      path: IP.path,
      outputItemPath: IP.outputItemPath,
      outputQuantity: IP.outputQuantity,
      craftTime: IP.craftTime,
      save: IP.save,
    },
    required: ['name', 'outputItemPath'],
    exampleInput: {
      action: 'create_crafting_recipe',
      name: 'R_Potion',
      outputItemPath: '/Game/Items/DA_Potion',
      outputQuantity: 1,
    },
  }),
  inventoryRecord({
    action: 'create_crafting_station',
    summary: 'Create a crafting station Blueprint asset.',
    whenToUse: ['A crafting station Blueprint is needed with a station mesh and an interaction box.'],
    whenNotToUse: ['An actor Blueprint with a different component set is needed (use blueprint.create).'],
    inputProps: { name: IP.name, path: IP.path, stationType: IP.stationType, save: IP.save },
    required: ['name'],
    exampleInput: { action: 'create_crafting_station', name: 'BP_Forge', stationType: 'Basic' },
  }),
  inventoryRecord({
    action: 'create_item_category',
    summary: 'Create an item category asset.',
    whenToUse: ['A group such as Consumable or Weapon is needed so items can be filed under it.'],
    whenNotToUse: ['An existing item only needs to be filed under an existing category (use manage_inventory.configure_item).'],
    inputProps: { name: IP.name, path: IP.path, save: IP.save },
    required: ['name'],
    exampleInput: { action: 'create_item_category', name: 'DA_Consumable', path: '/Game/Items/Categories' },
  }),
  inventoryRecord({
    action: 'create_item_data_asset',
    summary: 'Create an item data asset.',
    whenToUse: ['A new item is needed as a data asset that item settings, loot entries and recipes can point at.'],
    whenNotToUse: ['The item already exists and only its properties, icon, stacking or category change (use manage_inventory.configure_item).'],
    inputProps: { name: IP.name, path: IP.path, save: IP.save },
    required: ['name'],
    exampleInput: { action: 'create_item_data_asset', name: 'DA_Potion', path: '/Game/Items' },
  }),
  inventoryRecord({
    action: 'create_loot_table',
    summary: 'Create a loot table asset.',
    whenToUse: ['A loot table asset is needed to hold weighted item entries and quality tiers.'],
    whenNotToUse: ['Entries or tiers must go into an existing loot table (use manage_inventory.configure_loot).'],
    inputProps: { name: IP.name, path: IP.path, save: IP.save },
    required: ['name'],
    exampleInput: { action: 'create_loot_table', name: 'LT_Common', path: '/Game/Data/LootTables' },
  }),
  inventoryRecord({
    action: 'get_inventory_info',
    summary: 'Read an inventory asset: an item (properties), loot table (entries with item, weight and quantity range), recipe (ingredients, output item, station, craft time), or a pickup or inventory Blueprint (components, variables).',
    topics: ['item properties', 'list loot table entries', 'recipe ingredients', 'pickup blueprint variables'],
    whenToUse: [
      'The stored fields of an item, loot table or recipe asset must be checked, for example after changing it.',
      'The components and variable defaults of a pickup or inventory Blueprint must be read.',
    ],
    whenNotToUse: [
      'Assets must first be found by name, class or folder (use asset.query_asset).',
      'The functions, events or graph node counts of a Blueprint are needed (use inspect.get_blueprint_details).',
    ],
    read: true,
    inputProps: {
      blueprintPath: IP.blueprintPath,
      itemPath: IP.itemPath,
      lootTablePath: IP.lootTablePath,
      recipePath: IP.recipePath,
      pickupPath: IP.pickupPath,
    },
    outputProps: {
      assetPath: P.assetPath,
      assetType: { type: 'string', description: 'Resolved asset type (item, lootTable, recipe, pickup, blueprint).' },
      className: { type: 'string', description: 'UClass or data asset class name.' },
      itemPath: IP.itemPath,
      lootTablePath: IP.lootTablePath,
      recipePath: IP.recipePath,
      pickupPath: IP.pickupPath,
      blueprintPath: IP.blueprintPath,
      properties: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true, description: 'Authored item properties.' },
      category: { type: 'string', description: 'Item category asset path.' },
      stackable: IP.stackable,
      maxStackSize: IP.maxStackSize,
      icon: IP.iconPath,
      weight: { type: 'number', description: 'Item weight.' },
      replication: { type: 'string', description: 'Replication condition applied to inventory state.' },
      lootEntries: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Loot table entries.' },
      tiers: IP.tiers,
      lootEntryCount: { type: 'number', description: 'Number of loot entries.' },
      ingredients: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Recipe ingredients.' },
      outputItem: { type: 'string', description: 'Recipe output item asset path.' },
      outputQuantity: IP.outputQuantity,
      craftTime: IP.craftTime,
      requiredLevel: IP.requiredLevel,
      requiredStation: IP.requiredStation,
      components: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Blueprint SCS components.' },
      variables: { type: 'array', items: { type: 'object', additionalProperties: true, 'x-unreal-reflection-boundary': true }, description: 'Blueprint NewVariables (recipes, station settings).' },
      recipes: IP.recipePaths,
      unsupportedFields: { type: 'array', items: { type: 'string' }, description: 'Categories the handler could not project.' },
    },
    exampleInput: { action: 'get_inventory_info', blueprintPath: '/Game/Blueprints/BP_Player' },
  }),
  inventoryRecord({
    action: 'remove_loot_entry',
    summary: 'Remove an entry from a loot table asset.',
    whenToUse: ['A loot table entry must be dropped, chosen by the entryIndex that adding it returned or by its item, which removes every entry for that item.'],
    whenNotToUse: [
      'The loot table asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The table only needs to be read (use manage_inventory.get_inventory_info).',
    ],
    inputProps: {
      lootTablePath: IP.lootTablePath,
      entryIndex: IP.entryIndex,
      itemPath: IP.itemPath,
      save: IP.save,
    },
    required: ['lootTablePath'],
    requiredOneOf: ['entryIndex', 'itemPath'],
    exampleInput: {
      action: 'remove_loot_entry',
      lootTablePath: '/Game/Data/LootTables/LT_Common',
      entryIndex: 0,
    },
  }),
  inventoryRecord({
    action: 'set_inventory_replication',
    summary: 'Set inventory component replication metadata.',
    whenToUse: [
      'A Blueprint with InventorySlots, MaxSlots, CurrentWeight and MaxWeight variables must replicate them to clients, or stop (replicated defaults to false).',
      'Those variables need a replication condition such as OwnerOnly, SkipOwner, SimulatedOnly or InitialOnly.',
      'A RepNotify function already set on those variables is kept: replicated=true sets only the replication flag and condition, and replicated=false clears the flag and condition and leaves the function name in place.',
    ],
    whenNotToUse: [
      'The Blueprint keeps inventory state in differently named variables (use manage_networking.configure_replication).',
      'None of the four inventory variables exist yet (add them with blueprint.edit_variable).',
    ],
    inputProps: {
      blueprintPath: IP.blueprintPath,
      replicated: IP.replicated,
      replicationCondition: IP.replicationCondition,
      save: IP.save,
    },
    required: ['blueprintPath'],
    exampleInput: {
      action: 'set_inventory_replication',
      blueprintPath: '/Game/Blueprints/BP_Player',
      replicated: true,
    },
  }),
  inventoryRecord({
    action: 'set_item_icon',
    summary: 'Set the icon reference on an item asset.',
    whenToUse: ['An item needs an icon texture or material path recorded on it.'],
    whenNotToUse: [
      'The item asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The icon image is not in the project yet (use asset.import).',
      'The item is a custom class with none of the properties Icon, ItemIcon, Thumbnail, DisplayIcon or InventoryIcon, so the call fails and names the missing property (use inspect.set_property on the class\'s own icon property).',
    ],
    inputProps: { itemPath: IP.itemPath, iconPath: IP.iconPath, save: IP.save },
    required: ['itemPath'],
    exampleInput: {
      action: 'set_item_icon',
      itemPath: '/Game/Items/DA_Potion',
      iconPath: '/Game/UI/Icons/T_Potion',
    },
  }),
  inventoryRecord({
    action: 'set_item_properties',
    summary: 'Set persistent item asset properties.',
    whenToUse: ['An item needs custom fields such as a name, description, weight or value written onto its data asset.'],
    whenNotToUse: [
      'The item asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The target is a Blueprint or class default rather than an item data asset (use inspect.set_property).',
    ],
    inputProps: { itemPath: IP.itemPath, properties: IP.properties, save: IP.save },
    required: ['itemPath'],
    exampleInput: {
      action: 'set_item_properties',
      itemPath: '/Game/Items/DA_Potion',
      properties: { DisplayName: 'Potion' },
      save: true,
    },
  }),
  inventoryRecord({
    action: 'set_loot_quality_tiers',
    summary: 'Set quality tiers on a loot table asset.',
    whenToUse: ['A loot table needs quality tiers with drop weights; the tier list is replaced whole, and five default tiers apply if none are given.'],
    whenNotToUse: [
      'The loot table asset does not exist yet (use manage_inventory.create_inventory_asset).',
      'The table only needs to be read (use manage_inventory.get_inventory_info).',
    ],
    inputProps: { lootTablePath: IP.lootTablePath, tiers: IP.tiers, save: IP.save },
    required: ['lootTablePath'],
    exampleInput: {
      action: 'set_loot_quality_tiers',
      lootTablePath: '/Game/Data/LootTables/LT_Common',
      tiers: [{ name: 'Rare', dropWeight: 0.1 }],
    },
  }),
];
